[CmdletBinding(SupportsShouldProcess=$true)]
param([Parameter(Mandatory=$true)][string]$ProjectRoot,[switch]$Apply)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$root=(Resolve-Path -LiteralPath $ProjectRoot).Path
$utf8=[Text.UTF8Encoding]::new($false,$true)
function Get-HashText([string]$Text){$sha=[Security.Cryptography.SHA256]::Create();try{([BitConverter]::ToString($sha.ComputeHash([Text.Encoding]::UTF8.GetBytes($Text)))).Replace('-','').ToLowerInvariant()}finally{$sha.Dispose()}}
function Get-SourceHash([string]$Relative){$full=Join-Path $root $Relative;$bytes=[IO.File]::ReadAllBytes($full);$ext=[IO.Path]::GetExtension($Relative).ToLowerInvariant();if($ext -in @('.md','.json','.yaml','.yml','.ps1','.py','.txt','.cs','.asset','.meta','.asmdef','.csproj')){$text=$utf8.GetString($bytes).Replace("`r`n","`n").Replace("`r","`n");return Get-HashText $text};$sha=[Security.Cryptography.SHA256]::Create();try{return ([BitConverter]::ToString($sha.ComputeHash($bytes))).Replace('-','').ToLowerInvariant()}finally{$sha.Dispose()}}
function Get-BodyHash([string]$Text){$normalized=$Text.Replace("`r`n","`n").Replace("`r","`n");$lines=[Collections.Generic.List[string]]::new();foreach($line in $normalized.Split([char]10)){if($line -match '(?i)^\s*`EntryBodyHash`\s*[:：]\s*`[^`]*`\s*$'){continue};$lines.Add($line.TrimEnd([char[]]@(' ',"`t")))};while($lines.Count -gt 0 -and $lines[$lines.Count-1].Length -eq 0){$lines.RemoveAt($lines.Count-1)};Get-HashText (($lines -join "`n")+"`n")}
function Write-Atomic([string]$Path,[string]$Text){$tmp=$Path+'.scoped-refresh.tmp';[IO.File]::WriteAllText($tmp,$Text,$utf8);$read=$utf8.GetString([IO.File]::ReadAllBytes($tmp));if($read -cne $Text){throw "post-write-readback-mismatch: $Path"};Move-Item -LiteralPath $tmp -Destination $Path -Force}
$targetMap=[ordered]@{ 'es.project.game-ui-open-source-automation-patterns.v1'='Documentation/AIKnowledge/entries/game-ui-open-source-automation-patterns.md'; 'es.project.game-ui-request-intent-contract.v1'='Documentation/AIKnowledge/entries/game-ui-request-intent-contract.md' }
$updates=@();foreach($id in $targetMap.Keys){$relative=$targetMap[$id];$path=Join-Path $root $relative;if(-not(Test-Path -LiteralPath $path -PathType Leaf)){throw "target-not-found: $relative"};$lines=Get-Content -LiteralPath $path -Encoding UTF8;$newLines=[Collections.Generic.List[string]]::new();$sourceHashes=[Collections.Generic.List[string]]::new();foreach($line in $lines){$match=[regex]::Match($line,'^- `(.+?)` \(`[0-9a-f]{64}`\)$');if($match.Success){$sourcePath=$match.Groups[1].Value;$current=Get-SourceHash $sourcePath;$sourceHashes.Add($current);$newLines.Add('- `'+$sourcePath+'` (`'+$current+'`)')}else{$newLines.Add($line)}};if($sourceHashes.Count -eq 0){throw "source-refs-empty: $relative"};$ordered=[string[]]$sourceHashes.ToArray();[Array]::Sort($ordered,[StringComparer]::Ordinal);$content=Get-HashText ($ordered -join '');$text=($newLines -join "`n")+"`n";$text=[regex]::Replace($text,'(?m)^`ContentHash`: `[^`]+`$','`ContentHash`: `'+$content+'`');$text=[regex]::Replace($text,'(?m)^`SourceSetHash`: `[^`]+`$','`SourceSetHash`: `'+$content+'`');$body=Get-BodyHash $text;$text=[regex]::Replace($text,'(?m)^`EntryBodyHash`: `[^`]+`$','`EntryBodyHash`: `'+$body+'`');$updates += [pscustomobject]@{id=$id;path=$relative;text=$text;contentHash=$content;sourceSetHash=$content;entryBodyHash=$body}}
$indexPath=Join-Path $root 'Documentation/AIKnowledge/KnowledgeIndex.yaml';$index=$utf8.GetString([IO.File]::ReadAllBytes($indexPath));foreach($u in $updates){$pattern='(?ms)^  - knowledgeId: '+[regex]::Escape($u.id)+'\s*$.*?(?=^  - knowledgeId:|\z)';$blockMatch=[regex]::Match($index,$pattern);if(-not $blockMatch.Success){throw "index-binding-not-found: $($u.id)"};$block=$blockMatch.Value;$block=[regex]::Replace($block,'(?m)^    contentHash: [0-9a-f]{64}$','    contentHash: '+$u.contentHash);$block=[regex]::Replace($block,'(?m)^    sourceSetHash: [0-9a-f]{64}$','    sourceSetHash: '+$u.sourceSetHash);$block=[regex]::Replace($block,'(?m)^    entryBodyHash: [0-9a-f]{64}$','    entryBodyHash: '+$u.entryBodyHash);$index=$index.Remove($blockMatch.Index,$blockMatch.Length).Insert($blockMatch.Index,$block)}
if(-not $Apply){$updates|Select-Object id,path,contentHash,sourceSetHash,entryBodyHash;Write-Output 'preview-only';exit 0}
if(-not $PSCmdlet.ShouldProcess('two scoped Knowledge entries and their index bindings','apply stable SourceRef refresh')){exit 0}
foreach($u in $updates){Write-Atomic (Join-Path $root $u.path) $u.text};Write-Atomic $indexPath $index
$validator=Join-Path $root '.agents/skills/es-knowledge-validator/scripts/Invoke-ESKnowledgeValidation.ps1';$results=@();foreach($u in $updates){$results+=(& powershell -NoProfile -File $validator -ProjectRoot $root -Mode Entry -EntryPath $u.path | ConvertFrom-Json)};if(@($results|Where-Object status -notin @('passed','static-passed')).Count -gt 0){throw 'post-apply-validation-failed'};$results|Select-Object status,entryPath
