[CmdletBinding()]
param([Parameter(Mandatory)][string]$WorkerResultPath,[Parameter(Mandatory)][string]$EvaluationRecordPath,[Parameter(Mandatory)][string]$TaskId,[ValidateSet('structure','implementation','presentation','performance')][string]$Layer,[string]$OutputPath)
$ErrorActionPreference='Stop';$u=[Text.UTF8Encoding]::new($false,$true)
function Read-WorkerJson([string]$p){if(-not(Test-Path -LiteralPath $p -PathType Leaf)){throw "WORKER_EVIDENCE_INPUT_MISSING:$p"};$u.GetString([IO.File]::ReadAllBytes($p))|ConvertFrom-Json}
$w=Read-WorkerJson $WorkerResultPath;$e=Read-WorkerJson $EvaluationRecordPath
if([string]$w.taskId -cne 'es.task-context.evaluate' -or [string]$w.status -cne 'Passed'){throw 'WORKER_RESULT_NOT_ACCEPTED'}
if([string]$e.taskId -cne $TaskId -or [string]$e.recordType -cne 'EvaluationRecord' -or [string]$e.decisionScope -cne 'task-object'){throw 'EVALUATION_RECORD_SCOPE_INVALID'}
if($null -ne $w.completionDecision){throw 'WORKER_COMPLETION_INJECTION'}
$inputHash=[string]$w.inputManifestHash;if($inputHash -notmatch '^[a-f0-9]{64}$'){throw 'WORKER_INPUT_HASH_INVALID'}
$status=if([string]$e.decision -eq 'accepted'){'passed'}else{'failed'};$root=(Resolve-Path (Join-Path $PSScriptRoot '..\..\..\..')).Path
$refs=@('ES/Automation/Workers/PowerShell/Invoke-ESTaskContextEvaluationWorker.ps1','ES/Automation/TaskContextRuntime/Test-ESTaskContextEvaluationAdapter.ps1');$refHashes=@{};foreach($ref in $refs){$refHashes[$ref]=(Get-FileHash -LiteralPath (Join-Path $root $ref) -Algorithm SHA256).Hash.ToLowerInvariant()}
$out=[ordered]@{schemaVersion=1;receiptType='es-game-core-loop-evidence';evidenceContractId='es.skill-evidence-receipt';evidenceContractHash='9fbf168a71ff71c0b16d45ec8fdc18d7891a42b3c3f17638b28d3d3541b1f880';skillName='es-game-core-loop-validation';case='worker-evidence-conversion';evidenceLevel='S1';receiptPath='';toolId='es-task-context-evaluate-worker-adapter';unityVersion='not-run';capturedUtc=([DateTime]::UtcNow.ToString('o'));authorizationKind='read-only';taskId=$TaskId;agentId='es.task.context.evaluate';layer=$Layer;entryPoint='ES/Automation/Workers/PowerShell/Invoke-ESTaskContextEvaluationWorker.ps1';expected='scoped TaskContext evaluation';observed="decision=$([string]$e.decision);evidenceState=$([string]$e.evidenceState)";status=$status;sourceHash=$inputHash;runtimeStatus='runtime-not-run';claimsNotProven=@('Unity Runtime','Worker does not prove game-loop presentation/performance');sourceRefs=$refs;sourceRefHashes=$refHashes;workerResultPath=$WorkerResultPath;evaluationRecordPath=$EvaluationRecordPath;completionAuthority='ABCD-final-decision'}
$json=$out|ConvertTo-Json -Depth 12;if($OutputPath){$full=[IO.Path]::GetFullPath($OutputPath);$out.receiptPath=$full.Substring($root.Length+1).Replace('\','/');$json=$out|ConvertTo-Json -Depth 12;[IO.File]::WriteAllText($full,$json,[Text.UTF8Encoding]::new($false))};$json
