[CmdletBinding()]
param([Parameter(Mandatory)][string]$GoalRevisionPath,[Parameter(Mandatory)][string]$RoutePlanPath,[Parameter(Mandatory)][string]$TaskId,[ValidateSet('StaticReview','RuntimeAcceptance','PerformanceAcceptance')][string]$AcceptanceProfile='StaticReview',[string]$OutputPath)
$ErrorActionPreference='Stop';$OutputEncoding=[Console]::OutputEncoding=[Text.UTF8Encoding]::new($false)
function Read-Json([string]$p){if(-not(Test-Path -LiteralPath $p -PathType Leaf)){throw "PLAN_INPUT_MISSING:$p"};Get-Content -LiteralPath $p -Raw -Encoding UTF8|ConvertFrom-Json}
function Hash-Object($v){$bytes=[Text.Encoding]::UTF8.GetBytes(($v|ConvertTo-Json -Compress -Depth 40));$sha=[Security.Cryptography.SHA256]::Create();try{([BitConverter]::ToString($sha.ComputeHash($bytes))).Replace('-','').ToLowerInvariant()}finally{$sha.Dispose()}}
$goal=Read-Json $GoalRevisionPath;$route=Read-Json $RoutePlanPath;$layers=@('structure','implementation','presentation','performance');$abcd=@('bounded-tool-action','failure-recovery','branch-evaluation','state-transition-guard','environment-trust-gate','audit-evidence-chain');$stages=@('requirement-facts','player-outcomes','lexical-deanchor','seed-divergence','tree-expansion','global-convergence','interaction-graph','adaptive-weighting','player-replay','counterplay-audit','complexity-prune','candidate-tournament','final-decision')
$root=(Get-Location).Path;$branch=(& git -C $root branch --show-current 2>$null).Trim();$head=(& git -C $root rev-parse HEAD 2>$null).Trim();$status=(& git -C $root status --porcelain=v1 2>$null)-join "`n";$worktreeFingerprint=Hash-Object ([ordered]@{branch=$branch;head=$head;status=$status});$sourceSnapshotHash=Hash-Object ([ordered]@{goal=(Hash-Object $goal);route=(Hash-Object $route);worktree=$worktreeFingerprint});$runtimeEvidenceRequirements=if($AcceptanceProfile -eq 'RuntimeAcceptance'){@('unityCompilation','playModeReceipt','presentationTimeline')}elseif($AcceptanceProfile -eq 'PerformanceAcceptance'){@('profilerCapture','playerBuild','gcCpuMemoryBaseline','replayComparison')}else{@()}
$plan=[ordered]@{schemaVersion=1;planType='es-game-core-loop-validation';taskId=$TaskId;acceptanceProfile=$AcceptanceProfile;goalRevisionPath=$GoalRevisionPath;goalRevisionHash=(Hash-Object $goal);routePlanPath=$RoutePlanPath;routePlanHash=(Hash-Object $route);sourceSnapshotHash=$sourceSnapshotHash;branch=$branch;head=$head;worktreeFingerprint=$worktreeFingerprint;authorization=[ordered]@{kind='plan-only';runtimeAuthorized=$false};stateMachine='es.game-core-loop.validation-state.v1';initialState='intake';finalState='closed';requiredAgents=$layers;agentAssignments=@($layers|ForEach-Object{[ordered]@{agentId="game-core-loop-$_";layer=$_;scope="$_-validation";requiredReceipt=$true}});abcdCapabilities=$abcd;innovationRunStages=$stages;requiredEvidence=@('taskId','layer','entryPoint','expected','observed','status','sourceHash','runtimeStatus','claimsNotProven','planHash','sourceSnapshotHash');runtimeEvidenceRequirements=$runtimeEvidenceRequirements;runtimePolicy=[ordered]@{authorized=$false;status='runtime-not-run';requiresExplicitUserAuthorization=$true};nonClaims=@('Unity compilation','PlayMode presentation','Profiler/performance','Player/IL2CPP/release');planHash=''};$plan.planHash=Hash-Object $plan;$json=$plan|ConvertTo-Json -Depth 20
if([string]::IsNullOrWhiteSpace($OutputPath)){$json}else{$full=[IO.Path]::GetFullPath($OutputPath);$parent=Split-Path -Parent $full;if($parent){New-Item -ItemType Directory -Force -Path $parent|Out-Null};[IO.File]::WriteAllText($full,$json,[Text.UTF8Encoding]::new($false));$plan}
