[CmdletBinding()]
param([Parameter(Mandatory=$true)][string]$ProjectRoot,[switch]$Json)
$ErrorActionPreference='Stop'; $root=(Resolve-Path -LiteralPath $ProjectRoot).Path; $checks=[Collections.Generic.List[object]]::new()
function Add-Check([string]$Name,[string]$Status,[string]$Detail){$checks.Add([pscustomobject]@{name=$Name;status=$Status;detail=$Detail})}
try { & (Join-Path $root 'Documentation/AIKnowledge/tools/Test-ESWebKnowledgeCoverage.ps1') -ProjectRoot $root -Json | Out-Null; Add-Check 'coverage-matrix' 'passed' '11 domains and canonical bindings closed' } catch { Add-Check 'coverage-matrix' 'failed' $_.Exception.Message }
try { & (Join-Path $root 'Documentation/AIKnowledge/tools/Test-ESWebKnowledgeExternalSourcePlan.ps1') -ProjectRoot $root -Json | Out-Null; Add-Check 'external-source-plan' 'passed' 'deferred plan boundaries and budgets valid' } catch { Add-Check 'external-source-plan' 'failed' $_.Exception.Message }
$webEntries=Get-ChildItem (Join-Path $root 'Documentation/AIKnowledge/entries') -Filter 'web-*.md' | Sort-Object Name
$entryFailures=0; foreach($f in $webEntries){ try { & (Join-Path $root '.agents/skills/es-knowledge-creator/scripts/Test-ESKnowledgeEntry.ps1') -ProjectRoot $root -EntryPath ('Documentation/AIKnowledge/entries/'+$f.Name) | Out-Null } catch { $entryFailures++ } }
if($entryFailures -eq 0){Add-Check 'entry-contracts' 'passed' "$($webEntries.Count) Web entries passed"}else{Add-Check 'entry-contracts' 'failed' "$entryFailures Web entries failed"}
try { & (Join-Path $root '.agents/skills/es-utf8-guard/scripts/Test-ESUtf8.ps1') -ProjectRoot $root -Path @('Documentation/AIKnowledge/KnowledgeIndex.yaml','Documentation/AIKnowledge/RouteProbeRegistry.json','Documentation/AIKnowledge/WebKnowledgeCoverageMatrix.yaml','Documentation/AIKnowledge/WebKnowledgeExternalSourcePlan.yaml') -Json | Out-Null; Add-Check 'utf8' 'passed' 'index, registry and matrices are strict UTF-8' } catch { Add-Check 'utf8' 'failed' $_.Exception.Message }
$routeOutput=& (Join-Path $root 'Documentation/AIKnowledge/tools/Test-ESKnowledgeRouteProbeRegistry.ps1') -ProjectRoot $root 2>&1 | Out-String; $webRouteFindings=0; try { $routeJson=$routeOutput | ConvertFrom-Json; $webRouteFindings=@($routeJson.findings | Where-Object {$_.probeId -like 'web-*'}).Count } catch { $webRouteFindings=1 }
if($webRouteFindings -eq 0){Add-Check 'web-route-probes' 'passed' 'all Web probes pass; unrelated baseline findings are excluded'}else{Add-Check 'web-route-probes' 'failed' "$webRouteFindings Web probe findings"}
$failed=@($checks|Where-Object {$_.status -eq 'failed'}); $result=[ordered]@{validator='es-web-knowledge-static-gate';status=if($failed.Count -eq 0){'passed'}else{'blocked'};staticStatus=if($failed.Count -eq 0){'static-passed'}else{'static-blocked'};checks=@($checks);runtimeStatus='runtime-not-run';nonClaims=@('No browser, network, Unity, performance, or production claims')}; $result|ConvertTo-Json -Depth 8; if($failed.Count -gt 0){exit 1}
