[CmdletBinding()]
param(
 [Parameter(Mandatory=$true)][string]$CandidatePath,
 [Parameter(Mandatory=$true)][string]$OutputPath
)
$ErrorActionPreference='Stop';$root=(Resolve-Path '.').Path
function ReadJ([string]$p){$f=if([IO.Path]::IsPathRooted($p)){$p}else{Join-Path $root $p};if(-not(Test-Path -LiteralPath $f -PathType Leaf)){throw 'blocked.web-normalizer.candidate-missing'};[Text.UTF8Encoding]::new($false,$true).GetString([IO.File]::ReadAllBytes($f))|ConvertFrom-Json}
$doc=ReadJ $CandidatePath;$candidates=@();if($doc.PSObject.Properties['candidates']){$candidates=@($doc.candidates)}elseif($doc.PSObject.Properties['selectedCandidate']){$candidates=@($doc.selectedCandidate)}else{throw 'blocked.web-normalizer.candidate-set-missing'}
$selected=@($candidates|?{$_.decision -eq 'selected' -or $_.status -eq 'selected'}|Select-Object -First 1);if($selected.Count -ne 1){throw 'blocked.web-normalizer.selected-candidate-required'};$c=$selected[0]
$w=$c.webDesign;if($null -eq $w){throw 'blocked.web-normalizer.web-design-missing'}
foreach($n in @('objectiveBrief','securityContract','semanticHtml','informationArchitecture','visualDirection','interactionModel','implementationPlan','filesToCreate','filesToModify','riskAssessment','rejectedAlternatives','componentInventory','interactionStateGraph','responsiveMatrix','motionTimeline','a11yChecks','interactionContracts','viewContracts','detailContract')){if($null -eq $w.PSObject.Properties[$n]){throw "blocked.web-normalizer.web-design-field-missing:$n"}}
if([string]::IsNullOrWhiteSpace([string]$c.aiAnalysis) -or [string]$c.aiAnalysis.Length -lt 40 -or [string]::IsNullOrWhiteSpace([string]$c.execution) -or $null -eq $c.returnReceipt -or $null -eq $c.evidence -or $null -eq $c.provenance){throw 'blocked.web-normalizer.evidence-incomplete'}
if([string]::IsNullOrWhiteSpace([string]$doc.providerRunId)){throw 'blocked.web-normalizer.provider-run-id-required'}
$mode=if($doc.generationMode){[string]$doc.generationMode}else{throw 'blocked.web-normalizer.generation-mode-required'};$out=[ordered]@{schemaVersion=1;recordType='AiWebDesignModelResponse';providerRunId=[string]$doc.providerRunId;responses=@([ordered]@{phase='page-design-instantiation';generationMode=$mode;round=0;outputs=@([ordered]@{aiAnalysis=[string]$c.aiAnalysis;execution=[string]$c.execution;returnReceipt=$c.returnReceipt;evidence=$c.evidence;provenance=$c.provenance;objectiveBrief=$w.objectiveBrief;securityContract=$w.securityContract;semanticHtml=$w.semanticHtml;informationArchitecture=$w.informationArchitecture;visualDirection=$w.visualDirection;interactionModel=$w.interactionModel;implementationPlan=$w.implementationPlan;filesToCreate=$w.filesToCreate;filesToModify=$w.filesToModify;riskAssessment=$w.riskAssessment;rejectedAlternatives=$w.rejectedAlternatives;componentInventory=$w.componentInventory;interactionStateGraph=$w.interactionStateGraph;responsiveMatrix=$w.responsiveMatrix;motionTimeline=$w.motionTimeline;a11yChecks=$w.a11yChecks;interactionContracts=$w.interactionContracts;viewContracts=$w.viewContracts;detailContract=$w.detailContract})})};$f=if([IO.Path]::IsPathRooted($OutputPath)){$OutputPath}else{Join-Path $root $OutputPath};$d=Split-Path -Parent $f;New-Item -ItemType Directory -Force $d|Out-Null;[IO.File]::WriteAllText($f,($out|ConvertTo-Json -Depth 80),[Text.UTF8Encoding]::new($false));[pscustomobject]@{status='converted';outputPath=$f;generationMode=$mode;candidateId=$c.candidateId}
