using UnityEngine;
using ES;

namespace ES.Examples
{
    /// <summary>
    /// SimpleScriptMaker API 演示 - 脚本生成工具
    /// 提供动态生成C#代码片段和文件的功能
    /// 注意：主要用于Editor模式下的代码生成
    /// </summary>
    public class Example_SimpleScriptMaker : MonoBehaviour
    {
        private void Start()
        {
            Debug.Log("=== SimpleScriptMaker API 演示 ===");
            Debug.Log("注意：此工具主要在Editor模式下使用");

            // ========== 创建类内容 ==========
            Debug.Log("--- 创建类内容 ---");

            // 1. 创建简单类定义
            string classContent = ESDesignUtility.SimpleScriptMaker.CreateClassContentByString(
                className: "MyTestClass",
                parent: ": MonoBehaviour",
                Attribute: "[RequireComponent(typeof(Rigidbody))]"
            );
            Debug.Log($"类定义:\n{classContent}");

            // 2. 创建带内容的类
            string insideClass = @"
    void Start()
    {
        Debug.Log(""Hello from generated script!"");
    }

    public int health = 100;
    public string playerName = ""Player"";
";

            string fullClass = ESDesignUtility.SimpleScriptMaker.CreateClassContentByString(
                className: "PlayerController",
                insideClass: insideClass,
                parent: ": MonoBehaviour",
                Attribute: "",
                beforeClassName: "// Generated class\n"
            );
            Debug.Log($"完整类:\n{fullClass}");

            // ========== 创建字段 ==========
            Debug.Log("--- 创建字段 ---");

            // 3. 创建公开字段
            string field1 = ESDesignUtility.SimpleScriptMaker.CreateFieldContent(
                typeName: "int",
                fieldName: "score",
                modifier: "public",
                valueDefine: " = 0",
                attribute: "[SerializeField]"
            );
            Debug.Log($"字段1: {field1}");

            // 4. 创建私有字段
            string field2 = ESDesignUtility.SimpleScriptMaker.CreateFieldContent(
                typeName: "string",
                fieldName: "_playerName",
                modifier: "private",
                valueDefine: " = \"Default\"",
                attribute: ""
            );
            Debug.Log($"字段2: {field2}");

            // ========== 创建参数 ==========
            Debug.Log("--- 创建参数 ---");

            // 5. 创建方法参数
            string param = ESDesignUtility.SimpleScriptMaker.CreateParaOrDefineContent(
                typeName: "float",
                itName: "damage",
                modifier: "",
                valueDefine: " = 10f",
                isDefine: false
            );
            Debug.Log($"参数: {param}");

            // 6. 创建变量定义
            string define = ESDesignUtility.SimpleScriptMaker.CreateParaOrDefineContent(
                typeName: "Vector3",
                itName: "position",
                modifier: "",
                valueDefine: " = Vector3.zero",
                isDefine: true
            );
            Debug.Log($"定义: {define}");

            // ========== 创建方法 ==========
            Debug.Log("--- 创建方法 ---");

            // 7. 创建简单方法（手动拼接）
            string methodCode = @"
    public void Attack()
    {
        Debug.Log(""Attack!""  );
    }";
            Debug.Log($"方法代码:\n{methodCode}");

            // 8. 创建带参数的方法（手动拼接）
            string complexMethodCode = @"
    public void TakeDamage(int damage, bool isCritical)
    {
        if (isCritical)
            damage *= 2;
        health -= damage;
    }";
            Debug.Log($"复杂方法:\n{complexMethodCode}");

            // ========== 创建完整脚本 ==========
            Debug.Log("--- 创建完整脚本 ---");

            // 9. 生成完整脚本（不实际创建文件）
            string scriptCode = ESDesignUtility.SimpleScriptMaker.CreateScriptBounds(
                Folderpath: "Assets/Scripts",
                fileName: "GeneratedScript.cs",
                using_: "using System.Collections.Generic;",
                nameSpace: "ES.Generated",
                content: fullClass,
                TruelyCreate: false  // 仅生成代码，不创建文件
            );
            Debug.Log($"完整脚本预览:\n{scriptCode}");

#if UNITY_EDITOR
            // 10. 实际创建脚本文件（仅Editor模式）
            // 注意：这会在项目中实际创建文件
            /*
            ESDesignUtility.SimpleScriptMaker.CreateScriptEasy(
                Folderpath: "Assets/Scripts/Generated",
                className: "AutoGeneratedClass",
                parent: ": MonoBehaviour",
                Attribute: "",
                nameSpace: "ES.Generated"
            );
            Debug.Log("已创建脚本文件（仅Editor有效）");
            */
#endif

            // ========== 实用示例：生成数据类 ==========
            Debug.Log("--- 生成数据类示例 ---");

            // 11. 生成一个数据类
            string dataFields = @"
    public string itemName;
    public int itemID;
    public float price;
    public bool isStackable;

    public ItemData(string name, int id, float price, bool stackable)
    {
        this.itemName = name;
        this.itemID = id;
        this.price = price;
        this.isStackable = stackable;
    }
";

            string dataClass = ESDesignUtility.SimpleScriptMaker.CreateClassContentByString(
                className: "ItemData",
                insideClass: dataFields,
                parent: "",
                Attribute: "[System.Serializable]"
            );

            string dataScript = ESDesignUtility.SimpleScriptMaker.CreateScriptBounds(
                Folderpath: "Assets/Scripts/Data",
                fileName: "ItemData.cs",
                using_: "",
                nameSpace: "ES.Data",
                content: dataClass,
                TruelyCreate: false
            );

            Debug.Log($"数据类脚本:\n{dataScript}");

            // ========== 使用提示 ==========
            Debug.Log("\n=== 使用提示 ===");
            Debug.Log("• SimpleScriptMaker主要用于Editor工具中动态生成代码");
            Debug.Log("• TruelyCreate=false 可以先预览代码，确认无误后再创建");
            Debug.Log("• 适合生成重复性代码、数据类、配置类等");
            Debug.Log("• 记得设置正确的命名空间和using语句");
        }
    }
}
