[CmdletBinding()]
param([Parameter(Mandatory=$true)][string]$PromptText,[string]$WarningPath,[string]$WarningHash,[string[]]$RequiredReads=@(),[string[]]$MustPreserve=@(),[string]$OutputPath)
$ErrorActionPreference='Stop';if([string]::IsNullOrWhiteSpace($PromptText)){throw 'PROMPT_TEXT_REQUIRED'}
$utf8=[Text.UTF8Encoding]::new($false,$true)
function Get-Hash([byte[]]$b){$s=[Security.Cryptography.SHA256]::Create();try{([BitConverter]::ToString($s.ComputeHash($b))).Replace('-','').ToLowerInvariant()}finally{$s.Dispose()}}
function Get-TextHash([string]$t){Get-Hash $utf8.GetBytes($t)}
$prompt=$PromptText.Trim();$ph=Get-TextHash $prompt;$preserve=@($MustPreserve|?{$_});if(!$preserve){$preserve=@('preserve original user objective; expansion is not authorization','preserve AIWarning P0, permission and evidence boundaries','do not delete or overwrite authoritative source, Warning, Knowledge or index')}
$reads=@($RequiredReads|?{$_}|Select-Object -Unique);$key=Get-TextHash ("$ph`:$WarningPath`:$WarningHash`:$($reads -join '|')")
$source=[ordered]@{promptHash=$ph;capturedAtUtc=(Get-Date).ToUniversalTime().ToString('O')};if($WarningPath){$source.warningPath=$WarningPath.Replace('\','/');if($WarningHash){$source.warningHash=$WarningHash}}
$result=[ordered]@{schemaVersion=1;recordType='PromptExpansionCandidate';status='expanded';idempotencyKey=$key;source=$source;expandedPrompt=[ordered]@{objective=$prompt;scope=@('execute only within the original user objective','read only listed Warning/Knowledge/RequiredReads','verify evidence first and disclose unproven items');mustPreserve=$preserve;acceptanceSignals=@('map each expanded item to the original objective','provide rereadable evidence or mark key claims unproven','do not execute unauthorized Runtime, Unity, Profiler, Player, IL2CPP or release actions');requiredReads=$reads;nonGoals=@('expansion does not change user authorization','expansion does not replace AIWarning, source or Knowledge authority','do not auto Apply or write formal Knowledge');evidencePlan=@('record prompt SHA-256 and snapshot time','use current paths and hashes for Warning/Knowledge references','return review or blocked on validation failure; never guess missing facts')};nonClaims=@('derived candidate only; not authorization, Apply or formal Knowledge registration','Runtime, Unity, Profiler, Player, IL2CPP and release behavior were not executed')}
$json=$result|ConvertTo-Json -Depth 12
if($OutputPath){$full=[IO.Path]::GetFullPath($OutputPath);$dir=Split-Path $full -Parent;[IO.Directory]::CreateDirectory($dir)|Out-Null;$tmp="$full.tmp.$([Guid]::NewGuid().ToString('N'))";[IO.File]::WriteAllText($tmp,$json,(New-Object Text.UTF8Encoding($false)));if(Test-Path -LiteralPath $full){$existing=[IO.File]::ReadAllText($full);if($existing -ne $json){throw 'PROMPT_EXPANSION_OUTPUT_CONFLICT'}}else{[IO.File]::Move($tmp,$full)};if(Test-Path -LiteralPath $tmp){Remove-Item -LiteralPath $tmp -Force}}
$json
