Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
function ConvertTo-LgCanonical($v){if($null -eq $v){return 'null'};if($v -is [string]){return ($v|ConvertTo-Json -Compress)};if($v -is [bool]){return $(if($v){'true'}else{'false'})};if($v -is [Collections.IDictionary]){return '{'+((@($v.Keys|%{[string]$_}|sort)|%{('{0}:{1}' -f ($_|ConvertTo-Json -Compress),(ConvertTo-LgCanonical $v[$_]))})-join ',')+'}'};if($v -is [pscustomobject]){return '{'+((@($v.PSObject.Properties|sort Name)|%{('{0}:{1}' -f ($_.Name|ConvertTo-Json -Compress),(ConvertTo-LgCanonical $_.Value))})-join ',')+'}'};if($v -is [Collections.IEnumerable]){return '['+((@($v)|%{ConvertTo-LgCanonical $_})-join ',')+']'};return [string]$v}
function Get-LgHash($v){$sha=[Security.Cryptography.SHA256]::Create();try{([BitConverter]::ToString($sha.ComputeHash([Text.Encoding]::UTF8.GetBytes((ConvertTo-LgCanonical $v)))).Replace('-','').ToLowerInvariant())}finally{$sha.Dispose()}}
function New-ESLangGraphState { param([Parameter(Mandatory)][string]$GraphId,[Parameter(Mandatory)][string]$TaskId,[hashtable]$Values=@{}) $vals=[ordered]@{};foreach($k in $Values.Keys){$vals[$k]=$Values[$k]};[pscustomobject]@{schemaVersion=1;graphId=$GraphId;taskId=$TaskId;status='ready';currentNode='';values=$vals;sequence=0;events=@();checkpointHash=$null} }
function Add-LgEvent { param([Parameter(Mandatory)]$State,[Parameter(Mandatory)][string]$Type,[hashtable]$Payload=@{}) $prev=if($State.events.Count){$State.events[-1].eventHash}else{$null};$pl=[ordered]@{};foreach($k in $Payload.Keys){$pl[$k]=$Payload[$k]};$e=[ordered]@{sequence=([int]$State.sequence+1);eventType=$Type;payload=$pl;previousEventHash=$prev};$e.eventHash=Get-LgHash $e;$State.sequence=$e.sequence;$State.events=@($State.events)+[pscustomobject]$e;return $State }
function Invoke-ESLangGraphNode { param([Parameter(Mandatory)]$State,[Parameter(Mandatory)][string]$NodeId,[hashtable]$Update=@{},[switch]$Interrupt) if($State.status -eq 'interrupted' -and -not $Interrupt){throw 'graph is interrupted; resume is required'};$State.currentNode=$NodeId;$State.values=[ordered]@{}+$State.values;foreach($k in $Update.Keys){$State.values[$k]=$Update[$k]};$null=Add-LgEvent $State 'NodeCompleted' @{nodeId=$NodeId;updateHash=Get-LgHash $Update};if($Interrupt){$State.status='interrupted';$null=Add-LgEvent $State 'InterruptRaised' @{nodeId=$NodeId}}else{$State.status='running'};return $State }
function New-ESLangGraphCheckpoint { param([Parameter(Mandatory)]$State) $base=[ordered]@{schemaVersion=1;checkpointType='LangGraphCheckpoint';graphId=$State.graphId;taskId=$State.taskId;status=$State.status;currentNode=$State.currentNode;values=$State.values;sequence=$State.sequence;events=$State.events};$base.checkpointHash=Get-LgHash $base;[pscustomobject]$base }
function Resume-ESLangGraphCheckpoint { param([Parameter(Mandatory)]$Checkpoint,[Parameter(Mandatory)][string]$TaskId) if($Checkpoint.taskId -cne $TaskId){throw 'checkpoint task mismatch'};$base=[ordered]@{};foreach($p in $Checkpoint.PSObject.Properties){if($p.Name-ne'checkpointHash'){$base[$p.Name]=$p.Value}};if((Get-LgHash $base)-cne[string]$Checkpoint.checkpointHash){throw 'checkpoint hash mismatch'};$s=[pscustomobject]$base;$s.status='running';$s.events=@($s.events)+[pscustomobject]([ordered]@{sequence=([int]$s.sequence+1);eventType='ResumeAccepted';payload=@{taskId=$TaskId};previousEventHash=$s.events[-1].eventHash;eventHash=''});$s.events[-1].eventHash=Get-LgHash ([ordered]@{sequence=$s.events[-1].sequence;eventType='ResumeAccepted';payload=$s.events[-1].payload;previousEventHash=$s.events[-1].previousEventHash});$s.sequence=[int]$s.sequence+1;return $s }
function Test-ESLangGraphEventChain { param([Parameter(Mandatory)]$State) $prev=$null;foreach($e in $State.events){$base=[ordered]@{sequence=$e.sequence;eventType=$e.eventType;payload=$e.payload;previousEventHash=$prev};if((Get-LgHash $base)-cne[string]$e.eventHash){throw 'event chain hash mismatch'};$prev=$e.eventHash};[pscustomobject]@{status='passed';eventCount=$State.events.Count;lastEventHash=$prev} }
Export-ModuleMember -Function New-ESLangGraphState,Invoke-ESLangGraphNode,New-ESLangGraphCheckpoint,Resume-ESLangGraphCheckpoint,Test-ESLangGraphEventChain,Get-LgHash
