Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
function ConvertTo-LettaCanonical($v){if($null -eq $v){return 'null'};if($v -is [string]){return ($v|ConvertTo-Json -Compress)};if($v -is [bool]){return $(if($v){'true'}else{'false'})};if($v -is [Collections.IDictionary]){return '{'+((@($v.Keys|%{[string]$_}|sort)|%{('{0}:{1}' -f ($_|ConvertTo-Json -Compress),(ConvertTo-LettaCanonical $v[$_]))})-join ',')+'}'};if($v -is [pscustomobject]){return '{'+((@($v.PSObject.Properties|sort Name)|%{('{0}:{1}' -f ($_.Name|ConvertTo-Json -Compress),(ConvertTo-LettaCanonical $_.Value))})-join ',')+'}'};if($v -is [Collections.IEnumerable]){return '['+((@($v)|%{ConvertTo-LettaCanonical $_})-join ',')+']'};return [string]$v}
function Get-LettaHash($v){$sha=[Security.Cryptography.SHA256]::Create();try{([BitConverter]::ToString($sha.ComputeHash([Text.Encoding]::UTF8.GetBytes((ConvertTo-LettaCanonical $v)))).Replace('-','').ToLowerInvariant())}finally{$sha.Dispose()}}
function New-ESLettaMemory { param([Parameter(Mandatory)][string]$BlockId,[Parameter(Mandatory)][string]$Value,[int]$MaxChars=8192,[switch]$ReadOnly) if($Value.Length -gt $MaxChars){throw 'block-overflow'};[pscustomobject]@{schemaVersion=1;blockId=$BlockId;value=$Value;version=1;maxChars=$MaxChars;readOnly=[bool]$ReadOnly;blockHash=Get-LettaHash ([ordered]@{blockId=$BlockId;value=$Value;version=1;maxChars=$MaxChars;readOnly=[bool]$ReadOnly})} }
function Update-ESLettaMemory { param([Parameter(Mandatory)]$Block,[Parameter(Mandatory)][string]$Value,[Parameter(Mandatory)][int]$ExpectedVersion,[switch]$UserConfirmed) if($Block.readOnly){throw 'read-only block'};if($ExpectedVersion -ne [int]$Block.version){throw 'stale-block'};if(-not $UserConfirmed){throw 'confirmation-required'};if($Value.Length -gt [int]$Block.maxChars){throw 'block-overflow'};$next=[ordered]@{schemaVersion=1;blockId=$Block.blockId;value=$Value;version=([int]$Block.version+1);maxChars=$Block.maxChars;readOnly=$Block.readOnly};$next.blockHash=Get-LettaHash $next;[pscustomobject]$next }
function New-ESLettaContextProjection { param([Parameter(Mandatory)]$Block,[string[]]$ContextBlocks=@('task-focus','goal-revision')) $base=[ordered]@{schemaVersion=1;projectionType='LettaContextProjection';blockId=$Block.blockId;blockVersion=[int]$Block.version;value=$Block.value;includedBlocks=@($ContextBlocks);sourceBlockHash=$Block.blockHash};$base.projectionHash=Get-LettaHash $base;[pscustomobject]$base }
function Test-ESLettaProjectionReplay { param([Parameter(Mandatory)]$Projection) $base=[ordered]@{};foreach($p in $Projection.PSObject.Properties){if($p.Name-ne'projectionHash'){$base[$p.Name]=$p.Value}};if((Get-LettaHash $base)-cne[string]$Projection.projectionHash){throw 'projection-divergence'};[pscustomobject]@{status='passed';projectionHash=$Projection.projectionHash} }
Export-ModuleMember -Function New-ESLettaMemory,Update-ESLettaMemory,New-ESLettaContextProjection,Test-ESLettaProjectionReplay,Get-LettaHash
