$ErrorActionPreference = 'Stop'
Import-Module (Join-Path $PSScriptRoot 'ESTaskFocusContext.psm1') -Force
Import-Module (Join-Path $PSScriptRoot 'ESTaskFocusRuntimeAdapter.psm1') -Force
Import-Module (Join-Path $PSScriptRoot '..\TaskContextRuntime\ESTaskContextRuntime.psm1') -Force
. (Join-Path $PSScriptRoot '..\TaskContextRuntime\Test-ESTaskContextRoutePlanFixture.ps1')
$root = Join-Path ([IO.Path]::GetTempPath()) ('es-focus-runtime-integration-' + [guid]::NewGuid().ToString('N'))
New-Item -ItemType Directory -Path $root -Force | Out-Null
Initialize-ESTestRoutePlanRepository $root
[IO.File]::WriteAllText((Join-Path $root 'source.txt'), 'focus integration', [Text.UTF8Encoding]::new($false))
$goal = New-ESGoalRevision -ProjectRoot $root -StoreRoot 'state' -GoalId 'goal-focus' -GoalRevision 'r1' -Scope @('source.txt') -AcceptanceIntent 'static' -Budget ([ordered]@{maxReads=8;maxSeconds=30})
$plan = New-ESTestRoutePlan -Root $root -Goal $goal -Profile 'governance'
$focusProposal = New-TaskFocusProposal -Focus 'focus runtime integration' -AllowedScope @('source.txt') -ForbiddenExpansion @('Unity','Git','Network') -RequiredReads @('AGENTS.md') -AcceptanceSignals @('task-created')
$pending = Invoke-TaskFocusProposal -Current $null -Proposal $focusProposal
$confirmed = Invoke-TaskFocusProposal -Current $pending -Proposal $focusProposal -UserDecision confirm -ExpectedRevision $pending.revision
$request = New-ESTaskContextRuntimeRequestFromFocus -FocusContext $confirmed -TaskId 'focus-task' -RoutePlanPath $plan.path -GoalRevisionPath $goal.path -AcceptanceProfileId 'static' -OutcomeEvaluatorId 'platform.task-context-outcome-v1' -RequiredClaims @('source-integrity') -RequiredClaimVerifiers @{ 'source-integrity'='platform.file-hash-manifest-v1' } -RequestedSourceScope 'source.txt' -IdempotencyKey 'focus-task-create'
$checkpoint = New-FocusCheckpoint -Context $confirmed -TaskId 'focus-task'
$request = New-ESTaskContextRuntimeRequestFromFocusCheckpoint -Checkpoint $checkpoint -CheckpointTaskId 'focus-task' -TaskId 'focus-task' -RoutePlanPath $plan.path -GoalRevisionPath $goal.path -AcceptanceProfileId 'static' -OutcomeEvaluatorId 'platform.task-context-outcome-v1' -RequiredClaims @('source-integrity') -RequiredClaimVerifiers @{ 'source-integrity'='platform.file-hash-manifest-v1' } -RequestedSourceScope 'source.txt' -IdempotencyKey 'focus-task-create'
$commandInput = [ordered]@{schemaVersion=1;recordType='TaskFocusRuntimeCommandInput';storeRoot='state';taskId='command-focus-task';planHash=$plan.routePlanHash;routePlanPath=$plan.path;goalRevisionPath=$goal.path;acceptanceProfileId='static';outcomeEvaluatorId='platform.task-context-outcome-v1';requiredClaims=@('source-integrity');requiredClaimVerifiers=@{'source-integrity'='platform.file-hash-manifest-v1'};requestedSourceScope=@('source.txt');idempotencyKey='command-focus-create';maxEvidenceAgeHours=24;allowUnverifiedClaims=$false;focusContext=$confirmed}
[IO.File]::WriteAllText((Join-Path $root 'focus-command-input.json'),($commandInput|ConvertTo-Json -Depth 20),[Text.UTF8Encoding]::new($false))
$commandScript = (Resolve-Path (Join-Path $PSScriptRoot '..\TaskContextRuntime\Invoke-ESTaskContextRuntime.ps1')).Path
$commandOutput = & powershell.exe -NoProfile -ExecutionPolicy Bypass -File $commandScript -Action Create -InputPath 'focus-command-input.json' -ProjectRoot $root
$commandState = ($commandOutput -join "`n") | ConvertFrom-Json
$commandCreated = $commandState.taskId -eq 'command-focus-task' -and $commandState.taskStatus -eq 'Active'
$invalidInput = $commandInput | ConvertTo-Json -Depth 20 | ConvertFrom-Json
$invalidInput.focusContext.status = 'pending-confirmation'
[IO.File]::WriteAllText((Join-Path $root 'focus-command-invalid.json'),($invalidInput|ConvertTo-Json -Depth 20),[Text.UTF8Encoding]::new($false))
$savedErrorActionPreference=$ErrorActionPreference;$ErrorActionPreference='Continue';$invalidOutput = & powershell.exe -NoProfile -ExecutionPolicy Bypass -File $commandScript -Action Create -InputPath 'focus-command-invalid.json' -ProjectRoot $root 2>&1;$ErrorActionPreference=$savedErrorActionPreference
$invalidExitCode = $LASTEXITCODE
$invalidRejected = $invalidExitCode -ne 0 -and (($invalidOutput -join "`n") -match 'focusContext schema validation failed')
$state = New-ESTaskContextTask -ProjectRoot $root -StoreRoot 'state' -TaskId $request.taskId -PlanHash $plan.routePlanHash -RoutePlanPath $request.routePlanPath -GoalRevisionPath $request.goalRevisionPath -AcceptanceProfileId $request.acceptanceProfileId -OutcomeEvaluatorId $request.outcomeEvaluatorId -RequiredClaim $request.requiredClaims[0] -RequiredClaimVerifier $request.requiredClaimVerifiers -RequestedSourceScope $request.requestedSourceScope -IdempotencyKey $request.idempotencyKey -FocusContextId $request.focusContextId -FocusRevision $request.focusRevision -FocusProposalHash $request.focusProposalHash -FocusReceiptHash $request.focusReceiptHash -FocusScopeHash $request.focusScopeHash
$staleRejected = $false
try { Confirm-ESTaskSourceScope -ProjectRoot $root -StoreRoot 'state' -TaskId $request.taskId -ExpectedTaskRevision 0 -ExpectedContextVersion 0 -IdempotencyKey 'stale-focus-confirm' | Out-Null } catch { $staleRejected = $_.Exception.Message -like 'CAS conflict:*' }
$confirmedState = Confirm-ESTaskSourceScope -ProjectRoot $root -StoreRoot 'state' -TaskId $request.taskId -ExpectedTaskRevision $state.taskRevision -ExpectedContextVersion $state.contextVersion -IdempotencyKey 'focus-confirm'
$duplicateState = Confirm-ESTaskSourceScope -ProjectRoot $root -StoreRoot 'state' -TaskId $request.taskId -ExpectedTaskRevision $state.taskRevision -ExpectedContextVersion $state.contextVersion -IdempotencyKey 'focus-confirm'
$duplicateNoRevision = $duplicateState.taskRevision -eq $confirmedState.taskRevision -and $duplicateState.contextVersion -eq $confirmedState.contextVersion
$sameKeyConflictRejected = $false
try { Invoke-ESTaskContextTransition -ProjectRoot $root -StoreRoot 'state' -TaskId $request.taskId -Transition Suspend -ExpectedTaskRevision $confirmedState.taskRevision -ExpectedContextVersion $confirmedState.contextVersion -IdempotencyKey 'focus-confirm' | Out-Null } catch { $sameKeyConflictRejected = $_.Exception.Message -eq 'IdempotencyKey is already bound to a different operation.' }
$reloaded = Get-ESTaskContextState -ProjectRoot $root -StoreRoot 'state' -TaskId $request.taskId -VerifyIntegrity
$accepted = New-ESTaskContextTask -ProjectRoot $root -StoreRoot 'state' -TaskId 'focus-accepted' -PlanHash $plan.routePlanHash -RoutePlanPath $plan.path -GoalRevisionPath $goal.path -AcceptanceProfileId 'static' -OutcomeEvaluatorId 'platform.task-context-outcome-v1' -RequiredClaim 'source-integrity' -RequiredClaimVerifier @{ 'source-integrity'='platform.file-hash-manifest-v1' } -RequestedSourceScope 'source.txt' -IdempotencyKey 'focus-accepted-create' -FocusContextId $request.focusContextId -FocusRevision $request.focusRevision -FocusProposalHash $request.focusProposalHash -FocusReceiptHash $request.focusReceiptHash -FocusScopeHash $request.focusScopeHash
$accepted = Confirm-ESTaskSourceScope -ProjectRoot $root -StoreRoot 'state' -TaskId 'focus-accepted' -ExpectedTaskRevision $accepted.taskRevision -ExpectedContextVersion $accepted.contextVersion -IdempotencyKey 'focus-accepted-verify'
$sourceHash = [string]$accepted.verifiedSourceScope[0].sha256
$artifactName = 'focus-accepted-artifact.json'; $artifactPayload = [ordered]@{schemaVersion=1;claimId='source-integrity';sourceScopeHash=$accepted.verifiedSourceScopeHash;observations=@([ordered]@{path='source.txt';expectedSha256=$sourceHash})}
[IO.File]::WriteAllText((Join-Path $root $artifactName),($artifactPayload|ConvertTo-Json -Depth 12),[Text.UTF8Encoding]::new($false))
$artifactHash = (Get-FileHash -LiteralPath (Join-Path $root $artifactName) -Algorithm SHA256).Hash.ToLowerInvariant(); $evidenceName='focus-accepted-evidence.json'; $evidenceContractPath=(Resolve-Path (Join-Path $PSScriptRoot '..\Contracts\es-platform-evidence-v1.schema.json')).Path; $evidenceContractHash=(Get-FileHash -LiteralPath $evidenceContractPath -Algorithm SHA256).Hash.ToLowerInvariant()
$evidencePayload=[ordered]@{schemaVersion=1;contractId='es://automation/contracts/platform-evidence/v1';contractHash=$evidenceContractHash;recordType='CandidateEvidenceSet';taskId='focus-accepted';evidenceSetId='focus-accepted-evidence';capturedUtc=[DateTime]::UtcNow.ToString('o');items=@([ordered]@{claimId='source-integrity';candidateOutcome='passed';capturedUtc=[DateTime]::UtcNow.ToString('o');sourceScopeHash=$accepted.verifiedSourceScopeHash;candidateEvidenceHash=$artifactHash;candidateProducerType='platform';artifactPath=$artifactName});contradictions=@();sourceDrift=@();unverifiedClaims=@()}
[IO.File]::WriteAllText((Join-Path $root $evidenceName),($evidencePayload|ConvertTo-Json -Depth 12),[Text.UTF8Encoding]::new($false))
$accepted = Submit-ESTaskEvidenceSet -ProjectRoot $root -StoreRoot 'state' -TaskId 'focus-accepted' -EvidenceSetPath $evidenceName -ExpectedTaskRevision $accepted.taskRevision -ExpectedContextVersion $accepted.contextVersion -IdempotencyKey 'focus-accepted-evidence'
$accepted = Complete-ESTaskContextTask -ProjectRoot $root -StoreRoot 'state' -TaskId 'focus-accepted' -ExpectedTaskRevision $accepted.taskRevision -ExpectedContextVersion $accepted.contextVersion -IdempotencyKey 'focus-accepted-complete'
$acceptedIntegrity = Test-ESTaskContextIntegrity -ProjectRoot $root -StoreRoot 'state' -TaskId 'focus-accepted'
$receiptBound = $accepted.completionDecision -eq 'accepted' -and $accepted.completionReceipt -ne $null -and $accepted.focusContextId -eq $request.focusContextId -and $acceptedIntegrity.status -eq 'passed'
$identityBound = $state.focusContextId -eq $request.focusContextId -and $state.focusRevision -eq $request.focusRevision -and $state.focusProposalHash -eq $request.focusProposalHash -and $state.focusScopeHash -eq $request.focusScopeHash
$ok = $state.taskStatus -eq 'Active' -and $state.contextStatus -eq 'Live' -and $identityBound -and $receiptBound -and $request.focusProposalHash -eq $confirmed.proposalHash -and $staleRejected -and $confirmedState.taskRevision -eq ($state.taskRevision + 1) -and $duplicateNoRevision -and $sameKeyConflictRejected -and $reloaded.taskId -eq $state.taskId -and $reloaded.taskRevision -eq $confirmedState.taskRevision -and $reloaded.contextVersion -eq $confirmedState.contextVersion -and $commandCreated -and $invalidRejected
[pscustomobject]@{schemaVersion=1;validator='Test-ESTaskFocusRuntimeIntegration';status=$(if($ok){'passed'}else{'failed'});caseCount=9;passedCount=$(if($ok){9}else{0});failedCount=$(if($ok){0}else{9});cases=@([pscustomobject]@{case='confirmed-focus-creates-runtime-task';status=$(if($ok){'passed'}else{'failed'})},[pscustomobject]@{case='focus-identity-frozen-in-task-context';status=$(if($ok -and $identityBound){'passed'}else{'failed'})},[pscustomobject]@{case='focus-identity-bound-to-completion-receipt';status=$(if($ok -and $receiptBound){'passed'}else{'failed'})},[pscustomobject]@{case='runtime-command-focus-input-creates-task';status=$(if($ok -and $commandCreated){'passed'}else{'failed'})},[pscustomobject]@{case='runtime-command-invalid-focus-rejected-before-create';status=$(if($ok -and $invalidRejected){'passed'}else{'failed'})},[pscustomobject]@{case='stale-focus-write-rejected-by-cas';status=$(if($ok){'passed'}else{'failed'})},[pscustomobject]@{case='idempotent-focus-confirm-does-not-revise';status=$(if($ok){'passed'}else{'failed'})},[pscustomobject]@{case='idempotency-key-operation-conflict-rejected';status=$(if($ok){'passed'}else{'failed'})},[pscustomobject]@{case='runtime-get-preserves-focus-created-state';status=$(if($ok){'passed'}else{'failed'})});runtimeStatus='runtime-not-run';claimsNotProven=@('Unity/host runtime','TaskContextRuntime host/production equivalence')}|ConvertTo-Json -Depth 10
if(-not $ok){exit 1}
