[CmdletBinding()]param()
$ErrorActionPreference='Stop'; Import-Module (Join-Path $PSScriptRoot 'ESTaskFocusContext.psm1') -Force; Import-Module (Join-Path $PSScriptRoot '..\Contracts\ESJsonSchemaLite.psm1') -Force
$cases=[Collections.Generic.List[object]]::new(); function Case($n,[scriptblock]$b){try{&$b;[void]$cases.Add([pscustomobject]@{case=$n;status='passed'})}catch{[void]$cases.Add([pscustomobject]@{case=$n;status='failed';finding=$_.Exception.Message})}}
$p=New-TaskFocusProposal -Focus 'TaskFocusContext Phase 1' -Priority elevated -AllowedScope @('ES/Automation/TaskFocusContext') -ForbiddenExpansion @('Unity','Git') -RequiredReads @('AGENTS.md') -AcceptanceSignals @('static replay')
$s=Invoke-TaskFocusProposal -Proposal $p -Current $null; Case 'pending-before-confirm' {if($s.status -ne 'pending-confirmation'){throw 'expected pending'}}
$confirmation=New-FocusConfirmationReceipt -Context $s -UserMessage "user confirmed scope" -Decision confirm
$c=Invoke-TaskFocusProposal -Proposal $p -Current $s -UserDecision confirm -ConfirmationReceipt $confirmation -ExpectedRevision $s.revision; Case 'confirmed-after-user-confirm' {if($c.status -ne 'confirmed' -or $c.focusReceiptHash -ne $confirmation.receiptHash){throw 'expected confirmed with receipt binding'}}
$same=Invoke-TaskFocusProposal -Proposal $p -Current $c -ExpectedRevision $c.revision; Case 'repeat-idempotency' {if($same.proposalHash -ne $c.proposalHash -or $same.revision -ne $c.revision){throw 'not idempotent'}}
$p2=New-TaskFocusProposal -Focus 'other focus'; $amb=Invoke-TaskFocusProposal -Proposal $p2 -Current $c -ExpectedRevision $c.revision; Case 'conflict-ambiguous' {if($amb.status -ne 'ambiguous'){throw 'expected ambiguous'}}
$stale=Invoke-TaskFocusProposal -Proposal $p2 -Current $c -ExpectedRevision 0; Case 'old-revision-conflict' {if($stale.reason -ne 'stale-revision'){throw 'expected stale'}}
Case 'invalid-input' {try{New-TaskFocusProposal -Focus ''}catch{return};throw 'invalid accepted'}
Case 'denied-expansion-data-preserved' {if($p.forbiddenExpansion -notcontains 'Unity'){throw 'boundary missing'}}
Case 'interruption-recovery' {$r=Invoke-TaskFocusProposal -Proposal $p -Current $s -UserDecision confirm -ConfirmationReceipt $confirmation -ExpectedRevision $s.revision;if($r.status -ne 'confirmed'){throw 'recovery failed'}}
Case 'elevated-confirmation-requires-receipt' {try{Invoke-TaskFocusProposal -Proposal $p -Current $s -UserDecision confirm -ExpectedRevision $s.revision|Out-Null;throw 'confirmation without receipt accepted'}catch{if($_.Exception.Message -notlike '*requires a confirmation receipt*'){throw}}}
Case 'focus-identity-frozen' {if($c.focusContextId -notmatch '^FC-' -or $c.focusRevision -ne $c.revision -or $c.focusProposalHash -ne $c.proposalHash -or $c.focusScopeHash.Length -ne 64){throw 'focus identity mismatch'}}
Case 'confirmation-receipt' { if($confirmation.receiptHash.Length -ne 64){throw "receipt hash missing"} }
Case 'context-projection' { $pr=New-FocusContextProjection -Context $c; if($pr.sourceProposalHash -ne $c.proposalHash -or $pr.acceptanceSignals[0] -ne 'static replay'){throw "projection source or acceptance signal mismatch"} }
Case 'focus-schema-valid' { $errors=@(Test-ESJsonSchemaValue -SchemaPath (Join-Path $PSScriptRoot '..\Contracts\es-task-focus-context-v1.schema.json') -Value $c); if($errors.Count -ne 0){throw ('valid FocusContext rejected: ' + ($errors -join '; '))} }
Case 'focus-schema-rejects-nonconfirmed' { $bad=$c|ConvertTo-Json -Depth 20|ConvertFrom-Json; $bad.status='pending-confirmation'; if(@(Test-ESJsonSchemaValue -SchemaPath (Join-Path $PSScriptRoot '..\Contracts\es-task-focus-context-v1.schema.json') -Value $bad).Count -eq 0){throw 'non-confirmed FocusContext accepted'} }
Case 'focus-schema-rejects-unknown-field' { $bad=$c|ConvertTo-Json -Depth 20|ConvertFrom-Json; Add-Member -InputObject $bad -NotePropertyName unexpected -NotePropertyValue 'expansion'; if(@(Test-ESJsonSchemaValue -SchemaPath (Join-Path $PSScriptRoot '..\Contracts\es-task-focus-context-v1.schema.json') -Value $bad).Count -eq 0){throw 'unknown FocusContext field accepted'} }
Case 'checkpoint-roundtrip' { $cp=New-FocusCheckpoint -Context $c -TaskId "task-focus"; $rest=Restore-FocusCheckpoint -Checkpoint $cp -TaskId "task-focus"; if($rest.proposalHash -ne $c.proposalHash){throw "checkpoint restore mismatch"} }
Case 'pending-checkpoint-rejected' { try { New-FocusCheckpoint -Context $s -TaskId 'pending-task' | Out-Null; throw 'pending checkpoint accepted' } catch { if($_.Exception.Message -notlike '*requires confirmed FocusContext*'){throw} } }
Case 'checkpoint-tamper-rejected' { $cp=New-FocusCheckpoint -Context $c -TaskId "task-focus"; $cp.context.focus="tampered"; try { Restore-FocusCheckpoint -Checkpoint $cp -TaskId "task-focus" } catch { return }; throw "tampered checkpoint accepted" }
$failed=@($cases|? status -eq 'failed'); [pscustomobject]@{schemaVersion=1;validator='Test-ESTaskFocusContext';status=$(if($failed.Count){'failed'}else{'passed'});caseCount=$cases.Count;passedCount=($cases|? status -eq 'passed').Count;failedCount=$failed.Count;cases=@($cases);runtimeStatus='runtime-not-run';claimsNotProven=@('Unity/host runtime','external framework runtime')}|ConvertTo-Json -Depth 10; if($failed.Count){exit 1}
