[CmdletBinding()]param([string]$CatalogPath,[string]$MatrixPath)
$ErrorActionPreference='Stop'; if(!$CatalogPath){$CatalogPath=Join-Path $PSScriptRoot '..\Contracts\es-external-agent-feature-catalog-v1.json'};if(!$MatrixPath){$MatrixPath=Join-Path $PSScriptRoot '..\Contracts\es-external-agent-capability-matrix-v1.json'}
$cat=Get-Content -Raw -Encoding UTF8 $CatalogPath|ConvertFrom-Json;$mat=Get-Content -Raw -Encoding UTF8 $MatrixPath|ConvertFrom-Json;$registry=Get-Content -Raw -Encoding UTF8 (Join-Path $PSScriptRoot '..\Contracts\es-external-agent-adapter-registry-v1.json')|ConvertFrom-Json;$cases=[Collections.Generic.List[object]]::new();function C($n,$ok,$f=''){[void]$cases.Add([pscustomobject]@{case=$n;status=$(if($ok){'passed'}else{'failed'});finding=$f})}
$ids=@($cat.features|% featureId);C 'catalog-unique' ((@($ids|sort -Unique).Count -eq $ids.Count)) 'duplicate featureId';C 'framework-coverage' ((@('langgraph','letta','openhands','swe-agent','deepseek-harness'|?{$ids -like "$_.*"}).Count -eq 5)) 'missing framework';
$matIds=@($mat.records|% featureId);C 'matrix-covers-catalog' ((@($ids|?{$_ -notin $matIds}).Count -eq 0)) 'matrix missing feature';C 'status-bounded' ((@($mat.records|?{$_.status -notin $mat.allowedStatuses}).Count -eq 0)) 'unsupported status';C 'source-bound' ((@($cat.features|?{[string]::IsNullOrWhiteSpace($_.sourceUrl)}).Count -eq 0)) 'missing source';
$adapters=@($registry.adapters);C 'adapter-framework-coverage' ((@('langgraph','letta','openhands','swe-agent','deepseek-harness'|?{$adapters.frameworkId -contains $_}).Count -eq 5)) 'missing adapter descriptor';C 'adapter-contract-fields' ((@($adapters|?{$_.operations.Count -lt 1 -or $_.permissionBoundary.Count -lt 1 -or $_.failureSemantics.Count -lt 1 -or $_.evidenceOutputs.Count -lt 1}).Count -eq 0)) 'adapter fields incomplete';
$dshFeatures=@($cat.features|?{$_.frameworkId -eq 'deepseek-harness'});$dshMatrix=@($mat.records|?{$_.featureId -like 'deepseek-harness.*'});$dshAdapter=@($adapters|?{$_.frameworkId -eq 'deepseek-harness'});C 'deepseek-provider-declaration' (($dshFeatures.Count -gt 0 -and @($dshFeatures|?{$_.providerDeclaration -ne 'es-deepseek'}).Count -eq 0) -and ($dshMatrix.Count -gt 0 -and @($dshMatrix|?{$_.providerDeclaration -ne 'es-deepseek'}).Count -eq 0) -and ($dshAdapter.Count -eq 1 -and $dshAdapter[0].providerDeclaration -eq 'es-deepseek')) 'DSH-bound catalog, matrix, and adapter records must declare es-deepseek';
$testJson=& (Join-Path $PSScriptRoot 'Test-ESTaskFocusContext.ps1') | Out-String; $test=$testJson|ConvertFrom-Json; C 'focus-replay' ([string]$test.status -eq 'passed') 'focus replay failed';
$failed=@($cases|? status -eq 'failed');[pscustomobject]@{schemaVersion=1;validator='Test-ESExternalAgentConformance';status=$(if($failed.Count){'failed'}else{'passed'});caseCount=$cases.Count;passedCount=@($cases|? status -eq 'passed').Count;failedCount=$failed.Count;cases=@($cases);runtimeStatus='runtime-not-run';claimsNotProven=@('External framework runtime','Unity/host runtime','accepted capability status')}|ConvertTo-Json -Depth 10;if($failed.Count){exit 1}
