$ErrorActionPreference = 'Stop'
Import-Module (Join-Path $PSScriptRoot 'ESTaskFocusContext.psm1') -Force
Import-Module (Join-Path $PSScriptRoot 'ESTaskFocusRuntimeAdapter.psm1') -Force
$cases = [Collections.Generic.List[object]]::new()
function Case([string]$Name,[scriptblock]$Action) { try { & $Action; [void]$cases.Add([pscustomobject]@{case=$Name;status='passed'}) } catch { [void]$cases.Add([pscustomobject]@{case=$Name;status='failed';error=$_.Exception.Message}) } }
$proposal = New-TaskFocusProposal -Focus 'adapter focus' -AllowedScope @('ES/Automation') -ForbiddenExpansion @('Unity','Git') -RequiredReads @('AGENTS.md') -AcceptanceSignals @('static-test-pass')
$pending = Invoke-TaskFocusProposal -Current $null -Proposal $proposal
$confirmed = Invoke-TaskFocusProposal -Current $pending -Proposal $proposal -UserDecision confirm -ExpectedRevision $pending.revision
$request = New-ESTaskContextRuntimeRequestFromFocus -FocusContext $confirmed -TaskId 'focus-task' -RoutePlanPath 'plan.json' -GoalRevisionPath 'goal.json' -AcceptanceProfileId 'static' -OutcomeEvaluatorId 'platform.task-context-outcome-v1' -RequiredClaims @('source-integrity') -RequiredClaimVerifiers @{ 'source-integrity'='platform.file-hash-manifest-v1' } -RequestedSourceScope 'ES/Automation' -IdempotencyKey 'focus-create'
Case 'confirmed-maps-runtime-request' { if($request.requestType -ne 'TaskFocusRuntimeRequest' -or $request.focusProposalHash -ne $confirmed.proposalHash -or $request.forbiddenExpansion.Count -ne 2){throw 'mapping mismatch'} }
Case 'scope-preserved' { if($request.allowedScope[0] -ne 'ES/Automation' -or $request.requiredReads[0] -ne 'AGENTS.md' -or $request.acceptanceSignals[0] -ne 'static-test-pass'){throw 'focus fields not preserved'} }
Case 'checkpoint-restores-and-maps' { $cp=New-FocusCheckpoint -Context $confirmed -TaskId 'focus-task'; $restored=New-ESTaskContextRuntimeRequestFromFocusCheckpoint -Checkpoint $cp -CheckpointTaskId 'focus-task' -TaskId 'focus-task' -RoutePlanPath 'plan.json' -GoalRevisionPath 'goal.json' -AcceptanceProfileId 'static' -OutcomeEvaluatorId 'platform.task-context-outcome-v1' -RequiredClaims @('source-integrity') -RequestedSourceScope 'ES/Automation' -IdempotencyKey 'checkpoint-create'; if($restored.focusProposalHash -ne $confirmed.proposalHash -or $restored.focusRevision -ne $confirmed.revision){throw 'checkpoint mapping mismatch'} }
Case 'spec-facade-maps-with-one-object' { $spec=[pscustomobject]@{TaskId='focus-task';RoutePlanPath='plan.json';GoalRevisionPath='goal.json';AcceptanceProfileId='static';OutcomeEvaluatorId='platform.task-context-outcome-v1';RequiredClaims=@('source-integrity');RequiredClaimVerifiers=@{'source-integrity'='platform.file-hash-manifest-v1'};RequestedSourceScope='ES/Automation';IdempotencyKey='spec-create'}; $mapped=New-ESTaskContextRuntimeRequestFromFocusSpec -FocusContext $confirmed -RuntimeSpec $spec; if($mapped.taskId -ne 'focus-task' -or $mapped.focusProposalHash -ne $confirmed.proposalHash -or $mapped.requiredClaimVerifiers.'source-integrity' -ne 'platform.file-hash-manifest-v1'){throw 'spec facade mismatch'} }
Case 'spec-facade-requires-contract-fields' { try { New-ESTaskContextRuntimeRequestFromFocusSpec -FocusContext $confirmed -RuntimeSpec ([pscustomobject]@{TaskId='focus-task'}); throw 'incomplete spec accepted' } catch { if($_.Exception.Message -notlike '*RuntimeSpec.RoutePlanPath is required*'){throw} } }
Case 'scope-expansion-rejected' { try { New-ESTaskContextRuntimeRequestFromFocus -FocusContext $confirmed -TaskId 'focus-task' -RoutePlanPath 'plan.json' -GoalRevisionPath 'goal.json' -AcceptanceProfileId 'static' -OutcomeEvaluatorId 'platform.task-context-outcome-v1' -RequiredClaims @('source-integrity') -RequestedSourceScope 'Assets' -IdempotencyKey 'outside'; throw 'scope expansion accepted' } catch { if($_.Exception.Message -notlike '*outside the confirmed FocusContext scope*'){throw} } }
Case 'pending-rejected' { try { New-ESTaskContextRuntimeRequestFromFocus -FocusContext $pending -TaskId 'focus-task' -RoutePlanPath 'plan.json' -GoalRevisionPath 'goal.json' -AcceptanceProfileId 'static' -OutcomeEvaluatorId 'platform.task-context-outcome-v1' -RequiredClaims @('source-integrity') -RequestedSourceScope 'ES/Automation' -IdempotencyKey 'pending'; throw 'pending accepted' } catch { if($_.Exception.Message -notlike '*must be confirmed*'){throw} } }
Case 'ambiguous-rejected' { $amb=Invoke-TaskFocusProposal -Current $confirmed -Proposal (New-TaskFocusProposal -Focus 'other'); try { New-ESTaskContextRuntimeRequestFromFocus -FocusContext $amb -TaskId 'focus-task' -RoutePlanPath 'plan.json' -GoalRevisionPath 'goal.json' -AcceptanceProfileId 'static' -OutcomeEvaluatorId 'platform.task-context-outcome-v1' -RequiredClaims @('source-integrity') -RequestedSourceScope 'ES/Automation' -IdempotencyKey 'ambiguous'; throw 'ambiguous accepted' } catch { if($_.Exception.Message -notlike '*must be confirmed*'){throw} } }
Case 'invalid-identity-rejected' { $bad=$confirmed|ConvertTo-Json -Depth 20|ConvertFrom-Json; $bad.proposalHash='bad'; try { New-ESTaskContextRuntimeRequestFromFocus -FocusContext $bad -TaskId 'focus-task' -RoutePlanPath 'plan.json' -GoalRevisionPath 'goal.json' -AcceptanceProfileId 'static' -OutcomeEvaluatorId 'platform.task-context-outcome-v1' -RequiredClaims @('source-integrity') -RequestedSourceScope 'ES/Automation' -IdempotencyKey 'bad'; throw 'bad identity accepted' } catch { if($_.Exception.Message -notlike '*identity is invalid*'){throw} } }
$failed=@($cases|Where-Object status -eq 'failed')
[pscustomobject]@{schemaVersion=1;validator='Test-ESTaskFocusRuntimeAdapter';status=$(if($failed.Count){'failed'}else{'passed'});caseCount=$cases.Count;passedCount=@($cases|Where-Object status -eq 'passed').Count;failedCount=$failed.Count;cases=@($cases);runtimeStatus='runtime-not-run';claimsNotProven=@('TaskContextRuntime host integration','Unity/host runtime')}|ConvertTo-Json -Depth 10
if($failed.Count){exit 1}
