[CmdletBinding()]
param([Parameter(Mandatory=$true)][string]$Path,[string]$ParserVersion='1')
$ErrorActionPreference='Stop'; $full=(Resolve-Path -LiteralPath $Path).Path
$bytes=[IO.File]::ReadAllBytes($full); $hashAlgo=[Security.Cryptography.SHA256]::Create(); try{$sha=([BitConverter]::ToString($hashAlgo.ComputeHash($bytes))).Replace('-','').ToLowerInvariant()}finally{$hashAlgo.Dispose()}
$ext=[IO.Path]::GetExtension($full).ToLowerInvariant().TrimStart('.'); $name=[IO.Path]::GetFileName($full).ToLowerInvariant(); $format='bytes'
if($ext -eq 'json'){$format='json'} elseif($ext -in @('jsonl','ndjson')){$format='jsonl'} elseif($ext -in @('csv','tsv')){$format=$ext} elseif($ext -in @('html','htm')){$format='html'} elseif($ext -in @('yaml','yml')){$format='yaml'} elseif($ext -eq 'meta' -or $ext -in @('unity','scene','prefab','asset','mat','controller','anim','shader','compute')){$format='unityyaml'} elseif($ext -eq 'asmdef' -or $name -eq 'package.json'){$format='unity-structured'} elseif($ext -eq 'md' -or $ext -eq 'markdown'){$format='markdown'} elseif($ext -eq 'xml'){$format='xml'} elseif($ext -eq 'log'){$format='log'} elseif($ext -eq 'unitypackage'){$format='unitypackage'} elseif($ext -in @('tar','gz')){$format='archive'}
if($ext -eq 'xlsx'){$format='xlsx'} elseif($ext -eq 'pdf'){$format='pdf'} elseif($ext -in @('png','jpg','jpeg','wav','ogg','mp3','mp4','mov','gltf','obj','fbx','ttf','otf','woff','woff2')){$format='media'} elseif($ext -eq 'sqlite' -or $ext -eq 'db'){$format='sqlite'} elseif($ext -eq 'toml'){$format='toml'} elseif($ext -in @('ini','cfg','conf')){$format='ini'} elseif($ext -eq 'zip'){$format='zip'} elseif($ext -in @('tar','gz','tgz','bz2','xz')){$format='archive'}
$packet=[ordered]@{projectionVersion=1;sourcePath=$full;sourceSha256=$sha;parserId="${format}.v1";detectedFormat=$format;summary=[ordered]@{sizeBytes=$bytes.Length;extension=$ext};entries=@();warnings=@();errors=@();nonClaims=@('semantic completeness','Unity import','runtime behavior','network behavior');cacheKey="${sha}:${format}.v1:1"}
try {
  $text=$null; if($format -notin @('unitypackage','archive','zip','sqlite','bytes','xlsx','pdf','media')){$text=[Text.UTF8Encoding]::new($false,$true).GetString($bytes)}
  switch($format) {
    'json' { $o=$text|ConvertFrom-Json; $packet.summary.rootType=$o.GetType().Name; if($o -is [array]){$packet.summary.count=$o.Count} }
    'jsonl' { $lines=@($text -split "`r?`n" | Where-Object {$_.Trim()}); $packet.summary.lineCount=$lines.Count; $packet.summary.validLineCount=0; foreach($line in ($lines|Select-Object -First 100)) { try{$null=$line|ConvertFrom-Json;$packet.summary.validLineCount++}catch{$packet.warnings+='invalid JSONL line'}} }
    # CSV/TSV parsing is delegated exclusively to the RFC4180 parser below.
    'html' { $packet.summary.title=([regex]::Match($text,'(?is)<title[^>]*>(.*?)</title>')).Groups[1].Value.Trim(); $packet.summary.linkCount=([regex]::Matches($text,'(?is)<a\b')).Count; $packet.summary.scriptCount=([regex]::Matches($text,'(?is)<script\b')).Count; if($packet.summary.scriptCount -gt 0){$packet.warnings+='script content not executed'} }
    'markdown' { $packet.summary.headingCount=([regex]::Matches($text,'(?m)^#{1,6}\s')).Count; $packet.summary.codeBlockCount=([regex]::Matches($text,'(?m)^```')).Count; $packet.summary.linkCount=([regex]::Matches($text,'\[[^\]]+\]\([^\)]+\)')).Count }
    'xml' { $xml=[xml]$text; $packet.summary.rootName=$xml.DocumentElement.Name; $packet.summary.elementCount=($xml.SelectNodes('//*')).Count }
    'yaml' { $packet.summary.keyLineCount=([regex]::Matches($text,'(?m)^\s*[A-Za-z0-9_.-]+\s*:')).Count }
    'unityyaml' { $blocks=[regex]::Matches($text,'(?m)^--- !u!(\d+) &(-?\d+)'); $refs=[regex]::Matches($text,'guid: ([0-9a-f]{32})'); $classes=[ordered]@{}; $graphEntries=New-Object Collections.Generic.List[object]; foreach($m in $blocks){$k=$m.Groups[1].Value;if($classes.Contains($k)){$classes[$k]++}else{$classes[$k]=1}; $start=$m.Index; $end=$text.Length; $next=[regex]::Match($text.Substring($start+$m.Length),'(?m)^--- !u!'); if($next.Success){$end=$start+$m.Length+$next.Index}; $block=$text.Substring($start,$end-$start); $deps=@([regex]::Matches($block,'guid: ([0-9a-f]{32})')|ForEach-Object {$v=$_.Groups[1].Value.ToLowerInvariant(); if($v -ne ''){$v}}|Sort-Object -Unique); $graphEntries.Add([ordered]@{stableId=($m.Groups[1].Value+':'+$m.Groups[2].Value);classId=$m.Groups[1].Value;fileId=$m.Groups[2].Value;dependencyGuids=$deps}) }; $packet.summary.objectCount=$blocks.Count; $packet.summary.classIdCounts=$classes; $packet.summary.guidCount=$refs.Count; $packet.summary.uniqueGuidCount=@($refs|ForEach-Object {$_.Groups[1].Value.ToLowerInvariant()}|Sort-Object -Unique).Count; $packet.summary.fileIdCount=([regex]::Matches($text,'fileID:')).Count; $packet.summary.dependencyEdgeCount=@($graphEntries|ForEach-Object {$_.dependencyGuids.Count}|Measure-Object -Sum).Sum; $packet.entries=@($graphEntries|Select-Object -First 200) }
    'unity-structured' { $o=$text|ConvertFrom-Json; $packet.summary.rootType=$o.GetType().Name; $packet.summary.name=$o.name; $packet.summary.version=$o.version }
    'log' { $packet.summary.errorCount=([regex]::Matches($text,'(?im)\b(error|exception|fatal)\b')).Count; $packet.summary.warningCount=([regex]::Matches($text,'(?im)\bwarning\b')).Count; $packet.entries=@($text -split "`r?`n" | Where-Object {$_ -match '(?i)error|exception|fatal'} | Select-Object -First 20) }
    'unitypackage' { $py=Join-Path $PSScriptRoot 'Parse-ESUnityPackage.py'; $parsed=(& python.exe $py $full --max-entries 100000 --max-associations 100000 | Out-String); if($LASTEXITCODE -ne 0){throw 'unitypackage parser failed'}; $p=$parsed|ConvertFrom-Json; if($p.status -ne 'passed'){throw [string]$p.error}; $packet.parserId=$p.parserId; $packet.summary=$p.summary; $packet.entries=$p.entries }
    'archive' { $lines=@(& tar.exe -tf $full 2>$null); if($LASTEXITCODE -ne 0){$packet.warnings+='archive listing unavailable'}else{$packet.summary.entryCount=$lines.Count;$bad=@($lines|Where-Object {$_ -match '(^|[\\/])\.\.([\\/]|$)' -or $_ -match '^[\\/]'});if($bad.Count){throw 'archive contains unsafe path'};$packet.entries=@($lines|Select-Object -First 200)} }
  }
  if($format -in @('csv','tsv')) { $py=Join-Path $PSScriptRoot 'Parse-ESDelimited.py'; $parsed=(& python.exe $py $full $format | Out-String); if($LASTEXITCODE -ne 0){throw 'delimited parser failed'}; $p=$parsed|ConvertFrom-Json; if($p.status -ne 'passed'){throw [string]$p.error}; $packet.parserId=$p.parserId; $packet.summary=$p.summary; $packet.entries=$p.entries }
  if($format -in @('xlsx','pdf')) { $py=Join-Path $PSScriptRoot 'Probe-ESOfficePdf.py'; $parsed=(& python.exe $py $full | Out-String); if($LASTEXITCODE -ne 0){throw 'office/pdf probe failed'}; $p=$parsed|ConvertFrom-Json; if($p.status -ne 'passed'){throw [string]$p.error}; $packet.parserId=$p.parserId; $packet.summary=$p.summary }
  if($format -eq 'media') { $py=Join-Path $PSScriptRoot 'Probe-ESMedia.py'; $parsed=(& python.exe $py $full | Out-String); if($LASTEXITCODE -ne 0){throw 'media probe failed'}; $p=$parsed|ConvertFrom-Json; if($p.status -ne 'passed'){throw [string]$p.error}; $packet.parserId=$p.parserId; $packet.summary=$p.summary }
  if($format -in @('sqlite','toml','ini','zip')) { $py=Join-Path $PSScriptRoot 'Probe-ESStructuredPackage.py'; $parsed=(& python.exe $py $full $format | Out-String); if($LASTEXITCODE -ne 0){throw 'structured/package probe failed'}; $p=$parsed|ConvertFrom-Json; if($p.status -ne 'passed'){throw [string]$p.error}; $packet.parserId=$p.parserId; $packet.summary=$p.summary; $packet.entries=$p.entries }
} catch { $packet.errors+= $_.Exception.Message }
$packet | ConvertTo-Json -Depth 8
if($packet.errors.Count -gt 0){exit 1}; exit 0
