[CmdletBinding()]
param([Parameter(Mandatory=$true)][string]$Path,[string]$ProjectRoot='.',[string]$ParserVersion='1',[string]$CacheRoot='ES/Output/FileProjectionCache')
$ErrorActionPreference='Stop'; $root=(Resolve-Path -LiteralPath $ProjectRoot).Path.TrimEnd('\','/'); $source=(Resolve-Path -LiteralPath $Path).Path
if(-not($source.Equals($root,[StringComparison]::OrdinalIgnoreCase)-or $source.StartsWith($root+'\',[StringComparison]::OrdinalIgnoreCase))){throw 'Source must be inside ProjectRoot.'}
$relative=$source.Substring($root.Length).TrimStart('\','/').Replace('\','/'); $reader=Join-Path $PSScriptRoot 'Invoke-ESResourceReader.ps1'; $cache=Join-Path $root '.agents\skills\es-task-read-snapshot\scripts\Invoke-ESProjectionCache.ps1'
$ext=[IO.Path]::GetExtension($source).ToLowerInvariant().TrimStart('.'); $parserId='bytes.v1'; if($ext -eq 'json'){$parserId='json.v1'}elseif($ext -in @('jsonl','ndjson')){$parserId='jsonl.v1'}elseif($ext -eq 'csv'){$parserId='csv.rfc4180.v1'}elseif($ext -eq 'tsv'){$parserId='tsv.rfc4180.v1'}elseif($ext -in @('html','htm')){$parserId='html.v1'}elseif($ext -in @('yaml','yml')){$parserId='yaml.v1'}elseif($ext -in @('md','markdown')){$parserId='markdown.v1'}elseif($ext -eq 'xml'){$parserId='xml.v1'}elseif($ext -eq 'log'){$parserId='log.v1'}elseif($ext -in @('meta','unity','scene','prefab','asset','mat','controller','anim','shader','compute')){$parserId='unityyaml.v1'}elseif($ext -eq 'unitypackage'){$parserId='unitypackage.python-tar.v1'}elseif($ext -in @('zip','tar','gz')){$parserId='archive-probe.v1'}elseif($ext -eq 'xlsx'){$parserId='xlsx.probe.v1'}elseif($ext -eq 'pdf'){$parserId='pdf.probe.v1'}elseif($ext -in @('png','jpg','jpeg','wav','ogg','mp3','mp4','mov','gltf','obj','fbx','ttf','otf','woff','woff2')){$parserId='media.probe.v1'}
$read=& $reader -Path $source -ParserVersion $ParserVersion | Out-String; if($ext -in @('htm')){$parserId='html.v1'}elseif($ext -in @('meta','unity')){$parserId='unityyaml.v1'}; $projectionFile=Join-Path $root 'ES\Output\ResourceReader\current.projection.json'; $dir=Split-Path $projectionFile -Parent; New-Item -ItemType Directory -Force -Path $dir|Out-Null; [IO.File]::WriteAllText($projectionFile,$read,(New-Object Text.UTF8Encoding($false)))
$write=& $cache -Mode Write -ProjectRoot $root -SourcePath $relative -ParserId $parserId -ParserVersion $ParserVersion -ProjectionPath 'ES/Output/ResourceReader/current.projection.json' -CacheRoot $CacheRoot | Out-String
[ordered]@{status='stored';sourcePath=$relative;parserId=$parserId;projection=$read|ConvertFrom-Json;cacheReceipt=$write|ConvertFrom-Json}|ConvertTo-Json -Depth 12
