using UnityEngine;
using ES;

namespace ES.Samples{
    /// <summary>
    /// SimpleScriptMaker API 婕旂ず - 鑴氭湰鐢熸垚宸ュ叿
    /// 鎻愪緵鍔ㄦ€佺敓鎴怌#浠ｇ爜鐗囨鍜屾枃浠剁殑鍔熻兘
    /// 娉ㄦ剰锛氫富瑕佺敤浜嶦ditor妯″紡涓嬬殑浠ｇ爜鐢熸垚
    /// </summary>
    public class Example_SimpleScriptMaker : MonoBehaviour
    {
        private void Start()
        {
            Debug.Log("=== SimpleScriptMaker API 婕旂ず ===");
            Debug.Log("娉ㄦ剰锛氭宸ュ叿涓昏鍦‥ditor妯″紡涓嬩娇鐢?);

            // ========== 鍒涘缓绫诲唴瀹?==========
            Debug.Log("--- 鍒涘缓绫诲唴瀹?---");

            // 1. 鍒涘缓绠€鍗曠被瀹氫箟
            string classContent = ESDesignUtility.SimpleScriptMaker.CreateClassContentByString(
                className: "MyTestClass",
                parent: ": MonoBehaviour",
                Attribute: "[RequireComponent(typeof(Rigidbody))]"
            );
            Debug.Log($"绫诲畾涔?\n{classContent}");

            // 2. 鍒涘缓甯﹀唴瀹圭殑绫?
            string insideClass = @"
    void Start()
    {
        Debug.Log(""Hello from generated script!"");
    }

    public int health = 100;
    public string playerName = ""Player"";
";

            string fullClass = ESDesignUtility.SimpleScriptMaker.CreateClassContentByString(
                className: "PlayerController",
                insideClass: insideClass,
                parent: ": MonoBehaviour",
                Attribute: "",
                beforeClassName: "// Generated class\n"
            );
            Debug.Log($"瀹屾暣绫?\n{fullClass}");

            // ========== 鍒涘缓瀛楁 ==========
            Debug.Log("--- 鍒涘缓瀛楁 ---");

            // 3. 鍒涘缓鍏紑瀛楁
            string field1 = ESDesignUtility.SimpleScriptMaker.CreateFieldContent(
                typeName: "int",
                fieldName: "score",
                modifier: "public",
                valueDefine: " = 0",
                attribute: "[SerializeField]"
            );
            Debug.Log($"瀛楁1: {field1}");

            // 4. 鍒涘缓绉佹湁瀛楁
            string field2 = ESDesignUtility.SimpleScriptMaker.CreateFieldContent(
                typeName: "string",
                fieldName: "_playerName",
                modifier: "private",
                valueDefine: " = \"Default\"",
                attribute: ""
            );
            Debug.Log($"瀛楁2: {field2}");

            // ========== 鍒涘缓鍙傛暟 ==========
            Debug.Log("--- 鍒涘缓鍙傛暟 ---");

            // 5. 鍒涘缓鏂规硶鍙傛暟
            string param = ESDesignUtility.SimpleScriptMaker.CreateParaOrDefineContent(
                typeName: "float",
                itName: "damage",
                modifier: "",
                valueDefine: " = 10f",
                isDefine: false
            );
            Debug.Log($"鍙傛暟: {param}");

            // 6. 鍒涘缓鍙橀噺瀹氫箟
            string define = ESDesignUtility.SimpleScriptMaker.CreateParaOrDefineContent(
                typeName: "Vector3",
                itName: "position",
                modifier: "",
                valueDefine: " = Vector3.zero",
                isDefine: true
            );
            Debug.Log($"瀹氫箟: {define}");

            // ========== 鍒涘缓鏂规硶 ==========
            Debug.Log("--- 鍒涘缓鏂规硶 ---");

            // 7. 鍒涘缓绠€鍗曟柟娉曪紙鎵嬪姩鎷兼帴锛?
            string methodCode = @"
    public void Attack()
    {
        Debug.Log(""Attack!""  );
    }";
            Debug.Log($"鏂规硶浠ｇ爜:\n{methodCode}");

            // 8. 鍒涘缓甯﹀弬鏁扮殑鏂规硶锛堟墜鍔ㄦ嫾鎺ワ級
            string complexMethodCode = @"
    public void TakeDamage(int damage, bool isCritical)
    {
        if (isCritical)
            damage *= 2;
        health -= damage;
    }";
            Debug.Log($"澶嶆潅鏂规硶:\n{complexMethodCode}");

            // ========== 鍒涘缓瀹屾暣鑴氭湰 ==========
            Debug.Log("--- 鍒涘缓瀹屾暣鑴氭湰 ---");

            // 9. 鐢熸垚瀹屾暣鑴氭湰锛堜笉瀹為檯鍒涘缓鏂囦欢锛?
            string scriptCode = ESDesignUtility.SimpleScriptMaker.CreateScriptBounds(
                Folderpath: "Assets/Scripts",
                fileName: "GeneratedScript.cs",
                using_: "using System.Collections.Generic;",
                nameSpace: "ES.Generated",
                content: fullClass,
                TruelyCreate: false  // 浠呯敓鎴愪唬鐮侊紝涓嶅垱寤烘枃浠?
            );
            Debug.Log($"瀹屾暣鑴氭湰棰勮:\n{scriptCode}");

#if UNITY_EDITOR
            // 10. 瀹為檯鍒涘缓鑴氭湰鏂囦欢锛堜粎Editor妯″紡锛?
            // 娉ㄦ剰锛氳繖浼氬湪椤圭洰涓疄闄呭垱寤烘枃浠?
            /*
            ESDesignUtility.SimpleScriptMaker.CreateScriptEasy(
                Folderpath: "Assets/Scripts/Generated",
                className: "AutoGeneratedClass",
                parent: ": MonoBehaviour",
                Attribute: "",
                nameSpace: "ES.Generated"
            );
            Debug.Log("宸插垱寤鸿剼鏈枃浠讹紙浠匛ditor鏈夋晥锛?);
            */
#endif

            // ========== 瀹炵敤绀轰緥锛氱敓鎴愭暟鎹被 ==========
            Debug.Log("--- 鐢熸垚鏁版嵁绫荤ず渚?---");

            // 11. 鐢熸垚涓€涓暟鎹被
            string dataFields = @"
    public string itemName;
    public int itemID;
    public float price;
    public bool isStackable;

    public ItemData(string name, int id, float price, bool stackable)
    {
        this.itemName = name;
        this.itemID = id;
        this.price = price;
        this.isStackable = stackable;
    }
";

            string dataClass = ESDesignUtility.SimpleScriptMaker.CreateClassContentByString(
                className: "ItemData",
                insideClass: dataFields,
                parent: "",
                Attribute: "[System.Serializable]"
            );

            string dataScript = ESDesignUtility.SimpleScriptMaker.CreateScriptBounds(
                Folderpath: "Assets/Scripts/Data",
                fileName: "ItemData.cs",
                using_: "",
                nameSpace: "ES.Data",
                content: dataClass,
                TruelyCreate: false
            );

            Debug.Log($"鏁版嵁绫昏剼鏈?\n{dataScript}");

            // ========== 浣跨敤鎻愮ず ==========
            Debug.Log("\n=== 浣跨敤鎻愮ず ===");
            Debug.Log("鈥?SimpleScriptMaker涓昏鐢ㄤ簬Editor宸ュ叿涓姩鎬佺敓鎴愪唬鐮?);
            Debug.Log("鈥?TruelyCreate=false 鍙互鍏堥瑙堜唬鐮侊紝纭鏃犺鍚庡啀鍒涘缓");
            Debug.Log("鈥?閫傚悎鐢熸垚閲嶅鎬т唬鐮併€佹暟鎹被銆侀厤缃被绛?);
            Debug.Log("鈥?璁板緱璁剧疆姝ｇ‘鐨勫懡鍚嶇┖闂村拰using璇彞");
        }
    }
}

