[CmdletBinding()]
param([string]$ProjectRoot,[switch]$NoReport)
$ErrorActionPreference='Stop'
if([string]::IsNullOrWhiteSpace($ProjectRoot)){$ProjectRoot=(Resolve-Path (Join-Path $PSScriptRoot '..\..\..')).Path}
$root=(Resolve-Path -LiteralPath $ProjectRoot).Path
Import-Module (Join-Path $PSScriptRoot 'ESAITalkAggregation.psm1') -Force
Import-Module (Join-Path $root 'ES/Automation/Contracts/ESJsonSchemaLite.psm1') -Force
$results=[Collections.Generic.List[object]]::new()
function Case([string]$Name,[scriptblock]$Body){try{&$Body;[void]$results.Add([pscustomobject]@{case=$Name;status='passed';finding=$null})}catch{[void]$results.Add([pscustomobject]@{case=$Name;status='failed';finding=$_.Exception.Message})}}
function Assert-True([bool]$Value,[string]$Message){if(-not$Value){throw $Message}}
function Assert-Equal($Actual,$Expected,[string]$Message){if([string]$Actual -cne [string]$Expected){throw "$Message Expected=$Expected Actual=$Actual"}}
function Assert-Schema([string]$Name,[string]$Path,$Value){$errors=@(Test-ESJsonSchemaValue -SchemaPath (Join-Path $root $Path) -Value $Value);if($errors.Count){throw "$Name schema errors: $($errors -join '; ')"}}
$zero='0'*64;$one='1'*64;$created=[DateTime]::Parse('2026-08-29T00:00:00Z').ToUniversalTime()
$binding=[pscustomobject]@{taskId='task-a';taskRevision=2;contextVersion=4;routePlanHash=$zero;sourceScopeHash=$one}
$m1=New-ESAITalkMessage -ConversationId 'conv-1' -MessageId 'msg-1' -AuthorId 'codex' -Sequence 2 -MessageKind proposal -TaskBinding $binding -Payload ([ordered]@{decision='use-aitalk';reason='bounded'}) -EvidenceRefs @('src/readme') -CreatedUtc $created.AddSeconds(2)
$m2=New-ESAITalkMessage -ConversationId 'conv-1' -MessageId 'msg-2' -AuthorId 'other' -Sequence 1 -MessageKind evidence -TaskBinding $binding -Payload 'observed' -EvidenceRefs @('src/test') -CreatedUtc $created
Case 'message-schema-and-hash' {Assert-Schema 'message' 'ES/Automation/TaskCollaboration/es-aitalk-message-v1.schema.json' $m1;Assert-True (Test-ESAITalkMessage $m1).valid 'message should validate';Assert-Equal $m1.messageHash (Get-ESAITalkMessageHash $m1) 'message hash'}
Case 'evidence-requires-reference' {try{New-ESAITalkMessage -ConversationId 'conv-1' -MessageId 'bad' -AuthorId 'codex' -Sequence 3 -MessageKind evidence -TaskBinding $binding -Payload 'x'|Out-Null;throw 'missing evidence accepted'}catch{if($_.Exception.Message -notlike '*evidenceRef*'){throw}}}
Case 'deterministic-ordering' {$a=Invoke-ESAITalkAggregation -ConversationId 'conv-1' -Messages @($m1,$m2);$b=Invoke-ESAITalkAggregation -ConversationId 'conv-1' -Messages @($m2,$m1);Assert-Equal (($a.messages|ForEach-Object messageId)-join ',') 'msg-2,msg-1' 'sequence ordering';Assert-Equal $a.aggregationHash $b.aggregationHash 'aggregation hash'}
Case 'conversation-id-is-inferred' {$a=Invoke-ESAITalkAggregation -Messages @($m1,$m2);Assert-Equal $a.conversationId 'conv-1' 'conversation identity was not inferred';Assert-Equal @($a.messages).Count 2 'inferred conversation filtered valid messages'}
Case 'mixed-conversations-require-explicit-id' {$other=New-ESAITalkMessage -ConversationId 'conv-2' -MessageId 'msg-other' -AuthorId 'other' -Sequence 1 -MessageKind proposal -TaskBinding $binding -Payload 'other';try{Invoke-ESAITalkAggregation -Messages @($m1,$other)|Out-Null;throw 'mixed conversations accepted'}catch{if($_.Exception.Message -notlike '*CONVERSATION_ID_REQUIRED_FOR_MIXED_MESSAGES*'){throw}}}
Case 'duplicate-is-idempotent' {$a=Invoke-ESAITalkAggregation -ConversationId 'conv-1' -Messages @($m1,$m1,$m2);Assert-Equal $a.status 'partial' 'duplicate status';Assert-True (@($a.quarantined|Where-Object reasonCode -eq 'DUPLICATE_MESSAGE').Count -eq 1) 'duplicate missing'}
Case 'same-id-different-payload-conflicts' {$bad=New-ESAITalkMessage -ConversationId 'conv-1' -MessageId 'msg-1' -AuthorId 'codex' -Sequence 2 -MessageKind proposal -TaskBinding $binding -Payload 'different' -EvidenceRefs @('src/readme') -CreatedUtc $created.AddSeconds(2);$a=Invoke-ESAITalkAggregation -ConversationId 'conv-1' -Messages @($m1,$bad,$m2);Assert-Equal $a.status 'conflict' 'conflict status'}
Case 'stale-binding-isolated' {$old=New-ESAITalkMessage -ConversationId 'conv-1' -MessageId 'old' -AuthorId 'codex' -Sequence 3 -MessageKind proposal -TaskBinding ([pscustomobject]@{taskId='task-a';taskRevision=1;contextVersion=4;routePlanHash=$zero;sourceScopeHash=$one}) -Payload 'old' -CreatedUtc $created.AddSeconds(3);$a=Invoke-ESAITalkAggregation -ConversationId 'conv-1' -ExpectedTaskBinding $binding -Messages @($m1,$old);Assert-True (@($a.quarantined|Where-Object reasonCode -eq 'STALE_TASK_CONTEXT').Count -eq 1) 'stale not quarantined'}
Case 'route-and-source-binding-isolated' {$badRoute=New-ESAITalkMessage -ConversationId 'conv-1' -MessageId 'bad-route' -AuthorId 'codex' -Sequence 3 -MessageKind proposal -TaskBinding ([pscustomobject]@{taskId='task-a';taskRevision=2;contextVersion=4;routePlanHash=$one;sourceScopeHash=$one}) -Payload 'bad-route' -CreatedUtc $created.AddSeconds(3);$badSource=New-ESAITalkMessage -ConversationId 'conv-1' -MessageId 'bad-source' -AuthorId 'codex' -Sequence 4 -MessageKind proposal -TaskBinding ([pscustomobject]@{taskId='task-a';taskRevision=2;contextVersion=4;routePlanHash=$zero;sourceScopeHash=$zero}) -Payload 'bad-source' -CreatedUtc $created.AddSeconds(4);$a=Invoke-ESAITalkAggregation -ConversationId 'conv-1' -ExpectedTaskBinding $binding -Messages @($m1,$badRoute,$badSource);Assert-True (@($a.quarantined|Where-Object reasonCode -eq 'BINDING_ROUTEPLANHASH_MISMATCH').Count -eq 1) 'route mismatch not quarantined';Assert-True (@($a.quarantined|Where-Object reasonCode -eq 'BINDING_SOURCESCOPEHASH_MISMATCH').Count -eq 1) 'source mismatch not quarantined'}
Case 'private-message-isolated' {$private=New-ESAITalkMessage -ConversationId 'conv-1' -MessageId 'private' -AuthorId 'secret' -Sequence 4 -MessageKind proposal -TaskBinding $binding -Payload 'private' -Visibility private;$a=Invoke-ESAITalkAggregation -ConversationId 'conv-1' -Messages @($m1,$private);Assert-True (@($a.quarantined|Where-Object reasonCode -eq 'PRIVATE_NOT_AUTHORIZED').Count -eq 1) 'private leak'}
Case 'hash-mismatch-isolated' {$tampered=$m1|ConvertTo-Json -Depth 20|ConvertFrom-Json;$tampered.payload='tampered';$a=Invoke-ESAITalkAggregation -ConversationId 'conv-1' -Messages @($tampered,$m2);Assert-True (@($a.quarantined|Where-Object reasonCode -eq 'INVALID_MESSAGE').Count -eq 1) 'tampered accepted'}
Case 'aggregation-never-completes' {$a=Invoke-ESAITalkAggregation -ConversationId 'conv-1' -Messages @($m1,$m2);Assert-True $a.completionDecisionRequired 'completion boundary missing';Assert-True ($a.nonClaims -join ';' -match 'never declares Accepted') 'non-claim missing';Assert-True ($a.PSObject.Properties.Name -notcontains 'Accepted') 'accepted claim'}
Case 'markdown-session-ingestion' {$session=Join-Path $root 'Assets/Plugins/ES/AITalk/Sessions/20260717_163414_飞行物运动职责纠偏';$a=Invoke-ESAITalkSessionAggregation -SessionPath $session;Assert-Equal $a.status 'candidate' 'session aggregation status';Assert-Equal @($a.messages).Count 9 'session message count';Assert-Equal @($a.sourceMessageFiles).Count 9 'source file count'}
Case 'expected-binding-is-admission-filter' {$session=Join-Path $root 'Assets/Plugins/ES/AITalk/Sessions/20260717_163414_飞行物运动职责纠偏';$a=Invoke-ESAITalkSessionAggregation -SessionPath $session -ExpectedTaskBinding $binding;Assert-Equal @($a.messages).Count 0 'unbound messages copied expected binding';Assert-True (@($a.quarantined|Where-Object reasonCode -eq 'TASK_BINDING_MISMATCH').Count -eq 9) 'unbound messages not isolated'}
Case 'message-size-budget-enforced' {$session=Join-Path $root 'Assets/Plugins/ES/AITalk/Sessions/20260717_163414_飞行物运动职责纠偏';try{Invoke-ESAITalkSessionAggregation -SessionPath $session -MaxMessageBytes 1024|Out-Null;throw 'oversized message accepted'}catch{if($_.Exception.Message -notlike '*MESSAGE_SIZE_LIMIT_EXCEEDED*'){throw}}}
Case 'consensus-render-is-candidate-only' {$session=Join-Path $root 'Assets/Plugins/ES/AITalk/Sessions/20260717_163414_飞行物运动职责纠偏';$a=Invoke-ESAITalkSessionAggregation -SessionPath $session;$md=ConvertTo-ESAITalkConsensusMarkdown $a;Assert-True ($md -match '聚合状态') 'consensus status missing';Assert-True ($md -match '不声明') 'consensus authority boundary missing';Assert-True ($md -notmatch '(?m)^聚合状态：`(?:Accepted|Completed)`') 'consensus claimed completion'}
$failed=@($results|Where-Object status -eq 'failed')
$report=[ordered]@{schemaVersion=1;validator='Test-ESAITalkAggregation';status=if($failed.Count){'failed'}else{'passed'};caseCount=$results.Count;passedCount=@($results|Where-Object status -eq 'passed').Count;failedCount=$failed.Count;cases=@($results);runtimeStatus='runtime-not-run';claimsNotProven=@('Unity/Worker/MCP Runtime','cross-process mailbox delivery','performance','release acceptance');contract='es-aitalk-message-v1';aggregationContract='aitalk-aggregation-v1'}
if(-not $NoReport){$path=Join-Path $root 'ES/Output/StaticReplay/aitalk-aggregation.json';$parent=Split-Path -Parent $path;if(-not(Test-Path -LiteralPath $parent)){New-Item -ItemType Directory -Path $parent -Force|Out-Null};[IO.File]::WriteAllText($path,($report|ConvertTo-Json -Depth 20),[Text.UTF8Encoding]::new($false))}
$report|ConvertTo-Json -Depth 20
if($failed.Count){exit 1}
