[CmdletBinding()]
param([string]$ProjectRoot,[switch]$NoReport)
$ErrorActionPreference='Stop'
if([string]::IsNullOrWhiteSpace($ProjectRoot)){$ProjectRoot=(Resolve-Path (Join-Path $PSScriptRoot '..\..\..')).Path}
$root=(Resolve-Path -LiteralPath $ProjectRoot).Path
Import-Module (Join-Path $PSScriptRoot 'ESAITalkProjectAggregation.psm1') -Force
Import-Module (Join-Path $root 'ES/Automation/Contracts/ESJsonSchemaLite.psm1') -Force
$results=[Collections.Generic.List[object]]::new()
function Case([string]$Name,[scriptblock]$Body){try{&$Body;[void]$results.Add([pscustomobject]@{case=$Name;status='passed';finding=$null})}catch{[void]$results.Add([pscustomobject]@{case=$Name;status='failed';finding=$_.Exception.Message})}}
function Assert-True([bool]$Value,[string]$Message){if(-not$Value){throw $Message}}
function Assert-Equal($Actual,$Expected,[string]$Message){if([string]$Actual -cne [string]$Expected){throw "$Message Expected=$Expected Actual=$Actual"}}
function Assert-Schema([string]$Name,[string]$Path,$Value){$errors=@(Test-ESJsonSchemaValue -SchemaPath (Join-Path $root $Path) -Value $Value);if($errors.Count){throw "$Name schema errors: $($errors -join '; ')"}}
$sessions=Join-Path $root 'Assets/Plugins/ES/AITalk/Sessions'
$sessionDirs=@(Get-ChildItem -LiteralPath $sessions -Directory)
$expectedSessionCount=$sessionDirs.Count
$expectedMessageCount=[int](@($sessionDirs|ForEach-Object{@(Get-ChildItem -LiteralPath (Join-Path $_.FullName 'Messages') -File -Filter '*.md').Count}|Measure-Object -Sum).Sum)
Case 'project-aggregation-schema-and-counts' {$a=Invoke-ESAITalkProjectAggregation -SessionsRoot $sessions;Assert-Schema 'project aggregation' 'ES/Automation/TaskCollaboration/es-aitalk-project-aggregation-v1.schema.json' $a;Assert-Equal $a.status 'candidate' 'project status';Assert-Equal $a.sessionCount $expectedSessionCount 'session count';Assert-Equal $a.messageCount $expectedMessageCount 'message count';Assert-Equal $a.resourceLimits.maxMessagesPerSession 512 'message budget';Assert-True $a.completionDecisionRequired 'completion boundary'}
Case 'project-aggregation-is-deterministic' {$a=Invoke-ESAITalkProjectAggregation -SessionsRoot $sessions;$b=Invoke-ESAITalkProjectAggregation -SessionsRoot $sessions;Assert-Equal $a.aggregationHash $b.aggregationHash 'project hash';Assert-Equal $a.projectAggregationId $b.projectAggregationId 'project identity'}
Case 'project-session-cap-is-bounded' {$a=Invoke-ESAITalkProjectAggregation -SessionsRoot $sessions -MaxSessions 1;Assert-Equal $a.sessionCount 1 'session cap ignored';Assert-Equal $a.discoveredSessionCount $expectedSessionCount 'discovered count missing';Assert-True $a.sessionLimitReached 'truncation not surfaced';Assert-True ($a.messageCount -gt 0) 'bounded scan lost messages'}
Case 'project-message-cap-is-visible' {$a=Invoke-ESAITalkProjectAggregation -SessionsRoot $sessions -MaxMessagesPerSession 2;Assert-Equal $a.status 'needs-review' 'message cap status';Assert-True (@($a.sessions|Where-Object status -eq 'needs-review').Count -gt 0) 'message cap not surfaced';Assert-Equal $a.resourceLimits.maxMessagesPerSession 2 'message cap missing'}
Case 'five-round-no-consensus-interrupts' {$rounds=@(1..5|ForEach-Object{[pscustomobject]@{round=$_;consensusReached=$false;userDecisionRequired=$false;newMessageCount=1}});$g=Invoke-ESAITalkRoundGate -RoundObservations $rounds;Assert-Schema 'round gate' 'ES/Automation/TaskCollaboration/es-aitalk-round-gate-v1.schema.json' $g;Assert-Equal $g.status 'interrupted' 'max-round gate did not interrupt';Assert-Equal $g.stopReason 'MAX_ROUNDS_EXCEEDED' 'wrong interruption reason';Assert-Equal $g.stopRound 5 'wrong stop round'}
Case 'consensus-stops-before-five' {$rounds=@([pscustomobject]@{round=1;consensusReached=$false;userDecisionRequired=$false},[pscustomobject]@{round=2;consensusReached=$true;userDecisionRequired=$false},[pscustomobject]@{round=3;consensusReached=$false;userDecisionRequired=$false});$g=Invoke-ESAITalkRoundGate -RoundObservations $rounds;Assert-Equal $g.status 'consensus-reached' 'consensus not honored';Assert-Equal $g.stopRound 2 'consensus stop round'}
Case 'user-decision-precedes-consensus' {$rounds=@([pscustomobject]@{round=1;consensusReached=$true;userDecisionRequired=$true});$g=Invoke-ESAITalkRoundGate -RoundObservations $rounds;Assert-Equal $g.status 'needs-user-decision' 'user decision precedence lost'}
Case 'round-gate-rejects-duplicate-rounds' {$rounds=@([pscustomobject]@{round=1;consensusReached=$false;userDecisionRequired=$false},[pscustomobject]@{round=1;consensusReached=$false;userDecisionRequired=$false});try{Invoke-ESAITalkRoundGate -RoundObservations $rounds|Out-Null;throw 'duplicate rounds accepted'}catch{if($_.Exception.Message -notlike '*Duplicate round*'){throw}}}
Case 'round-gate-rejects-malformed-observation' {$rounds=@([pscustomobject]@{round=1;consensusReached='false';userDecisionRequired=$false});try{Invoke-ESAITalkRoundGate -RoundObservations $rounds|Out-Null;throw 'malformed observation accepted'}catch{if($_.Exception.Message -notlike '*must be boolean*'){throw}}}
Case 'missing-messages-directory-is-visible' {$tmp=Join-Path ([IO.Path]::GetTempPath()) ('es-aitalk-project-' + [guid]::NewGuid().ToString('N'));New-Item -ItemType Directory -Path (Join-Path $tmp 'broken-session') -Force|Out-Null;try{$i=@(Get-ESAITalkProjectSessionIndex -SessionsRoot $tmp);Assert-Equal $i.Count 1 'broken session hidden';Assert-Equal $i[0].status 'needs-review' 'broken session status';Assert-Equal $i[0].quarantineCount 1 'broken session quarantine'}finally{Remove-Item -LiteralPath $tmp -Recurse -Force}}
$failed=@($results|Where-Object status -eq 'failed')
$report=[ordered]@{schemaVersion=1;validator='Test-ESAITalkProjectAggregation';status=if($failed.Count){'failed'}else{'passed'};caseCount=$results.Count;passedCount=@($results|Where-Object status -eq 'passed').Count;failedCount=$failed.Count;cases=@($results);runtimeStatus='runtime-not-run';claimsNotProven=@('Unity/Worker/MCP Runtime','cross-process mailbox delivery','performance','release acceptance');contracts=@('es-aitalk-project-aggregation-v1','es-aitalk-round-gate-v1')}
if(-not $NoReport){$path=Join-Path $root 'ES/Output/StaticReplay/aitalk-project-aggregation.json';$parent=Split-Path -Parent $path;if(-not(Test-Path -LiteralPath $parent)){New-Item -ItemType Directory -Path $parent -Force|Out-Null};[IO.File]::WriteAllText($path,($report|ConvertTo-Json -Depth 20),[Text.UTF8Encoding]::new($false))}
$report|ConvertTo-Json -Depth 20
if($failed.Count){exit 1}
