[CmdletBinding()]
param([string]$ProjectRoot,[string]$ReportPath='ES/Output/StaticReplay/task-collaboration-abcd.json')
$ErrorActionPreference='Stop'
if([string]::IsNullOrWhiteSpace($ProjectRoot)){$ProjectRoot=(Resolve-Path (Join-Path $PSScriptRoot '..\..\..')).Path}
$root=(Resolve-Path -LiteralPath $ProjectRoot).Path
Import-Module (Join-Path $PSScriptRoot 'ESTaskCollaborationContracts.psm1') -Force
Import-Module (Join-Path $root 'ES/Automation/Contracts/ESJsonSchemaLite.psm1') -Force

$results=[Collections.Generic.List[object]]::new()
function Case([string]$Name,[scriptblock]$Body){try{&$Body;[void]$results.Add([pscustomobject]@{case=$Name;status='passed';finding=$null})}catch{[void]$results.Add([pscustomobject]@{case=$Name;status='failed';finding=$_.Exception.Message})}}
function Assert-True([bool]$Value,[string]$Message){if(-not$Value){throw $Message}}
function Assert-Equal($Actual,$Expected,[string]$Message){if([string]$Actual -cne [string]$Expected){throw "$Message Expected=$Expected Actual=$Actual"}}
function Assert-Schema([string]$Name,[string]$Path,$Value){$errors=@(Test-ESJsonSchemaValue -SchemaPath (Join-Path $root $Path) -Value $Value);if($errors.Count){throw "$Name schema errors: $($errors -join '; ')"}}

$zero='0'*64;$one='1'*64;$two='2'*64;$issued=[DateTime]::Parse('2026-08-29T00:00:00Z').ToUniversalTime()
$plan=New-ESCollaborationPlan -ParentTaskId 'parent-task' -GoalRevisionHash $zero -RoutePlanHash $one -ChildTaskIds @('child-a','child-b') -Dependencies @([pscustomobject]@{childTaskId='child-b';dependsOn=@('child-a')}) -ConcurrencyBudget 2 -AggregationStrategy 'all-required'
$registry=New-ESChildTaskRegistry -ParentTaskId 'parent-task' -ParentTaskRevision 3 -CollaborationPlan $plan
$leaseA=New-ESLeaseClaim -TaskId 'child-a' -WorkerId 'worker-a' -ExpectedTaskRevision 1 -ExpectedContextVersion 1 -LeaseDurationSeconds 60 -IssuedUtc $issued
$leaseB=New-ESLeaseClaim -TaskId 'child-b' -WorkerId 'worker-b' -ExpectedTaskRevision 1 -ExpectedContextVersion 1 -LeaseDurationSeconds 60 -IssuedUtc $issued
$resultA=New-ESResultEnvelope -ParentTaskId 'parent-task' -ChildTaskId 'child-a' -CollaborationPlanHash $plan.planHash -TaskRevision 1 -ContextVersion 1 -Attempt 1 -LeaseClaim $leaseA -ResultStatus candidate -OutputHash $two -EvidenceRefs @('evidence/a') -CapturedUtc $issued.AddSeconds(10)
$resultB=New-ESResultEnvelope -ParentTaskId 'parent-task' -ChildTaskId 'child-b' -CollaborationPlanHash $plan.planHash -TaskRevision 1 -ContextVersion 1 -Attempt 1 -LeaseClaim $leaseB -ResultStatus candidate -OutputHash $two -EvidenceRefs @('evidence/b') -CapturedUtc $issued.AddSeconds(10)

Case 'plan-is-deterministic-and-bounded' {Assert-Schema 'plan' 'ES/Automation/Contracts/es-task-collaboration-plan-v1.schema.json' $plan;Assert-True ($plan.childTaskIds.Count -eq 2) 'plan child count';Assert-True (-not($plan.PSObject.Properties.Name -contains 'taskStatus')) 'plan owns lifecycle'}
Case 'plan-rejects-duplicate-child' {try{New-ESCollaborationPlan -ParentTaskId 'parent-task' -GoalRevisionHash $zero -RoutePlanHash $one -ChildTaskIds @('child-a','child-a')|Out-Null;throw 'duplicate accepted'}catch{if($_.Exception.Message -notlike '*unique*'){throw}}}
Case 'plan-rejects-self-dependency' {try{New-ESCollaborationPlan -ParentTaskId 'parent-task' -GoalRevisionHash $zero -RoutePlanHash $one -ChildTaskIds @('child-a') -Dependencies @([pscustomobject]@{childTaskId='child-a';dependsOn=@('child-a')})|Out-Null;throw 'self dependency accepted'}catch{if($_.Exception.Message -notlike '*itself*'){throw}}}
Case 'registry-is-index-only' {Assert-Schema 'registry' 'ES/Automation/Contracts/es-task-child-task-registry-v1.schema.json' $registry;Assert-True (-not($registry.PSObject.Properties.Name -contains 'taskStatus')) 'registry owns task state';Assert-True (-not($registry.children[0].PSObject.Properties.Name -contains 'leaseId')) 'registry owns lease'}
Case 'lease-active-cas' {$o=Test-ESLeaseCas -LeaseClaim $leaseA -CurrentTaskRevision 1 -CurrentContextVersion 1 -NowUtc $issued.AddSeconds(10);Assert-Equal $o.status 'claimed' 'active status';Assert-True $o.canSubmitResult 'active lease rejected';Assert-Schema 'lease observation' 'ES/Automation/Contracts/es-task-lease-cas-v1.schema.json' $o}
Case 'lease-claim-schema' {Assert-Schema 'lease claim' 'ES/Automation/Contracts/es-task-lease-cas-v1.schema.json' $leaseA}
Case 'lease-stale-cas-isolation' {$o=Test-ESLeaseCas -LeaseClaim $leaseA -CurrentTaskRevision 2 -CurrentContextVersion 1 -NowUtc $issued.AddSeconds(10);Assert-Equal $o.status 'stale' 'stale status';Assert-True (-not$o.canSubmitResult) 'stale result may submit'}
Case 'lease-expiry-isolation' {$o=Test-ESLeaseCas -LeaseClaim $leaseA -CurrentTaskRevision 1 -CurrentContextVersion 1 -NowUtc $issued.AddSeconds(60);Assert-Equal $o.status 'expired' 'expiry status';Assert-True (-not$o.canSubmitResult) 'expired result may submit'}
Case 'result-envelope-is-candidate-only' {Assert-Schema 'result' 'ES/Automation/Contracts/es-task-result-envelope-v1.schema.json' $resultA;Assert-Equal $resultA.recordType 'CandidateResultEnvelope' 'record type';Assert-True (-not($resultA.PSObject.Properties.Name -contains 'Accepted')) 'result self-accepted';Assert-True (-not($resultA.PSObject.Properties.Name -contains 'Completed')) 'result self-completed'}
Case 'result-plan-hash-is-required' {$bad=$resultA|ConvertTo-Json -Depth 20|ConvertFrom-Json;$bad.PSObject.Properties.Remove('collaborationPlanHash');$errors=@(Test-ESJsonSchemaValue -SchemaPath (Join-Path $root 'ES/Automation/Contracts/es-task-result-envelope-v1.schema.json') -Value $bad);Assert-True ($errors.Count -gt 0) 'ResultEnvelope without collaborationPlanHash was accepted.'}
Case 'result-envelope-deterministic' {$repeat=New-ESResultEnvelope -ParentTaskId 'parent-task' -ChildTaskId 'child-a' -CollaborationPlanHash $plan.planHash -TaskRevision 1 -ContextVersion 1 -Attempt 1 -LeaseClaim $leaseA -ResultStatus candidate -OutputHash $two -EvidenceRefs @('evidence/a') -CapturedUtc $issued.AddSeconds(10);Assert-Equal $repeat.envelopeId $resultA.envelopeId 'envelope identity';Assert-Equal $repeat.resultHash $resultA.resultHash 'result hash'}
Case 'idempotency-key-replay-and-conflict' {$r1=New-ESResultEnvelope -ParentTaskId 'parent-task' -ChildTaskId 'child-a' -CollaborationPlanHash $plan.planHash -TaskRevision 1 -ContextVersion 1 -Attempt 1 -LeaseClaim $leaseA -ResultStatus candidate -OutputHash $two -IdempotencyKey 'retry-key' -CapturedUtc $issued.AddSeconds(10);$r2=New-ESResultEnvelope -ParentTaskId 'parent-task' -ChildTaskId 'child-a' -CollaborationPlanHash $plan.planHash -TaskRevision 1 -ContextVersion 1 -Attempt 1 -LeaseClaim $leaseA -ResultStatus candidate -OutputHash $two -IdempotencyKey 'retry-key' -CapturedUtc $issued.AddSeconds(10);Assert-Equal $r1.resultHash $r2.resultHash 'same idempotency fingerprint';$r3=New-ESResultEnvelope -ParentTaskId 'parent-task' -ChildTaskId 'child-a' -CollaborationPlanHash $plan.planHash -TaskRevision 1 -ContextVersion 1 -Attempt 1 -LeaseClaim $leaseA -ResultStatus candidate -OutputHash $one -IdempotencyKey 'retry-key' -CapturedUtc $issued.AddSeconds(10);$agg=Invoke-ESParentAggregation -CollaborationPlan $plan -ChildTaskRegistry $registry -ResultEnvelopes @($r1,$r3,$resultB);Assert-Equal $agg.status 'conflict' 'same key with different result must conflict'}
Case 'parent-aggregation-candidate' {$agg=Invoke-ESParentAggregation -CollaborationPlan $plan -ChildTaskRegistry $registry -ResultEnvelopes @($resultA,$resultB);Assert-Schema 'aggregation' 'ES/Automation/Contracts/es-task-parent-aggregation-v1.schema.json' $agg;Assert-Equal $agg.status 'candidate' 'aggregation status';Assert-True $agg.completionDecisionRequired 'completion decision boundary';Assert-True ($agg.nonClaims -join ';' -match 'never declares Accepted') 'non-claim missing'}
Case 'parent-aggregation-deterministic' {$first=Invoke-ESParentAggregation -CollaborationPlan $plan -ChildTaskRegistry $registry -ResultEnvelopes @($resultA,$resultB);$repeat=Invoke-ESParentAggregation -CollaborationPlan $plan -ChildTaskRegistry $registry -ResultEnvelopes @($resultB,$resultA);Assert-Equal $repeat.aggregationId $first.aggregationId 'aggregation identity';Assert-Equal $repeat.aggregationHash $first.aggregationHash 'aggregation hash'}
Case 'duplicate-result-isolated' {$agg=Invoke-ESParentAggregation -CollaborationPlan $plan -ChildTaskRegistry $registry -ResultEnvelopes @($resultA,$resultA,$resultB);Assert-Equal $agg.status 'candidate' 'duplicate changed candidate status';Assert-Equal $agg.children[0].duplicateCount 1 'duplicate was not counted'}
Case 'late-result-is-quarantined' {$late=New-ESResultEnvelope -ParentTaskId 'parent-task' -ChildTaskId 'child-a' -CollaborationPlanHash $plan.planHash -TaskRevision 1 -ContextVersion 1 -Attempt 2 -LeaseClaim $leaseA -ResultStatus candidate -OutputHash $two -CapturedUtc $issued.AddSeconds(15);$agg=Invoke-ESParentAggregation -CollaborationPlan $plan -ChildTaskRegistry $registry -ResultEnvelopes @($resultA,$late,$resultB);Assert-Equal $agg.status 'candidate' 'latest candidate status';Assert-True ($agg.children[0].quarantinedResultHashes -contains $resultA.resultHash) 'late result was not quarantined'}
Case 'terminal-state-is-immutable' {$failed=New-ESResultEnvelope -ParentTaskId 'parent-task' -ChildTaskId 'child-a' -CollaborationPlanHash $plan.planHash -TaskRevision 1 -ContextVersion 1 -Attempt 1 -LeaseClaim $leaseA -ResultStatus failed -OutputHash $one -ErrorCode 'worker-failed' -CapturedUtc $issued.AddSeconds(10);$recovery=New-ESResultEnvelope -ParentTaskId 'parent-task' -ChildTaskId 'child-a' -CollaborationPlanHash $plan.planHash -TaskRevision 1 -ContextVersion 1 -Attempt 2 -LeaseClaim $leaseA -ResultStatus candidate -OutputHash $two -CapturedUtc $issued.AddSeconds(11);$agg=Invoke-ESParentAggregation -CollaborationPlan $plan -ChildTaskRegistry $registry -ResultEnvelopes @($failed,$recovery,$resultB);Assert-Equal $agg.children[0].disposition 'failed' 'terminal state resurrected';Assert-True ($agg.children[0].quarantinedResultHashes -contains $recovery.resultHash) 'post-terminal candidate was not quarantined';Assert-Equal $agg.status 'partial' 'terminal child changed parent status'}
Case 'cancelled-state-is-immutable' {$cancelled=New-ESResultEnvelope -ParentTaskId 'parent-task' -ChildTaskId 'child-a' -CollaborationPlanHash $plan.planHash -TaskRevision 1 -ContextVersion 1 -Attempt 1 -LeaseClaim $leaseA -ResultStatus cancelled -OutputHash $one -CapturedUtc $issued.AddSeconds(10);$recovery=New-ESResultEnvelope -ParentTaskId 'parent-task' -ChildTaskId 'child-a' -CollaborationPlanHash $plan.planHash -TaskRevision 1 -ContextVersion 1 -Attempt 2 -LeaseClaim $leaseA -ResultStatus candidate -OutputHash $two -CapturedUtc $issued.AddSeconds(11);$agg=Invoke-ESParentAggregation -CollaborationPlan $plan -ChildTaskRegistry $registry -ResultEnvelopes @($cancelled,$recovery,$resultB);Assert-Equal $agg.children[0].disposition 'cancelled' 'cancelled state resurrected';Assert-True ($agg.children[0].quarantinedResultHashes -contains $recovery.resultHash) 'post-cancel candidate was not quarantined';Assert-Equal $agg.status 'partial' 'cancelled child changed parent status'}
Case 'result-plan-hash-mismatch-is-quarantined' {$old=New-ESResultEnvelope -ParentTaskId 'parent-task' -ChildTaskId 'child-a' -CollaborationPlanHash $one -TaskRevision 1 -ContextVersion 1 -Attempt 1 -LeaseClaim $leaseA -ResultStatus candidate -OutputHash $two -CapturedUtc $issued.AddSeconds(10);$agg=Invoke-ESParentAggregation -CollaborationPlan $plan -ChildTaskRegistry $registry -ResultEnvelopes @($old,$resultB);Assert-Equal $agg.children[0].disposition 'missing' 'old-plan result was accepted';Assert-True ($agg.children[0].quarantinedResultHashes -contains $old.resultHash) 'old-plan result was not quarantined';Assert-Equal $agg.status 'partial' 'old-plan result changed parent status'}
Case 'conflicting-same-attempt-is-replan' {$otherLease=New-ESLeaseClaim -TaskId 'child-a' -WorkerId 'worker-c' -ExpectedTaskRevision 1 -ExpectedContextVersion 1 -LeaseDurationSeconds 60 -IssuedUtc $issued;$other=New-ESResultEnvelope -ParentTaskId 'parent-task' -ChildTaskId 'child-a' -CollaborationPlanHash $plan.planHash -TaskRevision 1 -ContextVersion 1 -Attempt 1 -LeaseClaim $otherLease -ResultStatus candidate -OutputHash $one -CapturedUtc $issued.AddSeconds(11);$agg=Invoke-ESParentAggregation -CollaborationPlan $plan -ChildTaskRegistry $registry -ResultEnvelopes @($resultA,$other,$resultB);Assert-Equal $agg.status 'conflict' 'conflict status';Assert-True ($agg.conflictChildTaskIds -contains 'child-a') 'conflict child missing'}
Case 'failed-child-never-completes-parent' {$failed=New-ESResultEnvelope -ParentTaskId 'parent-task' -ChildTaskId 'child-b' -CollaborationPlanHash $plan.planHash -TaskRevision 1 -ContextVersion 1 -Attempt 1 -LeaseClaim $leaseB -ResultStatus failed -OutputHash $one -ErrorCode 'worker-failed' -CapturedUtc $issued.AddSeconds(12);$agg=Invoke-ESParentAggregation -CollaborationPlan $plan -ChildTaskRegistry $registry -ResultEnvelopes @($resultA,$failed);Assert-Equal $agg.status 'partial' 'partial status';Assert-True $agg.completionDecisionRequired 'completion remains external'}
Case 'plan-hash-mismatch-rejected' {$bad=$registry|ConvertTo-Json -Depth 20|ConvertFrom-Json;$bad.collaborationPlanHash=$two;try{Invoke-ESParentAggregation -CollaborationPlan $plan -ChildTaskRegistry $bad -ResultEnvelopes @($resultA,$resultB)|Out-Null;throw 'mismatch accepted'}catch{if($_.Exception.Message -notlike '*plan hash mismatch*'){throw}}}

Case 'abcd-dynamic-parity' {
    $mode=Get-Content -Raw -Encoding UTF8 -LiteralPath (Join-Path $root 'ES/Automation/Contracts/es-ai-abc-mode.registry.json')|ConvertFrom-Json
    $core=Get-Content -Raw -Encoding UTF8 -LiteralPath (Join-Path $root 'ES/Automation/Contracts/es-ai-abc-core-v1.json')|ConvertFrom-Json
    $required=@('bounded-tool-action','failure-recovery','branch-evaluation','state-transition-guard','environment-trust-gate','audit-evidence-chain')
    $dynamic=@($mode.modes|Where-Object {[string]$_.modeId -ceq 'ABCD.Dynamic'})[0]
    Assert-True $dynamic.independent 'ABCD.Dynamic must be independent'
    Assert-True ((@($dynamic.capabilityCoverage|Sort-Object) -join '|') -ceq (@($required|Sort-Object) -join '|')) 'ABCD capability parity drifted'
    Assert-True ((@($core.parityContract.requiredCapabilities|Sort-Object) -join '|') -ceq (@($required|Sort-Object) -join '|')) 'ABCC parity closure drifted'
    Assert-True (-not [bool]$mode.parityRule.silentFallback) 'silent fallback enabled'
}
Case 'abcd-boundary-no-runtime-claim' {Assert-True ($plan.PSObject.Properties.Name -notcontains 'runtimeStatus') 'collaboration plan claimed runtime';Assert-True ($registry.PSObject.Properties.Name -notcontains 'completionDecision') 'registry claimed completion';Assert-True ($resultA.PSObject.Properties.Name -notcontains 'completionDecision') 'result claimed completion'}

$failed=@($results|Where-Object status -eq 'failed')
$report=[ordered]@{schemaVersion=1;validator='Test-ESTaskCollaborationContracts';status=if($failed.Count){'failed'}else{'passed'};caseCount=$results.Count;passedCount=@($results|Where-Object status -eq 'passed').Count;failedCount=$failed.Count;cases=@($results);runtimeStatus='runtime-not-run';claimsNotProven=@('Unity/Worker/MCP Runtime','cross-process scheduling','performance','release acceptance');abcdMode='ABCD.Dynamic';contracts=@('es-task-collaboration-plan-v1','es-task-child-task-registry-v1','es-task-lease-cas-v1','es-task-result-envelope-v1','es-task-parent-aggregation-v1')}
$fullReport=Join-Path $root $ReportPath;$parent=Split-Path -Parent $fullReport;if(-not(Test-Path -LiteralPath $parent)){New-Item -ItemType Directory -Path $parent -Force|Out-Null};[IO.File]::WriteAllText($fullReport,($report|ConvertTo-Json -Depth 20),[Text.UTF8Encoding]::new($false));$report|ConvertTo-Json -Depth 20;if($failed.Count){exit 1}
