[CmdletBinding()]
param([string]$ArtifactRoot='ES/Output/WebPageStudio/artifacts/github-atlas',[string]$ReceiptPath='ES/Output/WebPageStudio/bootstrap/round-07-static-artifact-closeout.json')
$ErrorActionPreference='Stop';$root=(Resolve-Path (Join-Path $PSScriptRoot '..\..\..\..')).Path;$dir=(Resolve-Path (Join-Path $root $ArtifactRoot)).Path;$html=Join-Path $dir 'index.html';if(-not(Test-Path -LiteralPath $html -PathType Leaf)){throw 'missing-html-artifact'}
$manifest=[ordered]@{name='Atlas Repository Command Center';short_name='Atlas';start_url='./index.html';display='standalone';lang='zh-CN';theme_color='#08111f';background_color='#08111f';description='Deterministic GitHub-style collaboration workspace'}
$nl=[Environment]::NewLine;$robots='User-agent: *'+$nl+'Allow: /'+$nl+'Disallow: /private/'+$nl
$sitemap='<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url><loc>./index.html</loc></url></urlset>'
[IO.File]::WriteAllText((Join-Path $dir 'manifest.json'),($manifest|ConvertTo-Json -Depth 10),[Text.UTF8Encoding]::new($false));[IO.File]::WriteAllText((Join-Path $dir 'robots.txt'),$robots,[Text.UTF8Encoding]::new($false));[IO.File]::WriteAllText((Join-Path $dir 'sitemap.xml'),$sitemap,[Text.UTF8Encoding]::new($false))
$files=@('index.html','manifest.json','robots.txt','sitemap.xml')|ForEach-Object{[ordered]@{path=(Join-Path $ArtifactRoot $_).Replace('\','/');sha256=(Get-FileHash (Join-Path $dir $_) -Algorithm SHA256).Hash.ToLowerInvariant();bytes=(Get-Item (Join-Path $dir $_)).Length}}
$out=Join-Path $root $ReceiptPath;$receipt=[ordered]@{schemaVersion=1;recordType='StaticArtifactCloseoutReceipt';status='static-artifact-closed';artifactRoot=$ArtifactRoot.Replace('\','/');files=$files;manifest='validated';robots='validated';sitemap='validated';evidenceBindings=[ordered]@{jsSyntax='Node --check via Test-ESRound06InteractionContracts.ps1';interactionContracts='.agents/skills/es-web-generation-round-06-deep-design-html/scripts/Test-ESRound06InteractionContracts.ps1';performanceA11y='.agents/skills/es-web-generation-round-06-deep-design-html/scripts/Test-ESRound06PerformanceA11yGate.ps1';deepReplay='.agents/skills/es-web-generation-round-06-deep-design-html/scripts/Test-ESRound06DeepDesignHtml-StaticReplay.ps1';seoMetadata='.agents/skills/es-web-generation-round-06-deep-design-html/scripts/Test-ESRound07SeoMetadata.ps1';navigationContract='.agents/skills/es-web-generation-round-06-deep-design-html/scripts/Test-ESRound07NavigationContract.ps1';clientSecurity='.agents/skills/es-web-generation-round-06-deep-design-html/scripts/Test-ESRound07ClientSecurity.ps1'};releaseStatus='release-not-run';runtimeStatus='runtime-not-run';nonClaims=@('not browser visual proof','not network/release execution')};[IO.File]::WriteAllText($out,($receipt|ConvertTo-Json -Depth 20),[Text.UTF8Encoding]::new($false));[pscustomobject]@{recordType=$receipt.recordType;status=$receipt.status;artifactRoot=$receipt.artifactRoot;releaseStatus=$receipt.releaseStatus;runtimeStatus=$receipt.runtimeStatus;fileCount=@($receipt.files).Count;evidenceBindingCount=@($receipt.evidenceBindings.Keys).Count}
