[CmdletBinding()]
param(
 [Parameter(Mandatory=$true)][string]$Round01Path,
 [Parameter(Mandatory=$true)][string]$Round02Path,
 [Parameter(Mandatory=$true)][string]$Round03Path,
 [Parameter(Mandatory=$true)][string]$Round04Path,
 [Parameter(Mandatory=$true)][string]$Round05Path,
 [Parameter(Mandatory=$true)][string]$ModelResponsePath,
 [string]$OutputDesignPath='ES/Output/WebPageStudio/bootstrap/round-05-5-page-design-project-management.json',
 [string]$OutputTaskPath='ES/Output/WebPageStudio/bootstrap/ai-web-design-task-project-management.json'
)
$ErrorActionPreference='Stop';$root=(Resolve-Path (Join-Path $PSScriptRoot '..\..\..\..')).Path
function ReadJ([string]$p){$f=if([IO.Path]::IsPathRooted($p)){ $p }else{ [IO.Path]::GetFullPath((Join-Path $root $p)) };if(-not(Test-Path -LiteralPath $f -PathType Leaf)){throw "blocked.round-05-5.input-missing:$p"};[Text.UTF8Encoding]::new($false,$true).GetString([IO.File]::ReadAllBytes($f))|ConvertFrom-Json}
function Hash([object]$v){$h=[Security.Cryptography.SHA256]::Create();try{$s=$v|ConvertTo-Json -Depth 80 -Compress;([BitConverter]::ToString($h.ComputeHash([Text.Encoding]::UTF8.GetBytes($s)))).Replace('-','').ToLowerInvariant()}finally{$h.Dispose()}}
function FileHash([string]$p){$f=if([IO.Path]::IsPathRooted($p)){$p}else{Join-Path $root $p};(Get-FileHash $f -Algorithm SHA256).Hash.ToLowerInvariant()}
$r1=ReadJ $Round01Path;$r2=ReadJ $Round02Path;$r3=ReadJ $Round03Path;$r4=ReadJ $Round04Path;$r5=ReadJ $Round05Path;$m=ReadJ $ModelResponsePath
if([string]$r5.recordType -cne 'DesignSystemProfileReceipt' -or [string]$r5.status -cne 'accepted'){throw 'blocked.round-05-5.round05-not-accepted'}
foreach($up in @(@($r1,'RequirementIntakeReceipt','web-generation-round-01'),@($r2,'FocusContextReceipt','web-generation-round-02'),@($r3,'TaskContextCreationReceipt','web-generation-round-03'),@($r4,'KnowledgeRouteReceipt','web-generation-round-04'))){if([string]$up[0].recordType -cne $up[1] -or [string]$up[0].status -ne 'accepted' -or [string]$up[0].roundId -ne $up[2]){throw "blocked.round-05-5.upstream-round-invalid:$($up[2])"}}
if([string]$m.recordType -cne 'AiWebDesignModelResponse'){throw 'blocked.round-05-5.model-response-invalid'}
if([string]::IsNullOrWhiteSpace([string]$m.providerRunId) -or [string]$m.providerRunId -match '(?i)normalized-|synthetic|fixture'){throw 'blocked.round-05-5.provider-id-invalid'}
$entry=@($m.responses|Where-Object {[string]$_.phase -eq 'page-design-instantiation' -and [string]$_.generationMode -in @('creative-divergence','engineering','stable') -and [int]$_.round -eq 0})
if($entry.Count -ne 1){throw 'blocked.round-05-5.model-response-not-found'}
$o=$entry[0].outputs[0];if($null -eq $o){throw 'blocked.round-05-5.design-output-empty'}
if([string]::IsNullOrWhiteSpace([string]$o.aiAnalysis) -or [string]$o.aiAnalysis.Length -lt 40 -or [string]::IsNullOrWhiteSpace([string]$o.execution) -or [string]$o.execution.Length -lt 20 -or $null -eq $o.returnReceipt -or $null -eq $o.evidence){throw 'blocked.round-05-5.model-evidence-incomplete'}
$required=@('objectiveBrief','securityContract','semanticHtml','informationArchitecture','visualDirection','interactionModel','implementationPlan','filesToCreate','filesToModify','riskAssessment','rejectedAlternatives','componentInventory','interactionStateGraph','responsiveMatrix','motionTimeline','a11yChecks','interactionContracts','viewContracts','detailContract')
foreach($n in $required){if($null -eq $o.PSObject.Properties[$n]){throw "blocked.round-05-5.design-field-missing:$n"}}
if([string]::IsNullOrWhiteSpace([string]$o.semanticHtml)){throw 'blocked.round-05-5.semantic-html-empty'}
if(@($o.filesToCreate).Count+@($o.filesToModify).Count -eq 0){throw 'blocked.round-05-5.file-manifest-empty'}
if($null -eq $o.provenance -or [string]$o.provenance.actor -notin @('current-ai-session','provider')){throw 'blocked.round-05-5.ai-provenance-missing'}
if(@($o.provenance.reads).Count -lt 5){throw 'blocked.round-05-5.ai-read-evidence-incomplete'}
$allowedRoot=[IO.Path]::GetFullPath((Join-Path $root 'ES/Output/WebPageStudio/artifacts')).TrimEnd('\')
foreach($f in @($o.filesToCreate)+@($o.filesToModify)){$full=if([IO.Path]::IsPathRooted([string]$f)){[IO.Path]::GetFullPath([string]$f)}else{[IO.Path]::GetFullPath((Join-Path $root ([string]$f)))};if(-not($full.Equals($allowedRoot,[StringComparison]::OrdinalIgnoreCase)-or $full.StartsWith($allowedRoot+'\',[StringComparison]::OrdinalIgnoreCase))){throw "blocked.round-05-5.file-outside-allowlist:$f"}}
$snapshot=[ordered]@{round01=[ordered]@{path=$Round01Path;hash=(FileHash $Round01Path)};round02=[ordered]@{path=$Round02Path;hash=(FileHash $Round02Path)};round03=[ordered]@{path=$Round03Path;hash=(FileHash $Round03Path)};round04=[ordered]@{path=$Round04Path;hash=(FileHash $Round04Path)};round05=[ordered]@{path=$Round05Path;hash=(FileHash $Round05Path)}}
$design=[ordered]@{schemaVersion=1;recordType='PageDesignInstantiation';stage='round-05-5';status='accepted';taskId=$r5.taskId;upstream=$snapshot;modelResponsePath=$ModelResponsePath;modelResponseHash=(Hash $m);phase=$entry[0].phase;generationMode=$entry[0].generationMode;round=0;objectiveBrief=$o.objectiveBrief;securityContract=$o.securityContract;semanticHtml=$o.semanticHtml;informationArchitecture=$o.informationArchitecture;visualDirection=$o.visualDirection;interactionModel=$o.interactionModel;implementationPlan=$o.implementationPlan;filesToCreate=$o.filesToCreate;filesToModify=$o.filesToModify;riskAssessment=$o.riskAssessment;rejectedAlternatives=$o.rejectedAlternatives;componentInventory=$o.componentInventory;interactionStateGraph=$o.interactionStateGraph;responsiveMatrix=$o.responsiveMatrix;motionTimeline=$o.motionTimeline;a11yChecks=$o.a11yChecks;interactionContracts=$o.interactionContracts;viewContracts=$o.viewContracts;detailContract=$o.detailContract;contentModel=$o.contentModel;traceability=$o.traceability;acceptanceAssertions=$o.acceptanceAssertions;listSchemas=$o.listSchemas;dataContracts=$o.dataContracts;dynamicDataModel=$o.dynamicDataModel;apiAdapterConfig=$o.apiAdapterConfig;performanceBudget=$o.performanceBudget;aiAnalysis=$o.aiAnalysis;execution=$o.execution;returnReceipt=$o.returnReceipt;nonClaims=@('does not prove HTML was written','does not prove browser/runtime/network/release behavior')}
$upstreamRounds=@($snapshot.GetEnumerator()|ForEach-Object{[ordered]@{round=[int]([regex]::Match($_.Key,'\d+').Value);path=$_.Value.path;hash=$_.Value.hash;role='upstream'}})
$task=[ordered]@{schemaVersion=1;recordType='AiWebDesignTask';taskId=('{0}-round06' -f $r5.taskId);parentTaskId=$r5.taskId;status='admitted';designPath=$OutputDesignPath;designHash=(Hash $design);round05DesignPacket=[ordered]@{path=$Round05Path;hash=(FileHash $Round05Path)};round05DesignPacketHash=(FileHash $Round05Path);requirementSnapshot=[ordered]@{rawPrompt=$r1.rawPrompt;focus=$r2.focus;round03Hash=$snapshot.round03.hash;sourceScopeHash=$r3.sourceScopeHash;taskIntent=$r5.taskId};abcdDecision=[ordered]@{status='accepted';source='Round05 receipt'};stopConditions=@('missing AI revision evidence','write outside allowlist','failed static checks');allowedWriteRoots=@('ES/Output/WebPageStudio/artifacts');filesToCreate=$o.filesToCreate;filesToModify=$o.filesToModify;requiredReads=@($Round01Path,$Round02Path,$Round03Path,$Round04Path,$Round05Path);requiredChecks=@('utf8','interaction-contracts','layout-dom','a11y','artifact-integrity');maxIterations=5;minimumRevisionRounds=5;upstreamRounds=$upstreamRounds;aiProvenance=[ordered]@{providerRunId=$m.providerRunId;responseHash=(Hash $m);actor=$o.provenance.actor}}
foreach($item in @(@($OutputDesignPath,$design),@($OutputTaskPath,$task))){$f=[IO.Path]::GetFullPath((Join-Path $root $item[0]));$d=Split-Path -Parent $f;if(-not(Test-Path $d)){New-Item -ItemType Directory $d -Force|Out-Null};[IO.File]::WriteAllText($f,($item[1]|ConvertTo-Json -Depth 80),[Text.UTF8Encoding]::new($false))}
[pscustomobject]@{status='accepted';designPath=(Join-Path $root $OutputDesignPath);taskPath=(Join-Path $root $OutputTaskPath);taskId=$task.taskId;upstreamCount=$snapshot.Count}
