// <auto-generated>
// Generated projection of GameCore character fixed attributes. Do not edit by hand.
// Regenerate only after changing the fixed API structure: fixedApiName, stable identity, kind, or slot order.
// Fixed API structural signature: v1|Float|18:GroundMaxMoveSpeed;1|33:Character.Movement.GroundMaxSpeed;15:AirMaxMoveSpeed;2|30:Character.Movement.AirMaxSpeed;23:GroundMovementSharpness;3|34:Character.Movement.GroundSharpness;15:AirAcceleration;4|34:Character.Movement.AirAcceleration;4:Drag;5|23:Character.Movement.Drag;9:JumpSpeed;6|28:Character.Movement.JumpSpeed;19:JumpSpeedMultiplier;7|38:Character.Movement.JumpSpeedMultiplier;25:JumpApexGravityMultiplier;8|44:Character.Movement.JumpApexGravityMultiplier;25:JumpFallGravityMultiplier;9|44:Character.Movement.JumpFallGravityMultiplier;21:CrouchSpeedMultiplier;10|40:Character.Movement.CrouchSpeedMultiplier;20:OrientationSharpness;11|39:Character.Movement.OrientationSharpness;15:RootMotionScale;12|34:Character.Movement.RootMotionScale;|Permit|4:Move;101|21:Character.Permit.Move;4:Jump;102|21:Character.Permit.Jump;6:Rotate;103|23:Character.Permit.Rotate;
// </auto-generated>

using System.Collections.Generic;

namespace ES
{
    public enum ESCharacterFloatAttributeId : byte
    {
        GroundMaxMoveSpeed = 0,
        AirMaxMoveSpeed = 1,
        GroundMovementSharpness = 2,
        AirAcceleration = 3,
        Drag = 4,
        JumpSpeed = 5,
        JumpSpeedMultiplier = 6,
        JumpApexGravityMultiplier = 7,
        JumpFallGravityMultiplier = 8,
        CrouchSpeedMultiplier = 9,
        OrientationSharpness = 10,
        RootMotionScale = 11,
        Count = 12
    }

    public enum ESCharacterPermitAttributeId : byte
    {
        Move = 0,
        Jump = 1,
        Rotate = 2,
        Count = 3
    }

    public enum ESCharacterAttributeEnumKey : ushort
    {
        None = 0,
        GroundMaxMoveSpeed = 1,
        AirMaxMoveSpeed = 2,
        GroundMovementSharpness = 3,
        AirAcceleration = 4,
        Drag = 5,
        JumpSpeed = 6,
        JumpSpeedMultiplier = 7,
        JumpApexGravityMultiplier = 8,
        JumpFallGravityMultiplier = 9,
        CrouchSpeedMultiplier = 10,
        OrientationSharpness = 11,
        RootMotionScale = 12,
        Move = 101,
        Jump = 102,
        Rotate = 103,
    }

    public enum ESCharacterAttributeValueKind : byte
    {
        Float = 0,
        Permit = 1
    }

    public static class ESCharacterSuperAttributeKeys
    {
        public const string GroundMaxMoveSpeed = "Character.Movement.GroundMaxSpeed";
        public const string AirMaxMoveSpeed = "Character.Movement.AirMaxSpeed";
        public const string GroundMovementSharpness = "Character.Movement.GroundSharpness";
        public const string AirAcceleration = "Character.Movement.AirAcceleration";
        public const string Drag = "Character.Movement.Drag";
        public const string JumpSpeed = "Character.Movement.JumpSpeed";
        public const string JumpSpeedMultiplier = "Character.Movement.JumpSpeedMultiplier";
        public const string JumpApexGravityMultiplier = "Character.Movement.JumpApexGravityMultiplier";
        public const string JumpFallGravityMultiplier = "Character.Movement.JumpFallGravityMultiplier";
        public const string CrouchSpeedMultiplier = "Character.Movement.CrouchSpeedMultiplier";
        public const string OrientationSharpness = "Character.Movement.OrientationSharpness";
        public const string RootMotionScale = "Character.Movement.RootMotionScale";
        public const string Move = "Character.Permit.Move";
        public const string Jump = "Character.Permit.Jump";
        public const string Rotate = "Character.Permit.Rotate";
    }

    public static partial class ESCharacterAttributeCatalog
    {
        // IDs are compact compiled slots only. EnumKey/StringKey remain the serializable identity.
        private static readonly string[] FloatKeys =
        {
            ESCharacterSuperAttributeKeys.GroundMaxMoveSpeed,
            ESCharacterSuperAttributeKeys.AirMaxMoveSpeed,
            ESCharacterSuperAttributeKeys.GroundMovementSharpness,
            ESCharacterSuperAttributeKeys.AirAcceleration,
            ESCharacterSuperAttributeKeys.Drag,
            ESCharacterSuperAttributeKeys.JumpSpeed,
            ESCharacterSuperAttributeKeys.JumpSpeedMultiplier,
            ESCharacterSuperAttributeKeys.JumpApexGravityMultiplier,
            ESCharacterSuperAttributeKeys.JumpFallGravityMultiplier,
            ESCharacterSuperAttributeKeys.CrouchSpeedMultiplier,
            ESCharacterSuperAttributeKeys.OrientationSharpness,
            ESCharacterSuperAttributeKeys.RootMotionScale,
        };

        private static readonly string[] PermitKeys =
        {
            ESCharacterSuperAttributeKeys.Move,
            ESCharacterSuperAttributeKeys.Jump,
            ESCharacterSuperAttributeKeys.Rotate,
        };

        private static readonly ushort[] FloatEnumKeys =
        {
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
            10,
            11,
            12,
        };

        private static readonly ushort[] PermitEnumKeys =
        {
            101,
            102,
            103,
        };

        public static int FloatCount => (int)ESCharacterFloatAttributeId.Count;
        public static int PermitCount => (int)ESCharacterPermitAttributeId.Count;

        public static ESSuperAttributeTable CreateDefaultSuperAttributeTable()
        {
            return new ESSuperAttributeTable
            {
                catalogScope = ESAttributeBakeTable.CharacterScope,
                floatAttributes = new List<ESSuperFloatAttributeDefinition>
                {
                    Float(1, ESCharacterSuperAttributeKeys.GroundMaxMoveSpeed, "GroundMaxMoveSpeed"),
                    Float(2, ESCharacterSuperAttributeKeys.AirMaxMoveSpeed, "AirMaxMoveSpeed"),
                    Float(3, ESCharacterSuperAttributeKeys.GroundMovementSharpness, "GroundMovementSharpness"),
                    Float(4, ESCharacterSuperAttributeKeys.AirAcceleration, "AirAcceleration"),
                    Float(5, ESCharacterSuperAttributeKeys.Drag, "Drag"),
                    Float(6, ESCharacterSuperAttributeKeys.JumpSpeed, "JumpSpeed"),
                    Float(7, ESCharacterSuperAttributeKeys.JumpSpeedMultiplier, "JumpSpeedMultiplier"),
                    Float(8, ESCharacterSuperAttributeKeys.JumpApexGravityMultiplier, "JumpApexGravityMultiplier"),
                    Float(9, ESCharacterSuperAttributeKeys.JumpFallGravityMultiplier, "JumpFallGravityMultiplier"),
                    Float(10, ESCharacterSuperAttributeKeys.CrouchSpeedMultiplier, "CrouchSpeedMultiplier"),
                    Float(11, ESCharacterSuperAttributeKeys.OrientationSharpness, "OrientationSharpness"),
                    Float(12, ESCharacterSuperAttributeKeys.RootMotionScale, "RootMotionScale"),
                },
                permitAttributes = new List<ESSuperPermitAttributeDefinition>
                {
                    Permit(101, ESCharacterSuperAttributeKeys.Move, "Move"),
                    Permit(102, ESCharacterSuperAttributeKeys.Jump, "Jump"),
                    Permit(103, ESCharacterSuperAttributeKeys.Rotate, "Rotate"),
                }
            };
        }

        public static bool IsValid(ESCharacterFloatAttributeId id) => (uint)id < (uint)ESCharacterFloatAttributeId.Count;
        public static bool IsValid(ESCharacterPermitAttributeId id) => (uint)id < (uint)ESCharacterPermitAttributeId.Count;
        public static string GetKey(ESCharacterFloatAttributeId id) => IsValid(id) ? FloatKeys[(int)id] : null;
        public static ushort GetEnumKey(ESCharacterFloatAttributeId id) => IsValid(id) ? FloatEnumKeys[(int)id] : (ushort)0;
        public static string GetKey(ESCharacterPermitAttributeId id) => IsValid(id) ? PermitKeys[(int)id] : null;
        public static ushort GetEnumKey(ESCharacterPermitAttributeId id) => IsValid(id) ? PermitEnumKeys[(int)id] : (ushort)0;

        public static bool TryGetFloatId(ushort enumKey, out ESCharacterFloatAttributeId id)
        {
            for (int i = 0; i < FloatEnumKeys.Length; i++)
                if (FloatEnumKeys[i] != 0 && FloatEnumKeys[i] == enumKey)
                {
                    id = (ESCharacterFloatAttributeId)i;
                    return true;
                }
            id = default;
            return false;
        }

        public static bool TryGetPermitId(ushort enumKey, out ESCharacterPermitAttributeId id)
        {
            for (int i = 0; i < PermitEnumKeys.Length; i++)
                if (PermitEnumKeys[i] != 0 && PermitEnumKeys[i] == enumKey)
                {
                    id = (ESCharacterPermitAttributeId)i;
                    return true;
                }
            id = default;
            return false;
        }

        public static bool TryGetFloatId(string key, out ESCharacterFloatAttributeId id)
        {
            switch (key)
            {
                case ESCharacterSuperAttributeKeys.GroundMaxMoveSpeed: id = ESCharacterFloatAttributeId.GroundMaxMoveSpeed; return true;
                case ESCharacterSuperAttributeKeys.AirMaxMoveSpeed: id = ESCharacterFloatAttributeId.AirMaxMoveSpeed; return true;
                case ESCharacterSuperAttributeKeys.GroundMovementSharpness: id = ESCharacterFloatAttributeId.GroundMovementSharpness; return true;
                case ESCharacterSuperAttributeKeys.AirAcceleration: id = ESCharacterFloatAttributeId.AirAcceleration; return true;
                case ESCharacterSuperAttributeKeys.Drag: id = ESCharacterFloatAttributeId.Drag; return true;
                case ESCharacterSuperAttributeKeys.JumpSpeed: id = ESCharacterFloatAttributeId.JumpSpeed; return true;
                case ESCharacterSuperAttributeKeys.JumpSpeedMultiplier: id = ESCharacterFloatAttributeId.JumpSpeedMultiplier; return true;
                case ESCharacterSuperAttributeKeys.JumpApexGravityMultiplier: id = ESCharacterFloatAttributeId.JumpApexGravityMultiplier; return true;
                case ESCharacterSuperAttributeKeys.JumpFallGravityMultiplier: id = ESCharacterFloatAttributeId.JumpFallGravityMultiplier; return true;
                case ESCharacterSuperAttributeKeys.CrouchSpeedMultiplier: id = ESCharacterFloatAttributeId.CrouchSpeedMultiplier; return true;
                case ESCharacterSuperAttributeKeys.OrientationSharpness: id = ESCharacterFloatAttributeId.OrientationSharpness; return true;
                case ESCharacterSuperAttributeKeys.RootMotionScale: id = ESCharacterFloatAttributeId.RootMotionScale; return true;
                default: id = default; return false;
            }
        }

        public static bool TryGetPermitId(string key, out ESCharacterPermitAttributeId id)
        {
            switch (key)
            {
                case ESCharacterSuperAttributeKeys.Move: id = ESCharacterPermitAttributeId.Move; return true;
                case ESCharacterSuperAttributeKeys.Jump: id = ESCharacterPermitAttributeId.Jump; return true;
                case ESCharacterSuperAttributeKeys.Rotate: id = ESCharacterPermitAttributeId.Rotate; return true;
                default: id = default; return false;
            }
        }

        public static bool TryGetValueKind(string key, out ESCharacterAttributeValueKind kind)
        {
            if (TryGetFloatId(key, out _)) { kind = ESCharacterAttributeValueKind.Float; return true; }
            if (TryGetPermitId(key, out _)) { kind = ESCharacterAttributeValueKind.Permit; return true; }
            kind = default;
            return false;
        }

        public static bool TryGetValueKind(ushort enumKey, out ESCharacterAttributeValueKind kind)
        {
            if (TryGetFloatId(enumKey, out _)) { kind = ESCharacterAttributeValueKind.Float; return true; }
            if (TryGetPermitId(enumKey, out _)) { kind = ESCharacterAttributeValueKind.Permit; return true; }
            kind = default;
            return false;
        }

        private static ESSuperFloatAttributeDefinition Float(ushort enumKey, string key, string fixedApiName)
        {
            return new ESSuperFloatAttributeDefinition
            {
                enumKey = enumKey,
                key = key,
                fixedApiName = fixedApiName,
                storagePolicy = ESKeyStoragePolicy.HotSlot
            };
        }

        private static ESSuperPermitAttributeDefinition Permit(ushort enumKey, string key, string fixedApiName)
        {
            return new ESSuperPermitAttributeDefinition
            {
                enumKey = enumKey,
                key = key,
                fixedApiName = fixedApiName,
                storagePolicy = ESKeyStoragePolicy.HotSlot
            };
        }
    }
}
