[CmdletBinding()]param([Parameter(Mandatory=$true)][string]$AggregatePath,[string]$TaskId='',[string]$FocusKey='', [string]$CycleId='web-ui-cycle', [int]$ExpectedTaskRevision=1, [int]$ExpectedContextVersion=1, [string]$RoutePlanHash='', [string]$SourceScopeHash='', [ValidateSet('not-verified','verified','blocked')][string]$FocusVerificationStatus='not-verified', [string[]]$FocusVerificationFindings=@(), [string]$StaticReplayReportPath='', [string]$StaticReplayReportHash='')
$ErrorActionPreference='Stop';$a=Get-Content -Raw -Encoding UTF8 -LiteralPath $AggregatePath|ConvertFrom-Json
if([string]$a.recordType -ne 'WebPageStudioUiEvidenceAggregate'){throw 'Unsupported aggregate record.'}
$layers=@($a.layers)|ForEach-Object {if($_.receiptPath -and (Test-Path -LiteralPath ([string]$_.receiptPath) -PathType Leaf)){$actual=(Get-FileHash -LiteralPath ([string]$_.receiptPath) -Algorithm SHA256).Hash.ToLowerInvariant();if($_.receiptHash -and [string]$_.receiptHash -ne $actual){throw "RECEIPT_HASH_DRIFT:$($_.layer)"}};[ordered]@{layer=[string]$_.layer;status=[string]$_.status;runtimeStatus=[string]$_.runtimeStatus;receiptRef=$_.receiptPath;receiptId=$_.receiptId;receiptHash=$_.receiptHash}}
$evidenceReferences=@($layers|Where-Object { $_.receiptRef }|ForEach-Object {[ordered]@{layer=$_.layer;path=$_.receiptRef;sha256=$_.receiptHash;receiptId=$_.receiptId}})
$evidenceComplete=($evidenceReferences.Count -eq 4 -and @($evidenceReferences|Where-Object {[string]$_.sha256 -notmatch '^[a-f0-9]{64}$' -or [string]::IsNullOrWhiteSpace([string]$_.path)}).Count -eq 0)
$decision=[string]$a.decision
if ($decision -eq 'accepted' -and -not $evidenceComplete) { throw 'ABCD_EVIDENCE_INCOMPLETE' }
$projectionDecision=if($FocusVerificationStatus -eq 'blocked'){'blocked'}else{$decision}
$projectionClaim=if($projectionDecision -eq 'accepted'){'runtime-evidence'}elseif($projectionDecision -eq 'partial'){'claim-cap'}else{'blocked'}
$reportRef=$null;$reportVerified=$true
if($StaticReplayReportPath){if(-not(Test-Path -LiteralPath $StaticReplayReportPath -PathType Leaf)){throw 'STATIC_REPLAY_REPORT_MISSING'};$reportActual=(Get-FileHash -LiteralPath $StaticReplayReportPath -Algorithm SHA256).Hash.ToLowerInvariant();if($StaticReplayReportHash -and $StaticReplayReportHash.ToLowerInvariant() -cne $reportActual){throw 'STATIC_REPLAY_REPORT_HASH_DRIFT'};$reportRef=[ordered]@{path=$StaticReplayReportPath;sha256=$reportActual};$reportVerified=$true}
$task=if($TaskId){$TaskId}else{[string]$a.taskId};$focus=if($FocusKey){$FocusKey}else{[string]$a.focusKey};$verificationStatus=if($decision -eq 'accepted'){'passed'}elseif($decision -eq 'partial'){'review'}else{'failed'}
$verificationStatus=if($projectionDecision -eq 'accepted'){'passed'}elseif($projectionDecision -eq 'partial'){'review'}else{'failed'}
[ordered]@{schemaVersion=1;recordType='ABCDWebUiEvidenceProjection';taskId=$task;focusKey=$focus;sourceAggregateId=[string]$a.aggregateId;decision=$projectionDecision;claimLevel=$projectionClaim;evidenceRefs=$layers;evidenceReferences=$evidenceReferences;verificationReportRef=$reportRef;promotionAllowed=($projectionDecision -eq 'accepted' -and $FocusVerificationStatus -ne 'blocked' -and $evidenceComplete -and $reportVerified);verificationEvent=[ordered]@{eventType='verification-recorded';cycleId=$CycleId;taskId=$task;expectedTaskRevision=$ExpectedTaskRevision;expectedContextVersion=$ExpectedContextVersion;routePlanHash=$RoutePlanHash;sourceScopeHash=$SourceScopeHash;verificationStatus=$verificationStatus;focusVerification=[ordered]@{status=$FocusVerificationStatus;findings=@($FocusVerificationFindings)};verificationReceiptRef=if($projectionDecision -eq 'accepted'){$a.aggregateId}else{$null};verificationReceiptHash=if($a.PSObject.Properties['receiptHash']){[string]$a.receiptHash}else{$null};readyForABCD=($projectionDecision -eq 'accepted' -and $FocusVerificationStatus -ne 'blocked' -and $evidenceComplete -and $reportVerified -and $a.PSObject.Properties['receiptHash'] -and [string]$a.receiptHash -match '^[a-f0-9]{64}$')};routeKeys=@('abcd-evidence','task-focus-context','web-ui-closure');nonClaims=@('projection-does-not-flatten-layer-status','partial-never-promotes-runtime','projection-does-not-authorize-execution','verification-event-is-input-only','accepted-projection-needs-complete-evidence-references','focus-blocked-forces-projection-blocked')}|ConvertTo-Json -Depth 12
