[CmdletBinding()]
param([Parameter(Mandatory=$true)][string]$KernelRequestPath)
$ErrorActionPreference='Stop';$OutputEncoding=[Console]::OutputEncoding=[Text.UTF8Encoding]::new($false)
$root=[IO.Path]::GetFullPath((Get-Location).Path).TrimEnd('\')+'\';$full=(Resolve-Path -LiteralPath $KernelRequestPath -ErrorAction Stop).Path;if(-not $full.StartsWith($root,[StringComparison]::OrdinalIgnoreCase)){throw 'KernelRequestPath must remain under project root.'}
Import-Module (Join-Path (Get-Location) 'ES/Automation/Contracts/ESJsonSchemaLite.psm1') -Force
$request=Get-Content -Raw -Encoding UTF8 $full|ConvertFrom-Json;$schema=Join-Path (Get-Location) 'ES/Automation/Contracts/es-web-page-studio-kernel-v1.schema.json';$errors=@(Test-ESJsonSchemaValue -SchemaPath $schema -Value $request);if($errors.Count){throw ('Kernel request schema failed: '+($errors -join '; '))}
$outputDir=[IO.Path]::GetFullPath((Join-Path $root ([string]$request.output.directory)));if(-not $outputDir.StartsWith($root,[StringComparison]::OrdinalIgnoreCase)){throw 'Kernel output must remain under project root.'};if(Test-Path -LiteralPath $outputDir){throw "Refusing to overwrite kernel output: $outputDir"};$outputParent=Split-Path -Parent $outputDir;if(-not(Test-Path -LiteralPath $outputParent)){New-Item -ItemType Directory -Path $outputParent -Force|Out-Null}
$safeReq=Join-Path $root "ES/Output/WebPageStudio/kernel-requests/compiled-$([guid]::NewGuid().ToString('N')).json";$new=Join-Path $root 'ES/Automation/WebPageStudio/New-ESWebPageStudioRequest.ps1';$static=Join-Path $root 'ES/Automation/WebPageStudio/Invoke-ESWebPageStudioStatic.ps1';$preflight=Join-Path $root 'ES/Automation/WebPageStudio/Invoke-ESWebPageStudioPreflight.ps1';$deepDesign=Join-Path $root 'ES/Automation/WebPageStudio/Invoke-ESWebPageStudioDeepDesign.ps1';$convert=Join-Path $root 'ES/Automation/WebPageStudio/Convert-ESWebPageStudioRequest.ps1'
& $new -Objective ([string]$request.page.title) -PageKind ([string]$request.page.pageKind) -PrimaryAction ([string]$request.page.primaryAction) -Language ([string]$request.page.language) -OutputPath $safeReq|Out-Null
$compiled=Get-Content -Raw -Encoding UTF8 $safeReq|ConvertFrom-Json;$compiled.output.outputDirectory=([string]$request.output.directory).TrimEnd('/','\');$compiled.publicBaseUrl='';$compiled.sitemap=[ordered]@{changefreq='weekly';priority=0.8;paths=@('./')};$compiled|ConvertTo-Json -Depth 12|Set-Content -LiteralPath $safeReq -Encoding UTF8
$preflightPath=Join-Path $root "ES/Output/WebPageStudio/kernel-requests/preflight-$([guid]::NewGuid().ToString('N')).json";$pf=& $preflight -RequestPath $safeReq -OutputPath $preflightPath|ConvertFrom-Json;if([string]$pf.status -ne 'accepted'){throw 'P0_PREFLIGHT_BLOCKED: kernel request preflight failed.'};$designPath=Join-Path $root "ES/Output/WebPageStudio/kernel-requests/deep-design-$([guid]::NewGuid().ToString('N')).json";$ds=& $deepDesign -PreflightPath $preflightPath -OutputPath $designPath|ConvertFrom-Json;if([string]$ds.designStatus -ne 'accepted'){throw 'P0_DESIGN_NOT_ACCEPTED: kernel deep design failed.'};& $static -RequestPath $safeReq -DesignSpecPath $designPath|Out-Null
$entry=Join-Path $outputDir 'index.html';$files=@('index.html','icon.svg','site.webmanifest','robots.txt','sitemap.xml','design-tokens.json','kernel-page-request.json','route-manifest.json','component-graph.json')
[IO.File]::Copy($safeReq,(Join-Path $outputDir 'kernel-page-request.json'),$false)
[IO.File]::WriteAllText((Join-Path $outputDir 'route-manifest.json'),($request.routes|ConvertTo-Json -Depth 8),[Text.UTF8Encoding]::new($false));[IO.File]::WriteAllText((Join-Path $outputDir 'component-graph.json'),($request.components|ConvertTo-Json -Depth 8),[Text.UTF8Encoding]::new($false))
if([string]$request.renderMode -eq 'dynamic'){
  $html=Get-Content -Raw -Encoding UTF8 $entry;$html=$html.Replace("frame-ancestors 'none'","frame-ancestors 'none'; script-src 'self'; connect-src 'self'");$html=$html.Replace('<nav aria-label="Primary navigation">','<nav aria-label="Primary navigation"><button class="nav-action" type="button" data-theme-toggle aria-pressed="false">Theme</button>');$html=$html.Replace('<h1 itemprop="name">','<h1 itemprop="name" data-bind="content.title">').Replace('<p class="lede">','<p class="lede" data-bind="content.summary">');$themeOverrides='<style>:root[data-theme="dark"]{--ink:#f4f7f5;--muted:#9aa7a3;--bg:#101516;--panel:#172021;--line:#2b3938;--cyan:#75e1d1;--lime:#d1f36a;--pink:#f28a9a}:root[data-theme="light"]{--ink:#172021;--muted:#536562;--bg:#f4f7f5;--panel:#ffffff;--line:#c8d6d2;--cyan:#087f78;--lime:#8ab51f;--pink:#b63d5a}</style>';$html=$html.Replace('</head>',$themeOverrides+'<script type="module" src="runtime.mjs" defer></script></head>');[IO.File]::WriteAllText($entry,$html,[Text.UTF8Encoding]::new($false))
  $endpoint=([string]$request.data.endpoint)|ConvertTo-Json -Compress;$timeout=[int]$request.data.timeoutSeconds;$runtime="const ENDPOINT=$endpoint;const TIMEOUT_MS=$($timeout*1000);const root=document.documentElement;const toggle=document.querySelector('[data-theme-toggle]');const saved=localStorage.getItem('es-theme');if(saved==='light'||saved==='dark'){root.dataset.theme=saved;}toggle?.addEventListener('click',()=>{const next=root.dataset.theme==='light'?'dark':'light';root.dataset.theme=next;localStorage.setItem('es-theme',next);toggle.setAttribute('aria-pressed',String(next==='dark'));});if(ENDPOINT){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),TIMEOUT_MS);fetch(ENDPOINT,{method:'GET',headers:{Accept:'application/json'},signal:controller.signal}).then(r=>{if(!r.ok)throw new Error('response');return r.json();}).then(data=>{document.querySelectorAll('[data-bind]').forEach(node=>{const key=node.getAttribute('data-bind');if(Object.prototype.hasOwnProperty.call(data,key)){node.textContent=String(data[key]);}});}).catch(()=>document.documentElement.dataset.dataState='error').finally(()=>clearTimeout(timer));}"
  [IO.File]::WriteAllText((Join-Path $outputDir 'runtime.mjs'),$runtime,[Text.UTF8Encoding]::new($false));$files+='runtime.mjs'
}
$hashes=[ordered]@{};foreach($name in $files){$path=Join-Path $outputDir $name;if(Test-Path -LiteralPath $path -PathType Leaf){$hashes[$name]=(Get-FileHash -LiteralPath $path -Algorithm SHA256).Hash.ToLowerInvariant()}}
$manifest=[ordered]@{schemaVersion=1;recordType='ESWebPageStudioKernelArtifact';format='html-css-esm';renderMode=[string]$request.renderMode;requestPath=$full.Substring($root.Length).Replace('\','/');outputDirectory=$outputDir.Substring($root.Length).Replace('\','/');entryFile='index.html';files=@($files);contentHashes=$hashes;theme=[ordered]@{name=[string]$request.theme.name;dark=$request.theme.dark;light=$request.theme.light;behavior='system-preference-plus-user-override-in-dynamic-mode'};dynamic=[ordered]@{endpoint=[string]$request.data.endpoint;source=[string]$request.data.source;script=if([string]$request.renderMode -eq 'dynamic'){'runtime.mjs'}else{$null}};runtimeStatus='runtime-not-run';network='disabled';claimsNotProven=@('browser rendering','dynamic endpoint availability','JavaScript execution','visual regression','production deployment')}
[IO.File]::WriteAllText((Join-Path $outputDir 'kernel-manifest.json'),($manifest|ConvertTo-Json -Depth 15),[Text.UTF8Encoding]::new($false));$manifest|ConvertTo-Json -Depth 15
