[CmdletBinding()]
param(
  [Parameter(Mandatory=$true)][string]$RequestPath,
  [Parameter(Mandatory=$true)][string]$DesignSpecPath,
  [Parameter(Mandatory=$true)][string]$RevisionReceiptPath,
  [switch]$AllowOverwrite
)
$ErrorActionPreference='Stop';$OutputEncoding=[Console]::OutputEncoding=[Text.UTF8Encoding]::new($false)
$root=[IO.Path]::GetFullPath((Get-Location).Path).TrimEnd('\')+'\'
function R([string]$p){$f=if([IO.Path]::IsPathRooted($p)){[IO.Path]::GetFullPath($p)}else{[IO.Path]::GetFullPath((Join-Path (Get-Location) $p))};if(-not $f.StartsWith($root,[StringComparison]::OrdinalIgnoreCase)){throw 'Path outside project root.'};$f}
function H([string]$p){(Get-FileHash -LiteralPath $p -Algorithm SHA256).Hash.ToLowerInvariant()}
$reqFile=R $RequestPath;$designFile=R $DesignSpecPath;$receiptFile=R $RevisionReceiptPath
$req=Get-Content $reqFile -Raw -Encoding UTF8|ConvertFrom-Json;$design=Get-Content $designFile -Raw -Encoding UTF8|ConvertFrom-Json;$receipt=Get-Content $receiptFile -Raw -Encoding UTF8|ConvertFrom-Json
if([string]$design.designStatus -ne 'accepted' -or [string]$design.decisionStatus -ne 'accepted'){throw 'BLOCKED_WEB_MATERIALIZATION_DESIGN_NOT_ACCEPTED'}
if([string]$receipt.recordType -cne 'AiWebDesignRevisionReceipt' -or [int]$receipt.round -lt 1 -or [string]$receipt.status -notin @('revision','candidate')){throw 'BLOCKED_WEB_MATERIALIZATION_AI_REVISION_REQUIRED'}
foreach($field in @('reads','writes','changedFiles','changedRegions','nextHypotheses','requestedChecks','designDecision','implementationSummary','sourceHashBefore','sourceHashAfter','artifactPath')){if($null -eq $receipt.PSObject.Properties[$field] -or [string]::IsNullOrWhiteSpace([string]$receipt.$field)){throw "BLOCKED_WEB_MATERIALIZATION_RECEIPT_FIELD_MISSING:$field"}}
$artifactFile=R ([string]$receipt.artifactPath);if(-not(Test-Path $artifactFile -PathType Leaf)){throw 'BLOCKED_WEB_MATERIALIZATION_AI_ARTIFACT_MISSING'}
$actual=H $artifactFile;if($actual -cne ([string]$receipt.sourceHashAfter).ToLowerInvariant()){throw 'BLOCKED_WEB_MATERIALIZATION_AI_ARTIFACT_HASH_MISMATCH'}
$outRel=[string]$req.output.outputDirectory;if([IO.Path]::IsPathRooted($outRel)-or $outRel-match '(^|[/\\])\.\.([/\\]|$)'){throw 'Output directory must be project-relative.'};$out=R $outRel
if(Test-Path $out){if(-not $AllowOverwrite){throw "Refusing to overwrite existing output directory: $out"};Remove-Item $out -Recurse -Force};New-Item -ItemType Directory $out -Force|Out-Null
$entry=[string]$req.output.entryFile;if([string]::IsNullOrWhiteSpace($entry)){throw 'BLOCKED_WEB_MATERIALIZATION_ENTRY_MISSING'};$entryFile=R (Join-Path $outRel $entry);New-Item -ItemType Directory (Split-Path $entryFile) -Force|Out-Null;Copy-Item $artifactFile $entryFile -Force
$sourceDir=Split-Path -Parent $artifactFile;foreach($changed in @($receipt.changedFiles)){if([string]::IsNullOrWhiteSpace([string]$changed)){continue};$candidate=R ([string]$changed);if(-not(Test-Path $candidate -PathType Leaf)){continue};$ext=[IO.Path]::GetExtension($candidate).ToLowerInvariant();if($ext -notin @('.html','.css','.js','.mjs','.svg')){continue};$relative=([Uri]::new(($sourceDir.TrimEnd('\')+'\'))).MakeRelativeUri([Uri]::new($candidate)).ToString().Replace('/','\');$dest=Join-Path $out $relative;if(-not $dest.StartsWith($out,[StringComparison]::OrdinalIgnoreCase)){throw 'BLOCKED_WEB_MATERIALIZATION_CHANGED_FILE_OUTSIDE_OUTPUT'};New-Item -ItemType Directory (Split-Path $dest) -Force|Out-Null;Copy-Item $candidate $dest -Force}
$base=[string]$req.publicBaseUrl;if([string]::IsNullOrWhiteSpace($base)){$base='./'};[IO.File]::WriteAllText((Join-Path $out 'robots.txt'),"User-agent: *`nAllow: /`n",[Text.UTF8Encoding]::new($false));[IO.File]::WriteAllText((Join-Path $out 'sitemap.xml'),("<?xml version=`"1.0`" encoding=`"UTF-8`"?><urlset xmlns=`"http://www.sitemaps.org/schemas/sitemap/0.9`"><url><loc>"+[Net.WebUtility]::HtmlEncode(($base.TrimEnd('/')+'/'+$entry))+"</loc></url></urlset>"),[Text.UTF8Encoding]::new($false))
$manifest=[ordered]@{name=[string]$req.objective;short_name='ES WebPage';start_url=$entry;display='standalone';theme_color='#101516';background_color='#101516';icons=@()};[IO.File]::WriteAllText((Join-Path $out 'site.webmanifest'),($manifest|ConvertTo-Json -Depth 8),[Text.UTF8Encoding]::new($false));[IO.File]::WriteAllText((Join-Path $out 'icon.svg'),'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" role="img" aria-label="Web"><rect width="64" height="64" rx="12" fill="#101516"/><path d="M16 18h32v8H24v8h20v8H24v4h24v8H16z" fill="#75e1d1"/></svg>',[Text.UTF8Encoding]::new($false))
$manifest=[ordered]@{schemaVersion=1;recordType='WebPageStudioAiArtifactManifest';status='static-generated';sourceRevisionReceipt=$RevisionReceiptPath.Replace('\','/');sourceRevisionHash=H $receiptFile;entryFile=$entryFile.Substring($root.Length).Replace('\','/');entryHash=H $entryFile;bytes=([IO.File]::ReadAllBytes($entryFile)).Length;designSpecHash=H $designFile;runtimeStatus='runtime-not-run';nonClaims=@('does not prove browser, network, Unity or release')};[IO.File]::WriteAllText((Join-Path $out 'artifact-manifest.json'),($manifest|ConvertTo-Json -Depth 10),[Text.UTF8Encoding]::new($false));$manifest|ConvertTo-Json -Depth 10
