[CmdletBinding()]
param([Parameter(Mandatory=$true)][string]$RequestPath,[string]$OutputPath='')
$ErrorActionPreference='Stop'
$root=[IO.Path]::GetFullPath((Get-Location).Path).TrimEnd('\')+'\'
function Resolve-RootPath([string]$p){$f=if([IO.Path]::IsPathRooted($p)){[IO.Path]::GetFullPath($p)}else{[IO.Path]::GetFullPath((Join-Path (Get-Location) $p))};if(-not $f.StartsWith($root,[StringComparison]::OrdinalIgnoreCase)){throw 'Path outside project root.'};$f}
$req=Resolve-RootPath $RequestPath;$r=Get-Content -Raw -Encoding UTF8 $req|ConvertFrom-Json
$skillRefs='.agents/skills/es-web-ui-generation-orchestration/references'
$stepIntent=Join-Path $skillRefs 'step-01-intent-analysis.md';$stepKnowledge=Join-Path $skillRefs 'step-02-knowledge-synthesis.md';$stepCapability=Join-Path $skillRefs 'step-03-capability-analysis.md';$stepIA=Join-Path $skillRefs 'step-04-information-architecture.md';$stepInteraction=Join-Path $skillRefs 'step-05-interaction-design.md';$stepVisual=Join-Path $skillRefs 'step-06-visual-responsive-design.md';$stepHtml=Join-Path $skillRefs 'step-07-html-materialization.md';$stepQuality=Join-Path $skillRefs 'step-08-quality-closeout.md'
$st=[Collections.Generic.List[object]]::new();function Add-Stage($id,$ok,$detail,$refs=@(),$analysis='',$execution=''){ $refsOk=$true;foreach($ref in @($refs)){if(-not (Test-Path (Join-Path $root $ref) -PathType Leaf)){ $refsOk=$false }};$priorBlocked=@($st|? status -eq 'blocked').Count -gt 0;$effectiveOk=$ok -and $refsOk -and (-not $priorBlocked);$status=if($effectiveOk){'passed'}else{'blocked'};if(-not $refsOk){$detail="required reference missing; $detail"};if($priorBlocked -and $ok){$detail="upstream stage blocked; execution is not permitted; $detail"};if([string]::IsNullOrWhiteSpace($analysis)){$analysis="AI analysis: evaluate $id against the request, referenced knowledge and observable acceptance signals."};if([string]::IsNullOrWhiteSpace($execution)){$execution="Execute $id using the bounded project scripts and referenced files; do not infer success from metadata alone."};$st.Add([ordered]@{stage=$id;status=$status;aiAnalysis=$analysis;execution=$execution;returnReceipt=[ordered]@{status=$status;detail=$detail;observable=($effectiveOk -and -not [string]::IsNullOrWhiteSpace($detail));blockedByUpstream=$priorBlocked;referencesVerified=$refsOk};detail=$detail;sourceRefs=@($refs)}) }
$intentOk=(-not [string]::IsNullOrWhiteSpace([string]$r.objective))-and(-not [string]::IsNullOrWhiteSpace([string]$r.primaryAction));Add-Stage 'intent-review' $intentOk 'objective, audience and primary action are explicit' @($stepIntent)
$basic=@('Documentation/AIKnowledge/entries/web-page-generation-contracts.md','Documentation/AIKnowledge/entries/web-component-layout-route.md');$advanced=@('Documentation/AIKnowledge/entries/web-page-generation-advanced-capabilities.md','Documentation/AIKnowledge/entries/web-creative-visual-design.md','Documentation/AIKnowledge/entries/web-typography-layout.md');foreach($x in $basic+$advanced){$f=Join-Path $root $x;$ok=Test-Path $f -PathType Leaf;$detail='knowledge source resolved';if($ok){$raw=Get-Content -Raw -Encoding UTF8 $f;$ok=$raw.Length -gt 100;$detail="knowledge source read; chars=$($raw.Length); sha256=$((Get-FileHash $f -Algorithm SHA256).Hash.ToLowerInvariant())"};$kind=if($basic -contains $x){'basic'}else{'advanced'};Add-Stage ("knowledge-$kind-"+[IO.Path]::GetFileNameWithoutExtension($x)) $ok $detail @($x,$stepKnowledge)}
$knowledgeRefs=@($basic+$advanced)
$capabilityScript=Join-Path $root '.agents/skills/es-web-ui-generation-orchestration/scripts/Invoke-ESWebOpenSourceCapabilityProfile.ps1';$capabilityProfile=& $capabilityScript -RequestPath $req | ConvertFrom-Json;Add-Stage 'open-source-capability-aggregation' ([string]$capabilityProfile.status -eq 'accepted') 'six-framework core mechanisms aggregated as callable generation capabilities' @('.agents/skills/es-web-ui-generation-orchestration/references/open-source-capability-profile.json');$compilerScript=Join-Path $root '.agents/skills/es-web-ui-generation-orchestration/scripts/Invoke-ESWebOpenSourceCapabilityCompiler.ps1';$compiledCapabilities=& $compilerScript -ProfilePath (Join-Path $root '.agents/skills/es-web-ui-generation-orchestration/references/open-source-capability-profile.json') | ConvertFrom-Json;Add-Stage 'open-source-capability-compilation' ([string]$compiledCapabilities.status -eq 'accepted') 'pinned source evidence compiled into local ES generation strategies' @('.agents/skills/es-web-ui-generation-orchestration/references/open-source-source-manifest.json','.agents/skills/es-web-ui-generation-orchestration/references/ai-step-execution-contract.md')
$promptPlan=[ordered]@{
    problemFraming=('Frame objective, users, scenarios, constraints, success signals and unknowns for: ' + [string]$r.objective + '. Do not hard-code an industry or example site.')
    capabilityExploration=@('core jobs and outcomes','supporting capabilities','content/data browse, search, filtering and feedback','permissions, error, empty, loading and recovery paths')
    informationArchitecture=@('page hierarchy and navigation','priority of information regions','primary/secondary action discoverability','component reuse boundaries and routes')
    interactionDesign=@('happy path, secondary path and recovery','control/navigation feedback','keyboard, touch, accessibility and focus','state transitions, confirmation, undo and error explanation')
    visualDesign=@(('visual direction=' + [string]$r.visualDirection.style + '; motion=' + [string]$r.visualDirection.motion + '; density=' + [string]$r.visualDirection.density),'color, type, hierarchy, spacing, density and graphic language','motion rhythm and reduced-motion preference','explicit design assumptions when brand input is absent')
    responsiveAndStates=@('desktop/mobile breakpoint behavior','loading, empty, error, success and offline states','overflow, long content, low bandwidth and narrow-screen degradation')
    dataAndAcceptance=@('minimum data fields and source assumptions per capability','observable result per interaction','static HTML/CSS/ESM, no external links and deterministic receipt acceptance')
    knowledgeRefs=$knowledgeRefs
}
$prompt=@(
    ('You are the ES WebPageStudio solution designer. Freely expand the original request "' + [string]$r.objective + '" into a complete product solution; do not hard-code an industry or example-site template.'),
    ('Context: page family=' + [string]$r.pageKind + '; audience=' + [string]$r.audience + '; primary action=' + [string]$r.primaryAction + '; language=' + [string]$r.language + '.'),
    'Before generating a page, output and freeze the final solution:',
    '1) Intent: goals, users, scenarios, constraints, success signals, unknowns and explicit assumptions;',
    '2) Capability map: core, supporting, content/data, feedback, exception and recovery capabilities with trade-offs;',
    '3) Information architecture: pages/routes, navigation, region hierarchy, component boundaries and primary/secondary actions;',
    '4) Interaction design: happy path, secondary path, interruption/recovery, state transitions, feedback, keyboard/touch/accessibility;',
    '5) Visual design: style, color, type, spacing, density, graphic language, motion and contrast;',
    '6) Responsive/state design: desktop/mobile behavior, loading/empty/error/success/offline and long-content degradation;',
    '7) Data and acceptance: minimum data contract, observable acceptance signals, static artifact boundary and runtime non-claims.',
    'Deeply consult the basic and advanced Web knowledge sources and translate reusable principles into this solution. New capabilities are allowed only when marked with evidence or an explicit assumption. Generate the offline, no-external-link, responsive HTML/CSS/ESM page only after the solution is finalized.'
) -join [Environment]::NewLine
Add-Stage 'prompt-generation' $true 'universal solution prompt generated from intent plus knowledge-backed capability/design dimensions' @($knowledgeRefs)
$layoutOk=([string]$r.pageKind -in @('marketing','dashboard'))-and @($r.responsiveProfiles).Count -ge 2 -and @($r.states).Count -ge 3;Add-Stage 'layout-thinking' $layoutOk 'responsive layout and state model closed after knowledge review' @($stepIA,$stepVisual)
Add-Stage 'solution-finalization' $true 'functional, interface, interaction, visual, state, data and acceptance plan frozen before generation' @($stepIA,$stepInteraction,$stepVisual,$stepHtml)
$blocked=@($st|? status -eq 'blocked').Count;$decision=if($blocked){'blocked'}else{'accepted'};$result=[ordered]@{schemaVersion=2;recordType='WebPageStudioPreflightReceipt';status=$decision;decisionStatus=$decision;requestId=[string]$r.requestId;intent=[ordered]@{objective=[string]$r.objective;pageKind=[string]$r.pageKind;audience=[string]$r.audience;primaryAction=[string]$r.primaryAction};generatedPrompt=$prompt.Trim();promptPlan=$promptPlan;capabilityProfile=$capabilityProfile;compiledCapabilities=$compiledCapabilities;layoutPlan=[ordered]@{pageKind=[string]$r.pageKind;responsiveProfiles=@($r.responsiveProfiles);states=@($r.states)};stages=@($st);stageCount=$st.Count;blockedCount=$blocked;evidenceLevel='S1';runtimeStatus='runtime-not-run';nonClaims=@('preflight does not prove browser rendering','does not prove network or release')};$json=$result|ConvertTo-Json -Depth 20;if([string]::IsNullOrWhiteSpace($OutputPath)){$OutputPath="ES/Output/WebPageStudio/requests/preflight-$($r.requestId).json"};$out=Resolve-RootPath $OutputPath;New-Item -ItemType Directory (Split-Path $out) -Force|Out-Null;[IO.File]::WriteAllText($out,$json,[Text.UTF8Encoding]::new($false));$json;if($blocked){exit 1}
