[CmdletBinding()]
param([Parameter(Mandatory=$true)][string]$RequestPath,[string]$OutputPath='', [string]$AiSolutionPath='', [string[]]$RoundPaths=@())
$ErrorActionPreference='Stop'
# candidate-only: preflight cannot authorize writes or final completion; P0_DESIGN_NOT_ACCEPTED is the hard rejection marker.
$root=[IO.Path]::GetFullPath((Get-Location).Path).TrimEnd('\')+'\'
function Resolve-RootPath([string]$p){$f=if([IO.Path]::IsPathRooted($p)){[IO.Path]::GetFullPath($p)}else{[IO.Path]::GetFullPath((Join-Path (Get-Location) $p))};if(-not $f.StartsWith($root,[StringComparison]::OrdinalIgnoreCase)){throw 'Path outside project root.'};$f}
$solutionContractRel='ES/Automation/Contracts/es-ai-web-solution-response-v1.schema.json'
$solutionContractFile=Resolve-RootPath $solutionContractRel
if(-not (Test-Path -LiteralPath $solutionContractFile -PathType Leaf)){throw 'BLOCKED_WEB_PREFLIGHT_SOLUTION_CONTRACT_MISSING'}
$solutionContractHash=(Get-FileHash -LiteralPath $solutionContractFile -Algorithm SHA256).Hash.ToLowerInvariant()
$req=Resolve-RootPath $RequestPath;$r=Get-Content -Raw -Encoding UTF8 $req|ConvertFrom-Json
if(@($RoundPaths).Count -ne 5){$continuityOk=$false;$continuityJson='BLOCKED_WEB_PREFLIGHT_ROUND_PATHS_REQUIRED'}else{$continuityScript=Join-Path $root 'ES/Automation/WebPageStudio/Test-ESWebRoundContinuityGate.ps1';$continuityJson=& $continuityScript -RequestPath $req -RoundPaths $RoundPaths 2>&1 | Out-String;$continuityOk=$LASTEXITCODE -eq 0}
$skillRefs='.agents/skills/es-web-ui-generation-orchestration/references'
$stepIntent=Join-Path $skillRefs 'step-01-intent-analysis.md';$stepKnowledge=Join-Path $skillRefs 'step-02-knowledge-synthesis.md';$stepCapability=Join-Path $skillRefs 'step-03-capability-analysis.md';$stepIA=Join-Path $skillRefs 'step-04-information-architecture.md';$stepInteraction=Join-Path $skillRefs 'step-05-interaction-design.md';$stepVisual=Join-Path $skillRefs 'step-06-visual-responsive-design.md';$stepHtml=Join-Path $skillRefs 'step-07-html-materialization.md';$stepQuality=Join-Path $skillRefs 'step-08-quality-closeout.md'
$st=[Collections.Generic.List[object]]::new();function Add-Stage($id,$ok,$detail,$refs=@(),$analysis='',$execution=''){ $refsOk=$true;foreach($ref in @($refs)){if(-not (Test-Path (Join-Path $root $ref) -PathType Leaf)){ $refsOk=$false }};$priorBlocked=@($st|? status -eq 'blocked').Count -gt 0;$effectiveOk=$ok -and $refsOk -and (-not $priorBlocked);$status=if($effectiveOk){'passed'}else{'blocked'};if(-not $refsOk){$detail="required reference missing; $detail"};if($priorBlocked -and $ok){$detail="upstream stage blocked; execution is not permitted; $detail"};$toolAnalysis=if([string]::IsNullOrWhiteSpace($analysis)){"Tool validation for $id used bounded project scripts and referenced files."}else{$analysis};$toolExecution=if([string]::IsNullOrWhiteSpace($execution)){"Execute $id with deterministic checks; no AI design decision is inferred."}else{$execution};$st.Add([ordered]@{stage=$id;status=$status;aiAnalysis=$null;toolAnalysis=$toolAnalysis;toolExecution=$toolExecution;aiEvidenceRequired=$true;returnReceipt=[ordered]@{status=$status;detail=$detail;observable=($effectiveOk -and -not [string]::IsNullOrWhiteSpace($detail));blockedByUpstream=$priorBlocked;referencesVerified=$refsOk};detail=$detail;sourceRefs=@($refs)}) }
	Add-Stage 'round-continuity' $continuityOk $continuityJson @('ES/Automation/WebPageStudio/Test-ESWebRoundContinuityGate.ps1')
	$semanticContinuityOk=$false;$semanticContinuityJson='BLOCKED_WEB_PREFLIGHT_SEMANTIC_CONTINUITY_REQUIRED'
	if(@($RoundPaths).Count -eq 5){$semanticValidator=Join-Path $root 'ES/Automation/WebPageStudio/Test-ESWebRoundSemanticContinuity.ps1';if(Test-Path -LiteralPath $semanticValidator -PathType Leaf){$semanticRoundPaths=@($RoundPaths|Select-Object -First 4);$semanticContinuityJson=& $semanticValidator -RoundPaths $semanticRoundPaths -ProjectRoot $root 2>&1|Out-String;$semanticContinuityOk=$LASTEXITCODE -eq 0}}
	Add-Stage 'round-semantic-continuity' $semanticContinuityOk $semanticContinuityJson @('ES/Automation/WebPageStudio/Test-ESWebRoundSemanticContinuity.ps1')
	$intentOk=(-not [string]::IsNullOrWhiteSpace([string]$r.objective))-and(-not [string]::IsNullOrWhiteSpace([string]$r.primaryAction));Add-Stage 'intent-review' $intentOk 'objective, audience and primary action are explicit' @($stepIntent)
$basic=@('Documentation/AIKnowledge/entries/web-page-generation-contracts.md','Documentation/AIKnowledge/entries/web-component-layout-route.md');$advanced=@('Documentation/AIKnowledge/entries/web-page-generation-advanced-capabilities.md','Documentation/AIKnowledge/entries/web-creative-visual-design.md','Documentation/AIKnowledge/entries/web-typography-layout.md');foreach($x in $basic+$advanced){$f=Join-Path $root $x;$ok=Test-Path $f -PathType Leaf;$detail='knowledge source resolved';if($ok){$raw=Get-Content -Raw -Encoding UTF8 $f;$ok=$raw.Length -gt 100;$detail="knowledge source read; chars=$($raw.Length); sha256=$((Get-FileHash $f -Algorithm SHA256).Hash.ToLowerInvariant())"};$kind=if($basic -contains $x){'basic'}else{'advanced'};Add-Stage ("knowledge-$kind-"+[IO.Path]::GetFileNameWithoutExtension($x)) $ok $detail @($x,$stepKnowledge)}
$knowledgeRefs=@($basic+$advanced)
$capabilityScript=Join-Path $root '.agents/skills/es-web-ui-generation-orchestration/scripts/Invoke-ESWebOpenSourceCapabilityProfile.ps1';$capabilityProfile=& $capabilityScript -RequestPath $req | ConvertFrom-Json;Add-Stage 'open-source-capability-aggregation' ([string]$capabilityProfile.status -eq 'accepted') 'six-framework core mechanisms aggregated as callable generation capabilities' @('.agents/skills/es-web-ui-generation-orchestration/references/open-source-capability-profile.json');$compilerScript=Join-Path $root '.agents/skills/es-web-ui-generation-orchestration/scripts/Invoke-ESWebOpenSourceCapabilityCompiler.ps1';$compiledCapabilities=& $compilerScript -ProfilePath (Join-Path $root '.agents/skills/es-web-ui-generation-orchestration/references/open-source-capability-profile.json') | ConvertFrom-Json;Add-Stage 'open-source-capability-compilation' ([string]$compiledCapabilities.status -eq 'accepted') 'pinned source evidence compiled into local ES generation strategies' @('.agents/skills/es-web-ui-generation-orchestration/references/open-source-source-manifest.json','.agents/skills/es-web-ui-generation-orchestration/references/ai-step-execution-contract.md')
$promptPlan=[ordered]@{
    problemFraming=('Frame objective, users, scenarios, constraints, success signals and unknowns for: ' + [string]$r.objective + '. Do not hard-code an industry or example site.')
    capabilityExploration=@('core jobs and outcomes','supporting capabilities','content/data browse, search, filtering and feedback','permissions, error, empty, loading and recovery paths')
    informationArchitecture=@('page hierarchy and navigation','priority of information regions','primary/secondary action discoverability','component reuse boundaries and routes')
    interactionDesign=@('happy path, secondary path and recovery','control/navigation feedback','keyboard, touch, accessibility and focus','state transitions, confirmation, undo and error explanation')
    visualDesign=@(('visual direction=' + [string]$r.visualDirection.style + '; motion=' + [string]$r.visualDirection.motion + '; density=' + [string]$r.visualDirection.density),'color, type, hierarchy, spacing, density and graphic language','motion rhythm and reduced-motion preference','explicit design assumptions when brand input is absent')
    responsiveAndStates=@('desktop/mobile breakpoint behavior','loading, empty, error, success and offline states','overflow, long content, low bandwidth and narrow-screen degradation')
    dataAndAcceptance=@('minimum data fields and source assumptions per capability','observable result per interaction','static HTML/CSS/ESM, no external links and deterministic receipt acceptance')
    knowledgeRefs=$knowledgeRefs
}
$prompt=@(
    ('You are the ES WebPageStudio solution designer. Freely expand the original request "' + [string]$r.objective + '" into a complete product solution; do not hard-code an industry or example-site template.'),
    ('Context: page family=' + [string]$r.pageKind + '; audience=' + [string]$r.audience + '; primary action=' + [string]$r.primaryAction + '; language=' + [string]$r.language + '.'),
    'Before generating a page, output and freeze the final solution:',
    '1) Intent: goals, users, scenarios, constraints, success signals, unknowns and explicit assumptions;',
    '2) Capability map: core, supporting, content/data, feedback, exception and recovery capabilities with trade-offs;',
    '3) Information architecture: pages/routes, navigation, region hierarchy, component boundaries and primary/secondary actions;',
    '4) Interaction design: happy path, secondary path, interruption/recovery, state transitions, feedback, keyboard/touch/accessibility;',
    '5) Visual design: style, color, type, spacing, density, graphic language, motion and contrast;',
    '6) Responsive/state design: desktop/mobile behavior, loading/empty/error/success/offline and long-content degradation;',
    '7) Data and acceptance: minimum data contract, observable acceptance signals, static artifact boundary and runtime non-claims.',
    'Deeply consult the basic and advanced Web knowledge sources and translate reusable principles into this solution. New capabilities are allowed only when marked with evidence or an explicit assumption. Generate the offline, no-external-link, responsive HTML/CSS/ESM page only after the solution is finalized.'
) -join [Environment]::NewLine
if([string]::IsNullOrWhiteSpace($AiSolutionPath)){$solutionOk=$false;$solutionDetail='BLOCKED_WEB_PREFLIGHT_AI_SOLUTION_REQUIRED'}else{$solutionFile=Resolve-RootPath $AiSolutionPath;if(-not(Test-Path $solutionFile -PathType Leaf)){throw 'BLOCKED_WEB_PREFLIGHT_AI_SOLUTION_MISSING'};$solution=Get-Content $solutionFile -Raw -Encoding UTF8|ConvertFrom-Json;$requiredSolution=@('intent','capabilityMap','informationArchitecture','interactionDesign','visualDesign','responsiveAndStates','dataAndAcceptance','providerRunId','aiAnalysis','execution','returnReceipt','evidence','provenance','upstreamRounds');$missingSolution=@($requiredSolution|Where-Object{$null -eq $solution.PSObject.Properties[$_]});$upstreamOk=$true;if(@($solution.upstreamRounds).Count -ne 5 -or @($RoundPaths).Count -ne 5){$upstreamOk=$false}else{for($i=0;$i -lt 5;$i++){ $rp=Resolve-RootPath $RoundPaths[$i];$rh=(Get-FileHash $rp -Algorithm SHA256).Hash.ToLowerInvariant();$u=$solution.upstreamRounds[$i];if([string]$u.path -ne [string]$RoundPaths[$i] -or [string]$u.hash.ToLowerInvariant() -ne $rh){$upstreamOk=$false}}};$solutionOk=$missingSolution.Count -eq 0 -and $upstreamOk -and [string]$solution.recordType -eq 'AiWebSolutionResponse' -and [string]$solution.provenance.actor -in @('current-ai-session','provider') -and [string]$solution.providerRunId -notmatch '(?i)normalized-|synthetic|fixture' -and [string]$solution.aiAnalysis.Length -ge 80 -and [string]$solution.execution.Length -ge 40 -and [string]$solution.informationArchitecture.Length -ge 120 -and [string]$solution.interactionDesign.Length -ge 120 -and [string]$solution.visualDesign.Length -ge 120;$solutionDetail=if($solutionOk){'AI solution response read with provider identity, analysis, execution, evidence and current Round01-05 hashes'}else{'BLOCKED_WEB_PREFLIGHT_AI_SOLUTION_INCOMPLETE:'+$($missingSolution -join ',')+$(if(-not $upstreamOk){';upstream-round-hash-mismatch'}else{''})}};Add-Stage 'prompt-generation' $solutionOk $solutionDetail @($knowledgeRefs)
$layoutOk=([string]$r.pageKind -in @('marketing','dashboard'))-and @($r.responsiveProfiles).Count -ge 2 -and @($r.states).Count -ge 3;Add-Stage 'layout-thinking' $layoutOk 'responsive layout and state model closed after knowledge review' @($stepIA,$stepVisual)
$solutionContractValidation=$null
if(-not [string]::IsNullOrWhiteSpace($AiSolutionPath) -and $solutionFile -and (Test-Path -LiteralPath $solutionFile -PathType Leaf)){
  $solutionValidator=Join-Path $root 'ES/Automation/WebPageStudio/Test-ESWebSolutionResponse.ps1'
  if(Test-Path -LiteralPath $solutionValidator -PathType Leaf){
    $solutionContractValidation=& $solutionValidator -SolutionPath $AiSolutionPath -ProjectRoot $root 2>&1 | Out-String
    try{$solutionContractValidation=$solutionContractValidation|ConvertFrom-Json}catch{$solutionContractValidation=[pscustomobject]@{status='blocked';findings=@('validator-output-invalid')}}
    $solutionOk=$solutionOk -and [string]$solutionContractValidation.status -eq 'passed'
  }else{$solutionOk=$false;$solutionContractValidation=[pscustomobject]@{status='blocked';findings=@('blocked.solution-response.validator-missing')}}
}
Add-Stage 'solution-contract-validation' ($null -ne $solutionContractValidation -and [string]$solutionContractValidation.status -eq 'passed') 'AiWebSolutionResponse contract and evidence validator executed' @('ES/Automation/Contracts/es-ai-web-solution-response-v1.schema.json','ES/Automation/WebPageStudio/Test-ESWebSolutionResponse.ps1')
Add-Stage 'solution-finalization' $solutionOk 'functional, interface, interaction, visual, state, data and acceptance plan must come from the AI solution response' @($stepIA,$stepInteraction,$stepVisual,$stepHtml)
$blocked=@($st|? status -eq 'blocked').Count;$decision=if($blocked){'blocked'}else{'accepted'};$result=[ordered]@{schemaVersion=2;recordType='WebPageStudioPreflightReceipt';status=$decision;decisionStatus=$decision;requestId=[string]$r.requestId;intent=[ordered]@{objective=[string]$r.objective;pageKind=[string]$r.pageKind;audience=[string]$r.audience;primaryAction=[string]$r.primaryAction};generatedPrompt=$prompt.Trim();promptPlan=$promptPlan;aiSolutionPath=if($solutionFile){$AiSolutionPath.Replace('\','/')}else{$null};aiSolutionHash=if($solutionFile){(Get-FileHash $solutionFile -Algorithm SHA256).Hash.ToLowerInvariant()}else{$null};capabilityProfile=$capabilityProfile;compiledCapabilities=$compiledCapabilities;layoutPlan=[ordered]@{pageKind=[string]$r.pageKind;responsiveProfiles=@($r.responsiveProfiles);states=@($r.states)};stages=@($st);stageCount=$st.Count;blockedCount=$blocked;evidenceLevel='S1';runtimeStatus='runtime-not-run';nonClaims=@('preflight does not prove browser rendering','does not prove network or release','promptPlan alone is not an AI solution')};$json=$result|ConvertTo-Json -Depth 20;if([string]::IsNullOrWhiteSpace($OutputPath)){$OutputPath="ES/Output/WebPageStudio/requests/preflight-$($r.requestId).json"};$out=Resolve-RootPath $OutputPath;New-Item -ItemType Directory (Split-Path $out) -Force|Out-Null;[IO.File]::WriteAllText($out,$json,[Text.UTF8Encoding]::new($false));$json;if($blocked){exit 1}
