[CmdletBinding()]
param([Parameter(Mandatory=$true)][string]$KernelRequestPath,[string]$AiSolutionPath='',[string[]]$RoundPaths=@(),[string]$ModelResponsePath='', [string]$RevisionReceiptPath='')
$ErrorActionPreference='Stop';$OutputEncoding=[Console]::OutputEncoding=[Text.UTF8Encoding]::new($false)
$root=[IO.Path]::GetFullPath((Get-Location).Path).TrimEnd('\')+'\';$full=(Resolve-Path -LiteralPath $KernelRequestPath -ErrorAction Stop).Path;if(-not $full.StartsWith($root,[StringComparison]::OrdinalIgnoreCase)){throw 'KernelRequestPath must remain under project root.'}
Import-Module (Join-Path (Get-Location) 'ES/Automation/Contracts/ESJsonSchemaLite.psm1') -Force
$request=Get-Content -Raw -Encoding UTF8 $full|ConvertFrom-Json;$schema=Join-Path (Get-Location) 'ES/Automation/Contracts/es-web-page-studio-kernel-v1.schema.json';$errors=@(Test-ESJsonSchemaValue -SchemaPath $schema -Value $request);if($errors.Count){throw ('Kernel request schema failed: '+($errors -join '; '))}
$outputDir=[IO.Path]::GetFullPath((Join-Path $root ([string]$request.output.directory)));if(-not $outputDir.StartsWith($root,[StringComparison]::OrdinalIgnoreCase)){throw 'Kernel output must remain under project root.'};if(Test-Path -LiteralPath $outputDir){throw "Refusing to overwrite kernel output: $outputDir"};$outputParent=Split-Path -Parent $outputDir;if(-not(Test-Path -LiteralPath $outputParent)){New-Item -ItemType Directory -Path $outputParent -Force|Out-Null}
$safeReq=Join-Path $root "ES/Output/WebPageStudio/kernel-requests/compiled-$([guid]::NewGuid().ToString('N')).json";$new=Join-Path $root 'ES/Automation/WebPageStudio/New-ESWebPageStudioRequest.ps1';$static=Join-Path $root 'ES/Automation/WebPageStudio/Invoke-ESWebPageStudioStatic.ps1';$preflight=Join-Path $root 'ES/Automation/WebPageStudio/Invoke-ESWebPageStudioPreflight.ps1';$deepDesign=Join-Path $root 'ES/Automation/WebPageStudio/Invoke-ESWebPageStudioDeepDesign.ps1';$convert=Join-Path $root 'ES/Automation/WebPageStudio/Convert-ESWebPageStudioRequest.ps1'
& $new -Objective ([string]$request.page.title) -PageKind ([string]$request.page.pageKind) -PrimaryAction ([string]$request.page.primaryAction) -Language ([string]$request.page.language) -OutputPath $safeReq|Out-Null
$compiled=Get-Content -Raw -Encoding UTF8 $safeReq|ConvertFrom-Json;$compiled.output.outputDirectory=([string]$request.output.directory).TrimEnd('/','\');$compiled.publicBaseUrl='';$compiled.sitemap=[ordered]@{changefreq='weekly';priority=0.8;paths=@('./')};$compiled|ConvertTo-Json -Depth 12|Set-Content -LiteralPath $safeReq -Encoding UTF8
$preflightPath=Join-Path $root "ES/Output/WebPageStudio/kernel-requests/preflight-$([guid]::NewGuid().ToString('N')).json";$preflightArgs=@{RequestPath=$safeReq;OutputPath=$preflightPath};if(-not [string]::IsNullOrWhiteSpace($AiSolutionPath)){$preflightArgs.AiSolutionPath=$AiSolutionPath};if(@($RoundPaths).Count -eq 5){$preflightArgs.RoundPaths=$RoundPaths};$pf=& $preflight @preflightArgs|ConvertFrom-Json;if([string]$pf.status -ne 'accepted'){throw 'P0_PREFLIGHT_BLOCKED: kernel request preflight failed.'};$designPath=Join-Path $root "ES/Output/WebPageStudio/kernel-requests/deep-design-$([guid]::NewGuid().ToString('N')).json";$deepArgs=@{PreflightPath=$preflightPath;OutputPath=$designPath};if(-not [string]::IsNullOrWhiteSpace($ModelResponsePath)){$deepArgs.ModelResponsePath=$ModelResponsePath};$ds=& $deepDesign @deepArgs|ConvertFrom-Json;if([string]$ds.designStatus -ne 'accepted'){throw 'P0_DESIGN_NOT_ACCEPTED: kernel deep design failed.'};if([string]::IsNullOrWhiteSpace($RevisionReceiptPath)){throw 'BLOCKED_WEB_MATERIALIZATION_AI_REVISION_REQUIRED'};& $static -RequestPath $safeReq -DesignSpecPath $designPath -RevisionReceiptPath $RevisionReceiptPath|Out-Null
$entry=Join-Path $outputDir 'index.html';$files=@('index.html','icon.svg','site.webmanifest','robots.txt','sitemap.xml','design-tokens.json','kernel-page-request.json','route-manifest.json','component-graph.json')
[IO.File]::Copy($safeReq,(Join-Path $outputDir 'kernel-page-request.json'),$false)
[IO.File]::WriteAllText((Join-Path $outputDir 'route-manifest.json'),($request.routes|ConvertTo-Json -Depth 8),[Text.UTF8Encoding]::new($false));[IO.File]::WriteAllText((Join-Path $outputDir 'component-graph.json'),($request.components|ConvertTo-Json -Depth 8),[Text.UTF8Encoding]::new($false))
if([string]$request.renderMode -eq 'dynamic' -and -not (Test-Path -LiteralPath (Join-Path $outputDir 'runtime.mjs') -PathType Leaf)){throw 'BLOCKED_WEB_KERNEL_DYNAMIC_AI_RUNTIME_MISSING'}
$hashes=[ordered]@{};foreach($name in $files){$path=Join-Path $outputDir $name;if(Test-Path -LiteralPath $path -PathType Leaf){$hashes[$name]=(Get-FileHash -LiteralPath $path -Algorithm SHA256).Hash.ToLowerInvariant()}}
$manifest=[ordered]@{schemaVersion=1;recordType='ESWebPageStudioKernelArtifact';format='html-css-esm';renderMode=[string]$request.renderMode;requestPath=$full.Substring($root.Length).Replace('\','/');outputDirectory=$outputDir.Substring($root.Length).Replace('\','/');entryFile='index.html';files=@($files);contentHashes=$hashes;theme=[ordered]@{name=[string]$request.theme.name;dark=$request.theme.dark;light=$request.theme.light;behavior='system-preference-plus-user-override-in-dynamic-mode'};dynamic=[ordered]@{endpoint=[string]$request.data.endpoint;source=[string]$request.data.source;script=if([string]$request.renderMode -eq 'dynamic'){'runtime.mjs'}else{$null}};runtimeStatus='runtime-not-run';network='disabled';claimsNotProven=@('browser rendering','dynamic endpoint availability','JavaScript execution','visual regression','production deployment')}
[IO.File]::WriteAllText((Join-Path $outputDir 'kernel-manifest.json'),($manifest|ConvertTo-Json -Depth 15),[Text.UTF8Encoding]::new($false));$manifest|ConvertTo-Json -Depth 15
