[CmdletBinding()]
param([Parameter(Mandatory=$true)][string]$HtmlPath,[Parameter(Mandatory=$true)][string]$OutputPath)
$ErrorActionPreference='Stop';$root=[IO.Path]::GetFullPath((Get-Location).Path).TrimEnd('\')+'\';$html=(Resolve-Path $HtmlPath).Path;if(-not $html.StartsWith($root,[StringComparison]::OrdinalIgnoreCase)){throw 'HtmlPath must remain under project root.'}
$edge=@('C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe','C:\Program Files\Microsoft\Edge\Application\msedge.exe')|Where-Object{Test-Path $_}|Select-Object -First 1;if(-not $edge){throw 'Local Edge is required.'}
$run=Join-Path (Split-Path $html) ('.perf-'+[guid]::NewGuid().ToString('N').Substring(0,12));New-Item -ItemType Directory $run|Out-Null
# Instrument only a disposable preview copy. The canonical artifact remains
# script-free and is still checked by the preview security policy.
$instrumented=Join-Path $run 'instrumented.html';$source=Get-Content -LiteralPath $html -Raw -Encoding UTF8
$probe=@'
<script>(function(){var lcp=null,cls=0,inp=null;try{new PerformanceObserver(function(x){x.getEntries().forEach(function(e){if(e.entryType==='largest-contentful-paint')lcp=e.startTime;});}).observe({type:'largest-contentful-paint',buffered:true});new PerformanceObserver(function(x){x.getEntries().forEach(function(e){if(!e.hadRecentInput)cls+=e.value;});}).observe({type:'layout-shift',buffered:true});new PerformanceObserver(function(x){x.getEntries().forEach(function(e){if(e.name==='click'||e.name==='keydown'||e.name==='pointerdown')inp=Math.max(inp||0,e.duration);});}).observe({type:'event',buffered:true,durationThreshold:16});}catch(e){}addEventListener('load',function(){var rs=performance.getEntriesByType('resource'),b={jsBytes:0,fontBytes:0,imageBytes:0};rs.forEach(function(r){var n=(r.name||'').toLowerCase(),z=r.transferSize||r.encodedBodySize||0;if(/\.js(?:\?|$)/.test(n))b.jsBytes+=z;else if(/\.(woff2?|ttf|otf)(?:\?|$)/.test(n))b.fontBytes+=z;else if(/\.(png|jpe?g|gif|webp|svg)(?:\?|$)/.test(n))b.imageBytes+=z;});var out={lcpMs:lcp,inpMs:inp,cls:cls,resourceBytes:b};var m=document.createElement('meta');m.name='es-performance-probe';m.content=btoa(unescape(encodeURIComponent(JSON.stringify(out))));document.head.appendChild(m);});})();</script>
'@
$instrumentedHtml=$source.Replace("default-src 'none'; style-src 'unsafe-inline';", "default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline';").Replace('</head>',$probe+'</head>');[IO.File]::WriteAllText($instrumented,$instrumentedHtml,[Text.UTF8Encoding]::new($false))
$sw=[Diagnostics.Stopwatch]::StartNew();$shot=Join-Path $run 'probe.png';$dom=Join-Path $run 'probe-dom.html';$uri=([Uri]$instrumented).AbsoluteUri;$common="--headless=new --disable-gpu --disable-extensions --disable-background-networking --disable-component-update --disable-sync --disable-default-apps --no-first-run --user-data-dir=$run\profile --window-size=1440,900";$p=Start-Process $edge -ArgumentList "$common --screenshot=$shot --hide-scrollbars $uri" -PassThru -WindowStyle Hidden -Wait;$sw.Stop();$psi=[Diagnostics.ProcessStartInfo]::new();$psi.FileName=$edge;$psi.Arguments="$common --dump-dom $uri";$psi.UseShellExecute=$false;$psi.RedirectStandardOutput=$true;$psi.CreateNoWindow=$true;$q=[Diagnostics.Process]::new();$q.StartInfo=$psi;$q.Start()|Out-Null;$domText=$q.StandardOutput.ReadToEnd();$q.WaitForExit(30000);[IO.File]::WriteAllText($dom,$domText,[Text.UTF8Encoding]::new($false))
$metrics=[ordered]@{lcpMs=$null;inpMs=$null;cls=$null;p75=$null};$resource=[ordered]@{jsBytes=0;fontBytes=0;imageBytes=0};$m=[regex]::Match($domText,'name="es-performance-probe" content="([^"]+)"');if($m.Success){try{$decoded=[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String($m.Groups[1].Value));$j=$decoded|ConvertFrom-Json;$metrics.lcpMs=$j.lcpMs;$metrics.inpMs=$j.inpMs;$metrics.cls=$j.cls;$resource.jsBytes=$j.resourceBytes.jsBytes;$resource.fontBytes=$j.resourceBytes.fontBytes;$resource.imageBytes=$j.resourceBytes.imageBytes}catch{}}
$measured=($null -ne $metrics.lcpMs -and $null -ne $metrics.cls);$o=[ordered]@{schemaVersion=1;recordType='WebPageStudioPerformanceProbe';status=if($measured){'review'}else{'review'};runtimeStatus='runtime-passed';browser=[ordered]@{engine='chromium';executablePath=$edge;version=(Get-Item $edge).VersionInfo.ProductVersion};htmlBytes=(Get-Item $html).Length;probeWallClockMs=$sw.ElapsedMilliseconds;metrics=$metrics;resourceBytes=$resource;measurementMode='disposable-instrumented-file-preview';claimsNotProven=@('INP remains null when no qualifying real interaction is observed','p75 requires repeated population runs','probe does not replace Lighthouse or field data');screenshotHash=(Get-FileHash $shot -Algorithm SHA256).Hash.ToLowerInvariant()};$out=Join-Path $root $OutputPath;New-Item -ItemType Directory (Split-Path $out) -Force|Out-Null;[IO.File]::WriteAllText($out,($o|ConvertTo-Json -Depth 8),[Text.UTF8Encoding]::new($false));$o|ConvertTo-Json -Depth 8
