[CmdletBinding()]
param(
    [Parameter(Mandatory=$true)][string]$ArtifactDirectory,
    [string]$OutputDirectory = '',
    [switch]$EnableOfflineRuntime,
    [ValidateSet('prompt','autoUpdate')][string]$RegisterType='prompt'
)
$ErrorActionPreference='Stop';$OutputEncoding=[Console]::OutputEncoding=[Text.UTF8Encoding]::new($false)
$root=[IO.Path]::GetFullPath((Get-Location).Path).TrimEnd('\')+'\'
$source=(Resolve-Path -LiteralPath $ArtifactDirectory -ErrorAction Stop).Path
if(-not $source.StartsWith($root,[StringComparison]::OrdinalIgnoreCase)){throw 'ArtifactDirectory must remain under the project root.'}
$entry=Join-Path $source 'index.html';if(-not(Test-Path -LiteralPath $entry -PathType Leaf)){throw 'ArtifactDirectory must contain index.html.'}
if(-not $EnableOfflineRuntime){[pscustomobject]@{schemaVersion=1;recordType='WebPageStudioOfflinePackageReceipt';status='not-run';runtimeStatus='runtime-not-run';network='disabled';reason='EnableOfflineRuntime switch was not provided';claimsNotProven=@('offline cache behavior','service worker installation')}|ConvertTo-Json -Depth 8;exit 0}
if([string]::IsNullOrWhiteSpace($OutputDirectory)){$OutputDirectory=Join-Path (Split-Path -Parent $source) ((Split-Path -Leaf $source)+'-offline')}
$out=[IO.Path]::GetFullPath($OutputDirectory);if(-not $out.StartsWith($root,[StringComparison]::OrdinalIgnoreCase)){throw 'OutputDirectory must remain under the project root.'};if(Test-Path -LiteralPath $out){throw "Refusing to overwrite existing output: $out"};New-Item -ItemType Directory -Path $out -Force|Out-Null
Get-ChildItem -LiteralPath $source -File | Where-Object Name -in @('index.html','site.webmanifest','icon.svg','accessibility-receipt.json','quality-receipt.json') | Copy-Item -Destination $out -Force
$indexText=Get-Content -Raw -Encoding UTF8 (Join-Path $out 'index.html');$indexText=$indexText.Replace("default-src 'none'","default-src 'none'; script-src 'self'").Replace("script-src 'none'","script-src 'self'").Replace('</head>','<script src="sw-register.js" defer></script></head>');[IO.File]::WriteAllText((Join-Path $out 'index.html'),$indexText,[Text.UTF8Encoding]::new($false))
$version=((Get-FileHash -LiteralPath (Join-Path $out 'index.html') -Algorithm SHA256).Hash.Substring(0,12)+((Get-FileHash -LiteralPath (Join-Path $out 'site.webmanifest') -Algorithm SHA256).Hash.Substring(0,12))).ToLowerInvariant();$assetNames=@('./index.html','./site.webmanifest','./sw-register.js');foreach($optional in @('./icon.svg','./accessibility-receipt.json','./quality-receipt.json')){if(Test-Path -LiteralPath (Join-Path $out $optional.TrimStart('./')) -PathType Leaf){$assetNames+=$optional}};$assetsJson=$assetNames|ConvertTo-Json -Compress;$sw="const CACHE='es-webpagestudio-$version';const ASSETS=$assetsJson;self.addEventListener('install',event=>event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(ASSETS)).then(()=>self.skipWaiting())));self.addEventListener('activate',event=>event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(key=>key!==CACHE).map(key=>caches.delete(key)))).then(()=>self.clients.claim())));self.addEventListener('fetch',event=>{if(event.request.method!=='GET')return;event.respondWith(caches.match(event.request).then(cached=>cached||fetch(event.request).then(response=>{if(response.ok){const copy=response.clone();caches.open(CACHE).then(cache=>cache.put(event.request,copy));}return response}).catch(()=>caches.match('./index.html'))))});"
[IO.File]::WriteAllText((Join-Path $out 'sw.js'),$sw,[Text.UTF8Encoding]::new($false))
$updateCall=if($RegisterType -eq 'autoUpdate'){'.then(reg=>reg.update())'}else{''};$register="window.__esOfflineRegistration=Promise.resolve('unsupported');if('serviceWorker' in navigator){window.addEventListener('load',()=>{window.__esOfflineRegistration=navigator.serviceWorker.register('./sw.js',{scope:'./'})$updateCall.then(()=> 'registered').catch(()=> 'failed');});}"
[IO.File]::WriteAllText((Join-Path $out 'sw-register.js'),$register,[Text.UTF8Encoding]::new($false))
$files=@(Get-ChildItem -LiteralPath $out -File);$hashes=[ordered]@{};foreach($f in $files){$hashes[$f.Name]=(Get-FileHash -LiteralPath $f.FullName -Algorithm SHA256).Hash.ToLowerInvariant()}
$generated=[ordered]@{schemaVersion=1;recordType='WebPageStudioOfflinePackageReceipt';status='generated';runtimeStatus='runtime-not-run';network='disabled';sourceDirectory=$source.Replace($root,'').Replace('\','/');outputDirectory=$out.Replace($root,'').Replace('\','/');serviceWorker='sw.js';registerType=$RegisterType;cacheStrategy='cache-first-with-network-fill-and-index-fallback';secureContextRequired=$true;supportedContexts=@('https','http://localhost');files=$hashes;executionPolicy=[ordered]@{network='disabled';allowInstall=$false;allowShell=$false};claimsNotProven=@('browser service worker installation','offline cache behavior','production HTTPS scope') };[IO.File]::WriteAllText((Join-Path $out 'offline-package-receipt.json'),($generated|ConvertTo-Json -Depth 10),[Text.UTF8Encoding]::new($false));$generated|ConvertTo-Json -Depth 10
