[CmdletBinding()]
param(
 [Parameter(Mandatory=$true)][string]$Objective,
 [ValidateSet('marketing','dashboard')][string]$PageKind='marketing',
 [string]$PrimaryAction='Learn more', [string]$Audience='unspecified audience',
 [string]$BundleId='locale-bundle', [string]$PublicBaseUrl='', [ValidateSet('always','hourly','daily','weekly','monthly','yearly','never')][string]$SitemapChangeFreq='weekly', [ValidateRange(0.0,1.0)][double]$SitemapPriority=0.8, [string]$OutputPath=''
)
$ErrorActionPreference='Stop';$OutputEncoding=[Console]::OutputEncoding=[Text.UTF8Encoding]::new($false)
$root=[IO.Path]::GetFullPath((Get-Location).Path).TrimEnd('\')+'\'
$localeResource = Get-Content -Raw -Encoding UTF8 (Join-Path $root 'ES/Automation/WebPageStudio/locale-resources.json') | ConvertFrom-Json
if($BundleId -notmatch '^[a-z][a-z0-9._-]{1,63}$'){throw 'BundleId must be a lowercase stable identifier.'}
if($PublicBaseUrl -and (($PublicBaseUrl -notmatch '^https://[^\s/]+(?:/[^\s]*)?/?$') -or $PublicBaseUrl.Contains('?') -or $PublicBaseUrl.Contains('#'))){throw 'PublicBaseUrl must be an absolute HTTPS origin/path without query or fragment.'}
$PublicBaseUrl=$PublicBaseUrl.TrimEnd('/')
$bundleDir=Join-Path $root ("ES/Output/WebPageStudio/bundles/$BundleId");if(Test-Path $bundleDir){throw "Refusing to overwrite existing bundle: $bundleDir"};New-Item -ItemType Directory -Path $bundleDir -Force|Out-Null
$entries=[System.Collections.Generic.List[object]]::new();$newReq=Join-Path $root 'ES/Automation/WebPageStudio/New-ESWebPageStudioRequest.ps1';$static=Join-Path $root 'ES/Automation/WebPageStudio/Invoke-ESWebPageStudioStatic.ps1';$convert=Join-Path $root 'ES/Automation/WebPageStudio/Convert-ESWebPageStudioRequest.ps1';$localeTargets=@(@{code='en';href='../en/index.html'},@{code='zh-CN';href='../zh-cn/index.html'},@{code='ar';href='../ar/index.html'})
foreach($locale in @('en','zh-CN','ar')){
 $safe=($locale -replace '[^a-zA-Z0-9-]','-').ToLowerInvariant();$req=Join-Path $bundleDir "request-$safe.json";$label="$Objective [$locale]";
 & $newReq -Objective $label -PageKind $PageKind -PrimaryAction $PrimaryAction -Audience $Audience -Language $locale -OutputPath $req|Out-Null
 $r=Get-Content -Raw -Encoding UTF8 $req|ConvertFrom-Json;$r.output.outputDirectory="ES/Output/WebPageStudio/bundles/$BundleId/$safe";if($PublicBaseUrl){$r.publicBaseUrl="$PublicBaseUrl/$safe"};$r.sitemap.changefreq=$SitemapChangeFreq;$r.sitemap.priority=$SitemapPriority;$r|ConvertTo-Json -Depth 10|Set-Content -LiteralPath $req -Encoding UTF8
 & $static -RequestPath $req|Out-Null;$localeIndex=Join-Path (Join-Path $root $r.output.outputDirectory) 'index.html';$localeHtml=Get-Content -Raw -Encoding UTF8 $localeIndex;$hreflang=(($localeTargets|ForEach-Object{$targetHref=if($PublicBaseUrl){$PublicBaseUrl+'/'+($_.href -replace '^\.\./','')}else{$_.href};'<link rel="alternate" hreflang="'+$_.code+'" href="'+$targetHref+'">'}) -join '');[IO.File]::WriteAllText($localeIndex,$localeHtml.Replace('</head>',$hreflang+'</head>'),[Text.UTF8Encoding]::new($false));$contract=Join-Path (Join-Path $root $r.output.outputDirectory) 'web-page-contract.json';& $convert -RequestPath $req -OutputPath $contract|Out-Null
 $validationPath=Join-Path (Split-Path $contract) 'contract-validation.json';$v=& (Join-Path $root 'ES/Automation/WebPageStudio/Test-ESWebPageStudioContract.ps1') -ContractPath $contract|Out-String;[IO.File]::WriteAllText($validationPath,$v,[Text.UTF8Encoding]::new($false));$v=$v|ConvertFrom-Json
 $fallback = switch ($locale) { 'zh-CN' { @('zh-CN','en') } 'ar' { @('ar','en') } default { @('en') } }
 $entries.Add([ordered]@{locale=$locale;fallbackChain=$fallback;directory=$r.output.outputDirectory;contract=$contract.Substring($root.Length).Replace('\','/');status=$v.status;passedCount=$v.passedCount;failedCount=$v.failedCount})
}
$indexHtml=@'
<!doctype html>
<html lang="en" dir="ltr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="Localized WebPageStudio pages"><meta name="color-scheme" content="dark light"><meta name="theme-color" content="#101516"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; manifest-src 'self'; base-uri 'none'; frame-ancestors 'none'"><link rel="manifest" href="site.webmanifest"><title>Choose language</title><style>body{font:16px system-ui;max-width:720px;margin:12vh auto;padding:24px;background:#101516;color:#f4f7f5}a{display:block;padding:16px;margin:12px 0;background:#d1f36a;color:#172021;text-decoration:none;font-weight:700}a:focus-visible{outline:3px solid #75e1d1;outline-offset:3px}</style></head><body><main><h1>Choose language</h1><p>Select a localized static page.</p><nav aria-label="Languages"><a href="en/index.html">LOCALE_EN</a><a href="zh-cn/index.html" lang="zh-CN">LOCALE_ZH</a><a href="ar/index.html" lang="ar" dir="rtl">LOCALE_AR</a></nav></main></body></html>
'@
$indexHtml = $indexHtml.Replace('LOCALE_EN',[string]$localeResource.locales.en.name).Replace('LOCALE_ZH',[string]$localeResource.locales.'zh-CN'.name).Replace('LOCALE_AR',[string]$localeResource.locales.ar.name).Replace('</style>', '.skip{position:absolute;left:12px;top:8px;transform:translateY(-150%)}.skip:focus{transform:translateY(0)}a:focus-visible{outline:3px solid #75e1d1;outline-offset:3px}@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto!important}}@media(forced-colors:active){a:focus-visible{outline:2px solid CanvasText}}</style>').Replace('<main><h1>', '<a class="skip-link" href="#main-content">Skip to content</a><main id="main-content"><h1>')
$indexHtml = $indexHtml.Replace('</head>', '<link rel="alternate" hreflang="en" href="en/index.html"><link rel="alternate" hreflang="zh-CN" href="zh-cn/index.html"><link rel="alternate" hreflang="ar" href="ar/index.html"><link rel="alternate" hreflang="x-default" href="en/index.html"></head>')
if($PublicBaseUrl){$indexHtml=$indexHtml.Replace('href="en/index.html"','href="'+$PublicBaseUrl+'/en/"').Replace('href="zh-cn/index.html"','href="'+$PublicBaseUrl+'/zh-cn/"').Replace('href="ar/index.html"','href="'+$PublicBaseUrl+'/ar/"')}
[IO.File]::WriteAllText((Join-Path $bundleDir 'index.html'),$indexHtml,[Text.UTF8Encoding]::new($false))
$indexIconPath=Join-Path $bundleDir 'icon.svg';[IO.File]::WriteAllText($indexIconPath,'<svg xmlns="http://www.w3.org/2000/svg" width="512" height="512" viewBox="0 0 512 512"><rect width="512" height="512" rx="96" fill="#101516"/><path d="M112 128h288v64H176v64h176v64H176v64h224v64H112z" fill="#d1f36a"/></svg>',[Text.UTF8Encoding]::new($false));$indexIconHash=(Get-FileHash -LiteralPath $indexIconPath -Algorithm SHA256).Hash.ToLowerInvariant();$indexManifestPath=Join-Path $bundleDir 'site.webmanifest';[ordered]@{id='./';name='ES WebPageStudio Locale Bundle';short_name='ES Locales';start_url='./';scope='./';display='standalone';lang='en';dir='ltr';theme_color='#101516';background_color='#101516';icons=@([ordered]@{src='./icon.svg';sizes='192x192 512x512';type='image/svg+xml';purpose='any maskable'});description='Localized WebPageStudio language entrypoint'}|ConvertTo-Json -Depth 5|Set-Content -LiteralPath $indexManifestPath -Encoding utf8;$indexManifestHash=(Get-FileHash -LiteralPath $indexManifestPath -Algorithm SHA256).Hash.ToLowerInvariant()
$indexPath=Join-Path $bundleDir 'index.html';$indexHash=(Get-FileHash -LiteralPath $indexPath -Algorithm SHA256).Hash.ToLowerInvariant()
$indexReceiptPath=Join-Path $bundleDir 'index-accessibility-receipt.json';$indexReceiptJson=(& (Join-Path $root 'ES/Automation/WebPageStudio/Test-ESWebPageStudioAccessibility.ps1') -HtmlPath $indexPath|Out-String).Trim();[IO.File]::WriteAllText($indexReceiptPath,$indexReceiptJson,[Text.UTF8Encoding]::new($false));$indexReceipt=$indexReceiptJson|ConvertFrom-Json;$indexReceiptHash=(Get-FileHash -LiteralPath $indexReceiptPath -Algorithm SHA256).Hash.ToLowerInvariant()
$indexQualityPath=Join-Path $bundleDir 'index-quality-receipt.json';$indexQualityJson=(& (Join-Path $root 'ES/Automation/WebPageStudio/Test-ESWebPageStudioQuality.ps1') -HtmlPath $indexPath -SkipStateCoverage|Out-String).Trim();[IO.File]::WriteAllText($indexQualityPath,$indexQualityJson,[Text.UTF8Encoding]::new($false));$indexQuality=$indexQualityJson|ConvertFrom-Json;$indexQualityHash=(Get-FileHash -LiteralPath $indexQualityPath -Algorithm SHA256).Hash.ToLowerInvariant()
$localeResourcePath='ES/Automation/WebPageStudio/locale-resources.json';$localeResourceHash=(Get-FileHash -LiteralPath (Join-Path $root $localeResourcePath) -Algorithm SHA256).Hash.ToLowerInvariant()
$manifest=[ordered]@{schemaVersion=1;recordType='ESWebPageStudioLocaleBundle';bundleId=$BundleId;entrypoint='index.html';entryHash=$indexHash;indexManifest=[ordered]@{path='site.webmanifest';sha256=$indexManifestHash;iconPath='icon.svg';iconSha256=$indexIconHash};localeResource=[ordered]@{path=$localeResourcePath;sha256=$localeResourceHash};indexEvidence=[ordered]@{receipt='index-accessibility-receipt.json';receiptHash=$indexReceiptHash;status=$indexReceipt.status;passedCount=$indexReceipt.passedCount;failedCount=$indexReceipt.failedCount};indexQualityEvidence=[ordered]@{receipt='index-quality-receipt.json';receiptHash=$indexQualityHash;profile=$indexQuality.profile;status=$indexQuality.status;passedCount=$indexQuality.passedCount;failedCount=$indexQuality.failedCount};locales=@('en','zh-CN','ar');entries=@($entries);network='disabled';runtimeStatus='runtime-not-run';nonClaims=@('Locale bundle provides independent static artifacts; it does not prove translation quality or runtime locale negotiation.')}
if([string]::IsNullOrWhiteSpace($OutputPath)){$OutputPath=Join-Path $bundleDir 'manifest.json'}$out=[IO.Path]::GetFullPath($OutputPath);if(-not $out.StartsWith($root,[StringComparison]::OrdinalIgnoreCase)){throw 'OutputPath must remain under project root.'}
[IO.File]::WriteAllText($out,($manifest|ConvertTo-Json -Depth 10),[Text.UTF8Encoding]::new($false))
$sitemapItems=[System.Collections.Generic.List[string]]::new();foreach($localeTarget in $localeTargets){$localeUrl=if($PublicBaseUrl){$PublicBaseUrl+'/'+($localeTarget.href -replace '^\.\./','' -replace '/index\.html$','/')}else{$localeTarget.href};$alternateLinks=(($localeTargets|ForEach-Object{$alt=if($PublicBaseUrl){$PublicBaseUrl+'/'+($_.href -replace '^\.\./','' -replace '/index\.html$','/')}else{$_.href};'<xhtml:link rel="alternate" hreflang="'+$_.code+'" href="'+$alt+'" />'}) -join '');$sitemapItems.Add('<url><loc>'+ $localeUrl +'</loc><changefreq>'+ $SitemapChangeFreq +'</changefreq><priority>'+ $SitemapPriority.ToString('0.0',[Globalization.CultureInfo]::InvariantCulture) +'</priority>'+ $alternateLinks +'</url>')};$sitemapXml='<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">'+($sitemapItems -join '')+'</urlset>';[IO.File]::WriteAllText((Join-Path $bundleDir 'sitemap.xml'),$sitemapXml,[Text.UTF8Encoding]::new($false));$manifest.siteDiscovery=[ordered]@{sitemap='sitemap.xml';sha256=(Get-FileHash -LiteralPath (Join-Path $bundleDir 'sitemap.xml') -Algorithm SHA256).Hash.ToLowerInvariant();hreflang='xhtml:link';changefreq=$SitemapChangeFreq;priority=$SitemapPriority}
$resolutionPath=Join-Path $bundleDir 'locale-resolution-receipt.json';$resolutionJson=(& (Join-Path $root 'ES/Automation/WebPageStudio/Test-ESWebPageStudioLocaleResolution.ps1') -ManifestPath $out|Out-String).Trim();[IO.File]::WriteAllText($resolutionPath,$resolutionJson,[Text.UTF8Encoding]::new($false));$resolution=$resolutionJson|ConvertFrom-Json;$manifest.localeResolutionEvidence=[ordered]@{receipt='locale-resolution-receipt.json';receiptHash=(Get-FileHash -LiteralPath $resolutionPath -Algorithm SHA256).Hash.ToLowerInvariant();status=$resolution.status;passedCount=$resolution.passedCount;failedCount=$resolution.failedCount};[IO.File]::WriteAllText($out,($manifest|ConvertTo-Json -Depth 10),[Text.UTF8Encoding]::new($false));$manifest|ConvertTo-Json -Depth 10
$freshnessPath=Join-Path $bundleDir 'freshness-receipt.json';$freshnessJson=(& (Join-Path $root 'ES/Automation/WebPageStudio/Test-ESWebPageStudioLocaleBundleFreshness.ps1') -ManifestPath $out|Out-String).Trim();[IO.File]::WriteAllText($freshnessPath,$freshnessJson,[Text.UTF8Encoding]::new($false));$freshness=$freshnessJson|ConvertFrom-Json;$manifest.freshnessEvidence=[ordered]@{receipt='freshness-receipt.json';receiptHash=(Get-FileHash -LiteralPath $freshnessPath -Algorithm SHA256).Hash.ToLowerInvariant();status=$freshness.status;targetCount=$freshness.targetCount;passedCount=$freshness.passedCount;failedCount=$freshness.failedCount;sourceHashes=$freshness.sourceHashes};[IO.File]::WriteAllText($out,($manifest|ConvertTo-Json -Depth 10),[Text.UTF8Encoding]::new($false));$manifest|ConvertTo-Json -Depth 10
