[CmdletBinding()]
param([Parameter(Mandatory=$true)][string]$ManifestPath)
$ErrorActionPreference='Stop';$OutputEncoding=[Console]::OutputEncoding=[Text.UTF8Encoding]::new($false);$root=[IO.Path]::GetFullPath((Get-Location).Path).TrimEnd('\')+'\';$manifestFull=(Resolve-Path -LiteralPath $ManifestPath -ErrorAction Stop).Path;if(-not $manifestFull.StartsWith($root,[StringComparison]::OrdinalIgnoreCase)){throw 'ManifestPath must remain under project root.'}
$m=Get-Content -Raw -Encoding UTF8 $manifestFull|ConvertFrom-Json;$dir=[IO.Path]::GetFullPath((Join-Path $root ([string]$m.outputDirectory)));$checks=[System.Collections.Generic.List[object]]::new();function Add([string]$id,[bool]$ok,[string]$detail){$checks.Add([pscustomobject]@{check=$id;status=if($ok){'passed'}else{'failed'};detail=$detail})}
Add 'format' ([string]$m.format -eq 'html-css-esm') 'single canonical HTML/CSS/ESM artifact format is declared';Add 'render-mode' ([string]$m.renderMode -in @('static','dynamic')) 'render mode is static or dynamic';Add 'root-boundary' ($dir.StartsWith($root,[StringComparison]::OrdinalIgnoreCase)) 'artifact directory stays under project root'
$entry=Join-Path $dir 'index.html';$html=if(Test-Path $entry){Get-Content -Raw -Encoding UTF8 $entry}else{''};Add 'entry' (Test-Path $entry -PathType Leaf) 'index.html exists';Add 'theme-behavior' (($html -match '(?is)--ink:') -and ($html -match '(?is)prefers-color-scheme:\s*light') -and ($html -match '(?is)forced-colors:\s*active')) 'theme tokens, light preference, and forced-colors behavior are present';Add 'responsive' ($html -match '(?is)@media\s*\(max-width:760px\)') 'mobile responsive breakpoint is present'
$dynamic=[string]$m.renderMode -eq 'dynamic';$runtime=Join-Path $dir 'runtime.mjs';$scriptDeclared=$html -match '(?is)<script\b[^>]*type=["'']module["''][^>]*src=["'']runtime\.mjs["'']';Add 'dynamic-script-policy' ((-not $dynamic -and -not $scriptDeclared) -or ($dynamic -and $scriptDeclared -and (Test-Path $runtime -PathType Leaf) -and $html -match '(?is)script-src\s*''self''')) 'dynamic mode uses one same-origin ESM module and self-only script CSP';Add 'static-no-script' ($dynamic -or -not ($html -match '(?is)<script\b')) 'static mode contains no executable script'
$hashOk=$true;foreach($p in $m.contentHashes.PSObject.Properties){$fp=Join-Path $dir $p.Name;if(-not(Test-Path $fp -PathType Leaf)-or (Get-FileHash $fp -Algorithm SHA256).Hash.ToLowerInvariant() -ne [string]$p.Value){$hashOk=$false}};Add 'hashes' $hashOk 'all manifest file hashes match current artifacts';Add 'runtime-boundary' ([string]$m.runtimeStatus -eq 'runtime-not-run' -and [string]$m.network -eq 'disabled') 'manifest does not claim runtime execution or network access'
$routePath=Join-Path $dir 'route-manifest.json';$componentPath=Join-Path $dir 'component-graph.json';$routesOk=$false;$componentsOk=$false;try{$routes=@(Get-Content -Raw -Encoding UTF8 $routePath|ConvertFrom-Json);$components=@(Get-Content -Raw -Encoding UTF8 $componentPath|ConvertFrom-Json);$ids=@($components|% id);$children=@($components|% children|%{[string]$_});$routesOk=$routes.Count -gt 0 -and (@($routes|? {([string]$_.path) -notmatch '^/' -or [string]$_.entry -ne 'index.html'}).Count -eq 0);$componentsOk=$components.Count -gt 0 -and (@($children|? {$_ -and $ids -notcontains $_}).Count -eq 0) -and (@($ids|group|? Count -gt 1).Count -eq 0)}catch{};Add 'route-graph-closure' $routesOk 'route manifest has rooted paths and bounded entry files';Add 'component-graph-closure' $componentsOk 'component graph child references are closed and IDs are unique'
$passed=@($checks|? status -eq 'passed').Count;$failed=$checks.Count-$passed;[pscustomobject]@{schemaVersion=1;recordType='ESWebPageStudioKernelValidation';status=if($failed -eq 0){'passed'}else{'failed'};format=$m.format;renderMode=$m.renderMode;checkCount=$checks.Count;passedCount=$passed;failedCount=$failed;checks=@($checks);runtimeStatus='runtime-not-run';network='disabled'}|ConvertTo-Json -Depth 10
if($failed){exit 1}
