[CmdletBinding()]param([string]$ProjectRoot=(Resolve-Path (Join-Path $PSScriptRoot '..\..\..')).Path)
$ErrorActionPreference='Stop';Import-Module (Join-Path $ProjectRoot 'ES/Automation/ABCD/ESABCDOrchestrator.psm1') -Force
$zero='0'*64;$one='1'*64;$two='2'*64;$store=New-ESABCDOrchestrationStore -TaskId 'web-ui-abcd-test' -TaskBindingId 'web-ui-binding' -TaskBindingHash $two -AuthorizationRef 'user.authorization' -RoutePlanHash $zero -SourceScopeHash $one
$get=@{ExpectedTaskRevision=$store.taskRevision;ExpectedContextVersion=$store.contextVersion};Start-ESABCDIterationRound $store @get|Out-Null;$get=@{ExpectedTaskRevision=$store.taskRevision;ExpectedContextVersion=$store.contextVersion};Add-ESABCDCandidate $store 'web-ui-branch' $null $zero 'ui-closure' 'four-layer-receipts' @get|Out-Null
$get=@{ExpectedTaskRevision=$store.taskRevision;ExpectedContextVersion=$store.contextVersion};Add-ESABCDAuditRecord -Store $store -BranchId 'web-ui-branch' -AuditorRef 'independent.auditor' -Verdict 'pass' -EvidenceRefs @('web-ui/static-evidence') -VerifierRef 'static.verifier' -AuthorizationProof 'user.authorization' -VerifierDefinitionHash $one @get|Out-Null
$get=@{ExpectedTaskRevision=$store.taskRevision;ExpectedContextVersion=$store.contextVersion};Select-ESABCDDecision -Store $store -BranchId 'web-ui-branch' -Decision 'retry' -ClaimLevel 'claim-cap' @get|Out-Null;$get=@{ExpectedTaskRevision=$store.taskRevision;ExpectedContextVersion=$store.contextVersion};Start-ESABCDCorrectionCycle -Store $store -CycleId 'web-ui-cycle' -FindingReceiptRef 'web-ui/aggregate' -FailureClass 'evidence' -Decision 'retry' -ClaimLevel 'claim-cap' -AttemptNo 1 @get|Out-Null
$get=@{ExpectedTaskRevision=$store.taskRevision;ExpectedContextVersion=$store.contextVersion};$first=Add-ESABCDVerificationReceipt -Store $store -CycleId 'web-ui-cycle' -VerificationStatus 'review' @get;$second=Add-ESABCDVerificationReceipt -Store $store -CycleId 'web-ui-cycle' -VerificationStatus 'review' @get
if($first.status -ne 'appended' -or $second.status -ne 'replayed'){throw 'ABCD_VERIFICATION_REPLAY_FAILED'};$event=@($store.events|Where-Object {[string]$_.eventType -eq 'verification-recorded'})|Select-Object -Last 1;if(-not $event){throw 'ABCD_VERIFICATION_EVENT_MISSING'}
[ordered]@{validator='web-ui-abcd-verification-projection';status='passed';eventType=[string]$event.eventType;verificationStatus=[string]$event.payload.verificationStatus;firstStatus=[string]$first.status;replayStatus=[string]$second.status;runtimeStatus='runtime-not-run';nonClaims=@('in-memory-static-replay','no-worker-dispatch','no-runtime-or-release-claim')}|ConvertTo-Json -Depth 10
