[CmdletBinding()]param([Parameter(Mandatory=$true)][string]$ReceiptPath,[string]$MatrixPath='')
$ErrorActionPreference='Stop';$issues=[Collections.Generic.List[string]]::new();$r=Get-Content -Raw -Encoding UTF8 -LiteralPath $ReceiptPath|ConvertFrom-Json
if($r.schemaVersion -ne 1){$issues.Add('SCHEMA_VERSION')};if($r.recordType -ne 'WebPageStudioVisualRegressionReceipt'){$issues.Add('RECORD_TYPE')};foreach($n in 'receiptId','status','matrix','baselines','comparisons','humanReview','runtimeStatus','nonClaims'){if($null -eq $r.PSObject.Properties[$n]){$issues.Add("MISSING_$n")}}
if(@($r.matrix.profiles).Count -lt 2 -or @($r.matrix.themes).Count -lt 2){$issues.Add('MATRIX_TOO_SMALL')};if($r.matrix.themes -notcontains 'light' -or $r.matrix.themes -notcontains 'dark'){$issues.Add('THEME_PAIR_REQUIRED')};foreach($b in @($r.baselines)){foreach($h in @($b.environmentHash,$b.artifactHash,$b.screenshotHash,$b.domHash,$b.ariaHash)){if([string]$h -notmatch '^[a-f0-9]{64}$'){$issues.Add('BASELINE_HASH_INVALID')}};if([string]$b.screenshotPath -notmatch '^[^?#]+\.png$'){$issues.Add('BASELINE_SCREENSHOT_PATH_INVALID')};if([string]$b.domPath -notmatch '^[^?#]+\.(html|json)$'){$issues.Add('BASELINE_DOM_PATH_INVALID')};if([string]$b.ariaPath -notmatch '^[^?#]+\.(yaml|yml|json)$'){$issues.Add('BASELINE_ARIA_PATH_INVALID')};if($r.matrix.profiles -notcontains [string]$b.profileId){$issues.Add('BASELINE_PROFILE_UNKNOWN')};if($r.matrix.themes -notcontains [string]$b.theme){$issues.Add('BASELINE_THEME_UNKNOWN')};if($r.matrix.states -notcontains [string]$b.state){$issues.Add('BASELINE_STATE_UNKNOWN')};$stem=[IO.Path]::GetFileNameWithoutExtension([string]$b.screenshotPath).ToLowerInvariant();foreach($part in @([string]$b.profileId,[string]$b.theme,[string]$b.state)){if(-not $stem.Contains($part.ToLowerInvariant())){$issues.Add('BASELINE_PATH_ID_MISMATCH')}}};foreach($c in @($r.comparisons)){if([int]$c.diffPixels -gt [int]$c.maxDiffPixels -and $c.status -eq 'passed'){$issues.Add('DIFF_THRESHOLD_LIE')}};if($r.humanReview.status -eq 'passed' -and [string]::IsNullOrWhiteSpace([string]$r.humanReview.reviewerId)){$issues.Add('REVIEWER_REQUIRED')}
if($r.status -eq 'passed' -and $r.humanReview.status -ne 'passed'){$issues.Add('HUMAN_REVIEW_REQUIRED')};if($r.status -eq 'passed' -and @($r.comparisons | Where-Object {$_.status -eq 'passed'}).Count -lt 1){$issues.Add('PIXEL_COMPARISON_REQUIRED')};if($r.status -eq 'passed' -and $r.matrix.themes -notcontains 'forced-colors'){$issues.Add('FORCED_COLORS_REQUIRED')};if($r.status -eq 'passed'){foreach($state in @('default','loading','empty','error','success')){if($r.matrix.states -notcontains $state){$issues.Add("STATE_MISSING_$($state.ToUpperInvariant())")}}}
if($MatrixPath -and $r.matrix.PSObject.Properties['matrixHash']){$actual=(Get-FileHash -LiteralPath $MatrixPath -Algorithm SHA256).Hash.ToLowerInvariant();if([string]$r.matrix.matrixHash -cne $actual){$issues.Add('MATRIX_HASH_DRIFT')}}
if($MatrixPath -and $r.status -eq 'passed'){$pairs=@(Get-Content -LiteralPath $MatrixPath -Encoding UTF8 | ForEach-Object {if($_ -match '^\s*-\s*\[\s*([^,\]]+)\s*,\s*([^\]]+)\s*\]'){("{0}|{1}" -f $matches[1].Trim(),$matches[2].Trim()).ToLowerInvariant()}});$covered=@($r.baselines | ForEach-Object {("{0}|{1}" -f [string]$_.profileId,[string]$_.theme).ToLowerInvariant()});foreach($pair in $pairs){if($covered -notcontains $pair){$issues.Add("REQUIRED_PAIR_MISSING_$($pair.Replace('|','_'))")}}}
if($r.status -eq 'passed'){foreach($baseline in @($r.baselines)){if(@($r.comparisons | Where-Object {[string]$_.baselineId -eq [string]$baseline.baselineId -and [string]$_.status -eq 'passed'}).Count -lt 1){$issues.Add("BASELINE_COMPARISON_MISSING_$([string]$baseline.baselineId)")}}}
$o=[ordered]@{validator='visual-regression-receipt';status=if($issues.Count){'blocked'}else{'passed'};findingCount=$issues.Count;findings=@($issues);runtimeStatus=[string]$r.runtimeStatus;nonClaims=@('pixel-match-does-not-prove-usability','human-review-is-independent')};$o|ConvertTo-Json -Depth 8;if($issues.Count){exit 1}
