[CmdletBinding()]
param([Parameter(Mandatory=$true)][string]$PackageDirectory)
$ErrorActionPreference='Stop';$OutputEncoding=[Console]::OutputEncoding=[Text.UTF8Encoding]::new($false)
$root=[IO.Path]::GetFullPath((Get-Location).Path).TrimEnd('\')+'\';$dir=(Resolve-Path -LiteralPath $PackageDirectory -ErrorAction Stop).Path
if(-not $dir.StartsWith($root,[StringComparison]::OrdinalIgnoreCase)){throw 'PackageDirectory must remain under the project root.'}
$checks=[System.Collections.Generic.List[object]]::new();function Add([string]$id,[bool]$ok,[string]$detail){$checks.Add([pscustomobject]@{check=$id;status=if($ok){'passed'}else{'failed'};detail=$detail})}
$required=@('index.html','site.webmanifest','sw.js','sw-register.js');foreach($name in $required){Add "file-$name" (Test-Path -LiteralPath (Join-Path $dir $name) -PathType Leaf) "$name exists"}
$index=Get-Content -Raw -Encoding UTF8 (Join-Path $dir 'index.html');$register=Get-Content -Raw -Encoding UTF8 (Join-Path $dir 'sw-register.js');Add 'service-worker-registration' ($index -match 'sw-register\.js' -and $register -match 'navigator\.serviceWorker\.register') 'entrypoint registers the local service worker';Add 'registration-observability' ($register -match '__esOfflineRegistration' -and $register -match "'registered'" -and $register -match "'failed'") 'registration exposes explicit registered and failed states';Add 'registration-network-boundary' (-not($register -match 'https?://|//[A-Za-z]')) 'registration script contains no external URL'
Add 'csp-registration' ($index -match "script-src 'self'") 'offline entrypoint CSP permits only the local registration script'
Add 'csp-hardening' ($index -match "default-src 'none'" -and $index -notmatch "script-src[^;]*(?:https?://|\*)") 'CSP keeps default deny and has no wildcard or external script source'
Add 'secure-context-declaration' ($true) 'Service Worker deployment requires HTTPS or localhost'
$sw=Get-Content -Raw -Encoding UTF8 (Join-Path $dir 'sw.js');Add 'service-worker-lifecycle' ($sw -match 'addEventListener\(["'']install["'']' -and $sw -match 'addEventListener\(["'']activate["'']' -and $sw -match 'addEventListener\(["'']fetch["'']') 'install, activate, and fetch handlers are present';Add 'cache-fallback' ($sw -match 'caches\.match\(["'']\./index\.html["'']\)') 'offline fallback targets the local entrypoint';Add 'cache-cleanup' ($sw -match 'caches\.keys\(\).*caches\.delete') 'activate handler removes stale cache versions';Add 'cache-versioning' ($sw -match "CACHE='es-webpagestudio-[a-f0-9]{24}'") 'cache name is content-versioned';Add 'network-boundary' (-not($sw -match 'https?://|//[A-Za-z]')) 'service worker contains no external URL';$manifest=Get-Content -Raw -Encoding UTF8 (Join-Path $dir 'site.webmanifest')|ConvertFrom-Json;Add 'manifest-shape' ([string]$manifest.id -eq './' -and [string]$manifest.scope -eq './' -and [string]$manifest.display -eq 'standalone' -and [string]$manifest.start_url -eq './' -and -not [string]::IsNullOrWhiteSpace([string]$manifest.lang) -and [string]$manifest.dir -in @('ltr','rtl')) 'manifest has stable local identity, display, start URL, language, and direction';$expectedVersion=((Get-FileHash -LiteralPath (Join-Path $dir 'index.html') -Algorithm SHA256).Hash.Substring(0,12)+((Get-FileHash -LiteralPath (Join-Path $dir 'site.webmanifest') -Algorithm SHA256).Hash.Substring(0,12))).ToLowerInvariant();Add 'cache-version-binding' ($sw -match "CACHE='es-webpagestudio-$expectedVersion'") 'cache key matches current HTML and Manifest hashes'
$assetMatches=[regex]::Matches($sw,'["''](\./[^"'']+)["'']');$assetPaths=@($assetMatches|ForEach-Object{$_.Groups[1].Value}|Select-Object -Unique);Add 'precache-assets' (($assetPaths.Count -gt 0) -and (@($assetPaths|Where-Object{Test-Path -LiteralPath (Join-Path $dir $_) -PathType Leaf}).Count -eq $assetPaths.Count)) 'all precache assets resolve to local files'
$registerAndWorker="$register`n$sw";Add 'dynamic-code-policy' (-not($registerAndWorker -match '(?is)\beval\s*\(|new\s+Function\s*\(|importScripts\s*\(')) 'offline scripts do not use dynamic code evaluation or imports'
$receiptPath=Join-Path $dir 'offline-package-receipt.json';if(Test-Path -LiteralPath $receiptPath){try{$prior=Get-Content -Raw -Encoding UTF8 $receiptPath|ConvertFrom-Json;foreach($p in $prior.files.PSObject.Properties){$fp=Join-Path $dir $p.Name;$actual=if(Test-Path -LiteralPath $fp -PathType Leaf){(Get-FileHash -LiteralPath $fp -Algorithm SHA256).Hash.ToLowerInvariant()}else{''};Add "hash-$($p.Name)" ($actual -eq [string]$p.Value) "recorded SHA-256 matches $($p.Name)"} }catch{Add 'receipt-parse' $false 'existing offline receipt is not valid JSON'}}
$observedHashes=[ordered]@{};Get-ChildItem -LiteralPath $dir -File|Where-Object Name -ne 'offline-package-receipt.json'|ForEach-Object{$observedHashes[$_.Name]=(Get-FileHash -LiteralPath $_.FullName -Algorithm SHA256).Hash.ToLowerInvariant()};$registerType=if($register -match '\.update\(\)'){'autoUpdate'}else{'prompt'};$receipt=[ordered]@{schemaVersion=1;recordType='WebPageStudioOfflinePackageValidationReceipt';status='pending';packageDirectory=$dir;checks=$checks;registerType=$registerType;secureContextRequired=$true;supportedContexts=@('https','http://localhost');files=$observedHashes;evidenceLevel='S1';runtimeStatus='runtime-not-run';network='disabled';claimsNotProven=@('browser service worker installation','offline cache behavior','production HTTPS scope')};$passed=@($checks|Where-Object status -eq 'passed').Count;$receipt.status=if($passed -eq $checks.Count){'passed'}else{'failed'};$receipt.checkCount=$checks.Count;$receipt.passedCount=$passed;$receipt.failedCount=$checks.Count-$passed;[IO.File]::WriteAllText($receiptPath,($receipt|ConvertTo-Json -Depth 10),[Text.UTF8Encoding]::new($false));$receipt|ConvertTo-Json -Depth 10
