[CmdletBinding()]
param(
    [Parameter(Mandatory=$true)][string]$HtmlPath,
    [switch]$SkipStateCoverage
)
$ErrorActionPreference='Stop';$OutputEncoding=[Console]::OutputEncoding=[Text.UTF8Encoding]::new($false)
$root=[IO.Path]::GetFullPath((Get-Location).Path).TrimEnd('\')+'\';$full=(Resolve-Path -LiteralPath $HtmlPath -ErrorAction Stop).Path
if(-not $full.StartsWith($root,[StringComparison]::OrdinalIgnoreCase)){throw 'HtmlPath must remain under the project root.'}
$h=Get-Content -LiteralPath $full -Encoding UTF8 -Raw;$checks=[System.Collections.Generic.List[object]]::new()
function Add([string]$id,[bool]$ok,[string]$detail){$checks.Add([pscustomobject]@{check=$id;status=if($ok){'passed'}else{'failed'};detail=$detail})}
Add 'doctype' ($h -match '(?is)^\s*<!doctype\s+html>') 'HTML5 doctype is present'
Add 'viewport' ($h -match '(?is)<meta\b[^>]*name=["'']viewport["'']') 'responsive viewport metadata is present'
Add 'description' ($h -match '(?is)<meta\b[^>]*name=["'']description["''][^>]*content=["''][^"'']{20,}["'']') 'description metadata is non-trivial'
Add 'favicon-and-touch-icon' (($h -match '(?is)<link\b[^>]*rel=["'']icon["''][^>]*href=["''](?:icon\.svg|https://[^"'']+/icon\.svg)["'']') -and ($h -match '(?is)<link\b[^>]*rel=["'']apple-touch-icon["''][^>]*href=["''](?:icon\.svg|https://[^"'']+/icon\.svg)["'']')) 'same-origin favicon and Apple touch icon are declared'
Add 'canonical' ($h -match '(?is)<link\b[^>]*rel=["'']canonical["''][^>]*href=["''][^"'']+["'']') 'same-origin canonical link is present'
Add 'social-card' (($h -match '(?is)<meta\b[^>]*property=["'']og:url["'']') -and ($h -match '(?is)<meta\b[^>]*property=["'']og:image["''][^>]*content=["''](?:\./icon\.svg|https://[^"'']+/icon\.svg)["'']') -and ($h -match '(?is)<meta\b[^>]*name=["'']twitter:card["'']') -and ($h -match '(?is)<meta\b[^>]*name=["'']twitter:title["'']') -and ($h -match '(?is)<meta\b[^>]*name=["'']twitter:image["''][^>]*content=["''](?:\./icon\.svg|https://[^"'']+/icon\.svg)["'']')) 'Open Graph and Twitter Card metadata use the local preview icon'
Add 'theme-metadata' ($h -match '(?is)<meta\b[^>]*name=["'']theme-color["'']' -and $h -match '(?is)<meta\b[^>]*name=["'']color-scheme["'']') 'theme metadata is present'
Add 'structured-data-microdata' (($h -match '(?is)<main\b[^>]*itemscope[^>]*itemtype=["'']https://schema\.org/WebPage["'']') -and ($h -match '(?is)<h1\b[^>]*itemprop=["'']name["'']') -and ($h -match '(?is)\bitemprop=["'']description["'']')) 'schema.org WebPage Microdata describes the visible page without executable scripts'
Add 'inline-critical-css' ($h -match '(?is)<style\b') 'critical CSS is self-contained'
$metadataFreeHtml = [regex]::Replace($h, '(?is)<(?:meta|link)\b[^>]*(?:canonical|alternate|og:url|og:image|twitter:image)[^>]*>', '')
Add 'no-blocking-external' (-not ($metadataFreeHtml -match '(?is)<(?:link|script|img|iframe)\b[^>]*(?:https?:|//)')) 'no external blocking resources are declared'
Add 'resource-policy' ($h -notmatch '(?is)@import\s+url\s*\(') 'CSS does not import remote resources'
$securityOk = ($h -match '(?is)<meta\b[^>]*http-equiv=["'']Content-Security-Policy["'']') -and ($h -match '(?is)<link\b[^>]*rel=["'']manifest["''][^>]*href=["'']site\.webmanifest["'']')
Add 'security-metadata' $securityOk 'CSP and same-origin Web App Manifest link are present'
$robotsPath=Join-Path (Split-Path -Parent $full) 'robots.txt';$sitemapPath=Join-Path (Split-Path -Parent $full) 'sitemap.xml';$discoveryOk=$true;$discoveryDetail='Site discovery files are optional for an isolated page artifact';if((Test-Path -LiteralPath $robotsPath -PathType Leaf) -or (Test-Path -LiteralPath $sitemapPath -PathType Leaf)){try{$robotsOk=(Test-Path -LiteralPath $robotsPath -PathType Leaf) -and ((Get-Content -Raw -Encoding UTF8 $robotsPath) -match '(?im)^User-agent:\s*\*') -and ((Get-Content -Raw -Encoding UTF8 $robotsPath) -match '(?im)^Allow:\s*/');$xml=[xml](Get-Content -Raw -Encoding UTF8 $sitemapPath);$discoveryOk=$robotsOk -and ($xml.urlset.url.loc.Count -ge 1);$discoveryDetail='robots.txt and sitemap.xml are present with a valid local URL entry'}catch{$discoveryOk=$false;$discoveryDetail='robots.txt or sitemap.xml is malformed'}}
Add 'site-discovery' $discoveryOk $discoveryDetail
$targetOk=$true;$targetDetail='Sitemap target files are not applicable to an isolated page artifact';if(Test-Path -LiteralPath $sitemapPath -PathType Leaf){try{$xmlTargets=[xml](Get-Content -Raw -Encoding UTF8 $sitemapPath);$artifactRoot=Split-Path -Parent $full;foreach($locNode in @($xmlTargets.urlset.url.loc)){ $loc=[string]$locNode; if($loc -notmatch '^https?://'){ $relative=$loc.TrimStart('./');$target=Join-Path $artifactRoot $relative;if(Test-Path -LiteralPath $target -PathType Container){$target=Join-Path $target 'index.html'}if(-not(Test-Path -LiteralPath $target -PathType Leaf)){$targetOk=$false}}};$targetDetail=if($targetOk){'All relative Sitemap URLs resolve to local files or directory index.html entries'}else{'One or more relative Sitemap URLs do not resolve to local output files'}}catch{$targetOk=$false;$targetDetail='Sitemap targets could not be parsed'}}
Add 'sitemap-targets' $targetOk $targetDetail
$manifestPath=Join-Path (Split-Path -Parent $full) 'site.webmanifest';$manifestOk=$true;$manifestDetail='No local Manifest file is present';if(Test-Path -LiteralPath $manifestPath -PathType Leaf){try{$m=Get-Content -Raw -Encoding UTF8 $manifestPath|ConvertFrom-Json;$iconOk=$true;foreach($icon in @($m.icons)){$iconPath=Join-Path (Split-Path -Parent $full) ([string]$icon.src).TrimStart('./');$sizes=[string]$icon.sizes;if([string]$icon.src -match '^(?:[A-Za-z]:|/|\\|https?://)' -or -not(Test-Path -LiteralPath $iconPath -PathType Leaf) -or ($sizes -notmatch '192x192' -or $sizes -notmatch '512x512')){$iconOk=$false}else{if([string]$icon.type -eq 'image/svg+xml' -and (Get-Content -Raw -Encoding UTF8 $iconPath) -notmatch '(?is)<svg\b[^>]*viewBox='){$iconOk=$false}}};$colorOk=([string]$m.theme_color -match '^#[0-9a-fA-F]{6}$' -and [string]$m.background_color -match '^#[0-9a-fA-F]{6}$');$manifestOk=([string]$m.display -eq 'standalone' -and [string]$m.start_url -eq './' -and [string]$m.theme_color -ieq '#101516' -and [string]$m.background_color -ieq '#101516' -and $iconOk -and $colorOk);$manifestDetail=if($manifestOk){'Manifest JSON, colors, and declared local icons with 192/512 sizes are valid'}else{'Manifest identity, colors, icon path, sizes, or SVG structure is invalid'}}catch{$manifestOk=$false;$manifestDetail='Manifest JSON is invalid'}}
Add 'manifest-integrity' $manifestOk $manifestDetail
$stateOk = $SkipStateCoverage -or (([regex]::Matches($h, '(?is)class=["'']state-card(?:\s|["''])').Count -ge 3) -and $h -match '(?is)<[^>]+role=["'']alert["'']')
$stateDetail = if($SkipStateCoverage){'entrypoint profile: business state coverage is intentionally not required'}else{'loading, empty, and error states are represented'}
Add 'state-coverage' $stateOk $stateDetail
$bytes=[IO.File]::ReadAllBytes($full);Add 'payload-budget' ($bytes.Length -le 200000) ("HTML payload is {0} bytes (budget 200000)." -f $bytes.Length)
$passed=@($checks|Where-Object status -eq 'passed').Count;$failed=$checks.Count-$passed
[pscustomobject]@{schemaVersion=1;recordType='WebPageStudioQualityReceipt';profile=if($SkipStateCoverage){'entrypoint'}else{'content-page'};status=if($failed -eq 0){'passed'}else{'failed'};htmlPath=$full;checkCount=$checks.Count;passedCount=$passed;failedCount=$failed;evidenceLevel='S1';runtimeStatus='runtime-not-run';checks=$checks;claimsNotProven=@('Static quality checks do not produce Lighthouse scores or real Core Web Vitals.')}|ConvertTo-Json -Depth 8
