[CmdletBinding()]
param([Parameter(Mandatory=$true)][string]$ContractPath)
$ErrorActionPreference='Stop';$OutputEncoding=[Console]::OutputEncoding=[Text.UTF8Encoding]::new($false)
$root=[IO.Path]::GetFullPath((Get-Location).Path).TrimEnd('\')+'\';$contractFull=(Resolve-Path -LiteralPath $ContractPath -ErrorAction Stop).Path;if(-not $contractFull.StartsWith($root,[StringComparison]::OrdinalIgnoreCase)){throw 'ContractPath must remain under project root.'}
$contract=Get-Content -Raw -Encoding UTF8 $contractFull|ConvertFrom-Json;$checks=[System.Collections.Generic.List[object]]::new();function Add([string]$id,[bool]$ok,[string]$detail){$checks.Add([pscustomobject]@{check=$id;status=if($ok){'passed'}else{'failed'};detail=$detail})}
$artifactRoot=[IO.Path]::GetFullPath((Join-Path $root ([string]$contract.webArtifact.rootDirectory)));$hashOk=$true;foreach($p in $contract.webArtifact.files){$f=Join-Path $artifactRoot ([string]$p);$expected=[string]$contract.webArtifact.contentHashes.([string]$p);if(-not(Test-Path -LiteralPath $f -PathType Leaf)){$hashOk=$false;continue};$actual=(Get-FileHash -LiteralPath $f -Algorithm SHA256).Hash.ToLowerInvariant();if($actual -ne $expected){$hashOk=$false}}
Add 'artifact-hashes' $hashOk 'all contract-listed files exist and match recorded SHA-256 hashes'
$requestName='request-'+(Split-Path $artifactRoot -Leaf)+'.json';$requestPath=Join-Path (Split-Path $artifactRoot -Parent) $requestName;if(Test-Path -LiteralPath $requestPath -PathType Leaf){$requestObject=Get-Content -Raw -Encoding UTF8 $requestPath|ConvertFrom-Json;$requestCanonical=$requestObject|ConvertTo-Json -Depth 20 -Compress;$sha=[Security.Cryptography.SHA256]::Create();try{$requestHash=([BitConverter]::ToString($sha.ComputeHash([Text.UTF8Encoding]::new($false).GetBytes($requestCanonical))).Replace('-','')).ToLowerInvariant()}finally{$sha.Dispose()};Add 'request-hash-closure' ($requestHash -eq [string]$contract.identity.inputHash) 'sibling request snapshot hash binds to contract identity.inputHash'}
$entry=Join-Path $artifactRoot ([string]$contract.artifactPlan.entryFile);$quality=& (Join-Path $root 'ES/Automation/WebPageStudio/Test-ESWebPageStudioQuality.ps1') -HtmlPath $entry|ConvertFrom-Json;$access=& (Join-Path $root 'ES/Automation/WebPageStudio/Test-ESWebPageStudioAccessibility.ps1') -HtmlPath $entry|ConvertFrom-Json
Add 'current-quality' ([string]$quality.status -eq 'passed') ("current quality scan: {0} ({1}/{2})" -f $quality.status,$quality.passedCount,$quality.checkCount)
Add 'current-accessibility' ([string]$access.status -eq 'passed') ("current accessibility scan: {0} ({1}/{2})" -f $access.status,$access.passedCount,$access.checkCount)
$passed=@($checks|? status -eq 'passed').Count;$failed=$checks.Count-$passed;$sourceHashes=[ordered]@{};foreach($source in @('Invoke-ESWebPageStudioStatic.ps1','Convert-ESWebPageStudioRequest.ps1','Test-ESWebPageStudioQuality.ps1','Test-ESWebPageStudioAccessibility.ps1')){$sourcePath=Join-Path $root ('ES/Automation/WebPageStudio/'+$source);$sourceHashes[$source]=(Get-FileHash -LiteralPath $sourcePath -Algorithm SHA256).Hash.ToLowerInvariant()};[pscustomobject]@{schemaVersion=1;recordType='WebPageStudioFreshnessReceipt';status=if($failed -eq 0){'passed'}else{'stale'};contractPath=$contractFull;artifactRoot=$artifactRoot;checkCount=$checks.Count;passedCount=$passed;failedCount=$failed;evidenceLevel='S1';runtimeStatus='runtime-not-run';checks=$checks;sourceHashes=$sourceHashes;claimsNotProven=@('Freshness validation does not prove browser, backend, Unity, or production runtime behavior.') }|ConvertTo-Json -Depth 8
