[CmdletBinding()]
param([Parameter(Mandatory=$true)][string]$RequestPath,[Parameter(Mandatory=$true)][string]$HtmlPath,[string]$DesignSpecPath='')
$ErrorActionPreference='Stop';$root=[IO.Path]::GetFullPath((Get-Location).Path).TrimEnd('\')+'\'
function Resolve-RootPath([string]$p){$f=if([IO.Path]::IsPathRooted($p)){[IO.Path]::GetFullPath($p)}else{[IO.Path]::GetFullPath((Join-Path (Get-Location) $p))};if(-not $f.StartsWith($root,[StringComparison]::OrdinalIgnoreCase)){throw 'Path must remain under project root.'};$f}
$req=Resolve-RootPath $RequestPath;$htmlFile=Resolve-RootPath $HtmlPath;$r=Get-Content -Raw -Encoding UTF8 $req|ConvertFrom-Json;$h=Get-Content -Raw -Encoding UTF8 $htmlFile;$design=$null;if(-not [string]::IsNullOrWhiteSpace($DesignSpecPath)){$designFile=Resolve-RootPath $DesignSpecPath;$design=Get-Content -Raw -Encoding UTF8 $designFile|ConvertFrom-Json}
$checks=[Collections.Generic.List[object]]::new();function C($id,$ok,$detail){$checks.Add([pscustomobject]@{check=$id;status=if($ok){'passed'}else{'blocked'};detail=$detail})}
$isGithub=[string]$r.objective -match '(?i)github|repository dashboard';$required=@('repository','branch','latest commit','file tree','README','issues','pull requests','commits')
if($isGithub){foreach($term in $required){C ('github-semantic-'+($term -replace '\s+','-')) ($h -match [regex]::Escape($term)) "semantic content '$term'"};$githubRegions=@('code-panel','issues-panel','pulls-panel','activity-panel','insights-panel');foreach($id in $githubRegions){C ('github-region-'+$id) ($h -match ('(?is)<(?:section|div|article)\b[^>]*\bid=["'']'+$id+'["'']')) "DOM region id '$id' exists"};$navTargets=@([regex]::Matches($h,'(?is)<a\b[^>]*href=["''](#[^"'']+)["'']')|%{$_.Groups[1].Value.TrimStart('#')});$ids=@([regex]::Matches($h,'(?is)\bid=["'']([^"'']+)["'']')|%{$_.Groups[1].Value});C 'github-route-targets' ((@('code-panel','issues-panel','pulls-panel','activity-panel','insights-panel')|?{$navTargets -contains $_}).Count -eq 5 -and (@('code-panel','issues-panel','pulls-panel','activity-panel','insights-panel')|?{$ids -contains $_}).Count -eq 5) 'all GitHub navigation anchors resolve to designed region ids';$interactive=@([regex]::Matches($h,'(?is)<(?:button|input|select|textarea)\b'));C 'github-interaction-surface' ($interactive.Count -ge 1) 'at least one interactive control exists'}else{C 'intent-present' (-not [string]::IsNullOrWhiteSpace([string]$r.objective)) 'objective is present'}
if($design){C 'design-accepted' ([string]$design.designStatus -eq 'accepted' -and [string]$design.decisionStatus -eq 'accepted') 'accepted deep design is supplied';foreach($cap in @($design.capabilities)){ $rid=[regex]::Escape([string]$cap.region);$cid=[regex]::Escape([string]$cap.id);C ('design-region-'+[string]$cap.id) ($h -match ('(?is)id=["'']'+$rid+'["'']') -and $h -match ('(?is)data-capability-id=["'']'+$cid+'["'']')) 'design capability region and stable capability id are rendered' };C 'design-status-marker' ($h -match 'data-design-status=["'']accepted["'']') 'artifact declares accepted design status'}else{C 'design-input-present' $false 'DesignSpecPath is required for plan-to-artifact consistency audit'}
if($design){$profileOk=($null -ne $design.frameworkCapabilities -and @($design.frameworkCapabilities.frameworks).Count -ge 6);C 'framework-capability-profile' $profileOk 'six-framework capability profile is present';C 'framework-capability-binding' (($h -match 'data-capability-profile=') -and ($h -match 'data-render-policy=') -and ($h -match 'data-component-boundary=') -and ($h -match 'data-state-machine=')) 'framework capabilities are bound to HTML metadata'}
C 'no-executable-script' ($h -notmatch '(?is)<script\b') 'static artifact contains no executable script'
$passed=@($checks|? status -eq 'passed').Count;$blocked=$checks.Count-$passed;[ordered]@{schemaVersion=1;recordType='WebPageStudioIntentAuditReceipt';status=if($blocked){'blocked'}else{'passed'};profile='static-intent-structural';requestPath=$req;htmlPath=$htmlFile;checkCount=$checks.Count;passedCount=$passed;blockedCount=$blocked;checks=@($checks);runtimeStatus='runtime-not-run';nonClaims=@('semantic audit does not prove browser usability','does not prove backend or release')}|ConvertTo-Json -Depth 8;if($blocked){exit 1}
