[CmdletBinding()]
param([Parameter(Mandatory=$true)][string]$ManifestPath,[string]$OfflinePackageDirectory='')
$ErrorActionPreference='Stop';$OutputEncoding=[Console]::OutputEncoding=[Text.UTF8Encoding]::new($false)
$root=[IO.Path]::GetFullPath((Get-Location).Path).TrimEnd('\')+'\';$full=(Resolve-Path -LiteralPath $ManifestPath -ErrorAction Stop).Path;if(-not $full.StartsWith($root,[StringComparison]::OrdinalIgnoreCase)){throw 'ManifestPath must remain under project root.'}
$manifest=Get-Content -Raw -Encoding UTF8 $full|ConvertFrom-Json;$fresh=Join-Path $root 'ES/Automation/WebPageStudio/Test-ESWebPageStudioFreshness.ps1';$results=[System.Collections.Generic.List[object]]::new();$sourceHashes=$null
$rootContract=Join-Path (Split-Path -Parent $full) 'index-contract.json';if(Test-Path -LiteralPath $rootContract -PathType Leaf){$r=& $fresh -ContractPath $rootContract|ConvertFrom-Json;$results.Add([pscustomobject]@{target='root';status=$r.status;passedCount=$r.passedCount;failedCount=$r.failedCount})}
foreach($entry in @($manifest.entries)){$contract=Join-Path $root ([string]$entry.contract);if(-not(Test-Path -LiteralPath $contract -PathType Leaf)){ $results.Add([pscustomobject]@{target=[string]$entry.locale;status='stale';passedCount=0;failedCount=1});continue };$r=& $fresh -ContractPath $contract|ConvertFrom-Json;if($null -eq $sourceHashes){$sourceHashes=$r.sourceHashes};$results.Add([pscustomobject]@{target=[string]$entry.locale;status=$r.status;passedCount=$r.passedCount;failedCount=$r.failedCount})}
$offlineValidator=Join-Path $root 'ES/Automation/WebPageStudio/Test-ESWebPageStudioOfflinePackage.ps1';if($OfflinePackageDirectory){$offlineFull=if([IO.Path]::IsPathRooted($OfflinePackageDirectory)){[IO.Path]::GetFullPath($OfflinePackageDirectory)}else{[IO.Path]::GetFullPath((Join-Path $root $OfflinePackageDirectory))};if(-not $offlineFull.StartsWith($root,[StringComparison]::OrdinalIgnoreCase)){throw 'OfflinePackageDirectory must remain under project root.'};$o=& $offlineValidator -PackageDirectory $offlineFull|ConvertFrom-Json;$results.Add([pscustomobject]@{target='offline-package';status=$o.status;passedCount=$o.passedCount;failedCount=$o.failedCount})}
$failed=@($results|? status -ne 'passed').Count;$passed=@($results|? status -eq 'passed').Count;[pscustomobject]@{schemaVersion=1;recordType='WebPageStudioLocaleBundleFreshnessReceipt';status=if($failed -eq 0 -and $results.Count -gt 0){'passed'}else{'stale'};manifestPath=$full;targetCount=$results.Count;passedCount=$passed;failedCount=$failed;targets=$results;sourceHashes=$sourceHashes;evidenceLevel='S1';runtimeStatus='runtime-not-run';claimsNotProven=@('Batch freshness validation does not prove browser, backend, Unity, or production runtime behavior.') }|ConvertTo-Json -Depth 8
