[CmdletBinding()]
param([string]$ProjectRoot=(Resolve-Path (Join-Path $PSScriptRoot '..\..\..\..')).Path)
$ErrorActionPreference='Stop';$root=(Resolve-Path -LiteralPath $ProjectRoot).Path;Import-Module (Join-Path $PSScriptRoot 'ESAbcPartToolchain.psm1') -Force
$part=Read-ESAbcJson (Resolve-ESAbcProjectPath -ProjectRoot $root -RelativePath 'ES/Automation/Contracts/es-ai-abc-weapon-part.v1.json' -MustExist);$core=Get-ESAbcCoreContract -ProjectRoot $root;$route=Get-ESAbcRouteStageRegistry -ProjectRoot $root;$mode=Get-ESAbcModeRegistry -ProjectRoot $root;$authority=Get-ESAbcPartAuthorityRegistry -ProjectRoot $root;$results=[Collections.Generic.List[object]]::new();function Case([string]$n,[scriptblock]$b){try{&$b;[void]$results.Add([pscustomobject]@{case=$n;status='passed';finding=$null})}catch{[void]$results.Add([pscustomobject]@{case=$n;status='failed';finding=$_.Exception.Message})}}
Case 'canonical-part-passes'{$r=Test-ESAbcPartContractObject -Part $part -Core $core -RouteRegistry $route -ModeRegistry $mode -AuthorityRegistry $authority;if($r.status -ne 'passed'){throw($r.issues -join ';')}}
Case 'unknown-intent-is-rejected'{$x=$part|ConvertTo-Json -Depth 30|ConvertFrom-Json;$x.aProfile.intentKinds=@($x.aProfile.intentKinds)+'weapon.cheat.unlock';$x.aToBMappings=@($x.aToBMappings)+[pscustomobject]@{intentId='weapon.cheat.unlock';bCapability='bounded-tool-action';input='admin';output='unrestricted'};$r=Test-ESAbcPartContractObject -Part $x -Core $core -RouteRegistry $route -ModeRegistry $mode -AuthorityRegistry $authority;if($r.status -ne 'blocked' -or @($r.checks|Where-Object{$_.id -eq 'authority-intent-allowlist' -and $_.status -eq 'passed'}).Count -ne 0){throw'unknown intent bypassed authority registry'}}
Case 'unknown-provider-is-rejected'{$x=$part|ConvertTo-Json -Depth 30|ConvertFrom-Json;$x.bProfile.providers=@($x.bProfile.providers)+'untrusted-admin-provider';$r=Test-ESAbcPartContractObject -Part $x -Core $core -RouteRegistry $route -ModeRegistry $mode -AuthorityRegistry $authority;if($r.status -ne 'blocked' -or @($r.checks|Where-Object{$_.id -eq 'authority-provider-allowlist' -and $_.status -eq 'passed'}).Count -ne 0){throw'unknown provider bypassed authority registry'}}
Case 'mapping-capability-tamper-is-rejected'{$x=$part|ConvertTo-Json -Depth 30|ConvertFrom-Json;$x.aToBMappings[0].bCapability='branch-evaluation';$r=Test-ESAbcPartContractObject -Part $x -Core $core -RouteRegistry $route -ModeRegistry $mode -AuthorityRegistry $authority;if($r.status -ne 'blocked' -or @($r.checks|Where-Object{$_.id -eq 'authority-mapping-allowlist' -and $_.status -eq 'passed'}).Count -ne 0){throw'mapping tamper bypassed authority registry'}}
Case 'core-binding-selects-part'{$r=Resolve-ESAbcExecutionMode -Part $part -CoreBindingPresent $true;if($r.status -ne 'selected' -or $r.mode -ne 'ABCP.Part' -or $r.eventType -ne 'mode-selected'){throw'Core-bound Part was not selected deterministically'}}
Case 'missing-core-denies-silent-fallback'{$r=Resolve-ESAbcExecutionMode -Part $part -CoreBindingPresent $false;if($r.status -ne 'blocked' -or $r.reason -ne 'ABC_CORE_BINDING_REQUIRED' -or $r.eventType -ne 'fallback-denied'){throw'Silent fallback was not denied'}}
Case 'explicit-fallback-selects-dynamic'{$r=Resolve-ESAbcExecutionMode -Part $part -CoreBindingPresent $false -FallbackRequested $true -FallbackAuthorizationRef 'auth-123';if($r.status -ne 'selected' -or $r.mode -ne 'ABCD.Dynamic' -or $r.eventType -ne 'fallback-selected' -or $r.explicit -ne $true){throw'Explicit fallback did not select Dynamic mode'}}
Case 'fallback-without-authorization-denied'{$r=Resolve-ESAbcExecutionMode -Part $part -CoreBindingPresent $false -FallbackRequested $true;if($r.status -ne 'blocked' -or $r.reason -ne 'EXPLICIT_FALLBACK_AUTH_REQUIRED'){throw'Fallback without authorization was accepted'}}
$failed=@($results|Where-Object{$_.status-eq'failed'});$passed=@($results|Where-Object{$_.status-eq'passed'});[ordered]@{schemaVersion=1;validator='Test-ESAbcPartAuthorityBoundary';status=if($failed.Count){'failed'}else{'passed'};caseCount=$results.Count;passedCount=$passed.Count;failedCount=$failed.Count;cases=@($results);staticStatus=if($failed.Count){'static-failed'}else{'static-passed'};runtimeStatus='runtime-not-run';claimsNotProven=@('Unity/Runtime behavior','external provider execution','release acceptance')}|ConvertTo-Json -Depth 20;if($failed.Count){exit 1}
