[CmdletBinding()]
param([Parameter(Mandatory)][string]$EngineeringResultPath,[Parameter(Mandatory)][string]$CandidateEnvelopePath,[Parameter(Mandatory)][ValidateSet('DesignChange','RuntimeChange','DataMigration','ExternalSourceAdoption','PerformanceCritical','ReleaseCandidate')][string]$Scenario,[Parameter(Mandatory)][ValidatePattern('^[a-f0-9]{40}$')][string]$CurrentHead,[Parameter(Mandatory)][string]$AuthorizationRef,[Parameter(Mandatory)][string[]]$AllowedWriteScopes,[string]$ProjectRoot=(Resolve-Path (Join-Path $PSScriptRoot '..\..\..')).Path)
$ErrorActionPreference='Stop';$root=(Resolve-Path -LiteralPath $ProjectRoot).Path;Import-Module (Join-Path $root 'ES/Automation/ABCD/ESABCDPatchPlanning.psm1') -Force
$engineering=Get-Content -Raw -Encoding UTF8 -LiteralPath ([IO.Path]::GetFullPath($EngineeringResultPath))|ConvertFrom-Json;$envelope=Get-Content -Raw -Encoding UTF8 -LiteralPath ([IO.Path]::GetFullPath($CandidateEnvelopePath))|ConvertFrom-Json
if([string]$engineering.status -ne 'completed' -or $engineering.completionEligible -ne $true){throw 'ENGINEERING_RESULT_NOT_ELIGIBLE_FOR_PATCH_PLAN'};$e=$engineering.evidenceSummary;if($null -eq $e -or [int]$e.independentReplayVerifiedCount -ne [int]$e.eligibleCount -or [string]$e.providerScoreComparisonStatus -cne 'stable'){throw 'ENGINEERING_COMPLETION_EVIDENCE_NOT_VERIFIED'}
if([string]$envelope.status -ne 'candidate'){throw 'ENGINEERING_CANDIDATE_ENVELOPE_REQUIRED'};if([string]$engineering.winnerId -notin @($envelope.candidates|ForEach-Object {[string]$_.candidateId})){throw 'ENGINEERING_WINNER_NOT_IN_CANDIDATE_ENVELOPE'}
$candidate=@($envelope.candidates|Where-Object {[string]$_.candidateId -eq [string]$engineering.winnerId}|Select-Object -First 1);if(@($candidate[0].proposedChanges).Count -eq 0){throw 'ENGINEERING_WINNER_PROPOSED_CHANGES_REQUIRED'}
$files=@($candidate[0].proposedChanges|ForEach-Object {[string]$_.path});$plan=New-ESABCDCandidatePatchPlan -CandidateEnvelope $envelope -Scenario $Scenario -CurrentHead $CurrentHead -AuthorizationRef $AuthorizationRef -SourceFiles $files -AllowedWriteScopes $AllowedWriteScopes
[pscustomobject][ordered]@{status='candidate-only';engineeringWinnerId=[string]$engineering.winnerId;engineeringContractHash=[string]$engineering.contractHash;patchPlan=$plan;nonClaims=@('no-Apply','no-Git','no-Unity-runtime','no-release')}
