[CmdletBinding()]
param([string]$OutputPath='ES/Output/WebPageStudio/bootstrap/abcd-github-web-execution-receipt.json',[string]$TaskPath='ES/Output/WebPageStudio/bootstrap/round-03-task-context-github.json',[string]$RoutePath='ES/Output/WebPageStudio/bootstrap/round-04-knowledge-route-github.json',[string]$BindingPath='ES/Output/WebPageStudio/bootstrap/round-05-design-packet-github.json',[string]$ArtifactPath='ES/Output/WebPageStudio/artifacts/github-atlas/index.html',[string]$ModelResponsePath,[ValidateSet('deep-creative-engineering','creative-divergence','engineering','stable')][string]$GenerationProfile='deep-creative-engineering',[string]$Round01Path='ES/Output/WebPageStudio/bootstrap/round-01-intake-github.json',[string]$Round02Path='ES/Output/WebPageStudio/bootstrap/round-02-focus-github.json',[string]$Round03Path='ES/Output/WebPageStudio/bootstrap/round-03-task-context-github.json',[string]$Round04Path='ES/Output/WebPageStudio/bootstrap/round-04-knowledge-route-github.json',[string]$Round05Path='ES/Output/WebPageStudio/bootstrap/round-05-design-packet-github.json',[string]$AiDesignTaskOutputPath='ES/Output/WebPageStudio/bootstrap/ai-web-design-task-github.json')
$ErrorActionPreference='Stop';$root=(Resolve-Path (Join-Path $PSScriptRoot '..\..\..')).Path
Import-Module (Join-Path $root 'ES/Automation/ABCD/ESABCDOrchestrator.psm1') -Force
$task=Get-Content (Join-Path $root $TaskPath) -Raw -Encoding UTF8|ConvertFrom-Json
$route=Get-Content (Join-Path $root $RoutePath) -Raw -Encoding UTF8|ConvertFrom-Json
$binding=Get-Content (Join-Path $root $BindingPath) -Raw -Encoding UTF8|ConvertFrom-Json
$routePlan=Get-Content (Join-Path $root 'ES/Output/WebPageStudio/bootstrap/route-plan-github.json') -Raw -Encoding UTF8|ConvertFrom-Json
$bindingHash=(Get-FileHash (Join-Path $root $BindingPath) -Algorithm SHA256).Hash.ToLowerInvariant()
$upstream=@();$roundPaths=@($Round01Path,$Round02Path,$Round03Path,$Round04Path,$Round05Path);for($ri=0;$ri -lt $roundPaths.Count;$ri++){$rp=Join-Path $root $roundPaths[$ri];if(-not(Test-Path -LiteralPath $rp -PathType Leaf)){throw "BLOCKED_GITHUB_ABCD_UPSTREAM_ROUND_MISSING:$($roundPaths[$ri])"};$upstream+=[ordered]@{round=$ri+1;path=$roundPaths[$ri].Replace('\','/');hash=(Get-FileHash $rp -Algorithm SHA256).Hash.ToLowerInvariant();role=@('requirement-intake','focus-context','task-context','knowledge-route','capability-design')[$ri]}}
$sourceHash=[string]$task.sourceScopeHash;if($sourceHash -notmatch '^[a-f0-9]{64}$'){throw 'source-scope-hash-missing'}
$round1Doc=Get-Content (Join-Path $root $Round01Path) -Raw -Encoding UTF8|ConvertFrom-Json;$round2Doc=Get-Content (Join-Path $root $Round02Path) -Raw -Encoding UTF8|ConvertFrom-Json
$taskIntent=[string]$binding.taskIntent;if([string]::IsNullOrWhiteSpace($taskIntent)){$taskIntent=[string]$task.taskIntent};if([string]::IsNullOrWhiteSpace($taskIntent)){$taskIntent='GitHub 核心体验静态协作工作台'}
$selectedSeed=@($binding.divergenceCandidates|Where-Object{[string]$_.decision -ceq 'selected'}|Select-Object -First 1);$aiTask=[ordered]@{schemaVersion=1;recordType='AiWebDesignTask';taskId=[string]$task.taskId;requirementSnapshot=[ordered]@{taskIntent=$taskIntent;rawPrompt=[string]$round1Doc.rawPrompt;focus=[string]$round2Doc.focus;goalRevisionHash=[string]$task.goalRevisionHash;sourceScopeHash=$sourceHash};upstreamRounds=$upstream;round05DesignPacket=[ordered]@{path=$Round05Path.Replace('\','/');hash=($upstream|Where-Object round -eq 5).hash};abcdDecision=[ordered]@{invocationId='pending-model-response';selectedCandidateId=if($selectedSeed){[string]$selectedSeed.id}else{'unselected'};decision='revise';source='round-05-capability-design'};allowedWriteRoots=@('ES/Output/WebPageStudio/artifacts');requiredReads=@($upstream|ForEach-Object{$_.path})+@('ES/AISpace/README.md','ES/AISpace/Public/WebPageStudio/20260829/README.md');requiredChecks=@('build','interaction-replay','responsive-replay','a11y','utf8');maxIterations=5;stopConditions=@('no-unresolved-critical-findings','all-required-checks-pass','user-directed-stop')};$aiTaskFull=Join-Path $root $AiDesignTaskOutputPath;$aiTaskDir=Split-Path -Parent $aiTaskFull;if(-not(Test-Path $aiTaskDir)){New-Item -ItemType Directory $aiTaskDir -Force|Out-Null};[IO.File]::WriteAllText($aiTaskFull,($aiTask|ConvertTo-Json -Depth 30),[Text.UTF8Encoding]::new($false))
if([string]::IsNullOrWhiteSpace($ModelResponsePath)){throw 'BLOCKED_GITHUB_ABCD_MODEL_RESPONSE_REQUIRED'}
$modelResponseFull=Join-Path $root $ModelResponsePath;if(-not(Test-Path -LiteralPath $modelResponseFull -PathType Leaf)){throw "BLOCKED_GITHUB_ABCD_MODEL_RESPONSE_MISSING:$ModelResponsePath"}
$modelDoc=Get-Content -Raw -Encoding UTF8 $modelResponseFull|ConvertFrom-Json
if([string]$modelDoc.recordType -cne 'AiWebDesignModelResponse'){
  $normalizer=Join-Path $root '.agents/skills/es-web-generation-round-05-capability-design/scripts/Convert-ESAbcCandidateToWebModelResponse.ps1'
  $normalizedPath='ES/Output/WebPageStudio/bootstrap/normalized-web-model-response.json'
  & $normalizer -CandidatePath $ModelResponsePath -OutputPath $normalizedPath | Out-Null
  $ModelResponsePath=$normalizedPath
  $modelResponseFull=Join-Path $root $normalizedPath
  $modelDoc=Get-Content -Raw -Encoding UTF8 $modelResponseFull|ConvertFrom-Json
}
if([string]$modelDoc.recordType -cne 'AiWebDesignModelResponse' -or @($modelDoc.responses).Count -lt 1){throw 'BLOCKED_GITHUB_ABCD_MODEL_RESPONSE_INVALID'}
foreach($resp in @($modelDoc.responses)){
  if([string]::IsNullOrWhiteSpace([string]$resp.phase) -or [string]$resp.generationMode -notin @('creative-divergence','engineering','stable') -or [int]$resp.round -lt 0 -or @($resp.outputs).Count -lt 1){throw 'BLOCKED_GITHUB_ABCD_MODEL_RESPONSE_INVALID'}
  foreach($o in @($resp.outputs)){
    if([string]::IsNullOrWhiteSpace([string]$o.aiAnalysis) -or [string]$o.aiAnalysis.Length -lt 40 -or [string]::IsNullOrWhiteSpace([string]$o.execution) -or [string]$o.execution.Length -lt 20 -or $null -eq $o.returnReceipt -or $null -eq $o.evidence){throw 'BLOCKED_GITHUB_ABCD_MODEL_RESPONSE_EVIDENCE_INCOMPLETE'}
  }
}
$responseQueue=@($modelDoc.responses);$responseIndex=0
Import-Module (Join-Path $root 'ES/Automation/ABCD/ESABCDCapabilityDispatcher.psm1') -Force
Import-Module (Join-Path $root 'ES/Automation/ABCD/ESABCInnovationRun.psm1') -Force
$responseInvoker=New-ESABCDModelResponseInvoker -Responses $responseQueue
$modelInvoker={param($ctx);$responseIndex++;& $responseInvoker $ctx}.GetNewClosure()
$creative=$null;$innovation=$null
if($GenerationProfile -eq 'deep-creative-engineering' -or $GenerationProfile -eq 'creative-divergence'){$creative=Invoke-ESABCInnovationRun -Requirement $taskIntent -GoalRevision ([string]$task.goalRevisionHash) -SourceHash $sourceHash -GenerationMode 'creative-divergence' -ModelInvoker $modelInvoker -SeedBranches @($bindingHash) -SeedConstraints @('preserve repository scanability and keyboard reachability') -ProjectRoot $root;if([string]$creative.status -cne 'completed'){throw 'BLOCKED_GITHUB_ABCD_CREATIVE_RUN_NOT_COMPLETED'}}
if($GenerationProfile -eq 'deep-creative-engineering'){$creativeBranch=$creative.divergenceTree[[string]$creative.finalDecision.selectedBranchId];$innovation=Invoke-ESABCInnovationRun -Requirement $taskIntent -GoalRevision ([string]$task.goalRevisionHash) -SourceHash $sourceHash -GenerationMode 'engineering' -ModelInvoker $modelInvoker -SeedBranches @($creativeBranch.content) -SeedConstraints @('preserve repository scanability and keyboard reachability','challenge creative assumptions with implementation evidence') -ProjectRoot $root}
elseif($GenerationProfile -eq 'engineering' -or $GenerationProfile -eq 'stable'){$innovation=Invoke-ESABCInnovationRun -Requirement $taskIntent -GoalRevision ([string]$task.goalRevisionHash) -SourceHash $sourceHash -GenerationMode $GenerationProfile -ModelInvoker $modelInvoker -SeedBranches @($bindingHash) -SeedConstraints @('preserve repository scanability and keyboard reachability') -ProjectRoot $root}
else{$innovation=$creative}
if($null -eq $innovation -or [string]$innovation.status -cne 'completed'){throw 'BLOCKED_GITHUB_ABCD_INNOVATION_RUN_NOT_COMPLETED'}
$store=New-ESABCDOrchestrationStore -TaskId $task.taskId -TaskBindingId 'web-github-static-01-binding' -TaskBindingHash $bindingHash -AuthorizationRef 'user:github-abcd-run' -TaskRevision ([int]$task.taskRevision) -ContextVersion ([int]$task.contextVersion) -RoutePlanHash ([string]$routePlan.routePlanHash) -SourceScopeHash $sourceHash -MaxRounds 3 -AttemptsPerRound 2
$null=Start-ESABCDIterationRound $store ([int]$task.taskRevision) ([int]$task.contextVersion)
function Add-Candidate([string]$Id,[string]$Assumption){$snap=Get-ESABCDHash ([ordered]@{taskId=$store.taskId;branch=$Id;assumption=$Assumption;route=$store.routePlanHash});Add-ESABCDCandidate $store $Id $null $snap $Assumption 'static-design-and-existing-artifact-check' ([int]$store.taskRevision) ([int]$store.contextVersion)|Out-Null;return $snap}
$candidates=@();foreach($branch in @($innovation.divergenceTree.Values)){$candidates+=Add-Candidate ([string]$branch.branchId) ([string]$branch.content)}
$evidence=@([pscustomobject]@{path=$BindingPath.Replace('\\','/');sha256=$bindingHash})
Add-ESABCDAuditRecord $store ([string]$innovation.finalDecision.selectedBranchId) 'abcd-auditor:static-quality' 'review' $evidence 'abcd-verifier:design-contract' 'user:github-abcd-run' (Get-ESABCDHash 'verifier-definition-v1') ([int]$store.taskRevision) ([int]$store.contextVersion)|Out-Null
Select-ESABCDDecision $store ([string]$innovation.finalDecision.selectedBranchId) retry 'full' ([int]$store.taskRevision) ([int]$store.contextVersion)|Out-Null
$cycle=Start-ESABCDCorrectionCycle $store 'github-cycle-1' $RoutePath 'evidence' retry 'full' 1 ([int]$store.taskRevision) ([int]$store.contextVersion)
$receiptRef=$RoutePath.Replace('\\','/');$receiptHash=(Get-FileHash (Join-Path $root $receiptRef) -Algorithm SHA256).Hash.ToLowerInvariant();Add-ESABCDVerificationReceipt $store 'github-cycle-1' review $receiptRef $receiptHash ([int]$store.taskRevision) ([int]$store.contextVersion)|Out-Null
Stop-ESABCDIteration $store 'ABCD candidate tournament completed; selected candidate requires next correction/design pass.' ([int]$store.taskRevision) ([int]$store.contextVersion)|Out-Null
if(-not (Test-ESABCDEventStoreIntegrity $store)){throw 'abcd-event-store-integrity-failed'}
$snapPath=Join-Path $root 'ES/Output/WebPageStudio/bootstrap/abcd-github-web-snapshot.json';Save-ESABCDOrchestrationSnapshot $store $snapPath|Out-Null
$creativeRunId=if($creative){[string]$creative.runId}else{$null};$creativeRunHash=if($creative){[string]$creative.runHash}else{$null};$engineeringRunId=if($GenerationProfile -eq 'deep-creative-engineering'){[string]$innovation.runId}else{$null};$engineeringRunHash=if($GenerationProfile -eq 'deep-creative-engineering'){[string]$innovation.runHash}else{$null}
$artifactFull=Join-Path $root $ArtifactPath;$out=[ordered]@{schemaVersion=1;recordType='ABCDOrchestrationRunReceipt';invocationId=('abcd-invocation-'+$store.taskId);taskId=$store.taskId;innovationRunId=$innovation.runId;innovationRunHash=$innovation.runHash;modelResponsePath=$ModelResponsePath.Replace('\\','/');modelResponseHash=(Get-FileHash $modelResponseFull -Algorithm SHA256).Hash.ToLowerInvariant();modelInvokerCalls=$responseIndex;aiDesignTaskPath=$AiDesignTaskOutputPath.Replace('\\','/');aiDesignTaskHash=(Get-FileHash $aiTaskFull -Algorithm SHA256).Hash.ToLowerInvariant();upstreamRounds=$upstream;routePlanHash=$store.routePlanHash;sourceScopeHash=$store.sourceScopeHash;eventSequence=@($store.events).Count;eventHashes=@($store.events|ForEach-Object { $_.eventHash });candidateCount=$candidates.Count;candidateHashes=$candidates;selectedCandidateId=$innovation.finalDecision.selectedBranchId;decision='retry';existingArtifactBindings=@([pscustomobject]@{path=$BindingPath.Replace('\\','/');sha256=$bindingHash},[pscustomobject]@{path=$ArtifactPath.Replace('\\','/');sha256=(Get-FileHash $artifactFull -Algorithm SHA256).Hash.ToLowerInvariant()});snapshotPath='ES/Output/WebPageStudio/bootstrap/abcd-github-web-snapshot.json';snapshotHash=(Get-FileHash $snapPath -Algorithm SHA256).Hash.ToLowerInvariant();status='completed-with-retry-decision';integrityVerified=$true;nonClaims=@('model response artifact is not proof of provider identity','not HTML acceptance','not runtime/network/release')};[IO.File]::WriteAllText((Join-Path $root $OutputPath),($out|ConvertTo-Json -Depth 40),[Text.UTF8Encoding]::new($false));$out|Select-Object recordType,invocationId,innovationRunId,modelInvokerCalls,candidateCount,selectedCandidateId,decision,status,integrityVerified
$receiptFull=Join-Path $root $OutputPath;if(Test-Path -LiteralPath $receiptFull){$receiptDoc=Get-Content $receiptFull -Raw -Encoding UTF8|ConvertFrom-Json;$receiptDoc|Add-Member -NotePropertyName creativeInnovationRunId -NotePropertyValue $creativeRunId -Force;$receiptDoc|Add-Member -NotePropertyName engineeringInnovationRunId -NotePropertyValue $engineeringRunId -Force;$receiptDoc|Add-Member -NotePropertyName creativeRunHash -NotePropertyValue $creativeRunHash -Force;$receiptDoc|Add-Member -NotePropertyName engineeringRunHash -NotePropertyValue $engineeringRunHash -Force;[IO.File]::WriteAllText($receiptFull,($receiptDoc|ConvertTo-Json -Depth 40),[Text.UTF8Encoding]::new($false))}
