[CmdletBinding()]
param([string]$OutputPath='ES/Output/WebPageStudio/bootstrap/abcd-github-web-execution-receipt.json',[string]$TaskPath='ES/Output/WebPageStudio/bootstrap/round-03-task-context-github-verified.json',[string]$RoutePath='ES/Output/WebPageStudio/bootstrap/round-04-knowledge-route.json',[string]$BindingPath='ES/Output/WebPageStudio/bootstrap/round-05-design-packet-github.json',[string]$ArtifactPath='ES/Output/WebPageStudio/artifacts/github-atlas/index.html')
$ErrorActionPreference='Stop';$root=(Resolve-Path (Join-Path $PSScriptRoot '..\..\..')).Path
Import-Module (Join-Path $root 'ES/Automation/ABCD/ESABCDOrchestrator.psm1') -Force
$task=Get-Content (Join-Path $root $TaskPath) -Raw -Encoding UTF8|ConvertFrom-Json
$route=Get-Content (Join-Path $root $RoutePath) -Raw -Encoding UTF8|ConvertFrom-Json
$routePlan=Get-Content (Join-Path $root 'ES/Output/WebPageStudio/bootstrap/route-plan-github.json') -Raw -Encoding UTF8|ConvertFrom-Json
$bindingHash=(Get-FileHash (Join-Path $root $BindingPath) -Algorithm SHA256).Hash.ToLowerInvariant()
$sourceHash=[string]$task.sourceScopeHash;if($sourceHash -notmatch '^[a-f0-9]{64}$'){throw 'source-scope-hash-missing'}
$store=New-ESABCDOrchestrationStore -TaskId $task.taskId -TaskBindingId 'web-github-static-01-binding' -TaskBindingHash $bindingHash -AuthorizationRef 'user:github-abcd-run' -TaskRevision ([int]$task.taskRevision) -ContextVersion ([int]$task.contextVersion) -RoutePlanHash ([string]$routePlan.routePlanHash) -SourceScopeHash $sourceHash -MaxRounds 3 -AttemptsPerRound 2
$null=Start-ESABCDIterationRound $store ([int]$task.taskRevision) ([int]$task.contextVersion)
function Add-Candidate([string]$Id,[string]$Assumption){$snap=Get-ESABCDHash ([ordered]@{taskId=$store.taskId;branch=$Id;assumption=$Assumption;route=$store.routePlanHash});Add-ESABCDCandidate $store $Id $null $snap $Assumption 'static-design-and-existing-artifact-check' ([int]$store.taskRevision) ([int]$store.contextVersion)|Out-Null;return $snap}
$candidates=@();$candidates+=Add-Candidate 'github-candidate-a' 'split-pane workspace';$candidates+=Add-Candidate 'github-candidate-b' 'dashboard-first hierarchy';$candidates+=Add-Candidate 'github-candidate-c' 'activity-first hierarchy'
$evidence=@([pscustomobject]@{path=$BindingPath.Replace('\\','/');sha256=$bindingHash})
Add-ESABCDAuditRecord $store 'github-candidate-a' 'abcd-auditor:static-quality' 'pass' $evidence 'abcd-verifier:design-contract' 'user:github-abcd-run' (Get-ESABCDHash 'verifier-definition-v1') ([int]$store.taskRevision) ([int]$store.contextVersion)|Out-Null
Select-ESABCDDecision $store 'github-candidate-a' retry 'full' ([int]$store.taskRevision) ([int]$store.contextVersion)|Out-Null
$cycle=Start-ESABCDCorrectionCycle $store 'github-cycle-1' 'ES/Output/WebPageStudio/bootstrap/round-04-knowledge-route.json' 'evidence' retry 'full' 1 ([int]$store.taskRevision) ([int]$store.contextVersion)
$receiptRef=$RoutePath.Replace('\\','/');$receiptHash=(Get-FileHash (Join-Path $root $receiptRef) -Algorithm SHA256).Hash.ToLowerInvariant();Add-ESABCDVerificationReceipt $store 'github-cycle-1' passed $receiptRef $receiptHash ([int]$store.taskRevision) ([int]$store.contextVersion)|Out-Null
Stop-ESABCDIteration $store 'ABCD candidate tournament completed; selected candidate requires next correction/design pass.' ([int]$store.taskRevision) ([int]$store.contextVersion)|Out-Null
if(-not (Test-ESABCDEventStoreIntegrity $store)){throw 'abcd-event-store-integrity-failed'}
$snapPath=Join-Path $root 'ES/Output/WebPageStudio/bootstrap/abcd-github-web-snapshot.json';Save-ESABCDOrchestrationSnapshot $store $snapPath|Out-Null
$artifactFull=Join-Path $root $ArtifactPath;$out=[ordered]@{schemaVersion=1;recordType='ABCDOrchestrationRunReceipt';invocationId=('abcd-invocation-'+$store.taskId);taskId=$store.taskId;routePlanHash=$store.routePlanHash;sourceScopeHash=$store.sourceScopeHash;eventSequence=@($store.events).Count;eventHashes=@($store.events|ForEach-Object { $_.eventHash });candidateCount=$candidates.Count;candidateHashes=$candidates;selectedCandidateId=$store.selectedBranchId;decision='retry';existingArtifactBindings=@([pscustomobject]@{path=$BindingPath.Replace('\\','/');sha256=$bindingHash},[pscustomobject]@{path=$ArtifactPath.Replace('\\','/');sha256=(Get-FileHash $artifactFull -Algorithm SHA256).Hash.ToLowerInvariant()});snapshotPath='ES/Output/WebPageStudio/bootstrap/abcd-github-web-snapshot.json';snapshotHash=(Get-FileHash $snapPath -Algorithm SHA256).Hash.ToLowerInvariant();status='completed-with-retry-decision';integrityVerified=$true;nonClaims=@('not HTML acceptance','not runtime/network/release')};[IO.File]::WriteAllText((Join-Path $root $OutputPath),($out|ConvertTo-Json -Depth 40),[Text.UTF8Encoding]::new($false));$out|Select-Object recordType,invocationId,eventSequence,candidateCount,selectedCandidateId,decision,status,integrityVerified
