[CmdletBinding()]
param(
    [string]$ProjectRoot = (Resolve-Path (Join-Path $PSScriptRoot '..\..\..')).Path,
    [string]$ReportPath = 'ES/Output/StaticReplay/es-abc-generation-modes.json'
)
$ErrorActionPreference='Stop'
$root=(Resolve-Path -LiteralPath $ProjectRoot).Path
Import-Module (Join-Path $root 'ES/Automation/ABCD/ESABCDDivergence.psm1') -Force
Import-Module (Join-Path $root 'ES/Automation/ABCD/ESABCDPatchPlanning.psm1') -Force
$sourceHash=('a'*64)
$cases=[Collections.Generic.List[object]]::new()
function Add-Case([string]$Name,[bool]$Passed,[string]$Detail){[void]$cases.Add([pscustomobject][ordered]@{case=$Name;status=if($Passed){'passed'}else{'failed'};detail=$Detail})}
$profiles=@('creative-divergence','engineering','stable')|ForEach-Object{Get-ESABCGenerationMode -Mode $_ -ProjectRoot $root}
$scoringContractPath=Join-Path $root 'ES/Automation/Contracts/es-ai-abc-scoring-v1.json';$scoringContract=Get-Content -LiteralPath $scoringContractPath -Raw -Encoding UTF8|ConvertFrom-Json
Add-Case 'layered-scoring-contract-present' ($scoringContract.contractId -ceq 'es://automation/contracts/ai-abc/scoring/v1' -and @($scoringContract.layers.general.dimensions).Count -ge 5 -and @($scoringContract.layers.mode.modes.PSObject.Properties).Count -eq 3 -and [double]$scoringContract.layers.abcp.weight -gt 0) 'general + mode-specific + ABCP extension layers are centrally declared'
Add-Case 'repeated-score-review-policy-present' ([int]$scoringContract.review.minimumRounds -ge 3 -and [int]$scoringContract.review.defaultRounds -ge [int]$scoringContract.review.minimumRounds -and [double]$scoringContract.review.maximumScoreDrift -le 1.0 -and $scoringContract.review.independentRecomputeRequired) 'score review is multi-round, independently recomputed and drift-bounded'
Add-Case 'all-generation-modes-registered' ($profiles.Count -eq 3) (($profiles.modeId -join ','))
Add-Case 'mode-focuses-are-distinct' (@($profiles|%{$_.focus -join ','}|Sort-Object -Unique).Count -eq 3 -and $profiles[0].amplificationLoop -and $profiles[1].amplificationLoop -and $profiles[2].amplificationLoop) 'creative, engineering and stable carry distinct focus and amplification loops from the contract'
Add-Case 'mode-self-critique-loops-are-distinct' (($profiles | Where-Object { -not [string]::IsNullOrWhiteSpace($_.selfCritiqueLoop) }).Count -eq 3 -and @($profiles | ForEach-Object { $_.selfCritiqueLoop } | Sort-Object -Unique).Count -eq 3) 'each mode has an explicit generate-score-repair-rank loop instead of one-shot generation'
Add-Case 'creative-engineering-share-five-stage-pipeline' (@($profiles | Where-Object { $_.modeId -in @('creative-divergence','engineering') -and $_.sharedGenerationPipeline.stageOrderIsMandatory -and @($_.sharedGenerationPipeline.stages).Count -eq 5 -and @($_.sharedGenerationPipeline.stageEvidenceRequired).Count -eq 5 }).Count -eq 2) 'creative and engineering consume the same mandatory AB-seed/ABCD-expand/audit/playability/finalize pipeline'
Add-Case 'pipeline-profiles-bound-complexity-and-playability' (($profiles | Where-Object { $_.modeId -in @('creative-divergence','engineering') -and $_.pipelineProfile.deepAuditShortlist -eq 3 -and $_.pipelineProfile.playabilityGate -and $_.pipelineProfile.complexityBudget.coreResources -le 2 }).Count -eq 2) 'both modes carry explicit playability backpressure and bounded complexity budgets'
$creative=Invoke-ESABCModeDivergence -Requirement 'redesign-hero-for-player-expression' -SourceHash $sourceHash -Mode creative-divergence -ProjectRoot $root
$creativeIds=@($creative.directions.directionId|Sort-Object -Unique)
Add-Case 'creative-seven-visible-directions' ($creative.directionCount -ge 7 -and $creative.hiddenDirectionCount -eq 0 -and $creativeIds.Count -eq $creative.directionCount) "count=$($creative.directionCount);hidden=$($creative.hiddenDirectionCount)"
$engineering=Invoke-ESABCModeDivergence -Requirement 'implement-hero-as-benchmark' -SourceHash $sourceHash -Mode engineering -ProjectRoot $root
$stable=Invoke-ESABCModeDivergence -Requirement 'produce-content-variants' -SourceHash $sourceHash -Mode stable -ProjectRoot $root
function Get-FocusSpread($Envelope,[string]$Mode){
    $names=if($Mode -eq 'creative-divergence'){@('delight','smoothness','presentation','skillCeiling','joyLoop','first10sMoment','expressionCeiling','noveltyDelta','counterplayClarity')}elseif($Mode -eq 'engineering'){@('depth','breakthrough','reusability','longevity','counterplayClarity')}else{@('projectFit','completeness','safety','closure','reusability')}
    $values=@($Envelope.directions|ForEach-Object{$c=$_; $names|ForEach-Object{[int]$c.modeScores.$_}})
    [int](($values|Measure-Object -Maximum).Maximum-(($values|Measure-Object -Minimum).Minimum))
}
Add-Case 'generated-focus-scores-have-real-spread' ((Get-FocusSpread $creative 'creative-divergence' -gt 2) -and (Get-FocusSpread $engineering 'engineering' -gt 2) -and (Get-FocusSpread $stable 'stable' -gt 2)) 'deterministic generation itself carries non-uniform focus scores in every mode'
Add-Case 'engineering-and-stable-minimums' ($engineering.directionCount -ge 5 -and $stable.directionCount -ge 5) "engineering=$($engineering.directionCount);stable=$($stable.directionCount)"
$repeat=Invoke-ESABCModeDivergence -Requirement 'redesign-hero-for-player-expression' -SourceHash $sourceHash -Mode creative-divergence -ProjectRoot $root
Add-Case 'deterministic-candidate-set' ($repeat.candidateSetHash -ceq $creative.candidateSetHash) $creative.candidateSetHash
Add-Case 'audit-deferred-and-graph-not-authority' ($creative.auditDeferred -and $creative.graphAuthority -ceq 'candidate-only') 'generation does not preempt final audit'
$selection=Resolve-ESABCGenerationSelection -GenerationMode creative-divergence -AcceptanceProfile core-high-risk -Phase generate -ProjectRoot $root
Add-Case 'core-high-risk-does-not-prune-generation' ($selection.auditDeferred -and $selection.coreHighRiskEarlyPrune) 'profile is recorded and deferred, not silently applied as a generation filter'
$defaultSelection=Resolve-ESABCGenerationSelection -GenerationMode creative-divergence -Phase generate -ProjectRoot $root
Add-Case 'core-high-risk-is-global-default' ($defaultSelection.acceptanceProfile -ceq 'core-high-risk' -and $defaultSelection.auditDeferred) 'omitted acceptance profile cannot bypass the default high-risk audit gate'
$auditSelection=Resolve-ESABCGenerationSelection -GenerationMode engineering -AcceptanceProfile core-high-risk -Phase audit -ProjectRoot $root
Add-Case 'audit-phase-can-activate-strict-profile' (-not $auditSelection.auditDeferred -and $auditSelection.status -ceq 'audit-ready') 'strict profile activates only at audit phase'
$creativeSelection=Select-ESABCGenerationCandidate -Candidates $creative.directions -Mode creative-divergence
Add-Case 'creative-selection-ranks-and-recommends' ($creativeSelection.selectionStatus -ceq 'ranked-recommended' -and $creativeSelection.hiddenCandidates -eq 0 -and $creativeSelection.candidateCount -eq $creative.directionCount -and $creativeSelection.selectedDirectionId -ceq $creativeSelection.recommendedDirectionId) 'creative mode exposes every branch but recommends the highest-ranked candidate'
Add-Case 'creative-mode-focuses-on-flow-and-expression' ($creativeSelection.ranked[0].scoreBasis -ceq 'creative-flow-weighted' -and $creative.directions[0].amplificationChain -match 'amplify one action') 'creative ranking prioritizes joy loop, first-ten-second payoff, expression ceiling and amplification'
Add-Case 'creative-quality-self-check-is-visible' ($creativeSelection.qualityStatus -ceq 'mode-ready' -and $creativeSelection.ranked[0].quality.minimumFocusScore -ge 60) 'creative recommendation exposes a minimum focus score instead of hiding weak dimensions'
$pipelinePending=Invoke-ESABCGenerationPipeline -Candidates $creative.directions -Mode creative-divergence
Add-Case 'pipeline-stops-before-audit-and-playability' ($pipelinePending.status -ceq 'review-required' -and $pipelinePending.stageStatus.abcdAudit -ceq 'pending' -and $pipelinePending.stageStatus.playabilityBackpressure -ceq 'pending' -and $pipelinePending.stageStatus.finalize -ceq 'blocked') 'candidate selection cannot masquerade as finalization before audit and playability acceptance'
$pipelineReady=Invoke-ESABCGenerationPipeline -Candidates $creative.directions -Mode creative-divergence -AuditApproved $true -PlayabilityAccepted $true
Add-Case 'pipeline-finalizes-only-after-both-gates' ($pipelineReady.status -ceq 'finalized-candidate' -and $pipelineReady.stageStatus.finalize -ceq 'ready' -and $pipelineReady.finalDecision -eq $pipelineReady.selection.selectedDirectionId) 'finalization requires both explicit ABCD audit and playability backpressure acceptance'
$playability=Get-ESABCPlayabilityAssessment -Candidate $creative.directions[0]
Add-Case 'first-use-playability-is-not-full-comprehension' ($playability.status -ceq 'immediately-playable' -and $playability.firstPayoffSeconds -le 10 -and $playability.firstInputCount -le 3 -and $playability.onboardingBurden -gt 50 -and $playability.masteryDepthPresent) 'high onboarding burden remains playable when first input, partial path, feedback and layered mastery are explicit'
$noAffordance=$creative.directions[0]|ConvertTo-Json -Depth 20|ConvertFrom-Json;$noAffordance.firstUseAffordance='';$noAffordanceAssessment=Get-ESABCPlayabilityAssessment -Candidate $noAffordance
Add-Case 'playability-rejects-missing-first-affordance' ($noAffordanceAssessment.status -ceq 'unplayable-first-use' -and $noAffordanceAssessment.reasons -contains 'MISSING_firstUseAffordance') 'only missing first-use affordance or feedback blocks playability; complexity alone does not'
$novelty=Get-ESABCCreativeNoveltyAssessment -Candidate $creative.directions[0]
Add-Case 'creative-novelty-is-bold-but-grounded' ($novelty.status -ceq 'grounded-bold' -and $novelty.deletedAnchorCount -ge 2 -and $novelty.surpriseScore -ge 70 -and $novelty.plausibilityScore -ge 60) 'creative candidates must break at least two anchors while retaining causal plausibility and counterplay'
$integrity=Get-ESABCInnovationIntegrityAssessment -Candidate $creative.directions[0]
Add-Case 'innovation-preserves-identity-role-and-form-factor' ($integrity.status -ceq 'concrete-continuous' -and $integrity.formFactorPreserved -and $integrity.concretenessScore -ge 70 -and $integrity.acceptabilityScore -ge 60) 'innovation may change mechanism, but a requested knife cannot silently become a gun'
$iterated=Invoke-ESABCIterativeDivergence -Requirement 'redesign-with-player-acceptable-depth' -SourceHash $sourceHash -Mode creative-divergence -Iterations 12 -Branching 2 -ProjectRoot $root
Add-Case 'iterative-divergence-has-bounded-depth' ($iterated.roundCount -ge 12 -and $iterated.branchCount -ge 24 -and @($iterated.rounds|Where-Object{$_.roundId -and $_.parentCandidateId -and $_.branchReason -and $_.concreteChange -and $_.keepOrDiscardReason}).Count -eq $iterated.branchCount) 'each round branches, compares acceptability, and records a concrete keep/discard reason'
$wrongForm=$creative.directions[0]|ConvertTo-Json -Depth 20|ConvertFrom-Json;$wrongForm.formFactorPreserved=$false;$wrongFormIntegrity=Get-ESABCInnovationIntegrityAssessment -Candidate $wrongForm
Add-Case 'form-factor-substitution-is-rejected' ($wrongFormIntegrity.status -ceq 'needs-integrity' -and $wrongFormIntegrity.reasons -contains 'FORM_FACTOR_NOT_PRESERVED') 'unrelated form-factor replacement is a hard integrity failure'
$abstractOnly=$creative.directions[0]|ConvertTo-Json -Depth 20|ConvertFrom-Json;$abstractOnly.concretePlayerScenario='abstract power fantasy only';$abstractOnly.inputSequence='';$abstractOnly.visibleFeedback='';$abstractOnly.concretenessScore=100;$abstractOnly.acceptabilityScore=100;$abstractAssessment=Get-ESABCInnovationIntegrityAssessment -Candidate $abstractOnly
Add-Case 'abstract-extreme-is-not-innovation' ($abstractAssessment.status -ceq 'needs-integrity' -and @($abstractAssessment.reasons|Where-Object{$_ -like 'MISSING_*'}).Count -ge 2) 'abstract or extreme wording without player action and feedback cannot rank as innovation'
$ungrounded=$creative.directions[0]|ConvertTo-Json -Depth 20|ConvertFrom-Json;$ungrounded.deletedAnchors=@('one');$ungrounded.surpriseScore=95;$ungrounded.plausibilityScore=20;$ungroundedAssessment=Get-ESABCCreativeNoveltyAssessment -Candidate $ungrounded
Add-Case 'creative-novelty-rejects-unreasoned-extremes' ($ungroundedAssessment.status -ceq 'needs-grounding' -and $ungroundedAssessment.reasons -contains 'DELETED_ANCHORS_LT_2' -and $ungroundedAssessment.reasons -contains 'PLAUSIBILITY_SCORE_LT_60') 'high surprise without deleted anchors and plausibility cannot reach finalization'
$groundingPipeline=Invoke-ESABCGenerationPipeline -Candidates @($ungrounded) -Mode creative-divergence -AuditApproved $true -PlayabilityAccepted $true
Add-Case 'grounding-gate-blocks-finalization' ($groundingPipeline.status -ceq 'review-required' -and $groundingPipeline.reasonCode -ceq 'ABC_PIPELINE_CREATIVE_GROUNDING_REQUIRED') 'creative grounding is an authority gate, not a descriptive score'
$pipelineMissing=$creative.directions[0]|ConvertTo-Json -Depth 20|ConvertFrom-Json;$pipelineMissing.auditFindings='';$pipelineMissingRejected=$false;try{Invoke-ESABCGenerationPipeline -Candidates @($pipelineMissing) -Mode creative-divergence|Out-Null}catch{$pipelineMissingRejected=$_.Exception.Message -like 'ABC_PIPELINE_STAGE_EVIDENCE_MISSING:*'}
Add-Case 'pipeline-rejects-missing-stage-evidence' $pipelineMissingRejected 'stage evidence is mandatory and cannot be replaced by a candidate status'
$lowCreative=$creative.directions[0]|ConvertTo-Json -Depth 20|ConvertFrom-Json;$lowCreative.modeScores.joyLoop=10;$lowCreative.modeScores.first10sMoment=20;$lowCreative.modeScores.expressionCeiling=30;$lowCreative.modeScores.counterplayClarity=40;$lowCreativeSelection=Select-ESABCGenerationCandidate -Candidates @($lowCreative) -Mode creative-divergence
Add-Case 'creative-low-quality-is-not-hidden' ($lowCreativeSelection.qualityStatus -ceq 'needs-deepening' -and $lowCreativeSelection.hiddenCandidates -eq 0) 'creative weak joy remains visible but cannot be presented as mode-ready'
$shortChain=$creative.directions[0]|ConvertTo-Json -Depth 20|ConvertFrom-Json;$shortChain.amplificationChain='hit -> flash -> damage';$shortChainSelection=Select-ESABCGenerationCandidate -Candidates @($shortChain) -Mode creative-divergence
Add-Case 'short-amplification-chain-needs-deepening' ($shortChainSelection.qualityStatus -ceq 'needs-deepening' -and $shortChainSelection.ranked[0].quality.amplification.stageCount -eq 3) 'three-stage chains cannot pass the four-stage amplification gate'
$repeatedChain=$creative.directions[0]|ConvertTo-Json -Depth 20|ConvertFrom-Json;$repeatedChain.amplificationChain='hit -> hit -> hit -> hit';$repeatedSelection=Select-ESABCGenerationCandidate -Candidates @($repeatedChain) -Mode creative-divergence
Add-Case 'repeated-amplification-chain-needs-deepening' ($repeatedSelection.qualityStatus -ceq 'needs-deepening' -and $repeatedSelection.ranked[0].quality.amplification.repeatedStage) 'repeating one label cannot masquerade as multi-stage amplification'
$engineeringSelection=Select-ESABCGenerationCandidate -Candidates $engineering.directions -Mode engineering
Add-Case 'engineering-selection-is-deterministic' ($engineeringSelection.selectionStatus -ceq 'deterministic-selected' -and -not [string]::IsNullOrWhiteSpace([string]$engineeringSelection.selectedDirectionId)) 'engineering mode converges after explicit generation'
Add-Case 'engineering-mode-focuses-on-depth-and-longevity' ($engineeringSelection.ranked[0].scoreBasis -ceq 'engineering-depth-weighted') 'engineering ranking prioritizes depth, breakthrough, reuse, longevity and counterplay'
$stableSelection=Select-ESABCGenerationCandidate -Candidates $stable.directions -Mode stable
Add-Case 'stable-mode-focuses-on-project-closure' ($stableSelection.ranked[0].scoreBasis -ceq 'stable-closure-weighted') 'stable ranking prioritizes project fit, completeness, safety, closure and reuse'
$lowEngineering=$engineering.directions[0]|ConvertTo-Json -Depth 20|ConvertFrom-Json;$lowEngineering.modeScores.depth=10;$lowEngineering.modeScores.breakthrough=20;$lowEngineering.modeScores.reusability=30;$lowEngineering.modeScores.longevity=40;$lowEngineeringSelection=Select-ESABCGenerationCandidate -Candidates @($lowEngineering) -Mode engineering
$lowStable=$stable.directions[0]|ConvertTo-Json -Depth 20|ConvertFrom-Json;$lowStable.modeScores.projectFit=10;$lowStable.modeScores.completeness=20;$lowStable.modeScores.safety=30;$lowStable.modeScores.closure=40;$lowStableSelection=Select-ESABCGenerationCandidate -Candidates @($lowStable) -Mode stable
Add-Case 'engineering-and-stable-low-quality-are-visible' ($lowEngineeringSelection.qualityStatus -ceq 'needs-deepening' -and $lowStableSelection.qualityStatus -ceq 'needs-deepening') 'engineering depth and stable closure deficits remain explicit and require deepening'
$sameRequirement='redesign-arthur-for-high-skill-expression'
$scenario=@(@('creative-divergence','engineering','stable')|ForEach-Object{Invoke-ESABCModeDivergence -Requirement $sameRequirement -SourceHash $sourceHash -Mode $_ -ProjectRoot $root})
Add-Case 'same-requirement-mode-replay-diverges' (@($scenario|%{$_.profile.objective}|Sort-Object -Unique).Count -eq 3 -and @($scenario|%{$_.directions[0].amplificationChain}|Sort-Object -Unique).Count -eq 3) 'same requirement produces distinct mode objectives and amplification loops'
$t1=Resolve-ESABCModeTransition -FromMode creative-divergence -ToMode engineering -CandidateSelected $true
$t2=Resolve-ESABCModeTransition -FromMode engineering -ToMode stable -DesignContractReady $true -RegressionFixtureReady $false
$t3=Resolve-ESABCModeTransition -FromMode stable -ToMode engineering -VariationExceedsTemplateBoundary $true
Add-Case 'mode-transition-requires-real-gates' ($t1.status -ceq 'ready' -and $t2.status -ceq 'blocked' -and $t3.status -ceq 'ready' -and $t2.reasonCode -ceq 'ENGINEERING_CONTRACT_OR_FIXTURE_MISSING') 'creative to engineering, engineering to stable, and stable backflow use explicit readiness predicates'
$brainText=Get-Content -LiteralPath (Join-Path $root 'Assets/Plugins/ES/Editor/ESAutomation/ESAIBrainCoordinator.cs') -Raw -Encoding UTF8
$facadeText=Get-Content -LiteralPath (Join-Path $root 'Assets/Plugins/ES/Editor/ESAutomation/ESAutomationFacade.cs') -Raw -Encoding UTF8
$bridgeText=Get-Content -LiteralPath (Join-Path $root 'Assets/Plugins/ES/Editor/ESAutomation/ESAutomationAiBridge.cs') -Raw -Encoding UTF8
$providerText=Get-Content -LiteralPath (Join-Path $root 'Assets/Plugins/ES/Editor/ESAutomation/ESABCModelProviderAdapter.cs') -Raw -Encoding UTF8
$patchPlanningText=Get-Content -LiteralPath (Join-Path $root 'ES/Automation/ABCD/ESABCDPatchPlanning.psm1') -Raw -Encoding UTF8
$responseSchemaText=Get-Content -LiteralPath (Join-Path $root 'ES/Automation/Contracts/es-ai-abc-generation-response-v1.schema.json') -Raw -Encoding UTF8
$modeContractText=Get-Content -LiteralPath (Join-Path $root 'ES/Automation/Contracts/es-ai-abc-generation-mode-v1.json') -Raw -Encoding UTF8
Add-Case 'aibrain-freezes-generation-selection' ($brainText -match 'generationMode = source\.generationMode' -and $brainText -match 'request\.generationMode' -and $brainText -match 'ComputePlanHash' -and $brainText -match 'core-high-risk is the default') 'request snapshot and plan hash bind mode fields and default the audit gate'
Add-Case 'invocation-exposes-generation-selection' ($facadeText -match 'public string generationMode' -and $facadeText -match 'acceptanceProfile = "core-high-risk"' -and $brainText -match 'generationAuditDeferred = plan\.generationAuditDeferred') 'host invocation receives mode and default gate without Graph authority'
Add-Case 'ai-bridge-preserves-generation-selection' ($bridgeText -match 'generationMode' -and $bridgeText -match 'acceptanceProfile' -and $bridgeText -match 'core-high-risk') 'AI bridge accepts and forwards mode/profile instead of dropping them at the host boundary'
$providerPromptContract = (($providerText -match 'TryBuildGenerationPrompt') -and ($providerText -match 'MaximumObjectiveCharacters') -and ($providerText -match 'ABC_GENERATION_NO_SILENT_HIDING'))
$providerNoSideEffects = (($providerText -match 'never writes project files') -and ($providerText -match 'OpenAndSendPromptWithReceipt') -and ($providerText -notmatch 'File\.Write|AssetDatabase\.'))
Add-Case 'provider-constructs-bounded-mode-prompt' $providerPromptContract 'controlled provider receives mode and emits bounded candidate-only prompt'
Add-Case 'provider-prompts-mode-specific-quality' (($providerText -match 'ModeInstruction') -and ($providerText -match 'amplificationChain') -and ($providerText -match 'modeScores') -and ($providerText -match 'Mode-specific')) 'provider prompt keeps the three quality objectives explicit instead of collapsing them into one generic score'
Add-Case 'provider-enforces-innovation-integrity' (($providerText -match 'form-factor substitution') -and ($providerText -match 'concretePlayerScenario') -and ($providerText -match 'iterationTrace') -and ($providerText -match 'formFactorPreserved')) 'provider must preserve requested identity/role/form factor and emit concrete multi-round divergence evidence'
Add-Case 'provider-requires-self-critique-pass' (($providerText -match 'Self-critique loop') -and ($providerText -match 'repair/amplify')) 'provider must perform a visible repair pass before ranking candidates'
Add-Case 'mode-contract-and-schema-share-self-critique-field' (($modeContractText -match '"selfCritique"') -and ($responseSchemaText -match '"selfCritique"') -and ($modeContractText -match 'selfCritiqueLoop')) 'generation contract and response schema cannot drift on self-critique evidence'
Add-Case 'amplification-chain-has-minimum-stages' (($providerText -match 'amplificationStages') -and ($providerText -match 'at least four stages') -and ($responseSchemaText -match '"minLength": 32')) 'a candidate must express a four-stage action amplification rather than a one-line feature label'
Add-Case 'mode-quality-threshold-is-contract-bound' (($profiles | Where-Object { $_.minimumFocusScore -eq 60 }).Count -eq 3 -and ($providerText -match 'QualityStatus') -and ($providerText -match 'MinimumFocusScore')) 'all modes expose a contract-bound minimum focus score and candidate quality status'
Add-Case 'focus-spread-threshold-is-contract-bound' (($profiles | Where-Object { $_.minimumFocusSpread -eq 3 }).Count -eq 3 -and $creativeSelection.ranked[0].quality.minimumFocusSpread -eq 3 -and $creativeSelection.ranked[0].quality.focusSpread -ge 3) 'focus score distinction threshold is declared centrally and surfaced in candidate quality'
Add-Case 'mode-contract-rejects-invalid-focus-spread' ((Get-Content -LiteralPath (Join-Path $root 'ES/Automation/ABCD/ESABCDDivergence.psm1') -Raw -Encoding UTF8) -match 'ABC_GENERATION_MODE_FOCUS_SPREAD_INVALID' -and ($profiles | Where-Object { $_.minimumFocusSpread -lt 1 }).Count -eq 0) 'mode loader refuses missing or non-positive focus spread thresholds'
Add-Case 'provider-has-no-side-effect-authority' $providerNoSideEffects 'provider adapter delegates prompt dispatch only'
Add-Case 'provider-response-is-normalized-before-audit' (($providerText -match 'TryParseGenerationResponse') -and ($providerText -match 'CandidateSetHash') -and ($providerText -match 'ABC_RESPONSE_REJECT_ACCEPTED') -and ($providerText -match 'ABC_RESPONSE_REJECT_HIDDEN') -and ($providerText -match 'generation-response/v1') -and ($providerText -match 'minimum')) 'provider response becomes budgeted candidate envelope; contract identity and accepted/hidden claims are enforced'
Add-Case 'provider-receipt-consumption-is-exact' (($providerText -match 'TryReadProviderResponseReceipt') -and ($providerText -match 'result\.json') -and ($providerText -match 'Path\.IsPathRooted') -and ($providerText -match 'ReadAllText')) 'only one exact absolute managed receipt is consumed'
Add-Case 'host-dispatch-is-bound-to-normalized-candidate-envelope' (($providerText -match 'TryConsumeGenerationDispatch') -and ($providerText -match 'dispatch\.Accepted') -and ($providerText -match 'TryReadProviderResponseReceipt\(dispatch\.OperationDirectory') -and ($providerText -match 'TryParseGenerationResponse\(response, expectedGenerationMode')) 'the real host dispatch result is the only input to candidate normalization'
Add-Case 'provider-candidate-carries-bounded-proposed-changes' (($providerText -match 'ProposedChanges') -and ($providerText -match 'ESABCGenerationChange') -and ($providerText -match '2000000') -and ($providerText -match 'hasTraversal') -and ($providerText -match 'validationMetric') -and ($providerText -match 'PlayerDelightScore')) 'real provider candidates can carry bounded changes and an explicit delight score for ranking'
Add-Case 'self-critique-is-a-required-candidate-field' (($responseSchemaText -match '"selfCritique"') -and ($providerText -match 'selfCritique') -and ($providerText -match 'weakest') -and ($providerText -match 'repair') -and ($providerText -match 'ranking') -and $creative.directions[0].selfCritique.Length -ge 32) 'self-critique evidence is required in schema, provider parsing and deterministic candidates'
Add-Case 'self-critique-requires-repeated-passes' (($responseSchemaText -match 'selfCritiquePasses') -and ($providerText -match 'selfCritiquePasses') -and $creative.directions[0].selfCritiquePasses -ge 2) 'candidates must perform at least two self-critique and amplification passes'
Add-Case 'self-critique-pass-range-is-bounded' (($responseSchemaText -match '"minimum": 2') -and ($responseSchemaText -match '"maximum": 4') -and ($providerText -match 'selfCritiquePasses.Value < 2') -and ($providerText -match 'selfCritiquePasses.Value > 4')) 'self-critique repetition is enforced within a bounded 2-4 pass range'
Add-Case 'self-critique-missing-marker-is-rejected' (($providerText -match 'selfCritiqueShapeValid') -and ($providerText -match 'IndexOf\("weakest"') -and ($providerText -match 'IndexOf\("repair"') -and ($providerText -match 'IndexOf\("ranking"') -and ($providerText -match '!selfCritiqueShapeValid')) 'parser rejects self-critique text that omits any required structure marker'
Add-Case 'uniform-mode-scores-are-rejected' ($providerText -match 'focusScoreSpread' -and $providerText -match 'focusScoreSpread <= 2') 'parser rejects uniform or near-uniform focus scores that would fake mode-specific reasoning'
Add-Case 'provider-enforces-aggregate-change-budget' (($providerText -match 'MaximumTotalProposedChangeCharacters') -and ($providerText -match 'MaximumTotalProposedChangeFiles') -and ($providerText -match 'totalProposedChangeCharacters') -and ($providerText -match 'totalProposedChangeFiles')) 'aggregate proposedChanges budget prevents peak-memory amplification across candidates'
Add-Case 'generation-contract-declares-resource-budget' (($responseSchemaText -match 'materializeOnlySelectedCandidate') -and ($responseSchemaText -match 'maxTotalProposedChangeCharacters')) 'response contract records the same aggregate budget and staged materialization policy'
Add-Case 'generation-mode-contract-is-operation-cached' ((Get-Content -LiteralPath (Join-Path $root 'ES/Automation/ABCD/ESABCDDivergence.psm1') -Raw -Encoding UTF8) -match 'ESABCGenerationModeCache' -and (Get-Content -LiteralPath (Join-Path $root 'ES/Automation/ABCD/ESABCDDivergence.psm1') -Raw -Encoding UTF8) -match 'LastWriteTimeUtc') 'mode contract is cached only for an unchanged file snapshot'
$patchPlan = New-ESABCDCandidatePatchPlan -CandidateEnvelope ([pscustomobject]@{Status='candidate';CandidateSetHash=$creative.candidateSetHash;GenerationMode='creative-divergence';Candidates=$creative.directions}) -Scenario DesignChange -CurrentHead ('a'*40) -AuthorizationRef 'user:test' -SourceFiles @('ES/Automation/Contracts/es-ai-abc-generation-mode-v1.json') -AllowedWriteScopes @('ES/Automation/Contracts')
$patchCheck = Test-ESABCDCandidatePatchPlan -Plan $patchPlan
Add-Case 'candidate-patch-plan-is-audited-and-reversible' ($patchCheck.status -ceq 'passed' -and $patchPlan.planStatus -ceq 'awaiting-abcd-audit' -and $patchPlan.effects.writesAllowed -eq $false -and $patchPlan.rollback.available) 'patch plan pins source hashes and cannot apply before ABCD audit'
$proposalTarget = 'ES/Automation/Contracts/es-ai-abc-generation-mode-v1.json'
$proposalContent = Get-Content -LiteralPath (Join-Path $root $proposalTarget) -Raw -Encoding UTF8
$proposalOps = Convert-ESABCDCandidateToPatchOperations -Candidate ([pscustomobject]@{proposedChanges=@([pscustomobject]@{path=$proposalTarget;afterContent=$proposalContent;changeId='noop-contract-check'})}) -ProjectRoot $root -AllowedWriteScopes @('ES/Automation/Contracts')
Add-Case 'candidate-proposal-converts-to-scoped-operations' (@($proposalOps).Count -eq 1 -and $proposalOps[0].beforeHash -and $proposalOps[0].afterContent -ceq $proposalContent -and $proposalOps[0].path -like '*es-ai-abc-generation-mode-v1.json') 'candidate proposedChanges become hash-pinned project-relative operations without applying them'
$acceptedGate = [pscustomobject]@{status='accepted';decisionStatus='Accepted';gateId='gate-test';planHash=$patchPlan.planHash;candidateSetHash=$patchPlan.candidateSetHash}
$applyRequest = New-ESABCDApprovedApplyRequest -PatchPlan $patchPlan -FinalGate $acceptedGate -ObservedHead ('a'*40) -ApplyAuthorizationRef 'user:apply-test'
Add-Case 'accepted-gate-produces-one-shot-apply-request' ($applyRequest.requestStatus -ceq 'awaiting-explicit-apply' -and $applyRequest.oneShot -and $applyRequest.effects.writesAllowed -and -not $applyRequest.effects.runtimeAllowed -and $applyRequest.rollback.available) 'only accepted gate plus explicit apply authorization can open write channel'
$applyCheck = Test-ESABCDApprovedApplyRequest -ApplyRequest $applyRequest -ObservedHead ('a'*40) -ExpectedApplyAuthorizationRef 'user:apply-test'
$replayCheck = Test-ESABCDApprovedApplyRequest -ApplyRequest $applyRequest -ObservedHead ('a'*40) -ExpectedApplyAuthorizationRef 'user:apply-test' -AlreadyConsumed
Add-Case 'apply-request-is-validated-and-replay-safe' ($applyCheck.status -ceq 'passed' -and $replayCheck.status -ceq 'failed' -and @($replayCheck.issues) -contains 'APPLY_REQUEST_ALREADY_CONSUMED') 'apply request validates exact authority and rejects one-shot replay'
Add-Case 'approved-apply-executor-is-hash-and-scope-guarded' (($providerText -eq $providerText) -and (Test-Path (Join-Path $root 'ES/Automation/ABCD/ESABCDPatchPlanning.psm1')) -and ($patchPlanningText -match 'Invoke-ESABCDApprovedApplyRequest') -and ($patchPlanningText -match 'APPLY_BEFORE_HASH_MISMATCH') -and ($patchPlanningText -match 'ShouldProcess')) 'explicit apply performs scoped before-hash checks and emits rollback evidence'
Add-Case 'apply-receipt-closes-hash-loop' (($patchPlanningText -match 'Test-ESABCDApplyReceipt') -and ($patchPlanningText -match 'APPLY_RECEIPT_AFTER_HASH_MISMATCH') -and ($patchPlanningText -match 'APPLY_RECEIPT_ROLLBACK_MISSING')) 'post-apply receipt rechecks after hashes and rollback artifacts'
Add-Case 'apply-result-feeds-self-iteration-safely' (($patchPlanningText -match 'Convert-ESABCDApplyReceiptToVerificationInput') -and ($patchPlanningText -match 'learningPromotionAllowed') -and ($patchPlanningText -match "'review'")) 'only independently verified applied results can feed iteration learning'
$failed=@($cases|Where-Object status -eq 'failed')
$refs=@('ES/Automation/ABCD/ESABCDDivergence.psm1','ES/Automation/ABCD/ESABCInnovationRun.psm1','ES/Automation/ABCD/Test-ESABCGenerationModes.ps1','ES/Automation/Contracts/es-ai-abc-scoring-v1.json','ES/Automation/Contracts/es-ai-abc-generation-mode-v1.json','ES/Automation/Contracts/es-ai-abc-generation-response-v1.schema.json','ES/Automation/Contracts/es-ai-abc-mode.registry.json','Assets/Plugins/ES/Editor/ESAutomation/ESAIBrainCoordinator.cs','Assets/Plugins/ES/Editor/ESAutomation/ESAutomationFacade.cs','Assets/Plugins/ES/Editor/ESAutomation/ESAutomationAiBridge.cs','Assets/Plugins/ES/Editor/ESAutomation/ESABCModelProviderAdapter.cs')
$hashes=[ordered]@{};foreach($r in $refs){$hashes[$r]=(Get-FileHash -LiteralPath (Join-Path $root $r) -Algorithm SHA256).Hash.ToLowerInvariant()}
$evidenceContractPath=Join-Path $root 'ES/Automation/Contracts/es-skill-evidence-receipt-v1.schema.json'
$modeReplay=@($scenario|ForEach-Object{
    $modeSelection=Select-ESABCGenerationCandidate -Candidates $_.directions -Mode $_.mode
    [ordered]@{mode=$_.mode;objective=$_.profile.objective;focus=@($_.profile.focus);amplificationLoop=$_.profile.amplificationLoop;selfCritiqueLoop=$_.profile.selfCritiqueLoop;candidateCount=$_.directionCount;candidateSetHash=$_.candidateSetHash;recommendedDirectionId=$modeSelection.recommendedDirectionId;recommendedRankScore=$modeSelection.ranked[0].rankScore;recommendedFocusSpread=$modeSelection.ranked[0].quality.focusSpread;minimumFocusSpread=$modeSelection.ranked[0].quality.minimumFocusSpread;qualityStatus=$modeSelection.qualityStatus;amplificationStageCount=$modeSelection.ranked[0].quality.amplification.stageCount;selfCritiqueLength=$modeSelection.ranked[0].candidate.selfCritique.Length;selfCritiquePasses=$modeSelection.ranked[0].candidate.selfCritiquePasses}
})
$runtimeAdmission=[ordered]@{status='not-run';reason='target-project-unmatched';targetProject=$root;observedUnity=@()}
try {
    $observed=@(Get-CimInstance Win32_Process -ErrorAction Stop | Where-Object { $_.Name -like 'Unity*.exe' -or $_.Name -eq 'Unity.exe' } | ForEach-Object { [ordered]@{name=$_.Name;processId=$_.ProcessId;executablePath=$_.ExecutablePath;commandLine=$_.CommandLine;matchesTarget=([string]$_.CommandLine -match [regex]::Escape($root))} })
    $runtimeAdmission.observedUnity=$observed
    if(@($observed|Where-Object matchesTarget).Count -gt 0){$runtimeAdmission.status='target-project-process-present';$runtimeAdmission.reason='target-project-matched'}
} catch { $runtimeAdmission.reason='process-inspection-failed';$runtimeAdmission.error=$_.Exception.Message }
$report=[ordered]@{schemaVersion=1;validator='Test-ESABCGenerationModes';skillName='es-ai-abc-core';case='generation-modes';toolId='es-abc-generation-modes-validator';unityVersion='not-run';status=if($failed.Count){'failed'}else{'passed'};staticStatus=if($failed.Count){'static-failed'}else{'static-passed'};runtimeStatus='runtime-not-run';runtimeAdmission=$runtimeAdmission;evidenceLevel='S1';capturedUtc=[DateTime]::UtcNow.ToString('o');caseCount=$cases.Count;passedCount=($cases.Count-$failed.Count);failedCount=$failed.Count;cases=$cases;modeCount=$profiles.Count;modeIds=@($profiles.modeId);modeReplay=$modeReplay;authorizationKind='read-only';evidenceContractId='es.skill-evidence-receipt';evidenceContractHash=(Get-FileHash -LiteralPath $evidenceContractPath -Algorithm SHA256).Hash.ToLowerInvariant();sourceRefs=$refs;sourceRefHashes=$hashes;claimsNotProven=@('creative-quality','player-fun','Unity-runtime','balance')}
$full=if([IO.Path]::IsPathRooted($ReportPath)){$ReportPath}else{Join-Path $root $ReportPath};New-Item -ItemType Directory -Force (Split-Path $full)|Out-Null;[IO.File]::WriteAllText($full,($report|ConvertTo-Json -Depth 30),[Text.UTF8Encoding]::new($false));$report|ConvertTo-Json -Depth 30;if($failed.Count){exit 1}
