[CmdletBinding()]
param(
    [string]$ProjectRoot = (Resolve-Path (Join-Path $PSScriptRoot '..\..\..')).Path,
    [string]$ReportPath = 'ES/Output/StaticReplay/es-abcd-adaptive-learning.json'
)
$ErrorActionPreference = 'Stop'
Remove-Item Alias:H -ErrorAction SilentlyContinue
$root = (Resolve-Path -LiteralPath $ProjectRoot).Path
Import-Module (Join-Path $root 'ES/Automation/ABCD/ESABCDAdaptiveLearning.psm1') -Force
Import-Module (Join-Path $root 'ES/Automation/Contracts/ESJsonSchemaLite.psm1') -Force
$results = [Collections.Generic.List[object]]::new()
function Case([string]$Name, [scriptblock]$Body) { try { & $Body; [void]$results.Add([pscustomobject]@{case=$Name;status='passed';finding=$null}) } catch { [void]$results.Add([pscustomobject]@{case=$Name;status='failed';finding=$_.Exception.Message}) } }
function Assert-True([bool]$Value,[string]$Message){if(-not$Value){throw $Message}}
function MakeHash([string]$c){return (($c*64)-join '')}
function H([string]$c){return MakeHash $c}
function Rehash($v,[string]$exclude){$x=[ordered]@{};foreach($p in $v.PSObject.Properties){if($p.Name-ne$exclude){$x[$p.Name]=$p.Value}};return Get-ESABCDAdaptiveHash $x}
function Sample([string]$id,[string]$group,[string]$hash){[pscustomobject][ordered]@{caseId=$id;sourceGroupId=$group;snapshotHash=$hash}}
$schemaPath = Join-Path $root 'ES/Automation/Contracts/es-abcd-adaptive-learning-v1.schema.json'
$sourcePath = 'ES/Automation/ABCD/ESABCDAdaptiveLearning.psm1'; $sourceHash = (Get-FileHash (Join-Path $root $sourcePath) -Algorithm SHA256).Hash.ToLowerInvariant()
$metrics = @([pscustomobject][ordered]@{name='accuracy';direction='maximize';minDelta=0.01;noRegressionTolerance=0.005},[pscustomobject][ordered]@{name='latency';direction='minimize';minDelta=0.5;noRegressionTolerance=0.25})
function New-Fixture {
    $m=New-ESABCDDatasetPartitionManifest -DatasetId 'dataset.v1' -TrainRefs @((Sample train-a train-group-a (MakeHash '1')),(Sample train-b train-group-b (MakeHash '2'))) -ValidationRefs @((Sample val-a val-group-a (MakeHash '3')),(Sample val-b val-group-b (MakeHash '4'))) -HoldoutRefs @((Sample hold-a hold-group-a (MakeHash '5')),(Sample hold-b hold-group-b (MakeHash '6')))
    $p=New-ESABCDAdaptiveLearningPlan -DatasetManifest $m -GeneratorId 'generator.v1' -FixedSeed 'fixed-seed-v1' -MetricDefinitions $metrics -MaxRounds 3 -MaxCandidates 8 -MaxEvaluations 8 -MaxMetricCalls 100 -MaxCases 20 -ConvergenceWindow 2
    return [pscustomobject]@{manifest=$m;plan=$p}
}

Case 'partition-isolation-case-and-hash' {
    $f=New-Fixture; $r=Test-ESABCDDatasetPartitionManifest $f.manifest; Assert-True($r.status-eq'passed') 'partition manifest failed'; $e=@(Test-ESJsonSchemaValue -SchemaPath $schemaPath -Value $f.manifest); Assert-True($e.Count-eq0)($e-join';')
}
Case 'partition-leakage-is-rejected' {
    try { New-ESABCDDatasetPartitionManifest -DatasetId bad -TrainRefs @((Sample same g1 (MakeHash '1'))) -ValidationRefs @((Sample same g2 (MakeHash '2'))) -HoldoutRefs @((Sample h g3 (MakeHash '3'))); throw 'case overlap accepted' } catch { Assert-True($_.Exception.Message-like'*LEAKAGE*') 'wrong partition leakage rejection' }
}
Case 'candidate-lineage-and-train-only' {
    $f=New-Fixture; $c1=New-ESABCDPolicyCandidate -Plan $f.plan -RoundNo 1 -CandidateNo 1 -BasePolicyId base -BasePolicyHash (MakeHash 'a') -MutationKind threshold -MutationHash (MakeHash 'b'); Assert-True((Test-ESABCDPolicyCandidate $f.plan $c1 @()).status-eq'passed') 'root candidate invalid'; $c2=New-ESABCDPolicyCandidate -Plan $f.plan -RoundNo 2 -CandidateNo 2 -BasePolicyId base -BasePolicyHash (MakeHash 'a') -ParentCandidateRef ([pscustomobject]@{candidateId=$c1.candidateId;candidateHash=$c1.candidateHash;roundNo=1}) -MutationKind route-policy -MutationHash (MakeHash 'c'); Assert-True((Test-ESABCDPolicyCandidate $f.plan $c2 @($c1)).status-eq'passed') 'child lineage invalid'; Assert-True($c1.promotion.promotionAllowed-eq$false) 'candidate promotion enabled'
}
Case 'orphan-lineage-and-promotion-tamper' {
    $f=New-Fixture; try { New-ESABCDPolicyCandidate -Plan $f.plan -RoundNo 2 -CandidateNo 1 -BasePolicyId base -BasePolicyHash (MakeHash 'a') -MutationKind threshold -MutationHash (MakeHash 'b')|Out-Null;throw'orphan accepted' }catch{Assert-True($_.Exception.Message-like'*PARENT_REQUIRED*')'orphan lineage not rejected'}; $c=New-ESABCDPolicyCandidate -Plan $f.plan -RoundNo 1 -CandidateNo 1 -BasePolicyId base -BasePolicyHash (MakeHash 'a') -MutationKind threshold -MutationHash (MakeHash 'b');$c.promotion.promotionAllowed=$true;Assert-True((Test-ESABCDPolicyCandidate $f.plan $c @()).issues -contains 'POLICY_CANDIDATE_HASH_MISMATCH')'candidate tamper not detected'
}
function Eval($f,$c,[double]$accuracy,[double]$latency,[string]$e='evaluator.v1',[string]$a='auditor.v1') { New-ESABCDPolicyEvaluation -Plan $f.plan -Candidate $c -BaselineValidationMetrics @([pscustomobject]@{name='accuracy';value=.8},[pscustomobject]@{name='latency';value=10}) -CandidateValidationMetrics @([pscustomobject]@{name='accuracy';value=$accuracy},[pscustomobject]@{name='latency';value=$latency}) -ValidationCaseCount 2 -EvaluatorId $e -AuditorId $a -AuthorizationProof proof }
Case 'per-objective-no-regression-and-pareto' {
    $f=New-Fixture;$c1=New-ESABCDPolicyCandidate -Plan $f.plan -RoundNo 1 -CandidateNo 1 -BasePolicyId base -BasePolicyHash (MakeHash 'a') -MutationKind threshold -MutationHash (MakeHash 'b');$c2=New-ESABCDPolicyCandidate -Plan $f.plan -RoundNo 1 -CandidateNo 2 -BasePolicyId base -BasePolicyHash (MakeHash 'a') -MutationKind threshold -MutationHash (MakeHash 'c');$c3=New-ESABCDPolicyCandidate -Plan $f.plan -RoundNo 1 -CandidateNo 3 -BasePolicyId base -BasePolicyHash (MakeHash 'a') -MutationKind threshold -MutationHash (MakeHash 'd');$e1=Eval $f $c1 .82 10;$e2=Eval $f $c2 .85 12;$e3=Eval $f $c3 .81 8;$s=Invoke-ESABCDAdaptiveLearningSelection -Plan $f.plan -Candidates @($c1,$c2,$c3) -Evaluations @($e1,$e2,$e3);Assert-True(@($s.paretoFrontier|Where-Object { [string]$_.candidateId -eq [string]$c1.candidateId }).Count -eq 1)'c1 missing frontier';Assert-True(@($s.paretoFrontier|Where-Object { [string]$_.candidateId -eq [string]$c2.candidateId }).Count -eq 0)'regressed c2 selected';Assert-True(@($s.paretoFrontier|Where-Object { [string]$_.candidateId -eq [string]$c3.candidateId }).Count -eq 1)'c3 missing pareto frontier'
}
Case 'generator-evaluator-auditor-separation' {$f=New-Fixture;$c=New-ESABCDPolicyCandidate -Plan $f.plan -RoundNo 1 -CandidateNo 1 -BasePolicyId base -BasePolicyHash (MakeHash 'a') -MutationKind threshold -MutationHash (MakeHash 'b');try{Eval $f $c .82 10 'generator.v1' 'auditor.v1'|Out-Null;throw'generator evaluator accepted'}catch{Assert-True($_.Exception.Message-like'*INDEPENDENCE*')'identity separation bypassed'}}
Case 'holdout-final-gate-only' {$f=New-Fixture;$c=New-ESABCDPolicyCandidate -Plan $f.plan -RoundNo 1 -CandidateNo 1 -BasePolicyId base -BasePolicyHash (MakeHash 'a') -MutationKind threshold -MutationHash (MakeHash 'b');$e=Eval $f $c .82 10;$s=Invoke-ESABCDAdaptiveLearningSelection -Plan $f.plan -Candidates @($c) -Evaluations @($e);$g=New-ESABCDHoldoutGate -Plan $f.plan -SelectedCandidate $c -SelectionReceipt $s -BaselineHoldoutMetrics @([pscustomobject]@{name='accuracy';value=.8},[pscustomobject]@{name='latency';value=10}) -CandidateHoldoutMetrics @([pscustomobject]@{name='accuracy';value=.81},[pscustomobject]@{name='latency';value=10}) -HoldoutCaseCount 2 -EvaluatorId holdout-evaluator -AuditorId holdout-auditor -AuthorizationProof proof;Assert-True($g.decision-eq'await-explicit-review')'holdout gate failed';try{New-ESABCDHoldoutGate -Plan $f.plan -SelectedCandidate $c -SelectionReceipt $s -BaselineHoldoutMetrics @([pscustomobject]@{name='accuracy';value=.8},[pscustomobject]@{name='latency';value=10}) -CandidateHoldoutMetrics @([pscustomobject]@{name='accuracy';value=.81},[pscustomobject]@{name='latency';value=10}) -HoldoutCaseCount 2 -EvaluatorId holdout-evaluator -AuditorId holdout-auditor -AuthorizationProof proof|Out-Null;throw'repeated holdout accepted'}catch{Assert-True($_.Exception.Message-like'*ALREADY_CONSUMED*')'holdout repeat not rejected'}}
Case 'budget-convergence-and-no-promotion' {$f=New-Fixture;$c=New-ESABCDPolicyCandidate -Plan $f.plan -RoundNo 1 -CandidateNo 1 -BasePolicyId base -BasePolicyHash (MakeHash 'a') -MutationKind threshold -MutationHash (MakeHash 'b');$e=Eval $f $c .82 10;$s=Invoke-ESABCDAdaptiveLearningSelection -Plan $f.plan -Candidates @($c) -Evaluations @($e);Assert-True($s.promotion.promotionAllowed-eq$false)'selection promoted candidate';Assert-True($s.convergence.ownsTaskCompletion-eq$false)'convergence owns completion';try{Invoke-ESABCDAdaptiveLearningSelection -Plan $f.plan -Candidates (@(1..9)|ForEach-Object{$c}) -Evaluations @($e)|Out-Null;throw'candidate budget bypassed'}catch{Assert-True($_.Exception.Message-like'*BUDGET*')'budget failure absent'}}
Case 'receipt-hash-tamper-fails' {$f=New-Fixture;$c=New-ESABCDPolicyCandidate -Plan $f.plan -RoundNo 1 -CandidateNo 1 -BasePolicyId base -BasePolicyHash (MakeHash 'a') -MutationKind threshold -MutationHash (MakeHash 'b');$e=Eval $f $c .82 10;$s=Invoke-ESABCDAdaptiveLearningSelection -Plan $f.plan -Candidates @($c) -Evaluations @($e);$s.receiptHash=MakeHash 'f';$r=Test-ESABCDAdaptiveLearningReceipt -Receipt $s -Plan $f.plan;Assert-True($r.status-eq'failed' -and $r.issues -contains 'ADAPTIVE_RECEIPT_HASH_MISMATCH')'receipt tamper accepted'}
$failed=@($results|Where-Object { $_.status -eq 'failed' });$refs=@('ES/Automation/ABCD/ESABCDAdaptiveLearning.psm1','ES/Automation/ABCD/Test-ESABCDAdaptiveLearning.ps1','ES/Automation/Contracts/es-abcd-adaptive-learning-v1.schema.json');$refHashes=[ordered]@{};foreach($ref in $refs){$refHashes[$ref]=(Get-FileHash (Join-Path $root $ref) -Algorithm SHA256).Hash.ToLowerInvariant()};$evContract=Join-Path $root 'ES/Automation/Contracts/es-skill-evidence-receipt-v1.schema.json';$report=[ordered]@{schemaVersion=1;validator='Test-ESABCDAdaptiveLearning';contractId='es://automation/contracts/abcd/adaptive-learning/v1';status=if($failed.Count){'failed'}else{'passed'};caseCount=$results.Count;passedCount=@($results|Where-Object { $_.status -eq 'passed' }).Count;failedCount=$failed.Count;cases=@($results);staticStatus=if($failed.Count){'static-failed'}else{'static-passed'};runtimeStatus='runtime-not-run';evidenceLevel='S1';capturedUtc=[DateTime]::UtcNow.ToString('o');authorizationKind='read-only';planHash=Get-ESABCDAdaptiveHash([ordered]@{validator='Test-ESABCDAdaptiveLearning';cases=@($results);sourceRefHashes=$refHashes});evidenceContractId='es.skill-evidence-receipt';evidenceContractHash=(Get-FileHash $evContract -Algorithm SHA256).Hash.ToLowerInvariant();skillName='es-agent-mechanism-replication';case='adaptive-learning';receiptPath=$ReportPath.Replace('\','/');sourceRefs=$refs;sourceRefHashes=$refHashes;toolId='es-abcd-adaptive-learning-validator';unityVersion='not-run';claimsNotProven=@('Unity/Worker/host Runtime','cross-process CAS','external authority','automatic Knowledge promotion')};$full=Join-Path $root $ReportPath;New-Item -ItemType Directory -Force (Split-Path $full)|Out-Null;[IO.File]::WriteAllText($full,($report|ConvertTo-Json -Depth 40),[Text.UTF8Encoding]::new($false));$report|ConvertTo-Json -Depth 40;if($failed.Count){exit 1}
