[CmdletBinding()]
param([string]$ProjectRoot=(Resolve-Path (Join-Path $PSScriptRoot '..\..\..')).Path,[string]$ReportPath='ES/Output/StaticReplay/es-abcd-audit-gate.json')
$ErrorActionPreference='Stop'; $root=(Resolve-Path -LiteralPath $ProjectRoot).Path
Import-Module (Join-Path $root 'ES/Automation/ABCD/ESABCDAuditGate.psm1') -Force
$results=[Collections.Generic.List[object]]::new()
function Case([string]$Name,[scriptblock]$Body){try{&$Body;[void]$results.Add([pscustomobject]@{case=$Name;status='passed';finding=$null})}catch{[void]$results.Add([pscustomobject]@{case=$Name;status='failed';finding=$_.Exception.Message})}}
$head='a'*40
Case 'six-source-registry-is-explicit' { $r=Get-Content -LiteralPath (Join-Path $root 'ES/Automation/Contracts/es-abcd-source-mechanism-registry-v1.json') -Raw -Encoding UTF8|ConvertFrom-Json; if((Test-ESABCDAuditSourceRegistry $r).status -ne 'passed'){throw 'source registry incomplete'}; if(@($r.sources|Where-Object {$_.revision -match 'UNFROZEN' -or $_.license -match 'UNFROZEN'}).Count -ne 0){throw 'source freeze is incomplete'}; if(@($r.sources).Count -ne 6){throw 'source registry count invalid'} }
Case 'scenario-selects-strict-profile' { $p=New-ESABCDAuditPlan -Scenario RuntimeChange -SubjectId module-x -CurrentHead $head -AuthorizationRef user:current -SourceRefs @('Assets/module.cs') -AllowedWriteScopes @('Assets/module.cs') -RequestedCapabilities @('state-transition-guard'); if($p.minimumEvidenceLevel -ne 'S4' -or @($p.requiredNegativeCases).Count -lt 3){throw 'runtime profile is not strict'}; if((Test-ESABCDAuditPlan $p).status -ne 'passed'){throw 'plan rejected'} }
Case 'authority-cannot-be-self-granted' { $p=New-ESABCDAuditPlan -Scenario DesignChange -SubjectId module-x -CurrentHead $head -AuthorizationRef user:current; $g=New-ESABCDAuthorityGraph -Plan $p -Authorities @('project:AGENTS','source:module','evidence:receipt','user:current'); if((Test-ESABCDAuthorityGraph $g).status -ne 'passed'){throw 'authority graph invalid'}; if(@($g.nodes|Where-Object {$_.kind -eq 'unclassified'}).Count){throw 'unclassified authority accepted'} }
Case 'missing-proof-blocks-final-gate' { $p=New-ESABCDAuditPlan -Scenario DesignChange -SubjectId module-x -CurrentHead $head -AuthorizationRef user:current; $g=New-ESABCDAuthorityGraph -Plan $p -Authorities @('project:AGENTS','source:module','evidence:receipt','user:current'); $d=[pscustomobject]@{complete=$false;distinctAssumptions=1;rollbackVerified=$false};$a=[pscustomobject]@{status='failed';independent=$false};$v=[pscustomobject]@{status='review';requiredCasesMissing=@('forged-receipt');stale=$true};$r=New-ESABCDFinalGateReceipt -Plan $p -AuthorityGraph $g -Divergence $d -Audit $a -Verification $v -ObservedHead $head -EvidenceLevel S1;if($r.status -ne 'blocked' -or $r.decisionStatus -ne 'Blocked'){throw 'final gate accepted incomplete evidence'} }
Case 'complete-proof-can-accept' { $p=New-ESABCDAuditPlan -Scenario DesignChange -SubjectId module-x -CurrentHead $head -AuthorizationRef user:current; $g=New-ESABCDAuthorityGraph -Plan $p -Authorities @('project:AGENTS','source:module','evidence:receipt','user:current');$d=[pscustomobject]@{complete=$true;distinctAssumptions=3;rollbackVerified=$true};$a=[pscustomobject]@{status='passed';independent=$true};$v=[pscustomobject]@{status='passed';requiredCasesMissing=@();stale=$false};$coveragePath=Join-Path $root 'ES/Output/StaticReplay/es-abcd-framework-parity.json';$coverageReport=Get-Content -LiteralPath $coveragePath -Raw -Encoding UTF8|ConvertFrom-Json;$r=New-ESABCDFinalGateReceipt -Plan $p -AuthorityGraph $g -Divergence $d -Audit $a -Verification $v -FrameworkCoverage $coverageReport.coverage -ObservedHead $head -EvidenceLevel S1;if($r.status -ne 'accepted' -or $r.decisionStatus -ne 'Accepted'){throw 'complete proof did not accept'} }
Case 'coverage-below-threshold-blocks' { $p=New-ESABCDAuditPlan -Scenario DesignChange -SubjectId module-x -CurrentHead $head -AuthorizationRef user:current; $g=New-ESABCDAuthorityGraph -Plan $p -Authorities @('project:AGENTS','source:module','evidence:receipt','user:current');$d=[pscustomobject]@{complete=$true;distinctAssumptions=3;rollbackVerified=$true};$a=[pscustomobject]@{status='passed';independent=$true};$v=[pscustomobject]@{status='passed';requiredCasesMissing=@();stale=$false};$c=[pscustomobject]@{allMeetThreshold=$false};$r=New-ESABCDFinalGateReceipt -Plan $p -AuthorityGraph $g -Divergence $d -Audit $a -Verification $v -FrameworkCoverage $c -ObservedHead $head -EvidenceLevel S1;if($r.status -ne 'blocked' -or $r.issues -notcontains 'FRAMEWORK_COVERAGE_BELOW_THRESHOLD'){throw 'coverage below threshold was accepted'} }
$failed=@($results|Where-Object status -eq 'failed');$sourceRefs=@('ES/Automation/ABCD/ESABCDAuditGate.psm1','ES/Automation/ABCD/Test-ESABCDAuditGate.ps1','ES/Automation/Contracts/es-abcd-audit-plan-v1.schema.json','ES/Automation/Contracts/es-abcd-final-gate-v1.schema.json','ES/Automation/Contracts/es-abcd-source-mechanism-registry-v1.json');$hashes=[ordered]@{};foreach($s in $sourceRefs){$hashes[$s]=(Get-FileHash -LiteralPath (Join-Path $root $s) -Algorithm SHA256).Hash.ToLowerInvariant()};$report=[ordered]@{schemaVersion=1;validator='Test-ESABCDAuditGate';status=if($failed.Count){'failed'}else{'passed'};staticStatus=if($failed.Count){'static-failed'}else{'static-passed'};runtimeStatus='runtime-not-run';caseCount=$results.Count;passedCount=($results.Count-$failed.Count);failedCount=$failed.Count;cases=@($results);evidenceLevel='S1';capturedUtc=[DateTime]::UtcNow.ToString('o');authorizationKind='read-only';planHash=(Get-ESABCDAuditHash ([ordered]@{validator='Test-ESABCDAuditGate';cases=@($results);sourceRefHashes=$hashes}));evidenceContractId='es.skill-evidence-receipt';evidenceContractHash=(Get-FileHash -LiteralPath (Join-Path $root 'ES/Automation/Contracts/es-skill-evidence-receipt-v1.schema.json') -Algorithm SHA256).Hash.ToLowerInvariant();skillName='es-agent-mechanism-replication';case='audit-gate';toolId='es-abcd-audit-gate-validator';receiptPath=$ReportPath.Replace('\','/');sourceRefs=$sourceRefs;sourceRefHashes=$hashes;unityVersion='not-run';claimsNotProven=@('Unity/Worker/host Runtime','external certification','release readiness')};$full=if([IO.Path]::IsPathRooted($ReportPath)){$ReportPath}else{Join-Path $root $ReportPath};New-Item -ItemType Directory -Force -Path (Split-Path -Parent $full)|Out-Null;[IO.File]::WriteAllText($full,($report|ConvertTo-Json -Depth 20),[Text.UTF8Encoding]::new($false));$report|ConvertTo-Json -Depth 20;if($failed.Count){exit 1}
