[CmdletBinding()]
param([string]$ProjectRoot,[string]$ReportPath='ES/Output/StaticReplay/es-abcd-certification.json')
$ErrorActionPreference = 'Stop'
if ([string]::IsNullOrWhiteSpace($ProjectRoot)) { $scriptDirectory = Split-Path -Parent $PSCommandPath; $ProjectRoot = (Resolve-Path (Join-Path $scriptDirectory '..\..\..')).Path }
$root = (Resolve-Path -LiteralPath $ProjectRoot).Path
Import-Module (Join-Path $root 'ES/Automation/ABCD/ESABCDCertification.psm1') -Force
$schema = Join-Path $root 'ES/Automation/Contracts/es-abcd-certification-assessment-v1.schema.json'
Import-Module (Join-Path $root 'ES/Automation/Contracts/ESJsonSchemaLite.psm1') -Force
$cases = [Collections.Generic.List[object]]::new(); function Case([string]$Name,[scriptblock]$Body){try{&$Body;[void]$cases.Add([pscustomobject]@{case=$Name;status='passed';finding=$null})}catch{[void]$cases.Add([pscustomobject]@{case=$Name;status='failed';finding=$_.Exception.Message})}}
function Hash([string]$Path){(Get-FileHash -LiteralPath (Join-Path $root $Path) -Algorithm SHA256).Hash.ToLowerInvariant()}
$snapshot=Get-ESABCDCurrentGitSnapshot $root
if($null -eq $snapshot){throw 'Current Git snapshot is required for certification tests.'}
function ReceiptRef([string]$Path,[string]$BucketStatus){
    $full=Join-Path $root $Path
    $receipt=Get-Content -LiteralPath $full -Raw -Encoding UTF8 | ConvertFrom-Json
    [pscustomobject][ordered]@{
        path=$Path.Replace('\','/'); sha256=(Hash $Path); status=$BucketStatus; capturedUtc=[string]$receipt.capturedUtc
        receiptPath=[string]$receipt.receiptPath; skillName=[string]$receipt.skillName; case=[string]$receipt.case
        evidenceLevel=[string]$receipt.evidenceLevel; evidenceContractId=[string]$receipt.evidenceContractId; evidenceContractHash=[string]$receipt.evidenceContractHash
    }
}
$sourcePath='ES/Automation/ABCD/ESABCDCertification.psm1'; $sourceRef=[pscustomobject][ordered]@{path=$sourcePath;sha256=(Hash $sourcePath);role='implementation'}
$staticPath='ES/Output/StaticReplay/es-abcd-orchestration.json'; $staticRef=ReceiptRef $staticPath 'static-passed'
$runtimeRef=ReceiptRef $staticPath 'runtime-passed'; $releaseRef=ReceiptRef $staticPath 'release-passed'
$evidence=[pscustomobject][ordered]@{static=@($staticRef);runtime=@();release=@()}; $casesRequired=@([string]$staticRef.case); $allCompleted=@($casesRequired)
function SignedAssessment([string]$SignedAtUtc) {
    $a=New-ESABCDCertificationAssessment -Subject ([ordered]@{kind='abcd-system';id='abcd'}) -Profile DesignReview -Branch $snapshot.branch -Head $snapshot.head -WorktreeHash $snapshot.worktreeHash -SourceRefs @($sourceRef) -Evidence $evidence -RequiredCaseIds $casesRequired -CompletedCaseIds $allCompleted -VerifierId 'auditor' -VerifierDefinitionHash ('c'*64) -VerifierRole external-certification-body -IndependenceProof 'separate-process' -IssuerRef 'esframework-trust-root-v1' -SignatureStatus verified -SignatureVerificationMethod external-detached-signature -SignatureRef '.gitignore' -SignatureHash (Hash '.gitignore') -SignedAtUtc $SignedAtUtc
    $a.verifier.signedPayloadHash=Get-ESABCDCertificationSignedPayloadHash $a
    $a.assessmentHash=Get-ESABCDCertificationHash (Get-ESABCDCertificationHashInput $a)
    return $a
}
Case 'design-review-accepts-static-only' { $a=New-ESABCDCertificationAssessment -Subject ([ordered]@{kind='abcd-system';id='abcd'}) -Profile DesignReview -Branch $snapshot.branch -Head $snapshot.head -WorktreeHash $snapshot.worktreeHash -SourceRefs @($sourceRef) -Evidence $evidence -RequiredCaseIds $casesRequired -CompletedCaseIds $allCompleted -VerifierId 'owner' -VerifierDefinitionHash ('c'*64) -VerifierRole project-acceptance-owner -IndependenceProof 'owner-scope'; $r=Test-ESABCDCertificationAssessment $a $root; if($r.eligibleForCertification){throw 'Design review incorrectly issued authority.'} }
Case 'runtime-requires-runtime-evidence' { $a=New-ESABCDCertificationAssessment -Subject ([ordered]@{kind='abcd-system';id='abcd'}) -Profile RuntimeAcceptance -Branch $snapshot.branch -Head $snapshot.head -WorktreeHash $snapshot.worktreeHash -SourceRefs @($sourceRef) -Evidence $evidence -RequiredCaseIds $casesRequired -CompletedCaseIds $allCompleted -VerifierId 'owner' -VerifierDefinitionHash ('c'*64) -VerifierRole project-acceptance-owner -IndependenceProof 'owner-scope'; $r=Test-ESABCDCertificationAssessment $a $root; if($r.issues -notcontains 'RUNTIME_EVIDENCE_REQUIRED'){throw 'Runtime acceptance bypassed runtime gate.'} }
Case 'required-case-must-bind-evidence' { $a=New-ESABCDCertificationAssessment -Subject ([ordered]@{kind='abcd-system';id='abcd'}) -Profile DesignReview -Branch $snapshot.branch -Head $snapshot.head -WorktreeHash $snapshot.worktreeHash -SourceRefs @($sourceRef) -Evidence $evidence -RequiredCaseIds @('unrepresented-case') -CompletedCaseIds @('unrepresented-case') -VerifierId 'owner' -VerifierDefinitionHash ('c'*64) -VerifierRole project-acceptance-owner -IndependenceProof 'owner-scope'; $r=Test-ESABCDCertificationAssessment $a $root; if($r.issues -notcontains 'CASE_EVIDENCE_MISSING:unrepresented-case'){throw 'Required case was accepted without matching evidence.'} }
Case 'cryptographic-signature-required' { $a=SignedAssessment ([DateTime]::UtcNow.ToString('o')); $r=Test-ESABCDCertificationAssessment $a $root -RequireIndependent; if($r.issues -notcontains 'CRYPTOGRAPHIC_SIGNATURE_VERIFICATION_REQUIRED' -or $r.eligibleForCertification){throw 'Metadata-only detached signature was accepted.'} }
Case 'signature-time-bounds-enforced' { $future=SignedAssessment ([DateTime]::UtcNow.AddMinutes(10).ToString('o')); $stale=SignedAssessment ([DateTime]::UtcNow.AddHours(-169).ToString('o')); $rf=Test-ESABCDCertificationAssessment $future $root -RequireIndependent; $rs=Test-ESABCDCertificationAssessment $stale $root -RequireIndependent; if($rf.issues -notcontains 'SIGNATURE_FROM_FUTURE' -or $rs.issues -notcontains 'SIGNATURE_STALE'){throw 'Signature timestamp bounds were not enforced.'} }
Case 'static-receipt-cannot-masquerade-runtime-release' { $fakeRuntime=[pscustomobject][ordered]@{static=@($staticRef);runtime=@($runtimeRef);release=@($releaseRef)}; $a=New-ESABCDCertificationAssessment -Subject ([ordered]@{kind='abcd-system';id='abcd'}) -Profile ReleaseAcceptance -Branch $snapshot.branch -Head $snapshot.head -WorktreeHash $snapshot.worktreeHash -SourceRefs @($sourceRef) -Evidence $fakeRuntime -RequiredCaseIds $casesRequired -CompletedCaseIds $allCompleted -VerifierId 'owner' -VerifierDefinitionHash ('c'*64) -VerifierRole project-acceptance-owner -IndependenceProof 'owner-scope'; $r=Test-ESABCDCertificationAssessment $a $root; if(($r.issues -notcontains "EVIDENCE_AXIS_STATUS_INVALID:runtime:$staticPath") -or ($r.issues -notcontains "EVIDENCE_AXIS_STATUS_INVALID:release:$staticPath")){throw 'Static receipt masqueraded as runtime/release evidence.'} }
Case 'fake-head-and-worktree-rejected' { $a=New-ESABCDCertificationAssessment -Subject ([ordered]@{kind='abcd-system';id='abcd'}) -Profile DesignReview -Branch '__fake__' -Head ('a'*40) -WorktreeHash ('b'*64) -SourceRefs @($sourceRef) -Evidence $evidence -RequiredCaseIds $casesRequired -CompletedCaseIds $allCompleted -VerifierId 'owner' -VerifierDefinitionHash ('c'*64) -VerifierRole project-acceptance-owner -IndependenceProof 'owner-scope'; $r=Test-ESABCDCertificationAssessment $a $root; if(($r.issues -notcontains 'SOURCE_SNAPSHOT_HEAD_DRIFT') -or ($r.issues -notcontains 'SOURCE_SNAPSHOT_WORKTREE_DRIFT')){throw 'Fake HEAD/worktree snapshot was accepted.'} }
Case 'signature-cannot-cover-source-file' { $a=New-ESABCDCertificationAssessment -Subject ([ordered]@{kind='abcd-system';id='abcd'}) -Profile DesignReview -Branch $snapshot.branch -Head $snapshot.head -WorktreeHash $snapshot.worktreeHash -SourceRefs @($sourceRef) -Evidence $evidence -RequiredCaseIds $casesRequired -CompletedCaseIds $allCompleted -VerifierId 'auditor' -VerifierDefinitionHash ('c'*64) -VerifierRole independent-auditor -IndependenceProof 'separate-process' -IssuerRef 'esframework-trust-root-v1' -SignedPayloadHash ('d'*64) -SignatureStatus verified -SignatureVerificationMethod external-detached-signature -SignatureRef $sourcePath -SignatureHash (Hash $sourcePath) -SignedAtUtc ([DateTime]::UtcNow.ToString('o')); $r=Test-ESABCDCertificationAssessment $a $root; if(($r.issues -notcontains 'SIGNATURE_REF_OVERLAPS_SOURCE') -or ($r.issues -notcontains 'SIGNATURE_REF_NOT_SIGNATURE_ARTIFACT') -or ($r.issues -notcontains 'SIGNED_PAYLOAD_COVERAGE_MISMATCH')){throw 'Source file was accepted as signed assessment.'} }
Case 'signature-cannot-cover-evidence-receipt' { $a=New-ESABCDCertificationAssessment -Subject ([ordered]@{kind='abcd-system';id='abcd'}) -Profile DesignReview -Branch $snapshot.branch -Head $snapshot.head -WorktreeHash $snapshot.worktreeHash -SourceRefs @($sourceRef) -Evidence $evidence -RequiredCaseIds $casesRequired -CompletedCaseIds $allCompleted -VerifierId 'auditor' -VerifierDefinitionHash ('c'*64) -VerifierRole independent-auditor -IndependenceProof 'separate-process' -IssuerRef 'esframework-trust-root-v1' -SignedPayloadHash ('d'*64) -SignatureStatus verified -SignatureVerificationMethod external-detached-signature -SignatureRef $staticPath -SignatureHash (Hash $staticPath) -SignedAtUtc ([DateTime]::UtcNow.ToString('o')); $r=Test-ESABCDCertificationAssessment $a $root; if(($r.issues -notcontains 'SIGNATURE_REF_OVERLAPS_EVIDENCE') -or ($r.issues -notcontains 'SIGNATURE_REF_NOT_SIGNATURE_ARTIFACT')){throw 'Evidence receipt was accepted as its own signature artifact.'} }
Case 'independent-signature-required' { $e=[pscustomobject][ordered]@{static=@($staticRef);runtime=@($runtimeRef);release=@()}; $a=New-ESABCDCertificationAssessment -Subject ([ordered]@{kind='abcd-system';id='abcd'}) -Profile RuntimeAcceptance -Branch $snapshot.branch -Head $snapshot.head -WorktreeHash $snapshot.worktreeHash -SourceRefs @($sourceRef) -Evidence $e -RequiredCaseIds $casesRequired -CompletedCaseIds $allCompleted -VerifierId 'owner' -VerifierDefinitionHash ('c'*64) -VerifierRole project-acceptance-owner -IndependenceProof 'owner-scope'; $r=Test-ESABCDCertificationAssessment $a $root -RequireIndependent; if($r.issues -notcontains 'INDEPENDENT_VERIFIER_REQUIRED'){throw 'Owner was accepted as independent verifier.'} }
Case 'source-drift-rejected' { $a=New-ESABCDCertificationAssessment -Subject ([ordered]@{kind='abcd-system';id='abcd'}) -Profile DesignReview -Branch $snapshot.branch -Head $snapshot.head -WorktreeHash $snapshot.worktreeHash -SourceRefs @([pscustomobject][ordered]@{path=$sourcePath;sha256=('0'*64);role='implementation'}) -Evidence $evidence -RequiredCaseIds $casesRequired -CompletedCaseIds $allCompleted -VerifierId 'auditor' -VerifierDefinitionHash ('c'*64) -VerifierRole independent-auditor -IndependenceProof 'separate-process'; $r=Test-ESABCDCertificationAssessment $a $root; if($r.issues -notcontains "SOURCE_DRIFT:$sourcePath"){throw 'Source drift was not rejected.'} }
Case 'certificate-schema-is-strict' { $a=New-ESABCDCertificationAssessment -Subject ([ordered]@{kind='abcd-system';id='abcd'}) -Profile DesignReview -Branch $snapshot.branch -Head $snapshot.head -WorktreeHash $snapshot.worktreeHash -SourceRefs @($sourceRef) -Evidence $evidence -RequiredCaseIds $casesRequired -CompletedCaseIds $allCompleted -VerifierId 'owner' -VerifierDefinitionHash ('c'*64) -VerifierRole project-acceptance-owner -IndependenceProof 'owner-scope'; $errors=@(Test-ESJsonSchemaValue -SchemaPath $schema -Value $a); if($errors.Count -ne 0){throw ($errors -join '; ')} }
$failed=@($cases|Where-Object status -eq 'failed');$sourceRefs=@('ES/Automation/ABCD/ESABCDCertification.psm1','ES/Automation/ABCD/Test-ESABCDCertification.ps1','ES/Automation/Contracts/es-abcd-certification-assessment-v1.schema.json');$sourceHashes=[ordered]@{};foreach($ref in $sourceRefs){$sourceHashes[$ref]=(Get-FileHash -LiteralPath (Join-Path $root $ref) -Algorithm SHA256).Hash.ToLowerInvariant()};$evidenceContractPath=Join-Path $root 'ES/Automation/Contracts/es-skill-evidence-receipt-v1.schema.json';$evidenceContractHash=(Get-FileHash -LiteralPath $evidenceContractPath -Algorithm SHA256).Hash.ToLowerInvariant();$planHash=Get-ESABCDCertificationHash ([ordered]@{validator='Test-ESABCDCertification';sourceRefHashes=$sourceHashes;cases=@($cases)});$report=[ordered]@{schemaVersion=1;validator='Test-ESABCDCertification';skillName='es-agent-mechanism-replication';case='certification-assessment';status=if($failed.Count){'failed'}else{'passed'};caseCount=$cases.Count;passedCount=($cases.Count-$failed.Count);failedCount=$failed.Count;cases=@($cases);staticStatus=if($failed.Count){'static-failed'}else{'static-passed'};runtimeStatus='runtime-not-run';evidenceLevel='S1';capturedUtc=[DateTime]::UtcNow.ToString('o');authorizationKind='read-only';planHash=$planHash;evidenceContractId='es.skill-evidence-receipt';evidenceContractHash=$evidenceContractHash;toolId='es-abcd-certification-validator';unityVersion='not-run';receiptPath=$ReportPath.Replace('\','/');sourceRefs=$sourceRefs;sourceRefHashes=$sourceHashes;claimsNotProven=@('independent external certification','Unity/Worker/host Runtime','ReleaseAcceptance')};$full=Join-Path $root $ReportPath;New-Item -ItemType Directory -Force -Path (Split-Path $full)|Out-Null;[IO.File]::WriteAllText($full,($report|ConvertTo-Json -Depth 20),[Text.UTF8Encoding]::new($false));$report|ConvertTo-Json -Depth 20;if($failed.Count){exit 1}
