[CmdletBinding()]
param([string]$ProjectRoot=(Resolve-Path (Join-Path $PSScriptRoot '..\..\..')).Path,[string]$ReportPath='ES/Output/StaticReplay/es-abcd-dynamic-controller.json')
$ErrorActionPreference='Stop';$root=(Resolve-Path -LiteralPath $ProjectRoot).Path;Import-Module (Join-Path $root 'ES/Automation/ABCD/ESABCDDynamicController.psm1') -Force;Import-Module (Join-Path $root 'ES/Automation/ABCD/ESABCDOrchestrator.psm1') -Force
$z='0'*64;$h='1'*64;$v='2'*64;$auditProof='3'*64;$receipt='4'*64;$results=[Collections.Generic.List[object]]::new();function Case([string]$n,[scriptblock]$b){try{&$b;[void]$results.Add([pscustomobject]@{case=$n;status='passed';finding=$null})}catch{[void]$results.Add([pscustomobject]@{case=$n;status='failed';finding=$_.Exception.Message})}}
function New-Store([string]$id,[int]$maxRounds=3){New-ESABCDOrchestrationStore -TaskId $id -TaskBindingId ($id+'.binding') -TaskBindingHash $h -AuthorizationRef 'auth.current' -RoutePlanHash $z -SourceScopeHash $z -MaxRounds $maxRounds -AttemptsPerRound 2}
function Proposals{ @([pscustomobject]@{branchId='branch-a';parentBranchId=$null;snapshotHash=$z;changedAssumption='a';verificationPredicate='verify-a'},[pscustomobject]@{branchId='branch-b';parentBranchId=$null;snapshotHash=$h;changedAssumption='b';verificationPredicate='verify-b'}) }
function Audits{ @([pscustomobject]@{branchId='branch-a';auditorRef='auditor';verdict='fail';evidenceRefs=@('e-a');verifierRef='verifier';authorizationProof=$auditProof;verifierDefinitionHash=$v},[pscustomobject]@{branchId='branch-b';auditorRef='auditor';verdict='pass';evidenceRefs=@('e-b');verifierRef='verifier';authorizationProof=$auditProof;verifierDefinitionHash=$v}) }
Case 'diverge-audit-select-correct-verify-advance'{$s=New-Store 'dynamic-positive';$r=Invoke-ESABCDDynamicIteration -Store $s -CandidateProposals (Proposals) -AuditProposals (Audits) -SelectedBranchId branch-b -FindingReceiptRef finding -FailureClass source -Decision retry -AttemptNo 1 -VerificationStatus passed -VerificationReceiptRef receipt-1 -VerificationReceiptHash $receipt;if (($r.status -ne 'advanced') -or (-not $r.advanced) -or (-not $r.eligibility.eligible)){throw 'dynamic iteration did not advance'}}
Case 'failed-audit-cannot-be-selected'{$s=New-Store 'dynamic-audit-fail';try{Invoke-ESABCDDynamicIteration -Store $s -CandidateProposals (Proposals) -AuditProposals (Audits) -SelectedBranchId branch-a -FindingReceiptRef finding -FailureClass route -Decision replan -AttemptNo 1 -VerificationStatus review|Out-Null;throw'failed audit selected'}catch{if($_.Exception.Message-notmatch'DYNAMIC_SELECTED_BRANCH_NOT_AUDITED_PASS|AUDIT_PASS_REQUIRED'){throw}}}
Case 'failed-verification-stays-review'{$s=New-Store 'dynamic-review';$r=Invoke-ESABCDDynamicIteration -Store $s -CandidateProposals (Proposals) -AuditProposals (Audits) -SelectedBranchId branch-b -FindingReceiptRef finding -FailureClass evidence -Decision replan -AttemptNo 1 -VerificationStatus failed;if($r.status-ne'review'-or$r.advanced){throw'failed verification advanced'}}
Case 'round-budget-is-enforced'{$s=New-Store 'dynamic-budget' 1;$r=Invoke-ESABCDDynamicIteration -Store $s -CandidateProposals (Proposals) -AuditProposals (Audits) -SelectedBranchId branch-b -FindingReceiptRef finding -FailureClass source -Decision retry -AttemptNo 1 -VerificationStatus passed -VerificationReceiptRef receipt-1 -VerificationReceiptHash $receipt;if($r.status-ne'advanced'){throw'first bounded round failed'};try{Invoke-ESABCDDynamicIteration -Store $s -CandidateProposals (Proposals) -AuditProposals (Audits) -SelectedBranchId branch-b -FindingReceiptRef finding2 -FailureClass source -Decision retry -AttemptNo 1 -VerificationStatus passed -VerificationReceiptRef receipt-2 -VerificationReceiptHash $receipt|Out-Null;throw'budget bypassed'}catch{if($_.Exception.Message-notlike'*ROUND_BUDGET_EXHAUSTED*'){throw}}}
Case 'candidate-audit-branch-set-mismatch-is-rejected'{$s=New-Store 'dynamic-set-mismatch';$badAudits=@([pscustomobject]@{branchId='branch-a';auditorRef='auditor';verdict='fail';evidenceRefs=@('e-a');verifierRef='verifier';authorizationProof=$auditProof;verifierDefinitionHash=$v},[pscustomobject]@{branchId='branch-c';auditorRef='auditor';verdict='pass';evidenceRefs=@('e-c');verifierRef='verifier';authorizationProof=$auditProof;verifierDefinitionHash=$v});try{Invoke-ESABCDDynamicIteration -Store $s -CandidateProposals (Proposals) -AuditProposals $badAudits -SelectedBranchId branch-a -FindingReceiptRef finding -FailureClass route -Decision replan -AttemptNo 1 -VerificationStatus review|Out-Null;throw'branch-set mismatch accepted'}catch{if($_.Exception.Message-notlike'*DYNAMIC_CANDIDATE_AUDIT_BRANCH_SET_MISMATCH*'){throw}}}
Case 'branch-decision-waits-for-collaborator'{$s=New-Store 'dynamic-branch-wait';$r=Invoke-ESABCDDynamicIteration -Store $s -CandidateProposals (Proposals) -AuditProposals (Audits) -SelectedBranchId branch-b -FindingReceiptRef finding -FailureClass route -Decision branch -AttemptNo 1 -VerificationStatus passed -VerificationReceiptRef receipt-branch -VerificationReceiptHash $receipt;if(($r.status -ne 'review') -or $r.advanced -or $r.eligibility.eligible -or ($r.nextAction -ne 'await-collaborator-choice')){throw 'branch decision advanced without collaborator choice'}}
Case 'invalid-batch-does-not-partially-commit'{$s=New-Store 'dynamic-atomic';$bad=@( [pscustomobject]@{branchId='branch-a';parentBranchId=$null;snapshotHash=$z;changedAssumption='a';verificationPredicate='v'}, [pscustomobject]@{branchId='branch-b';parentBranchId=$null;snapshotHash='bad';changedAssumption='b';verificationPredicate='v'} );try{Invoke-ESABCDDynamicIteration -Store $s -CandidateProposals $bad -AuditProposals (Audits) -SelectedBranchId branch-a -FindingReceiptRef finding -FailureClass input -Decision retry -AttemptNo 1 -VerificationStatus review|Out-Null;throw'invalid batch accepted'}catch{if($s.events.Count -ne 0){throw'partial event commit remained'}}}
$failed=@($results|Where-Object{$_.status-eq'failed'});$passed=@($results|Where-Object{$_.status-eq'passed'});$sourceRefs=@('ES/Automation/ABCD/ESABCDDynamicController.psm1','ES/Automation/ABCD/Test-ESABCDDynamicController.ps1','ES/Automation/ABCD/ESABCDOrchestrator.psm1','ES/Automation/Contracts/es-abcd-orchestration-event-v1.schema.json');$sourceHashes=[ordered]@{};foreach($ref in $sourceRefs){$sourceHashes[$ref]=(Get-FileHash -LiteralPath (Join-Path $root $ref) -Algorithm SHA256).Hash.ToLowerInvariant()};$evidenceContractPath=Join-Path $root 'ES/Automation/Contracts/es-skill-evidence-receipt-v1.schema.json';$evidenceContractHash=(Get-FileHash -LiteralPath $evidenceContractPath -Algorithm SHA256).Hash.ToLowerInvariant();$planHash=Get-ESABCDHash ([ordered]@{validator='Test-ESABCDDynamicController';sourceRefHashes=$sourceHashes;cases=@($results)});$report=[ordered]@{schemaVersion=1;validator='Test-ESABCDDynamicController';status=if($failed.Count){'failed'}else{'passed'};caseCount=$results.Count;passedCount=$passed.Count;failedCount=$failed.Count;cases=@($results);staticStatus=if($failed.Count){'static-failed'}else{'static-passed'};runtimeStatus='runtime-not-run';evidenceLevel='S1';capturedUtc=[DateTime]::UtcNow.ToString('o');authorizationKind='read-only';planHash=$planHash;evidenceContractId='es.skill-evidence-receipt';evidenceContractHash=$evidenceContractHash;skillName='es-agent-mechanism-replication';case='dynamic-controller';toolId='es-abcd-dynamic-controller-validator';receiptPath=$ReportPath.Replace('\','/');sourceRefs=$sourceRefs;sourceRefHashes=$sourceHashes;unityVersion='not-run';claimsNotProven=@('cross-process recovery','Unity/Worker/host Runtime','external authority')};$full=Join-Path $root $ReportPath;New-Item -ItemType Directory -Force -Path (Split-Path $full)|Out-Null;[IO.File]::WriteAllText($full,($report|ConvertTo-Json -Depth 20),[Text.UTF8Encoding]::new($false));$report|ConvertTo-Json -Depth 20;if($failed.Count){exit 1}
