[CmdletBinding()]
param([string]$ProjectRoot=(Resolve-Path (Join-Path $PSScriptRoot '..\..\..')).Path,[string]$ReportPath='ES/Output/StaticReplay/es-abcd-learning.json')
$ErrorActionPreference='Stop';$root=(Resolve-Path -LiteralPath $ProjectRoot).Path
Import-Module (Join-Path $root 'ES/Automation/ABCD/ESABCDLearning.psm1') -Force
Import-Module (Join-Path $root 'ES/Automation/ABCD/ESABCDOrchestrator.psm1') -Force
Import-Module (Join-Path $root 'ES/Automation/Contracts/ESJsonSchemaLite.psm1') -Force
$results=[Collections.Generic.List[object]]::new();function Assert-True([bool]$v,[string]$m){if(-not$v){throw$m}};function Case([string]$n,[scriptblock]$b){try{&$b;[void]$results.Add([pscustomobject]@{case=$n;status='passed';finding=$null})}catch{[void]$results.Add([pscustomobject]@{case=$n;status='failed';finding=$_.Exception.Message})}}
function Assert-Schema($value){$errors=@(Test-ESJsonSchemaValue -SchemaPath (Join-Path $root 'ES/Automation/Contracts/es-abcd-learning-candidate-v1.schema.json') -Value $value);if($errors.Count){throw($errors -join '; ')}}
$z='0'*64;$bindingHash='2'*64;$v='3'*64;$s=New-ESABCDOrchestrationStore -TaskId 'learning-task' -TaskBindingId 'learning-binding' -TaskBindingHash $bindingHash -AuthorizationRef 'auth.current-user' -RoutePlanHash $z -SourceScopeHash $z
Start-ESABCDIterationRound $s $s.taskRevision $s.contextVersion|Out-Null;Add-ESABCDCandidate $s root $null $z assumption verify $s.taskRevision $s.contextVersion|Out-Null
Add-ESABCDAuditRecord -Store $s -BranchId root -AuditorRef auditor -Verdict pass -EvidenceRefs @('e') -VerifierRef verifier -AuthorizationProof ('4'*64) -VerifierDefinitionHash $v -ExpectedTaskRevision $s.taskRevision -ExpectedContextVersion $s.contextVersion|Out-Null
Select-ESABCDDecision -Store $s -BranchId root -Decision retry -ClaimLevel full -ExpectedTaskRevision $s.taskRevision -ExpectedContextVersion $s.contextVersion|Out-Null
Start-ESABCDCorrectionCycle $s cycle-1 finding evidence retry full 1 $s.taskRevision $s.contextVersion|Out-Null
$receiptHash=Get-ESABCDHash ([ordered]@{receiptRef='receipt-learning';taskId=$s.taskId;taskBindingRef=$s.taskBindingRef;routePlanHash=$s.routePlanHash;sourceScopeHash=$s.sourceScopeHash;cycleId='cycle-1';branchId='root';attemptNo=1})
Add-ESABCDVerificationReceipt -Store $s -CycleId cycle-1 -VerificationStatus passed -VerificationReceiptRef receipt-learning -VerificationReceiptHash $receiptHash -ExpectedTaskRevision $s.taskRevision -ExpectedContextVersion $s.contextVersion|Out-Null
$refs=@([pscustomobject][ordered]@{path='ES/Automation/ABCD/ESABCDOrchestrator.psm1';sha256=(Get-FileHash (Join-Path $root 'ES/Automation/ABCD/ESABCDOrchestrator.psm1') -Algorithm SHA256).Hash.ToLowerInvariant();role='contract'})
Case 'verified-cycle-produces-claim-capped-candidate' {$c=New-ESABCDLearningCandidate -Store $s -CycleId cycle-1 -KnowledgeId abcd.knowledge.demo -TargetPath 'ES/Automation/Candidates/ABCDLearning/demo.json' -RouteKeys @('abcd','learning') -SourceRefs $refs -VerifierId verifier -VerifierDefinitionHash $v;Assert-Schema $c;Assert-True ($c.validation.promotionAllowed -eq $false) 'promotion must remain disabled';$r=Test-ESABCDLearningCandidate -Store $s -Candidate $c -ProjectRoot $root;Assert-True ($r.status -eq 'validated') 'candidate should validate'}
Case 'unverified-cycle-cannot-learn' {$x=New-ESABCDOrchestrationStore -TaskId x -TaskBindingId xb -TaskBindingHash $bindingHash -AuthorizationRef auth -RoutePlanHash $z -SourceScopeHash $z;try{New-ESABCDLearningCandidate -Store $x -CycleId missing -KnowledgeId x -TargetPath 'x.json' -RouteKeys @('x') -SourceRefs $refs -VerifierId verifier -VerifierDefinitionHash $v|Out-Null;throw 'unverified learning accepted'}catch{Assert-True ($_.Exception.Message -like '*LEARNING_REQUIRES_VERIFIED_CYCLE*') 'wrong learning gate'}}
Case 'source-drift-invalidates-candidate' {$c=New-ESABCDLearningCandidate -Store $s -CycleId cycle-1 -KnowledgeId abcd.knowledge.drift -TargetPath 'x.json' -RouteKeys @('abcd') -SourceRefs @([pscustomobject][ordered]@{path=$refs[0].path;sha256=('f'*64);role='contract'}) -VerifierId verifier -VerifierDefinitionHash $v; $r=Test-ESABCDLearningCandidate -Store $s -Candidate $c -ProjectRoot $root;Assert-True ($r.status -eq 'stale') 'source drift not detected'}
$failed=@($results|Where-Object status -eq 'failed');$sourceRefs=@('ES/Automation/ABCD/ESABCDLearning.psm1','ES/Automation/ABCD/Test-ESABCDLearning.ps1','ES/Automation/Contracts/es-abcd-learning-candidate-v1.schema.json');$sourceRefHashes=[ordered]@{};foreach($ref in $sourceRefs){$sourceRefHashes[$ref]=(Get-FileHash (Join-Path $root $ref) -Algorithm SHA256).Hash.ToLowerInvariant()};$evidenceContractPath=Join-Path $root 'ES/Automation/Contracts/es-skill-evidence-receipt-v1.schema.json';$evidenceContractHash=(Get-FileHash -LiteralPath $evidenceContractPath -Algorithm SHA256).Hash.ToLowerInvariant();$planHash=Get-ESABCDHash ([ordered]@{validator='Test-ESABCDLearning';sourceRefHashes=$sourceRefHashes;cases=@($results)});$report=[ordered]@{schemaVersion=1;validator='Test-ESABCDLearning';status=if($failed.Count){'failed'}else{'passed'};caseCount=$results.Count;passedCount=@($results|Where-Object status -eq 'passed').Count;failedCount=$failed.Count;cases=@($results);runtimeStatus='runtime-not-run';staticStatus=if($failed.Count){'static-failed'}else{'static-passed'};evidenceLevel='S1';capturedUtc=[DateTime]::UtcNow.ToString('o');authorizationKind='read-only';planHash=$planHash;evidenceContractId='es.skill-evidence-receipt';evidenceContractHash=$evidenceContractHash;skillName='es-agent-mechanism-replication';case='learning-candidate';receiptPath=$ReportPath.Replace('\','/');sourceRefs=$sourceRefs;sourceRefHashes=$sourceRefHashes;toolId='es-abcd-learning-validator';unityVersion='not-run';claimsNotProven=@('Knowledge promotion','Runtime behavior','external authority')};$full=Join-Path $root $ReportPath;New-Item -ItemType Directory -Force -Path (Split-Path $full)|Out-Null;[IO.File]::WriteAllText($full,($report|ConvertTo-Json -Depth 20),[Text.UTF8Encoding]::new($false));$report|ConvertTo-Json -Depth 20;if($failed.Count){exit 1}
