[CmdletBinding()]
param([string]$ProjectRoot=(Resolve-Path (Join-Path $PSScriptRoot '..\..\..')).Path,[string]$ReportPath='ES/Output/StaticReplay/es-abcd-learning-review.json')
$ErrorActionPreference='Stop';$root=(Resolve-Path -LiteralPath $ProjectRoot).Path;Import-Module (Join-Path $root 'ES/Automation/ABCD/ESABCDLearningReview.psm1') -Force;Import-Module (Join-Path $root 'ES/Automation/Contracts/ESJsonSchemaLite.psm1') -Force
$schema=Join-Path $root 'ES/Automation/Contracts/es-abcd-learning-review-v1.schema.json';$src='ES/Automation/ABCD/ESABCDLearningReview.psm1';$hash=(Get-FileHash -LiteralPath (Join-Path $root $src) -Algorithm SHA256).Hash.ToLowerInvariant();$candidate=[pscustomobject][ordered]@{candidateId='abcd-lc-'+('a'*32);candidateHash=('b'*64);status='validated';sourceRefs=@([pscustomobject][ordered]@{path=$src;sha256=$hash;role='contract'});validation=[pscustomobject][ordered]@{state='passed';verifierId='verifier';verifierDefinitionHash=('c'*64);sourceStableAtEnd=$true;promotionAllowed=$false}}
$validation=[pscustomobject][ordered]@{status='validated';sourceStableAtEnd=$true;checks=@('sourceRefs','candidateHash')};$results=[Collections.Generic.List[object]]::new();function Case([string]$n,[scriptblock]$b){try{&$b;[void]$results.Add([pscustomobject]@{case=$n;status='passed';finding=$null})}catch{[void]$results.Add([pscustomobject]@{case=$n;status='failed';finding=$_.Exception.Message})}}
Case 'validated-candidate-enters-human-review'{$r=New-ESABCDLearningReview -Candidate $candidate -ValidationResult $validation -ReviewerId reviewer -ReviewerRole knowledge-reviewer -AuthorizationProof proof;$t=Test-ESABCDLearningReview $r $root;if($t.status-ne'review'-or$r.promotion.promotionAllowed-ne$false){throw'learning review was not bounded'}}
Case 'unvalidated-candidate-rejected'{$v=[pscustomobject]@{status='stale';sourceStableAtEnd=$false};try{New-ESABCDLearningReview -Candidate $candidate -ValidationResult $v -ReviewerId reviewer -ReviewerRole knowledge-reviewer -AuthorizationProof proof|Out-Null;throw'unvalidated candidate accepted'}catch{if($_.Exception.Message-notlike'*REQUIRES_VALIDATED*'){throw}}}
Case 'source-drift-becomes-stale'{$r=New-ESABCDLearningReview -Candidate $candidate -ValidationResult $validation -ReviewerId reviewer -ReviewerRole knowledge-reviewer -AuthorizationProof proof;$r.sourceRefs[0].sha256='d'*64;$t=Test-ESABCDLearningReview $r $root;if($t.status-ne'stale'-or$t.sourceStableAtEnd){throw'source drift did not stale review'}}
Case 'review-schema-is-strict'{$r=New-ESABCDLearningReview -Candidate $candidate -ValidationResult $validation -ReviewerId reviewer -ReviewerRole knowledge-reviewer -AuthorizationProof proof;$errors=@(Test-ESJsonSchemaValue -SchemaPath $schema -Value $r);if($errors.Count){throw($errors-join';')}}
$failed=@($results | Where-Object { $_.status -eq 'failed' });$passed=@($results | Where-Object { $_.status -eq 'passed' });$sourceRefs=@('ES/Automation/ABCD/ESABCDLearningReview.psm1','ES/Automation/ABCD/Test-ESABCDLearningReview.ps1','ES/Automation/Contracts/es-abcd-learning-review-v1.schema.json');$sourceHashes=[ordered]@{};foreach($ref in $sourceRefs){$sourceHashes[$ref]=(Get-FileHash -LiteralPath (Join-Path $root $ref) -Algorithm SHA256).Hash.ToLowerInvariant()};$evidenceContractPath=Join-Path $root 'ES/Automation/Contracts/es-skill-evidence-receipt-v1.schema.json';$evidenceContractHash=(Get-FileHash -LiteralPath $evidenceContractPath -Algorithm SHA256).Hash.ToLowerInvariant();$planHash=Get-ESABCDLearningReviewHash ([ordered]@{validator='Test-ESABCDLearningReview';sourceRefHashes=$sourceHashes;cases=@($results)});$report=[ordered]@{schemaVersion=1;validator='Test-ESABCDLearningReview';status=if($failed.Count){'failed'}else{'passed'};caseCount=$results.Count;passedCount=$passed.Count;failedCount=$failed.Count;cases=@($results);staticStatus=if($failed.Count){'static-failed'}else{'static-passed'};runtimeStatus='runtime-not-run';evidenceLevel='S1';capturedUtc=[DateTime]::UtcNow.ToString('o');authorizationKind='read-only';planHash=$planHash;evidenceContractId='es.skill-evidence-receipt';evidenceContractHash=$evidenceContractHash;skillName='es-agent-mechanism-replication';case='learning-review';toolId='es-abcd-learning-review-validator';receiptPath=$ReportPath.Replace('\','/');sourceRefs=$sourceRefs;sourceRefHashes=$sourceHashes;unityVersion='not-run';claimsNotProven=@('automatic Knowledge promotion','Runtime behavior','external authority')};$full=Join-Path $root $ReportPath;New-Item -ItemType Directory -Force -Path (Split-Path $full)|Out-Null;[IO.File]::WriteAllText($full,($report|ConvertTo-Json -Depth 20),[Text.UTF8Encoding]::new($false));$report|ConvertTo-Json -Depth 20;if($failed.Count){exit 1}
