[CmdletBinding()]param([string]$ProjectRoot=(Resolve-Path (Join-Path $PSScriptRoot '..\..\..')).Path,[string]$ReportPath='ES/Output/StaticReplay/es-abcd-framework-parity.json')
$ErrorActionPreference='Stop';$root=(Resolve-Path -LiteralPath $ProjectRoot).Path;Import-Module (Join-Path $root 'ES/Automation/ABCD/ESABCDFrameworkParity.psm1') -Force
$m=Get-ESABCDFrameworkCoverage;$cases=@();foreach($f in @($m.frameworks)){foreach($cap in @($f.capabilities)){$payload=[ordered]@{probe='parity';framework=$f.frameworkId;scope='project';feedback='observed';reflection='bounded-reflection';count=2;max=3;used=0;output='';text='{}';maxLines=20;pruned=@('b1');backtrack=$true;seed='fixed';turns=3;stale=$false;score=0.7;expected='same';actual='same';trace=@('a','b');toolCalls=@('read')};try{$r=Invoke-ESABCDFrameworkCapability -FrameworkId $f.frameworkId -CapabilityId $cap -Payload $payload;$ok=($r.status -eq 'adapted' -and $null -ne $r.result)}catch{$ok=$false};$cases+=,[pscustomobject]@{frameworkId=$f.frameworkId;framework=$f.frameworkId;capability=$cap;status=if($ok){'adapted'}else{'failed'}}}}
$negativeCases=@(
 [pscustomobject]@{frameworkId='swe-agent-aci';capability='bounded-tool-surface';payload=[ordered]@{scope=$null};expected='reject'},
 [pscustomobject]@{frameworkId='swe-agent-aci';capability='edit-lint-gate';payload=[ordered]@{text='{';scope='project'};expected='reject'},
 [pscustomobject]@{frameworkId='reflexion';capability='feedback-capture';payload=[ordered]@{feedback=$null};expected='reject'},
 [pscustomobject]@{frameworkId='tree-of-thoughts';capability='branch-generation';payload=[ordered]@{count=1};expected='reject'},
 [pscustomobject]@{frameworkId='envtrustbench';capability='truth-oracle';payload=[ordered]@{expected=$null};expected='reject'}
)
foreach($n in $negativeCases){$rejected=$false;try{[void](Invoke-ESABCDFrameworkCapability -FrameworkId $n.frameworkId -CapabilityId $n.capability -Payload $n.payload)}catch{$rejected=$true};$cases+=,[pscustomobject]@{frameworkId=$n.frameworkId;framework=$n.frameworkId;capability=$n.capability;caseType='negative';status=if($rejected){'adapted'}else{'failed'}}}
$failed=@($cases|Where-Object status -eq 'failed');$m=Get-ESABCDFrameworkCoverage -ExecutionResults $cases;$refs=@('ES/Automation/ABCD/ESABCDFrameworkParity.psm1','ES/Automation/ABCD/Test-ESABCDFrameworkParity.ps1','ES/Automation/Contracts/es-abcd-framework-parity-v1.json');$hashes=[ordered]@{};foreach($s in $refs){$hashes[$s]=(Get-FileHash -LiteralPath (Join-Path $root $s) -Algorithm SHA256).Hash.ToLowerInvariant()};$report=[ordered]@{schemaVersion=1;validator='Test-ESABCDFrameworkParity';status=if($failed.Count){'failed'}else{'passed'};staticStatus=if($failed.Count){'static-failed'}else{'static-passed'};runtimeStatus='runtime-not-run';evidenceLevel='S1';capturedUtc=[DateTime]::UtcNow.ToString('o');caseCount=$cases.Count;passedCount=($cases.Count-$failed.Count);failedCount=$failed.Count;cases=$cases;coverage=$m;authorizationKind='read-only';planHash=([BitConverter]::ToString(([Security.Cryptography.SHA256]::Create()).ComputeHash([Text.Encoding]::UTF8.GetBytes(($cases|ConvertTo-Json -Compress))))).Replace('-','').ToLowerInvariant();evidenceContractId='es.skill-evidence-receipt';evidenceContractHash=(Get-FileHash -LiteralPath (Join-Path $root 'ES/Automation/Contracts/es-skill-evidence-receipt-v1.schema.json') -Algorithm SHA256).Hash.ToLowerInvariant();skillName='es-agent-mechanism-replication';case='framework-parity';toolId='es-abcd-framework-parity-validator';receiptPath=$ReportPath.Replace('\','/');sourceRefs=$refs;sourceRefHashes=$hashes;unityVersion='not-run';claimsNotProven=@('external framework runtime equivalence','third-party benchmark parity','license compliance')};$full=if([IO.Path]::IsPathRooted($ReportPath)){$ReportPath}else{Join-Path $root $ReportPath};New-Item -ItemType Directory -Force -Path (Split-Path -Parent $full)|Out-Null;[IO.File]::WriteAllText($full,($report|ConvertTo-Json -Depth 30),[Text.UTF8Encoding]::new($false));$report|ConvertTo-Json -Depth 30;if($failed.Count){exit 1}
