[CmdletBinding()]param()
$ErrorActionPreference='Stop';Import-Module (Join-Path $PSScriptRoot 'ESABCInnovationRun.psm1') -Force
$h=('b'*64)
$generator={param($ctx)
 if($ctx.phase -eq 'engineering-architecture-divergence'){$parents=@($ctx.previousDirections|ForEach-Object{$_.architectureId}|Select-Object -First 2);if($parents.Count -lt 2){$parents=@('seed-a','seed-b')};$a=@();foreach($i in 1..5){$cf=@(1..3|ForEach-Object{[pscustomobject]@{round=$_;baselineOutcome='baseline';candidateOutcome='candidate';baselineScore=0;candidateScore=3;qualitativeDifference='different'}});$a+=[pscustomobject]@{architectureId="arch-$($ctx.round)-$i";implementationBoundary='bounded';lifecycleAssessment='lifecycle';performanceAssessment='performance';networkAssessment='network';debuggingAssessment='debug';editorProductionAssessment='editor';innovationDifferentialAssessment='qualitative-difference';innovationDifferentialLevel=[math]::Min(5,$i);counterfactualRegression=$cf;baselinePlayerLevel=0;playerIncrementDelta=3;playerIncrementRegression=3;technicalInnovationLevel=[math]::Min(5,$i);safetyLevel=3;performanceLevel=[math]::Min(5,$i);reusabilityLevel=[math]::Min(5,$i);lifecycleLevel=[math]::Min(5,$i);networkLevel=3;debuggingLevel=3;editorProductionLevel=3;fusionParentIds=$parents}};return $a}
 if($ctx.phase -eq 'seed-selection'){return 1..5|ForEach-Object{[pscustomobject]@{content="seed-$_";changedVariable="axis-$_";playerAcceptability=70;novelty=70}}}
 return @([pscustomobject]@{content="round-$($ctx.round)-a";changedVariable='timing';playerAcceptability=82;novelty=78;counterplay=80;complexity=35;clarity=85;roleFit=80},[pscustomobject]@{content="round-$($ctx.round)-b";changedVariable='space';playerAcceptability=74;novelty=88;counterplay=70;complexity=55;clarity=70;roleFit=65})
}
$runs=@();foreach($mode in @('creative-divergence','engineering','stable')){$runs+=Invoke-ESABCInnovationRun -Requirement 'mode-test' -GoalRevision ('r-'+$mode) -SourceHash $h -GenerationMode $mode -ModelInvoker $generator}
$pass=(@($runs|ForEach-Object generationMode|Sort-Object -Unique).Count -eq 3 -and @($runs|Where-Object{$_.finalDecision.challengeLensCount -lt 10}).Count -eq 0 -and @($runs|Where-Object{$_.finalDecision.challengeScore -lt 0 -or $_.finalDecision.challengeScore -gt 100}).Count -eq 0)
[pscustomobject]@{status=if($pass){'passed'}else{'failed'};modeCount=@($runs).Count;distinctModeScores=@($runs|ForEach-Object{$_.finalDecision.modeScore}|Sort-Object -Unique).Count;minChallengeLenses=(@($runs|ForEach-Object{$_.finalDecision.challengeLensCount}|Measure-Object -Minimum).Minimum);engineeringScore=($runs|Where-Object generationMode -eq 'engineering'|Select-Object -ExpandProperty finalDecision).modeScore}
if(-not $pass){exit 1}
