[CmdletBinding()]
param([string]$ProjectRoot)
$ErrorActionPreference='Stop';if([string]::IsNullOrWhiteSpace($ProjectRoot)){$ProjectRoot=(Resolve-Path (Join-Path $PSScriptRoot '..\..\..')).Path};Import-Module (Join-Path $ProjectRoot 'ES/Automation/ABCD/ESABCInnovationRun.psm1') -Force
$h=('e'*64)
$invoker={param($ctx) $items=@();$parents=@($ctx.previousDirections|ForEach-Object{[string]$_.architectureId}|Select-Object -First 2);if($parents.Count -lt 2){$parents=@('seed-a','seed-b')};foreach($i in 1..6){$inc=if($i -eq 1){1}else{$i-1};$base=2;$cf=@(1..3|ForEach-Object{[pscustomobject]@{round=$_;baselineOutcome="baseline-$($_)-$i";candidateOutcome="candidate-$($_)-$i";baselineScore=2;candidateScore=$inc;qualitativeDifference="different-decision-$($_)-$i"}});$items+=[pscustomobject][ordered]@{architectureId="g$($ctx.round)-arch-$i";implementationBoundary="g$($ctx.round)-boundary-$i";lifecycleAssessment="lifecycle-$i";performanceAssessment="performance-$i";networkAssessment="network-$i";debuggingAssessment="debug-$i";editorProductionAssessment="editor-$i";innovationDifferentialAssessment="qualitative-engineering-difference-$i";innovationDifferentialLevel=if($i -eq 1){1}else{[math]::Min(5,$i-1)};counterfactualRegression=$cf;fusionParentIds=$parents;baselinePlayerLevel=$base;playerIncrementDelta=$inc-$base;playerIncrementRegression=$inc;technicalInnovationLevel=if($i -eq 1){1}else{[math]::Min(5,$i-1)};safetyLevel=if($i -eq 1){5}else{3};performanceLevel=if($i -eq 1){5}else{[math]::Min(5,$i-1)};reusabilityLevel=if($i -eq 1){5}else{[math]::Min(5,$i-1)};lifecycleLevel=[math]::Min(5,$i);networkLevel=[math]::Min(5,$i);debuggingLevel=[math]::Min(5,$i);editorProductionLevel=[math]::Min(5,$i)}};$items}
$baseInvoker=$invoker;$invoker={param($ctx)$out=@(& $baseInvoker $ctx);foreach($x in $out){$de=@('lifecycle','performance','network','debugging','editorProduction')|ForEach-Object{[pscustomobject]@{dimension=$_;metric='metric';target='target';observed='observed';verificationRef='verify'}};Add-Member -InputObject $x -NotePropertyName dimensionEvidence -NotePropertyValue @($de) -Force};$out};$r=Invoke-ESABCEngineeringArchitectureCompetition -Requirement '工程架构竞争' -GoalRevision 'goal-r1' -SourceHash $h -ModelInvoker $invoker -ProjectRoot $ProjectRoot
$contractHash=(Get-FileHash -LiteralPath (Join-Path $ProjectRoot 'ES/Automation/Contracts/es-ai-abc-engineering-architecture-competition-v1.schema.json') -Algorithm SHA256).Hash.ToLowerInvariant();$contractBinding=(([string]$r.contractHash).ToLowerInvariant() -eq $contractHash)
$badParentInvoker={param($ctx) $items=@();foreach($i in 1..6){$items+=[pscustomobject][ordered]@{architectureId="bad-$($ctx.round)-$i";implementationBoundary='b';lifecycleAssessment='l';performanceAssessment='p';networkAssessment='n';debuggingAssessment='d';editorProductionAssessment='e';fusionParentIds=@('not-a-prior-id','still-invalid');playerIncrementRegression=3;technicalInnovationLevel=3;safetyLevel=3;performanceLevel=3;reusabilityLevel=3;lifecycleLevel=3;networkLevel=3;debuggingLevel=3;editorProductionLevel=3}};$items}
$badParentResult=$null;$badParentRejected=$false;try{$badParentResult=Invoke-ESABCEngineeringArchitectureCompetition -Requirement '工程架构竞争' -GoalRevision 'goal-r1' -SourceHash $h -ModelInvoker $badParentInvoker;$badParentRejected=(@($badParentResult.directions|Where-Object{ @($_.missingFields) -contains 'fusionParentIds.must-reference-prior-generation' }).Count -ge 1)}catch{$badParentRejected=($_.Exception.Message -like '*PARETO_SET_INSUFFICIENT*')}
$eligible=@($r.directions|Where-Object status -eq 'eligible');$counterfactualRegression=(@($eligible|Where-Object{[double]$_.counterfactualGain -le 0}).Count -eq 0)
$pass=($r.status -eq 'review-required' -and $r.completionEligible -eq $false -and $r.generationCount -eq 3 -and $r.directionCount -ge 15 -and @($r.paretoShortlist).Count -ge 2 -and @($r.discarded|Where-Object{[string]$_.reason -eq 'SAFE_BUT_NO_PLAYER_INCREMENT'}).Count -ge 1 -and [string]$r.winnerId -ne '' -and $r.implementationEvidenceRequiredForFinal -and $badParentRejected -and $counterfactualRegression -and $contractBinding)
$state=if($pass){'passed'}else{'failed'}
[pscustomobject]@{status=$state;directionCount=$r.directionCount;paretoCount=@($r.paretoShortlist).Count;safeNoIncrementRejected=@($r.discarded|Where-Object{[string]$_.reason -eq 'SAFE_BUT_NO_PLAYER_INCREMENT'}).Count;discardedReasons=@($r.discarded|ForEach-Object{$_.reason}|Sort-Object -Unique);winnerId=$r.winnerId;winnerBand=$r.winnerBand;completionEligible=$r.completionEligible;implementationEvidenceRequiredForFinal=$r.implementationEvidenceRequiredForFinal;invalidFusionRejected=$badParentRejected;counterfactualRegression=$counterfactualRegression;contractHashBinding=$contractBinding;mapping=$r.scoringRule}
if(-not $pass){exit 1}
